### ISSUE TITLE
Add Discovery Support for this Adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.knx#10]
Hey,

please check out the Discovery-Adapter (https://github.com/ioBroker/ioBroker.discovery) and check if the device can be detected somehow (special url with defined answer, special port, upnp, udp or other technologies?!). If yes it would great if you could add a pull request to the Discovery-Adapter with the needed code.
Support needed? Contact me (Apollon77) in Forum as forum thread or PN ;-)

Ingo

**Comment by chefkoch009** [comment]
Already eine. Knx-discovery ist implented in iobroker.discovery
