### ISSUE TITLE
KNX GAs werden nicht gelesen 1.0.41

### ISSUE THREAD

**Issue by tobias-net** [ioBroker/ioBroker.knx#103]
Die Version 1.0.41 liest bei mir weder beim Start des Adapter noch beim normalen Betrieb die GAs von KNX aus. Wenn ich ein Objekt in Objekte manuell bearbeite wird allerdings der neue Wert auf den KNX Bus geschrieben.

Gehe ich zurück auf 1.0.38 werden die GAs direkt richtig eingelesen und aktualisiert.

**Comment by mghomedev** [comment]
Yes, I think there is a  bug in the ETS importer that breaks the associations to the status updates when values are read
I think it works when you import the project with an older version (before April 2020) and then upgrade only after import.

**Comment by mghomedev** [comment]
.. the workaround to import with older version unfortunately also does NOT work for me. The read operation on start is just broken with the versions since April

**Comment by chefkoch009** [comment]
I think this issue is solved, so I close it.
