### ISSUE TITLE
2bit Datentyp DPT 2.001 wird als [object Object] gelesen

### ISSUE THREAD

**Issue by Ralf31337** [ioBroker/ioBroker.knx#104]
Für einen ABB Aktor habe ich die Zwangsführung als 2bit Datentyp eingerichtet (2.001). Das funktioniert auch, jedoch weder lesend noch schreibend über IObroker und auch node red.

Als Wert wird wohl irgendwo ein toString() gemacht, der zu einem [object Object]-String führt.

![image](https://user-images.githubusercontent.com/51866902/83339440-15260f80-a2ce-11ea-8b33-89bfc1094828.png)

In node red kommt der String an:
![image](https://user-images.githubusercontent.com/51866902/83339446-2a02a300-a2ce-11ea-9f60-332a43377212.png)

**Comment by chefkoch009** [comment]
Das sollte ein Array sein in der Form [x,y]. Wobei x der Zwang und y das Schalten ist.

**Comment by Ralf31337** [comment]
Es war wohl noch ein nicht unterstützter Datentyp in der Version 0.8.x Ich hatte vor 2 Monaten iobroker installiert, jetzt bin ich auf der neusten Version und alles funktioniert einwandfrei. Warum ich bei einer Neuinstallation eine so alte Version erwischt habe weiß ich nicht. Sorry, dass ich das übersehen habe.
