### ISSUE TITLE
State Not Connected

### ISSUE THREAD

**Issue by TomSC1984** [ioBroker/ioBroker.knx#105]
Hi

ich bekomme immer und andauernd diese Meldungen im LOG. Was könnte das sein? Ich habe alle GA mit DPT versehen.  Das kann es also nicht sein. Ich nutze keine Sonderzeichen oder ähnliches. was wäre noch möglich? 
Gruß Thomas

´
knx.0 | 2020-06-03 19:47:47.520 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
-- | -- | -- | --
knx.0 | 2020-06-03 19:47:47.518 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:47:47.516 | info | (3917)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:45:48.204 | info | (3917) Connected  - local UDP Server listening on 192.168.178.65:36218
knx.0 | 2020-06-03 19:45:48.203 | info | (3917) Using UDP with local IP: 192.168.178.65
knx.0 | 2020-06-03 19:45:46.206 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:45:46.204 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:45:46.202 | info | (3917)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:43:46.880 | info | (3917) Connected  - local UDP Server listening on 192.168.178.65:45052
knx.0 | 2020-06-03 19:43:46.879 | info | (3917) Using UDP with local IP: 192.168.178.65
knx.0 | 2020-06-03 19:43:44.883 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:43:44.881 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:43:44.879 | info | (3917)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
info.0 | 2020-06-03 19:43:19.702 | info | (2032) Popup news was read...
knx.0 | 2020-06-03 19:41:45.556 | info | (3917) Connected  - local UDP Server listening on 192.168.178.65:35753
knx.0 | 2020-06-03 19:41:45.555 | info | (3917) Using UDP with local IP: 192.168.178.65
knx.0 | 2020-06-03 19:41:43.559 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:41:43.557 | info | (3917)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:41:43.554 | info | (3917)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-06-03 19:39:43.212 | info | (3917) Connected  - local UDP Server listening on 192.168.178.65:41059
knx.0 | 2020-06-03 19:39:43.211 | info | (3917) Using UDP with local IP: 192.168.178.65
´

**Comment by chefkoch009** [comment]
Das heißt, das er dein LAN-GW nicht erreichen kann und es periodisch immer wieder versucht.

**Comment by TomSC1984** [comment]
Das heisst, es liegt an meinem IP-Router? Aber warum sollte dieser nicht erreichbar sein?

**Comment by chefkoch009** [comment]
Ich habe nicht gesagt, das es an deinem IP-Router liegt. Ich habe gesagt das er nicht erreicht werden kann und das kann viele Ursachen haben (Firewall, Routing,.....). Was hast du denn für einen? Es gibt welche die können nur eine bestimmte Anzahl an Verbindungen annehmen.

**Comment by boellner** [comment]
possibly same as #184

**Comment by chefkoch009** [comment]
Ist ab V2.0.3 behoben
