### ISSUE TITLE
Rückmeldung vom KNX

### ISSUE THREAD

**Issue by matze1708** [ioBroker/ioBroker.knx#11]
Hallo,

falls es doppelt ist sorry. Im closed habe ich auf einen Thread geantwortet. Weiss aber nicht ob man das dann noch beachtet.

wo packe ich das Rückmeldeobjekt hin?

Beispiel ich schalte auf der Gruppenadresse 1/0/1 und bekomme von dem Aktor Aktiv eine Rückmeldung auf der Gruppenadresse 1/0/2.

Wo stelle ich das in der Objekt ID im IOBroker ein?
 Bei statusGARefId oder bei actGARefId ?
 Und was trage ich da ein? Die KNX Gruppen Adresse oder die adressRefID aus der Objekt ID bsp: P-040C-0_GA-227?

Vielen Dank.

**Comment by chefkoch009** [comment]
Es sollte automatisch erkannt werden ab Version 0.8.3.  sollte es nicht funktionieren möchte ich um die knxproj bitten, ggf habe ich einen Fall übersehen. Ansonsten steht bei der Statusadresse unter actGARefId die ID des Schaltobjektes und bei der schaltadresse unter statusGARefId die korrespondierende statusadressID.

**Comment by matze1708** [comment]
Hallo vielen Dank für die Info.

Erkannt hat er das bei mir nicht. 
Wo soll ich dir die Datei hin senden?

Muss grundsätzlich die Verknüpfung auf beiden Seiten erstellt werden?

**Comment by chefkoch009** [comment]
Am besten Kontakt via iobroker Forum.

**Comment by matze1708** [comment]
Ist das der gleiche Name wie hier

Meine PN ist im Forum im Postausgang

**Comment by chefkoch009** [comment]
solved with binding the status-change to actor-state.

**Comment by cyberax17** [comment]
Wie erkennt man denn im Objekt, ob er die Zuordnung Schaltadresse/Rückmeldeadresse automatisch erkannt hat oder nicht?
