### ISSUE TITLE
Heizungssteuerung 2 actGa und 1 status GA?

### ISSUE THREAD

**Issue by 1704eu** [ioBroker/ioBroker.knx#110]
Hi zusammen,

vielen Dank für den tollen Adapter, ohne den der ioBroker für mich nicht die gleiche Bedeutung hätte wie mit dem Adapter.

Ich habe versucht mein ETS Projekt gemäss Adapterbeschreibung sauber aufzubauen vor allem _einheitliche Beschriftung der GA-Namen (z.B "EG Wohnen Decke Licht schalten" und "EG Wohnen Decke Licht schalten status" )_ Jetzt stosse ich aber auf ein Problem. Ich habe ein Theben HMG 6 T KNX im Einatz. Hier ist die Idee, dass man jeder Heizzone einen Basissollwert vergibt und darauf eine Sollwertverschiebung addiert. Das resultiert dann im aktuellen Sollwert. Ich habe den aktuellen Sollwert als Status zum Basissollwert konfiguriert. Aber was mache ich nun mit der Sollwertverschiebung? 2 Act Adr und eine status GA??

Könnt ihr mir helfen?

Danke Benni

**Comment by chefkoch009** [comment]
Du legst eine Gruppenadresse an, in der alle Sollwertverschiebungen(act) drin sind. Dann kannst Du global alle Temperaturen verschieben. Problem bei schreibenden Sammeladressen ist immer, das es keine globale Rückmeldung gibt, da musst Du Dir einen Wert raussuchen und den als Referenz nehmen.
