### ISSUE TITLE
Datum kann nicht auf Gruppenadresse geschrieben werden

### ISSUE THREAD

**Issue by mpenn0** [ioBroker/ioBroker.knx#113]
Im ioBroker [Forum](https://forum.iobroker.net/post/475484) hatte ich schon geschrieben und nachgefragt:

Ich kann über den KNX-Adapter kein Datum-Wert schreiben. Das Lesen des Datums (und vieles andere, Danke dafür!) hingegen klappt.
Meine Eckdaten:
- KNX-Adapter Version 1.0.41
- KNX-NetIP-Router von Enertex Bayern

Flags in der ETS siehe Screenshot:

![ETS_KNX-Objekt](https://user-images.githubusercontent.com/56229993/91737363-4654fb00-ebaf-11ea-8001-b4385a6335df.png)

Die Flags für's Lesen und Schreiben habe ich hier gesetzt, da der Wert geschrieben und ausgelesen werden soll.

Raw-Daten vom Datenpunkt im ioBroker:
`{
  "_id": "knx.0.Messwerte.Zähler.Nächstesstichdatum",
  "type": "state",
  "common": {
    "name": "Nächstesstichdatum",
    "type": "number",
    "read": false,
    "write": true,
    "role": "value",
    "min": 0,
    "max": 670670
  },
  "native": {
    "dpt": "DPT11.001",
    "address": "10/3/19",
    "addressRefId": "P-02CC-0_GA-347",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1596549863547,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Das Schreiben eines Datums wird nicht auf dem Bus gegeben. Dank der Tipps aus dem Forum habe ich "Read" = "false" gesetzt.
Unabhängig von "Read" = "true" oder "false", wird nichts auf den Bus geschrieben. Allerdings stürzt der KNX-Adapter nur bei "Read" = "false" ab. Details siehe Log, dort gibt es auch eine Fehlermeldung.
[iobroker.2020-08-31_Auszug.log](https://github.com/ioBroker/ioBroker.knx/files/5151201/iobroker.2020-08-31_Auszug.log)

Interessanterweise bleibt vom Datum in der Adminoberfläche nicht viel übrig: Eingegeben habe ich "29.08.2020" :
![Admin-Oberfläche nach Eingabe_Datum](https://user-images.githubusercontent.com/56229993/91738113-4f929780-ebb0-11ea-9cff-d98a6b40b519.png)

Kann eventuell jemand helfen?

**Comment by mpenn0** [comment]
Die Hinweise in Bezug auf die richtigen Flags vom Entwickler im ioBroker Forum habe ich umgesetzt:
![2020-09-24_Flags](https://user-images.githubusercontent.com/56229993/94182929-f7df0780-fea1-11ea-8bc2-3c91838354ee.png)

Jetzt erfolgt beim Absetzen eines Datumwertes über die Admin-Oberfläche vom ioBroker ein GroupValueWrite durchgeführt. Was ich aber erst später bemerkt habe, war, dass das Gerät die Einstellung nicht übernommen hat. Augenscheinlich saher beide Schreibbefehle (über ioBroker und über die ETS) laut Gruppenmonitor gleich aus:
![2020-09-24_ETS-Monitor](https://user-images.githubusercontent.com/56229993/94183173-48eefb80-fea2-11ea-96ab-71bd69b2dd4c.png)

Jedoch zeigte erst ein Blick in die Details die Unterschiede.

GroupValueWrite über den ioBroker:
![2020-09-24_GroupValueWrite_ioBroker](https://user-images.githubusercontent.com/56229993/94183287-7dfb4e00-fea2-11ea-86ae-bf9dc4b9172f.png)

GroupValueWrite über die ETS:
![2020-09-24_GroupValueWrite_ETS](https://user-images.githubusercontent.com/56229993/94183494-cadf2480-fea2-11ea-90ed-3a9f7476ca82.png)

Die Unterschiede habe ich einmal markiert.

Was heißt das nun?

**Comment by RESDE** [comment]
Hallo, mir scheint bei Dir in der ETS die IP Schnittstelle eine mögliche Ursache des Problems zu sein. Hast Du die EIB Adresse des IP Interface ungleich (!) der EIB adresse im KNX Adapter (IOBroker) gesetzt? Schaumal in die Beschreibung des NKX Adaptes, dort stehen die Details der Geräte Adressierung.
Wenn ich bei mir in der ETS Software arbeite,kann ich keine eine EIB Adresse der ETS realisieren. GA Adressen Wertänderungen im Gruppenmonitor direkt weggeschrieben ohne Angabe der ETS... )siehe Dein Screenshot)
Grüße
Reiner

**Comment by mpenn0** [comment]
Hallo Reiner,
danke für Deine Rückmeldung. Warum vermutest Du eine fehlerhafte IP-Schnittstelle in der ETS?
Mit der ETS kann ich alle Adressen beschreiben und auslesen. Mit dem ioBroker über den KNX-Adapter ebenfalls, außer das Schreiben eines Datum-Wertes.
Sensor-Werte auslesen, Rollladen fahren lassen, klappt alles.

Zur Vollständigkeit: die Adresse des IP-Gateways ist 1.1.0, dem KNX-Adapter habe ich die 1.1.250 zugewiesen. Die ETS hat die 1.1.152.

Könntest Du mir bitte Deinen zweiten Absatz noch einmal erläutern, den habe ich nicht ganz verstanden?

Viele Grüße
Michael

**Comment by RESDE** [comment]
Hallo Michael,

mein 2ter Absatz ist nicht korrekt und daher macht es keinen Sinn dies zu wiederholen. Meine Gas mit Typ Datum werden aus dem Bus anstandslos in Iobroker übergeben und können auch von dort überschrieben werden. Es bleibt aber beim Datumswert und Formatierung.
Denke daher dass ich hier nicht mehr helfen kann.
Grüße
Reiner

**Comment by Videonisse** [comment]
@mpenn0 Besteht immer noch das Problem? 

Ich habe die gleiche werte bei mir in Busmonitor wenn ioBroker ein Datum wert schreibe. Habe aber noch nicht ein Gerät die Datum benutzt /liest. 

Wenn es noch nicht geht solltest du vieleicht den Titel fuer dieses Issue ändern? Weil ioBroker sendest doch den Wert aber dein KNX Gerät kann es nicht lesen, stimmt?

Wenn es noch nicht geht kannst du vielleicht probieren ein neues GA in ETS zu erstellen mit DPT 9.001, und neu Importieren mit letzte Version (1.0.44). In meinem Object stehts dann nicht Type = "Number" sogar "Mixed". Sieht aber immer noch gleich aus in Busmonitor.

`{
  "_id": "knx.0.Centrala_funktioner.Generella_funktioner.Datum_3-Byte",
  "type": "state",
  "common": {
    "name": "Datum 3-Byte",
    "type": "mixed",
    "role": "indicator",
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "DPT11.001",
    "address": "29/1/254",
    "addressRefId": "P-095B-0_GA-212",
    "statusGARefId": "",
    "actGARefId": "",
    "update": true,
    "objRef": "O-48_R-48",
    "devName": "M-0008_A-0000-01-9542",
    "devInst": "P-095B-0_DI-13",
    "objectSize": ""
  }`

**Comment by mpenn0** [comment]
@Videonisse 
Ja, das Problem besteht bei der Version 1.0.44 auch noch.

Ich probiere noch ein paar Sachen. Denn aus irgendwelchen Gründen war der type auf einmal "boolean". Wann und wie das dahin gekommen ist, weiß ich nicht. Bei 344 reinen KNX-Objekten hat man nicht alles immer im Blick.

Ich habe den type jetzt auch auf "mixed" gestellt und nur das write-Flag auf "true" gesetzt.

Kann sein, dass mein Titel nicht passt. Ich hätte mich gefreut, wenn mir ein KNX-Freak den unterschiedlichen "MessageCode" erklärt hätte. Das war am 24.September der einzige Unterschied.

Ich melde mich.

**Comment by chefkoch009** [comment]
Das ist mit V2.0.5 behoben
