### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by Percy2Live** [ioBroker/ioBroker.knx#116]
Hi,
this might be somehow related to #66 

I cannot import my ETS 5.7.4 project, no matter which iobroker knx version I tried (e.g. 1.0.20, 1.0.39, 1.0.42).

The log file states the following:

`

knx.0 | 2020-09-06 21:56:08.419 | warn | at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:234:41)
-- | -- | -- | --
knx.0 | 2020-09-06 21:56:08.419 | warn | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5313:34)
knx.0 | 2020-09-06 21:56:08.419 | warn | at Adapter.emit (events.js:198:13)
knx.0 | 2020-09-06 21:56:08.419 | warn | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:7072)
knx.0 | 2020-09-06 21:56:08.419 | warn | at _0x465449 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8493)
knx.0 | 2020-09-06 21:56:08.419 | warn | at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13499)
knx.0 | 2020-09-06 21:56:08.419 | warn | at Object._0x3a7cff [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40526)
knx.0 | 2020-09-06 21:56:08.419 | warn | at _0x2caea3 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38907)
knx.0 | 2020-09-06 21:56:08.419 | warn | at _0x4081bb (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38576)
knx.0 | 2020-09-06 21:56:08.419 | warn | at _0x3dee37 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:3508)
knx.0 | 2020-09-06 21:56:08.419 | warn | (1267) TypeError: Cannot read property 'replace' of undefined
knx.0 | 2020-09-06 21:56:08.415 | warn | (1267) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":586,"ack":false,"time":159

`

If I remember correctly the project was originally created with ETS v. 5.5.3

**Comment by Percy2Live** [comment]
@GermanBluefox  Can you confirm that this is related to #66 ?

**Comment by chefkoch009** [comment]
this was a bug in the importer. 
No further reportings since over a year.
