### ISSUE TITLE
GA werden bei 1.0.42 nicht richtig erkannt

### ISSUE THREAD

**Issue by mane444** [ioBroker/ioBroker.knx#117]
Ich habe einige GA die nach dem Import nicht richtig erkannt werden. Alle auf dem Screenshot zu sehenden GA sind gleich programmiert das Objekt "Laterne_schalten" wird aber nicht richtig erkannt und lässt sich leider auch nicht steuern.

![image](https://user-images.githubusercontent.com/59375254/92406689-f17a2d00-f138-11ea-8069-7e1a30191764.png)

Da es beim Import scheinbar immer wieder Probleme gibt, wäre es dann nicht besser wenn man alle Datenpunkte in einer Tabelle einlesen könnte und dann dort die Rückmeldeadressen zuordnen könnte?

**Comment by mane444** [comment]
Hier noch ein Nachtrag. 
Ich hab mich mal hingesetzt und verschieden Versuche gemacht. 
Die Erkennung der 5 Objekte beim Schalten funktioniert sobald ich bei den Gruppen die Bedieneinheit raus genommen habe und beim Kommunikationsobjekt des Schaltaktors das Bit "Lesen" deaktiviert habe. Das Bit "Lesen" ist aber beim Kommunikationsobjekt der Aktoren von Hensel grundsätzlich gesetzt.
Leider kann ich den Adapter so nicht einsetzen da ich den Iobroker nicht als alleinige Steuereinheit haben möchte.
Für meinen Fall wäre es besser der Adapter würde die Zuweisung von schalten und status nicht selbstständig machen sondern man müsste dies in einer Liste o.ä. händisch machen.
Vielleicht konnte ich euch mit diesen Erkenntnissen bei der Weiterentwicklung des Adapters helfen.

**Comment by mghomedev** [comment]
Ich habe übrigens ein ähnliches Problem. Das tritt erst in neueren Versionen vom ioBroker.knx auf:
Wenn auf einer Gruppenadresse auch nur ein Gerät das "Lesen" Bit aktiviert hat - obwohl noch ein anderes drauf ist was ein "Schreiben" Bit aktiviert hat, dann klassifizieren die neuren ioBrokern.knx-Importer die Adresse fälschlicherweise auch einfach nur als "Indikator"-Objekt, obwohl es ein Schaltobjekt sein sollte.

Tatsächlich war das früher "richtiger", wo er vermutlich einfach nur auf die Namen der Objekte geschaut hat, d.h. nur mit "_Status" ist Indikator ...

Das sollte man alles mal besser konfigurierbar machen

**Comment by mghomedev** [comment]
ich habe diverse Probleme im Import seit den letzten Versionen und auch schon Vorschläge/Patches zur Verbesserung an @chefkoch009  geschickt... er hat aber sehr viel zu tun zur Zeit. Ich hoffe, er kommt in den nächsten Wochen dazu, sie zu übernehmen

**Comment by RESDE** [comment]
@mane444 und @mghomedev Bestehen Eure Importprobleme immer noch? Neue Adapterversion installieren? Aonsonsten bitte den Issue auf gelöst setzen...
