### ISSUE TITLE
Bei Doppelt vergebenen Gruppenadresse passiert nichts

### ISSUE THREAD

**Issue by lammy000** [ioBroker/ioBroker.knx#119]
Ich hatte den Fehler das ich in einem Alten "Reserve" Objekt was ich mal Import habe die Gruppen Adresse /4/2/50 schon mal vergeben habe, diese habe ich dann in ETS aktualisiert und mit einem Temperatur Gerät verbunden. 
In iobroker hat der Adapter einfach nicht gehört wenn ich einen Wert auf die Gruppenadresse gesendet habe.
Ist das verhalten gewollt? Wenn ja wäre es geil wenn eine Fehlermeldung raus purzelt in der Log wie z.B. "Gruppenadresse doppelt vergeben oder so"

VG

**Comment by chefkoch009** [comment]
Eine doppelt vergebene Gruppenadresse? Wie geht das denn?
Wenn das Gerät nicht funktioniert, dann kommt ja auch keine Fehlermeldung: "Bitte Strom anschalten"
