### ISSUE TITLE
KNX-Adapter bringt Fehler im IOBroker Log - kann aber Werte lesen, nicht schreiben

### ISSUE THREAD

**Issue by Haeusele** [ioBroker/ioBroker.knx#12]
Hallo,

ich habe vorgestern IOBroker und den KNX-Adapter mit IOBroker installiert.
Mit openHAB 2.1 geht KNX. Beim IOBroker werden mir zwar Werte vom KNX-Bus angezeigt, aber wenn ich etwas schalten (also schreiben) will, wird der Wert vom KNX-Bus wieder gesetzt.

Im Log steht, dass er eine "uncaugth exception" hat. "Cannot read property '_id' of undefined".

Ein Eintrag im IOBroker-Forum habe ich hier gepostet:
http://forum.iobroker.net/viewtopic.php?f=20&t=7726

Was läuft da schief?

Viele Grüße und vielen Dank vorab
Tucca

**Comment by Apollon77** [comment]
War laut Forum gefixt oder ?!

**Comment by Haeusele** [comment]
Problem gelöst. Es lag wirklich an den "/" in den Gruppenadressen.

Wäre schön, wenn beim Import des Projekts gleich eine Warnung kommt oder im Log die Exception abgefangen wird, damit der Anwender sich selbst helfen kann.

Vielen Dank vorab
Tucca
