### ISSUE TITLE
Empfängt in Containerumgebung keine KNX Telegramme 

### ISSUE THREAD

**Issue by mthauth** [ioBroker/ioBroker.knx#120]
Hallo,

ich habe ein CentOS 8 mit podman.
Dort läuft ein pod mit dem buanet/iobroker Containerimage.
Leider empfange ich mit dem Adapter keine Telegramme. Auf den KNX Bus senden funktioniert.

Am Netzwerk kann es nicht liegen, da über den nodered ioBroker-Adapter im selben Container mit dem Node-Red Node "node-red-contrib-knx-ultimate" (https://flows.nodered.org/node/node-red-contrib-knx-ultimate) unter der gleichen Schnittstellenkonfiguration die Kommunikation in beide Richtungen funktioniert. Was macht der node-red Node anderes?

Anbei ein kleines Snippet, wie der Container gestartet wird:
```
# podman pod create --name smarthome \
  -p 8081:8081 \
  -p 8082:8082 \
  -p 1980:1980 \
  -p 1880:1880 \
  -p 3761:3761/udp \
  -p 1883:1883 \
  -p 9001:9001

# podman run -d --name iobroker --pod smarthome \
  -v /opt/smarthome/container/iobroker/data/:/opt/iobroker \
  buanet/iobroker:latest

```
Viele Grüße
Mike

**Comment by schnti** [comment]
Ich habe das selbe Problem.

**Comment by gre000** [comment]
bei mir genauso

**Comment by RESDE** [comment]
Hallo zusammen,

leider können wir keinen support des Adapters in einer Docker Umgebung übernehmen. Wir bitte um Verständnis.
Beste Grüße

**Comment by chefkoch009** [comment]
Nur mal so eine Idee am Rande: udp incoming muss erlaubt sein. Also 3671/UDP outgoing und UDP incoming. Ansonsten schliesse ich mich RESDE an.

**Comment by chefkoch009** [comment]
Netzwerk- und Routing Problematiken kann ich leider nicht behandeln, ebenso das Handling von VM's, da die verschiedenen Virtualisierungsumgebungen unterschiedlich damit umgehen.
