### ISSUE TITLE
Import von KNX Projektdatei schlägt fehl. Es werden nicht alle importiert

### ISSUE THREAD

**Issue by DennisKNX** [ioBroker/ioBroker.knx#121]
Hallo, 
bin recht neu hier und beschäftige mich mit dem Thema iobroker und KNX. Ich habe mich jetzt mit der Visu angefreundet und möchte die KNX Projektdatei importieren. Leider wird nur ein Teil importiert und ich kann keine Fehler feststellen.

ETS Version. 5.7.4
iobroker KNX Adapter Version 1.0.39

Ich hoffe mir kann jemand helfen. 

Danke vorab.

[iobroker.log](https://github.com/ioBroker/ioBroker.knx/files/5295342/iobroker.log)

**Comment by Percy2Live** [comment]
ETS 5.7.4 Import funktioniert leider unter gewissen Umständen nicht, siehe #116 
Bisher hat sich kein Entwickler dazu geäußert, müssen uns wohl noch etwas gedulden...

**Comment by danny70437** [comment]
Hi, ich habe mein KNX Projekt  (ETS 5.7.4) importiert. Es kam die Meldung "Es wurde 1294 Objekte extrahiert". 
Allerdings fehlen alle ca. 200 GA's der Mittelgruppe 1/1/x. Das Logfile sagt über diese Objekte/GA's nichts aus.

Bei 1/1/x handelt es sich um den Datentyp 1.001 (Schalten). Das Namesschema ist im ETS wie folgt aufgebaut:

1 Beleuchtung 
1/1 Schalten (Ein/Aus 1 Bit) - Neuanlage 
1/1/1 OG Schlagen Spots s
1/1/2 OH Wohnen Spots s
1/1/xx ...

Bei diversen GA's meiner Vaillant Steuerung (ist aber nicht wichtig) gibt es Log-Fehler [1]. 

Gerne kann ich Import-Tests machen, falls es was hilft. Ich würde mich freuen, wenn mein gesamtes Projekt importiert werden könnte (-:

Viele Grüße
Daniel




[1]

2020-10-03 21:50:59.144 | warn | (7942) Object Heizung___Lüftung.Vaillant_Heizung.Vaillant_Heizung_Systemstatus_Heizen_RMs is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
-- | -- | --
knx.1 | 2020-10-03 21:50:59.142 | warn | (7942) This object will not be created in future versions. Please report this to the developer.
knx.1 | 2020-10-03 21:50:59.142 | warn | (7942) Object knx.1.Heizung___Lüftung.Vaillant_Heizung.Vaillant_Heizung_Systemstatus_Standby_RMs is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
knx.1 | 2020-10-03 21:50:59.141 | warn | (7942) This object will not be created in future versions. Please report this to the developer.
knx.1 | 2020-10-03 21:50:59.141 | warn | (7942) Object Heizung___Lüftung.Vaillant_Heizung.Vaillant_Heizung_Systemstatus_Standby_RMs is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
knx.1 | 2020-10-03 21:50:59.138 | warn | (7942) This object will not be created in future versions. Please report this to the developer.

**Comment by danny70437** [comment]
>  ich habe mein KNX Projekt (ETS 5.7.4) importiert. Es kam die Meldung "Es wurde 1294 Objekte extrahiert".

bei mit ist der iobroker KNX Adapter v1.0.39 installiert

**Comment by RESDE** [comment]
@danny70437 Bestehen Deine Importprobleme immer noch? Dann schick mir mal die Projektdatei via PN. Ansonsten bitte den Issue als gelöst deklarieren (siehe Guthub Forumsregeln)

**Comment by DennisKNX** [comment]
Seit dem Umstellen der Gruppenadressen und  dem Update des KNX Adapters funktioniert es.
