### ISSUE TITLE
Temperatur manuell auslesen funktioniert nicht

### ISSUE THREAD

**Issue by steleatHome** [ioBroker/ioBroker.knx#122]
Hallo,
nach meinem Wechsel von openhab nach ioBroker arbeite ich gerade begeistert mit dem knx Adapter (1.0.42). Vielen Dank für diese tolle Implementation.
Nur mit dem Auslesen von Temperaturen gibt es gerade ein paar Probleme.

Einige Temperatursensoren schicken zyklisch per Write ihre Daten auf den Bus und diese werden auch richtig im ioBroker erkannt  und dargestellt.
Andere wiederum muss man abfragen, was ja entsprechend des hiddenfeatures in der Beschreibung auch kein Problem ist. Wenn ich nun also einen Wert 0 in den state hinein schreibe, dann wird der Lese-Prozess getriggered und ich sehe im Log-File auch den entsprechenden Hinweis, dass die Daten den ioBroker erreichen:

Log-File Auszug

`knx.0 | 2020-10-05 10:42:17.892 | info | (21568) RESPONSE single-array value : 23 auf knx.0.Temperatur.Temperatur_Schlafzimmer
-- | -- | -- | --
knx.0 | 2020-10-05 10:42:17.891 | info | (21568) RESPONSE : mappedName : Temperatur Schlafzimmer  dest : 4/2/6 val: 23 (DPT9.001) Temperatur_Schlafzimmer
knx.0 | 2020-10-05 10:42:17.891 | info | (21568) main.js: onGroupValue_Response from 4/2/6`

der zugehörige DPP sieht wie folgt aus: 
`{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1601885361490,
  "common": {
    "name": "Temperatur Schlafzimmer",
    "type": "number",
    "role": "value.temperature",
    "unit": "°C",
    "max": 670670,
    "min": -273,
    "read": true,
    "write": true
  },
  "native": {
    "dpt": "DPT9.001",
    "address": "4/2/6",
    "addressRefId": "P-033B-0_GA-153",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-11_R-81",
    "devName": "M-0008_A-C016-02-1019",
    "devInst": "P-033B-0_DI-15",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Temperatur.Temperatur_Schlafzimmer",
  "type": "state"
}`

Der Wert in den Objekte bleibt aber auf 0 °C. Nach dem Starten der Instanz wird der Read, anders als ich es der Dokumentation entnommen habe, bleibt der Wert auf null °C.
Wo kann der Fehler liegen?

Vielen Dank und Grüße
Steffen

**Comment by RESDE** [comment]
Hallo Steffen, 
ich hatte auch ein wenig Mühe, die Generierung der KNX/IOBroker Datenpaare (DPP) gemäß der Tabelle, die Chefkoch in seiner ausführlichen Beschreibung eingefügt hat. Wichtig: es liegt nicht an Chefkochs Formuliereungn oä, sondern eher an meinen sehr begrenztem KNX KnowHow... ;-) Ich denke, Du musst nochmals intensiver auf diese Tabelle schauen: Deine oben angegebenen GA scheint keine Groupwrite adresse zu sein (check die Flags in der ETS Software). Gleichzeitig ist diese GA sowohl lese auch als schreib-rechte zugeordnet.
Wenn ich die Chefkoch Tabelle richtig interpretiere kann im KNX Bus nur"R" Flags auf den Bus schreiben....
Grüße
Reiner

**Comment by Videonisse** [comment]
It's probably the same issue as with "GroupValueResponse is ignored": https://github.com/ioBroker/ioBroker.knx/issues/162
