### ISSUE TITLE
Fehlerhafter KNX Import

### ISSUE THREAD

**Issue by armintan** [ioBroker/ioBroker.knx#123]
Hallo,
nach dem Import der KNX Projektdatei, sehe ich bei mir vermutlich gleich mehrere Probleme, versuche aber hier eins nach dem anderen durch einfache Projektbeispiele zu adressieren. 

ETS Version. 5.7.4 (Build 1093)
iobroker KNX Adapter Version 1.0.42

Hier das erste Beispiel mit einem meiner Meinung nach fehlerhaft importiertem Rückmeldeobjekt, und fehlenden Zuordnungen zwischen Aktor- und Rückmeldeobjekt:
(Mein Testprojekt hat nur 4 Objekte, und diese auch importiert.)

Hier die Schalten-Kommunikationsobjekte in der ETS:
![Schalten KOs](https://user-images.githubusercontent.com/25298280/96366306-2f5e6e00-1147-11eb-9bff-997097e2b3d9.PNG)

Und hier die Rückmelde-Kommunikationsobjekte in der ETS:
![RM KOs](https://user-images.githubusercontent.com/25298280/96366315-41d8a780-1147-11eb-80d3-873e11d689ae.PNG)

Und hier das Resultat nach dem Import in ioBroker:
![iobroker_knx_objects](https://user-images.githubusercontent.com/25298280/96366326-5d43b280-1147-11eb-9a00-389622582109.png)

Hier die Details von "EG-A-W_Li Schalten RM":

```json
{
  "_id": "knx.1.Licht_und_Steckdose.Schalten_RM.EG-A-W_Li_Schalten_RM",
  "type": "state",
  "common": {
    "name": "EG-A-W_Li Schalten RM",
    "type": "boolean",
    "role": "value",
    "read": false,
    "write": true,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.011",
    "address": "1/2/19",
    "addressRefId": "P-0646-0_GA-141",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-43_R-154",
    "devName": "M-0083_A-000B-21-8C1C",
    "devInst": "P-0646-0_DI-33",
    "objectSize": ""
  },
  "from": "system.adapter.knx.1",
  "user": "system.user.admin",
  "ts": 1603020549681,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

Hier die Details von "EG-A-W_StD Schalten RM":
```json
{
  "_id": "knx.1.Licht_und_Steckdose.Schalten_RM.EG-A-W_StD_Schalten_RM",
  "type": "state",
  "common": {
    "name": "EG-A-W_StD Schalten RM",
    "type": "boolean",
    "role": "indicator",
    "read": true,
    "write": false,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.011",
    "address": "1/2/14",
    "addressRefId": "P-0646-0_GA-67",
    "statusGARefId": "",
    "actGARefId": "",
    "update": true,
    "objRef": "O-44_R-2073",
    "devName": "M-0004_A-1108-11-43DF-O000A",
    "devInst": "P-0646-0_DI-28",
    "objectSize": ""
  },
  "from": "system.adapter.knx.1",
  "user": "system.user.admin",
  "ts": 1603020549668,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Problem A:**
Dass "EG-A-W_Li Schalten RM" Rückmeldeobjekt eine state (write: true, read: false), während das "EG-A-W_StD Schalten RM" Rückmeldeobjekt ein indicator ((write: false, read: true) ist.

**Problem B:**
Die Zuordnung wischen Aktor und Rückmeldeobjekt funktioniert nicht, obwohl ich mir bei der Namensgebung der Gruppenadressen große Mühe gegeben habe, was aber einen Fehler meinerseits nicht ausschließt ;-).

Ich benutze KNX intensiv und iobroker is mein Automatisierungs- und Visualisierungsumgebung. 
Ich hoffe daher, dass mir jemand helfen kann. 

Vielen Dank schon mal vorab.

**Comment by ThorstenGTV** [comment]
Hallo,

gleiches Problem auch hier bei mir.

Erneuter Import des ETS-Projekts hat mir alle Objekte zerschossen. 
Beispiel erübrige ich mir da armintan das schon sehr gut dokumentiert hat ;-)

ETS Version. 5.7.4 (Build 1093)
iobroker KNX Adapter Version 1.0.42

Auch von mir schonmal ein dickes Dankeschön fürs Debugging 👍 

Viele Grüße
Thorsten

**Comment by mghomedev** [comment]
ich habe diverse Probleme im Import seit den letzten Versionen und auch schon Vorschläge/Patches an @chefkoch009 geschickt... er hat aber sehr viel zu tun zur Zeit. Ich hoffe, er kommt in den nächsten Wochen dazu, sie zu übernehmen

**Comment by ThorstenGTV** [comment]
Hallo zusammen,

als Workaround hat bei mir folgendes geholfen. 

1. Alle Objekte der knx.0 Instanz löschen
2. Downgrade auf die Adapter-Release 1.0.20 
3. Import der ETS Projektdatei (ETS 5.7.4)
4. Upgrade auf die Release 1.0.42

Viele Grüße
Thorsten

**Comment by spencer2785** [comment]
> Hallo zusammen,
> 
> als Workaround hat bei mir folgendes geholfen.
> 
>     1. Alle Objekte der knx.0 Instanz löschen
> 
>     2. Downgrade auf die Adapter-Release 1.0.20
> 
>     3. Import der ETS Projektdatei (ETS 5.7.4)
> 
>     4. Upgrade auf die Release 1.0.42
> 
> 
> Viele Grüße
> Thorsten

Gleiches Problem und genauso gelöst. Hoffentlich kann das Problem bald beseitigt werden.

**Comment by RESDE** [comment]
@armintan Schick mir mal bitte Deine ETS Projektdatei via PN, dann importiere ich mal in meiner Umgebung.
Warum hast Du eine zweite KNX Instanz eingerichtet? Normalerweise starten wir mit der Instanz 0, Du bist schon bei Instanz 1...

@ThorstenGTV ebenfalls bitte Deine ETS Datei via PN senden. Ich schaue mir das mal an...
Bei mir hatte ich die StatusGAs auch nicht sauber benannt, nach einer deutlichen Überarbeitung der Nomenklatur hatte alles sauber gefunzt...

**Comment by armintan** [comment]
@RESDE In der KNX Instanz läuft meine normales KNX Projekt. Die Instanz 1 habe ich nur für dieses Testprojekt angelegt, um die Fehlersuche zu vereinfachen.

Dumme Frage: Was genau ist PN?

**Comment by spencer2785** [comment]
> 
> Dumme Frage: Was genau ist PN?

@armintan Private Nachricht

@RESDE Dürfte ich dir auch mein Datei senden? Mit 1.0.42 oder neuer ging es bei mir nicht. Nur mit 1.0.20
Habe meine Nomenklatur auch überarbeitet aber komme trotzdem nicht weiter mit der neuen Version.

**Comment by RESDE** [comment]
persönliche nachricht siehe chat funktion im Forum, wenn Du mich als User aufrufst, gibt es oben ein Knopf mit drei Punkten (menü), dort dann Chat beginnen auswählen...klar schick die Datei ruhig mit...

    Am Mittwoch, 3. Februar 2021, 14:05:14 MEZ hat spencer2785 <notifications@github.com> Folgendes geschrieben:  
 
 



Dumme Frage: Was genau ist PN?


@armintan Private Nachricht

@RESDE Dürfte ich dir auch mein Datei senden? Mit 1.0.42 oder neuer ging es bei mir nicht. Nur mit 1.0.20
Habe meine Nomenklatur auch überarbeitet aber komme trotzdem nicht weiter mit der neuen Version.

**Comment by RESDE** [comment]
Hallo,
PN ist persönliche nachricht = chat function here im Forum.GrüßeReiner

    Am Dienstag, 2. Februar 2021, 23:47:52 MEZ hat armintan <notifications@github.com> Folgendes geschrieben:  
 
 


@RESDE In der KNX Instanz läuft meine normales KNX Projekt. Die Instanz 1 habe ich nur für dieses Testprojekt angelegt, um die Fehlersuche zu vereinfachen.

Dumme Frage: Was genau ist PN?

**Comment by RESDE** [comment]
@armintan:
hmmh ich denke, Du hast zwar die GA als Status definiert, aber semantisch kommt der Adapter damit nicht zurecht: es sollte so etwas wie Status schon in der Bezeichnung des entsprechenden GAs auftauchen, mit _RM kommen wir da nicht weit.
Konkret also 1x GA mit Bezeichnung xy Schalten und die korrelierende GA als Status mit zB. erweiterten Bezeichnung xy Schalten_Status. Dann sollte der Adapter auch beide Objekte im IOBroker miteinander "verknüpfen" was für die VIS von großem Vorteil ist. Diese Zuordnungsregel hilft bei 95% der anderen KNX Adapter user, Euch bekommen wir auch noch dahin....

@mghomedev 
Kannst Du mir Deine Vorschläge ebenfalls nochmals zusenden, damit wir die in den Issuebereich aufnehmen können?

**Comment by armintan** [comment]
@RESDE Danke für Deine Hilfe. Werde ich gleich morgen ausprobieren.
Vielleicht könntest du das so klar wie hier beschrieben in die Doku aufnehmen.

Dort steht:
_'In dem ETS-Export sind die Schalt- und Statusadressen nicht hinterlegt. Somit führe ich eine Ähnlichkeitsprüfung aller Gruppenadressnamen durch mit der Auswertung auf status und state. Wird ein Pärchen gefunden, dessen Ähnlichkeit mehr als 90% beträgt, dann wird angenommen, dass die GA1 die Schaltadresse und GA2 die Statusadresse ist.'_

Damit konnte zumindest ich das Problem nicht selbst lösen.
Danke nochmals.

**Comment by RESDE** [comment]
@armintan
hmmmh ich lese das bereits schon länger in der Doku...

https://github.com/ioBroker/ioBroker.knx#3-herausfinden-der-schalt--und-statusaddressen

aber Danke für den Hinweis.

**Comment by spencer2785** [comment]
@RESDE

ich habe nach der Chatfunktion geschaut im github, aber die gibts wohl nicht mehr. Bist du auch im iobroker.forum?

Grüße

**Comment by RESDE** [comment]
ja bin ich als RES_DE dort zu finden... sorry in github gibt es keine PN/Chatfunktion., hatte ich übersehen. Melde Dich im IOForum direkt an mich dann tauschen wir die Email adresse aus

**Comment by chefkoch009** [comment]
no further posts since feb 2020. So I close this issue.
