### ISSUE TITLE
DPT 5.100 Lüfterstufe wird nicht korrekt erkannt

### ISSUE THREAD

**Issue by cryptedx** [ioBroker/ioBroker.knx#124]
Hi,

ich möchte nur kurz darauf hinweisen, dass DPT 5.100 Lüfterstufe (0...255) nicht korrekt erkannt wird. Ich weiche nun aus auf DPT 5.005 Dezimalfaktor (0...255).

Gruß

**Comment by chefkoch009** [comment]
Danke für die Info.... wird im nächsten update mit drin sein.

**Comment by cryptedx** [comment]
Besten Dank!
