### ISSUE TITLE
Verbindungsprobleme zum KNX-Gateway, ioBroker kann sich nicht mit Gira KNX-Router verbinden

### ISSUE THREAD

**Issue by afeldt1957** [ioBroker/ioBroker.knx#125]
Hallo zusammen,
habe mir letzte Woche den Raspi4 mit dem ioBroker Image installiert, feste IP vergeben und soweit erst einmal alle relevanten Schnittstellen auf den neuesten Stand gebracht... System gibt grünes Licht.

Plattform: linux
RAM: 3.7 GB
Node.js: v12.19.1
NPM: 6.14.8
IP: 192.168.10.228

So, nun zum eigentlichen Problem:
Hatte den KNX-Adapter in der aktuellsten Version installiert, die Lizenz eingelesen und die Schnittstelle zu meinem GIRA IP-Router 2167 00 eingerichtet. 

Der GIRA KNX Router funktioniert mit der ETS.5 und auch mit meinem SmarthomeNG einwandfrei!!

Da der Router 4 Schnittstellen zur Verfügung stellt, also von 1.1.60 - 1.1.63, hatte ich mit der ersten Gruppenadresse angefangen..., der IP-Router ist im Netzwerk mit 192.168.10.250 sichtbar.
Als KNX Ethernetschnittstelle habe ich natürlich die richtige ETH0 und nicht den Loopadapter ausgewählt.

Egal, welche Gruppenadresse ich auswähle, die Connection wird nicht aufgebaut und die Instanz bleibt gelb, anbei einmal das Log:

host.iobroker | 2020-11-17 08:41:41.378 | info | instance system.adapter.knx.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
-- | -- | -- | --
knx.0 | 2020-11-17 08:41:40.857 | info | (4579) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
knx.0 | 2020-11-17 08:41:40.854 | info | (4579) terminating
knx.0 | 2020-11-17 08:41:40.850 | info | (4579) Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2020-11-17 08:41:40.848 | info | stopInstance system.adapter.knx.0 send kill signal
host.iobroker | 2020-11-17 08:41:40.842 | info | stopInstance system.adapter.knx.0 (force=false, process=true)
host.iobroker | 2020-11-17 08:41:40.838 | info | "system.adapter.knx.0" disabled
knx.0 | 2020-11-17 08:41:40.394 | info | (4579) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-11-17 08:41:40.393 | info | (4579) ... not able to close connection, because already closed
knx.0 | 2020-11-17 08:41:40.389 | info | (4579) Connection persists.....closing now
knx.0 | 2020-11-17 08:41:38.387 | info | (4579) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 00 00 00 00 b4 e1 08 01 c0 a8 0a e4 b4 e1 04 04 02 00 sent to 192.168.10.250:3671
knx.0 | 2020-11-17 08:41:38.385 | info | (4579) Connected - local UDP Server listening on 192.168.10.228:46305
knx.0 | 2020-11-17 08:41:38.381 | info | (4579) Event : UDP - listening
knx.0 | 2020-11-17 08:41:38.376 | info | (4579) Debuglevel: 2 3
knx.0 | 2020-11-17 08:41:38.369 | info | (4579) Connecting to knx GW: 192.168.10.250:3671 with phy. Adr: 1.1.61
knx.0 | 2020-11-17 08:41:38.366 | info | (4579) knx license is OK.
knx.0 | 2020-11-17 08:41:38.204 | warn | (4579) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!
knx.0 | 2020-11-17 08:41:38.173 | info | (4579) starting. Version 1.0.39 in /opt/iobroker/node_modules/iobroker.knx, node: v12.19.1, js-controller: 3.1.6
host.iobroker | 2020-11-17 08:41:36.868 | info | instance system.adapter.knx.0 started with pid 4579

Hat jemand eine Idee, was hier falsch läuft??
Alexander

Siehe auch meine bisher installierten Instanzen, also recht wenig..:
![ioBroker](https://user-images.githubusercontent.com/57762030/99360605-27fac380-28b1-11eb-947a-236b0411aa46.jpg)

**Comment by chefkoch009** [comment]
Die Adresse die Du in den Adapter einträgst sollte nicht 1.1.60 - 1.1.63 sein....die gehören ja dem Gateway. Du vergibst eine beliebige frei Adresse. Und der Adapter sollte aktiv sein...in deiner Abbildung ist er deaktiv.

**Comment by afeldt1957** [comment]
Hallo Chefkoch009,
hm, habe die EIB Adresse einmal auf 1.1.100 geändert, die wird garantiert nicht verwendet..., aber der Adapter will noch immer nicht starten... siehe Log:

knx.0 | 2021-01-19 06:39:18.995 | info | (1299) terminating
-- | -- | -- | --
knx.0 | 2021-01-19 06:39:18.995 | info | (1299) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-01-19 06:39:18.994 | info | (1299) ... not able to close connection, because already closed
knx.0 | 2021-01-19 06:39:18.992 | info | (1299) Connection persists.....closing now
knx.0 | 2021-01-19 06:39:18.990 | info | (1299) Got terminate signal TERMINATE_YOURSELF
host.iobroker | 2021-01-19 06:39:18.989 | info | stopInstance system.adapter.knx.0 send kill signal
host.iobroker | 2021-01-19 06:39:18.986 | info | stopInstance system.adapter.knx.0 (force=false, process=true)
host.iobroker | 2021-01-19 06:39:18.985 | info | "system.adapter.knx.0" disabled
knx.0 | 2021-01-19 06:39:18.834 | info | (1299) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 00 00 00 00 95 6d 08 01 c0 a8 0a e4 95 6d 04 04 02 00 sent to 192.168.10.250:3671
knx.0 | 2021-01-19 06:39:18.831 | info | (1299) Connected - local UDP Server listening on 192.168.10.228:38253
knx.0 | 2021-01-19 06:39:18.823 | info | (1299) Event : UDP - listening
knx.0 | 2021-01-19 06:39:18.815 | info | (1299) Debuglevel: 2 3
knx.0 | 2021-01-19 06:39:18.802 | info | (1299) Connecting to knx GW: 192.168.10.250:3671 with phy. Adr: 1.1.100
knx.0 | 2021-01-19 06:39:18.797 | info | (1299) knx license is OK.
**_knx.0 | 2021-01-19 06:39:13.626 | warn | (1299) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!_**
knx.0 | 2021-01-19 06:39:13.595 | info | (1299) starting. Version 1.0.39 in /opt/iobroker/node_modules/iobroker.knx, node: v12.19.1, js-controller: 3.1.6
host.iobroker | 2021-01-19 06:39:12.270 | info | instance system.adapter.knx.0 started with pid 1299

auch, dass der Adapter veraltet ist, wundert mich ein wenig..
Idee??

**Comment by afeldt1957** [comment]
habe dem KNX-Adapter einmal die 1.1.254 als EIB-Adresse gegeben, leider auch ohne Erfolg.

Idee?

**Comment by RESDE** [comment]
@afeldt1957 
hmmmh .... Dein IObroker.host beendet den KNX Adapter, siehe oben... das hat wohl die Ursache im IOBroker host vermute ich. Ich hatte auch einmal Probleme mit den userrechten für die Adapter etc. Hast Du den IOBroker sehr aufwendig mit Zugriffsrechten per Adapter ausgestattet. wie sieht es mit der IOBroker installation aus, ganz normaler Standard oder auf der Betriebssystemebene andere Zugriffsrechte der IOBroker Instanz vergeben?

**Comment by micha-hein** [comment]
Hallo, ich habe das gleiche Problem mit dem gleichen IP Router. Wie wurde denn dein Problem nun behoben?

**Comment by afeldt1957** [comment]
tja, leider hatte bisher keiner eine richtige Idee bzw. Lösung...
Damit ist das Projekt für mich gestorben, denn ohne Kommunikation zum KNX bringt dies alles nichts..

**Comment by RESDE** [comment]
@afeldt1957 hatte Dir Fragen gestellt ohne Antworten von Dir.... siehe oben. Ich selbst nutze auch den Gira X1, der hat die KNX Schnittstelle ebenfalls integriert.

**Comment by afeldt1957** [comment]
ich benutze das Raspi Image und habe dann entsprechend KNX einfach installiert.
Alle anderen Adapter arbeiten ja und die Updates konnten auch alle einwandfrei installiert werden.

Welche Rechte in welchem Unterverzeichnis müssen denn welche Werte haben??

**Comment by micha-hein** [comment]
Also ich habe den IOBroker in einem Debian als VM auf einer Qnap NAS laufen. Die sonstigen Adapter funktionieren. Die Installation aller Adapter erfolgte ohne Änderung irgendwelcher benutzerrechte. Hatte bis vor kurzem auch einen Hager TH210 erfolgreich laufen, leider ist dieser nun defekt.

**Comment by RESDE** [comment]
Bei mir funzt die Gira Hardware und der KNX Adapter einwandfrei.... ich kenne auch fünf weitere Nutzer der Gira Schnittstelle die alle keine Probleme haben, Also es liegt also nicht am IOBroker adapter....
aktualisiere mal den KNX Adapter auf die aktuellste Version, Du bist noch auf der 0.1.39, aktuelle ETS Software Version wird aber noch nicht klappen..... chefkoch arbeitet an einem Update vermute ich.
Kannst Du mir der Gira Schnittstelle auch per ETS Software auf Deinen KNX Bus zugriefen sprich die Geräte programmieren, Bus Monitoring anschalten etc?

**Comment by micha-hein** [comment]
Also ich habe parallel im KNX Forum gepostet und für mich eine Lösung finden können. Bei mir war der Adapter 1.39 als letzter stabiler installiert nun habe ich auf Anraten des Forums auf 1.44 (Beta) upgedatet. Und seid dem läuft der Adapter wieder.

**Comment by chefkoch009** [comment]
Vielen Dank für dein feedback. Das freut mich. Somit schliesse ich also diesen Issue.
