### ISSUE TITLE
DPT 14.039 Länge (m) wird nicht korrekt erkannt

### ISSUE THREAD

**Issue by savek-cc** [ioBroker/ioBroker.knx#126]
Meine Wetterstation liefert eine "Standorthöhe" in Meter; in ETS wird diese korrekt angezeigt; in ioBroker sind es dann aber nur noch "2m" (anstelle von 210,3171m).

Hier die original-Daten:

```
Eigenschaft | Wert
-- | --
RawData | 29 00 BC E0 11 50 44 27 05 00 40 43 52 51 2E
MessageCode | LDataInd
Source | 1.1.80
SourceName | Wetterstation Universal
Destination | 8/4/39
DestinationName | A4 Dach-Wetterstation.GPS.Standorthöhe
RepeatedFlag | False
Acknowledge | Ack
ConfirmFlag | False
RoutingCounter | 6
Priority | Low
FrameFormat | Standard
Service | vom Bus
LocalizedType | GroupValueResponse
Security |  
TPCI | T_Data
APCI | APciGroupValueResponse
DataPointType | 14.039 Länge (m)
DecodedDpValue | 43 52 51 2E \| 210,3171 m
RawDpValue | 43 52 51 2E
```

Hier das Objekt in ioBroker:
```
{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1605603589761,
  "common": {
    "name": "A4 Dach-Wetterstation.GPS.Standorthöhe",
    "type": "number",
    "role": "value",
    "unit": "m",
    "max": "",
    "min": "",
    "read": true,
    "write": true,
    "update": false,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "900",
        "retention": 0,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {
    "dpt": "DPT14.039",
    "address": "8/4/39",
    "addressRefId": "P-0193-0_GA-2473",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-21_R-100",
    "devName": "M-0004_A-B00D-21-A4D0-O00F4",
    "devInst": "P-0193-0_DI-47",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Geräte.Außen.A4_Dach-Wetterstation_GPS_Standorthöhe",
  "type": "state"
}
```

**Comment by strackm** [comment]
Es scheint ein generelles Problem mit DPT 14.XXX zu sein, bei mir ist es DPT 14.027 der anstelle 30V nur 3V anzeigt.

Außerdem habe ich noch das hier gefunden: https://forum.iobroker.net/topic/36222/dpt-14-056 
Dabei handelt es sich auch um das gleiche Problem.

**Comment by chefkoch009** [comment]
Ich kann dies leider nicht reproduzieren. ETS<=>iobroker zeigen die korrekten Werte an. 
Was ist das Ergebnis bei z.B.: 3.123 m ?

**Comment by strackm** [comment]
Bei mir war es ja DPT 10.027. Wollte gerade entsprechende Screenshots machen und habe erfreulicherweise festgestellt, dass jetzt alles passt. 
Kann es mir zwar nicht erklären, da ich das Problem zuvor permanent reproduzierbar hatte und seit meinem letzten Post zumindest an der Stelle nichts mehr geändert habe.
Hab zwar generell noch Updates etc. gemacht aber kann mir nicht erklären was zur Lösung geführt hat

**Comment by savek-cc** [comment]
Bei mir sind es immernoch 2m (manchmal sprigt es auch auf 1m, da es ziemlich genau 200m sind uns das Signal manchmal auch 198m oder so etwas gehauptet).
Was kann/soll ich an Debug-Daten liefern? (Kann auch wie oben gefragt Werte über ETS scheiben und schauen, was bei IoBroker ankommt)

**Comment by RESDE** [comment]
@savek-cc Hallo, ich habe mal Deinen Datentyp in meiner DTS nachgebaut und den Wert 210,31,,,, auf den Bus geschickt. Im IOBroker kommt der Wert auch als Gleitkommawert an.
 Dein Problem konnte ich daher nicht nachstellen
![image](https://user-images.githubusercontent.com/59728312/106657793-bf141500-659c-11eb-888e-38e29ab726de.png)

mach besser mal ein update auf den neueste KNX Adapterversion...

Hast Du auch einen Empfänger der Meterangabe in der ETS? Falls nicht, lege auch einen Empfänger des GA Werts in der ETS an, damit der Bus auch sauber die Kommunikation zwischen Sender und Empfänger abbildet...

**Comment by Videonisse** [comment]
The issue should be solved in v.2.0.3 or later, I have verified other DPT 14.x values that wasn't working correctly before. @savek-cc Can you verify and close if fixed.

**Comment by chefkoch009** [comment]
The initial post ist very old, so @Videonisse , if you have verified this, I trust you that the problem has gone.
