### ISSUE TITLE
knx-Adapter startet laufend neu - adapter.objects.getObjectView is deprecated

### ISSUE THREAD

**Issue by stromer70** [ioBroker/ioBroker.knx#127]
5821) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!

**Comment by chefkoch009** [comment]
issue title does not match issue. for issue titel: this already is fixed.

**Comment by chefkoch009** [comment]
for the warning message exists an issue.
