### ISSUE TITLE
KNX Import aus ETS 4 schreibt keine Datenpunkte (DPT) in den Adapter. 

### ISSUE THREAD

**Issue by malotira** [ioBroker/ioBroker.knx#128]
Trotz Dr.Google, schaffe ich es nicht mein Problem selbständig zu lösen.

Ich nutze in Kombination mit dem IO Broker den KNX-Adapter von Chefkoch.
Leider werden nicht die richtigen Schalt- und Statusadressen an den KNX-Adapter übertragen.
Nach folgender Syntax (https://github.com/ioBroker/ioBroker.knx) habe ich die Gruppenadressen benannt... 

- Fürs schalten: 	Obergeschoss_Buero_Licht_Decke_schalten_Ein_Aus_Status
- Für den Status: 	Obergeschoss_Buero_Licht_Decke_schalten_Ein_Aus

![KNX_IOBroker](https://user-images.githubusercontent.com/75495277/101199582-67713000-3665-11eb-82af-f599f62db2c0.jpg)

Folgende Flags und Datentypen habe ich gesetzt wie folgt:

- 6-Fach Taster: Datentyp = 1.001 Schalten Flag = K L Ü
- Schaltaktor: Datentyp = 1.001 Schalten Flag = K S

![KNX_ETS](https://user-images.githubusercontent.com/75495277/101199648-7e178700-3665-11eb-8ff2-f304e7fed973.jpg)

Der Export erfolgt aus einer ETS4 Version. Der KNX Adapter in IO Broker hat die Version 1.0.42.
Wenn ich das richtig verstanden habe, wird der Import aus ETS 4 und ETS 5 unterstützt.
Wenn ich die Raw view richtig interpretiere, dann werden die DPT ("dpt": "",) nicht mitgenommen. Ein Downgrade auf eine ältere Version hat leider auch nichts gebracht.

Kennt jemand das Problem? Lässt sich das irgendwie lösen? Eventuell durch eine Bestimmter Version des Adapters?

![IO01](https://user-images.githubusercontent.com/75495277/101199678-866fc200-3665-11eb-9788-3e529bc728ae.jpg)

**Obergeschoss Buero Licht Decke schalten Ein/Aus**
`{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1606925330601,
  "common": {
    "name": "Obergeschoss Buero Licht Decke schalten Ein/Aus",
    "type": "mixed",
    "role": "level",
    "min": 0,
    "max": 1,
    "read": false,
    "write": true
  },

  "native": {
    "dpt": "",
    "address": "2/0/110",
    "addressRefId": "P-05E7-0_GA-385",
    "statusGARefId": "P-05E7-0_GA-387",
    "actGARefId": ""
  },

  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },

  "_id": "knx.0.Obergeschoss.Obergeschoss_Licht_und_Steckdosen_schalten_Ein_Aus.Obergeschoss_Buero_Licht_Decke_schalten_Ein_Aus",
  "type": "state"`

**Obergeschoss Buero Licht Decke schalten Ein/Aus Status**

`{
  "_id": "knx.0.Obergeschoss.Obergeschoss_Licht_und_Steckdosen_Schalten_Ein_Aus_status.Obergeschoss_Buero_Licht_Decke_schalten_Ein_Aus_Status",
  "type": "state",
  "common": {
    "name": "Obergeschoss Buero Licht Decke schalten Ein/Aus Status",
    "type": "mixed",
    "read": true,
    "write": false,
    "role": "indicator",
    "min": 0,
    "max": 1
  },

  "native": {
    "dpt": "",
    "address": "2/1/112",
    "addressRefId": "P-05E7-0_GA-387",
    "statusGARefId": "",
    "actGARefId": "P-05E7-0_GA-385"
  },

  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1606925330338,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
`

**Comment by chefkoch009** [comment]
Hallo, 

entferne mal bitte die Kombi Ein/Aus aus den Gruppenadressbezeichnungen. "Schalten" selbst inmpliziert schon das "ein" und "aus".

VG chefkoch009

**Comment by malotira** [comment]
Hallo Chefkoch,

wie in deiner Empfehlung, habe ich testweise den Zusatz Ein/Aus mal für diese spezifische Gruppe entfernt und die Datei neu importiert. 
Leider bleibt "dpt": "" immer noch leer.

**Obergeschoss_Buero_Licht_Decke_schalten** 


`{
  "_id": "knx.0.Obergeschoss.Obergeschoss_Licht_und_Steckdosen_schalten.Obergeschoss_Buero_Licht_Decke_schalten",
  "type": "state",
  "common": {
    "name": "Obergeschoss Buero Licht Decke schalten",
    "type": "mixed",
    "read": false,
    "write": true,
    "role": "level",
    "min": 0,
    "max": 1
  },
  "native": {
    "dpt": "",
    "address": "2/0/110",
    "addressRefId": "P-05E7-0_GA-385",
    "statusGARefId": "P-05E7-0_GA-387",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1607197413166,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
`



**Obergeschoss_Buero_Licht_Decke_schalten_Status**  

`{
  "_id": "knx.0.Obergeschoss.Obergeschoss_Licht_und_Steckdosen_schalten.Obergeschoss_Buero_Licht_Decke_schalten",
  "type": "state",
  "common": {
    "name": "Obergeschoss Buero Licht Decke schalten",
    "type": "mixed",
    "read": false,
    "write": true,
    "role": "level",
    "min": 0,
    "max": 1
  },
  "native": {
    "dpt": "",
    "address": "2/0/110",
    "addressRefId": "P-05E7-0_GA-385",
    "statusGARefId": "P-05E7-0_GA-387",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1607197413166,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
`

![2020-12-05_20-58-33](https://user-images.githubusercontent.com/75495277/101262142-b8a02300-373c-11eb-8126-c66b5662ccfc.jpg)

**Comment by malotira** [comment]
Würde es helfen? Wenn ich meine Exportdatei zur Verfügung stelle?￼

**Comment by malotira** [comment]
@chefkoch009 

Wollte fragen ob du eventuell eine Idee hast woran es liegt bzw. ob es sich hier um ein bug handelt?

Mir ist klar das du viel zu tun hast. Würde mich über ein Kleines Feedback freuen.

Würde dir gerne meine Exportdatei zur Verfügung stellen.

**Comment by malotira** [comment]
@chefkoch009 

Ich denke dass du viel zu tun hast. Vor allen Dingen entwickelst du diesen Adapter bekanntermaßen in deiner Freizeit. Dafür bin ich dir sehr dankbar, da für mich der IOBroker ohne deinen Adapter nur wenig Sinn machen würde. Für mich ist dein Adapter ganz klar eine Kernkomponente.￼

Eventuell hast ein kleines Update für mich....Vielleicht entwickelst du ja schon eine neue Version deines Adapters und die dieser Fehler wir damit obsolet.

**Comment by malotira** [comment]
Hallo Chefkoch, Mir ist wirklich bewusst, dass du das ganze Projekt freiwillig stemmst und die Entwicklung des Adapters in deiner Freizeit machst. Großes Dankeschön an dieser Stelle dafür!!!

Mir ist auch bewusst dass du viele Anfragen über E-Mail und in diversen Foren bekommst. Bleibt wahrscheinlich wenig Zeit diese alle zu bearbeiten.￼￼

Aber es ist natürlich auch auf meiner Seite sehr frustrierend wenn so gar keine Antwort mehr kommt auch wenn ich die GrundProblematik verstehe.   

Nach wie vor würde ich mich über deine Hilfe freuen :-)￼￼

**Comment by malotira** [comment]
@RESDE 
Erste mal möchte ich mich bei dir bedanken das du dich meinem Thema angenommen hast! Auch das du dich so intensiv mit meiner Problematik beschäftigt hast.

`1.	der Schaltaktor wird m.E. korrekt mit dem S Flag "angesprochen", aber wieso setzt Du das L Flag beim Taster? Bei mir setzt der Taster einfach die GA fürs Schalten ab (Flag Ü, kein L) und wartet auf die Statusrückmeldung vom Aktor mit einem KO Objekt Flag S. Kannst ja mal versuchen ob der Taster auch ohne das L Flag funktioniert `

**Zu1**
Das L-FLAG (Read) ist bei meinem MDT Glastaster immer gesetzt, damit dieser Leseanfrage beantworten kann. Damit kannst du zum Beispiel abfragen ober der entsprechende Taster gesperrt ist.  Ich werde aber mal Testweise das L-FLAG entfernen.

`2.	Fürs Schalten benennst Du die GA Adresse mit Status und für den Status nimmst Du dann nicht einen "hilfseintragsergänzung" = status. Das würde ich genau umgekehrt machen: die GA für das Schalt KO sollte keinen Status oder ähnliches im Namen haben, die StatusGA natürlich ein StatusHinweis`

**Zu2**
Ich hatte die Benennung der Gruppenadresse nach den Vorgaben von Cherfkoch gemacht. 

- Die Gruppenadresse für das Schalten = „Obergeschoss_Buero_Licht_Decke_schalten“

- Die Gruppenadresse für den Status =“Obergeschoss_Buero_Licht_Decke_schalten_Status“

Ich würde aber auch diese nach deinem Vorschlag anpassen… also:

- Die Gruppenadresse für das Schalten = „Obergeschoss_Buero_Licht_Decke_schalten“

- Die Gruppenadresse für den Status =“Obergeschoss_Buero_Licht_Decke_Status“

`3.	Die Hinweise Ein/aus in der GA Bezeichnung besser nicht verwenden.`

**Zu3**
Die Bezeichnung "Ein/Aus" habe bei meinem letzten Test entfernt ....leider ohne Erfolg (siehe Eintrag/Antwort vom 05.12).


`4.	Beim Schaltaktor dann auch das KO Objekt für die Statusrückmeldung an den Bus (und damit z.B. an den Taster) aktivieren und dann die Status GA dahin richtig verknüpfen. Oder hast Du die Status GA schon mit dem Aktor und Taster ausgestattet, dann sollte das ja klappen. So sieht es aus, dass Du beim Thema Status an ein Flag in der ETS "denkst", das sollte aber eine separate eigenständieg GA sein, die zwischen den KOs der ETS auf den Bus hin und herreist."`

**Zu4**
Ich bin mir bei deinem Punkt 4 nicht ganz sicher was du meinst? Der Schaltaktor und der Taste befinden sich in der gleichen GA.

**Comment by RESDE** [comment]
Hallo,
zu 1:
das L Flag gibt es beim MDT Taster nur bei den wenigen Ausgängen. Sonst haben  die dort nichts zu suchen und wären m.E. falsch. Nur S Flags teilweise.
zu 2: nein Deine Vorgabe von Chefkoch ist richtig, so wie Du es im letzten Post richtig geschrieben hattest. In Deinem ersten Post sind das andere Bezeichnungen.
zu 5) der MDt Glastaster hat den Schaltkanal  nur das K und Ü Flag (kein S oder L). Beim Schaltaktor dagegen wird das K und S beim Schaltkanal gesetzt, das Status KO Rückmeldeobjekt  bekommt dagegen ein L und Ü Flag.
Irgendwie hast Du alle Flags komplett invertiert wie ich bei meinen funktionierenden... Seltsam

**Comment by malotira** [comment]
@RESDE 
Vielen Dank noch mal für deine Antwort... ich würde mal 1zu1 deinen Vorschlag umsetzen und die Flags entsprechend setzen. Jetzt aber noch mal für die alten Männer:
GA= **Obergeschoss Buero Licht Decke schalten**
![schalten](https://user-images.githubusercontent.com/75495277/108269898-efe47480-716e-11eb-99cd-3ad021526303.jpg)
Welche FLAGS Soll ich hier setzen für den Taster (Schalter) und welche für den Aktor (Schalten)?

GA=**Obergeschoss Buero Licht Decke schalten Status**
![status](https://user-images.githubusercontent.com/75495277/108269999-173b4180-716f-11eb-893b-564003222a11.jpg)
Welche FLAGS Soll ich hier setzen für den Taster (Wert für Umschaltung) und welche für den Aktor (Status)?

**Comment by malotira** [comment]
Hallo zusammen, ich konnte nun bei einem Bekannten das ganze über ETS5 einspielen und den entsprechenden Export ziehen. Und siehe da, jetzt erkennt der Adapter alles richtig. Anscheinend ist was beim Parsing von ETS 4 Dateien schief gegangen. 

Schade das, dass Skript nicht abwärtskompatibel ist.￼￼￼

**Comment by RESDE** [comment]
Hallo, der KNX Adapter kann das nicht leisten, da zwischen der ETS 4 und der ETS 5 Version hat sich in der Software sehr viel geändert. Selbst ETS4 Projekte müssen konvertiert werden in die ETS 5 Version und können nicht einfach mal so geöffnet und weiterbearbeitet werden. 
Da die Mehrzahl der KNX Adapter User aber bereits auf der ETS5 arbeiten, könntest Du einen alten Adapter (siehe Adapter Historie Angaben) verwenden. Leider gibt hier die ETS und die ETS Community den Takt an. Win 3.1 software lässt sich auch nicht mehr in der Win10 Maschine installieren....

**Comment by malotira** [comment]
Der Vergleich Win10 zu Win3.1 hinkt etwas. Auch bei Windows werden mindestens die letzten 2-3 Versionen unterstützt. Aber ich weiß schon was du meinst. 

Der Import von ETS4 Projekten in ETS5 war kein Problem. Auch im Anschluss war die Programmierung der KNX Komponenten aus ETS5 kein Problem.

Auch der Export aus der ETS5 ähnelt von der Syntax her den Export aus der ETS4 Software. Natürlich möchte ich mir nicht anmaßen, bei einer Gratis Software zu meckern. ￼Ich kann schon gut verstehen, das sich der Aufwand zu Pflege so eines Adapters sich in Grenzen halten muss.

Wie auch immer.... ich habe zumindest einen guten WorkAround gefunden. Eine ETS 5 Software kaufe ich trotzdem nicht.... bleibe dann lieber bei ETS4.... Mal schauen was ETS 6 bringt.

**Comment by chefkoch009** [comment]
Ich habe in V2.0.5 den Importfilter für ETS4 projekte überarbeitet/angepasst. damit sollte es laufen.
