### ISSUE TITLE
ETS-Inside?

### ISSUE THREAD

**Issue by oe8bck** [ioBroker/ioBroker.knx#129]
Hi,

Thanks in general for this adapter, it makes ioBroker usable for my setup!

I have to admit, that this posting is in the wrong location. This is not an issue it's more a general question/feature request.

To be honest, I'm not so deep into the KNX-"universe". I just took over the (ETS5-)Configuration from the guys who installed our new electric setup. To configure/fine-tune the system I did not want to spend €1000,- for our small system, so I decided to use ETS-Inside. I just imported the KNXROJ-file into ETS-Inside - this worked.

To include this in my ioBroker eco-system, I also imported the KNXPROJ-file to the KNX-adapter as proposed in the documentation. It worked flawlessly, because the naming was consistent. Now I can interact with the lights and the buttons ;-)

But I would also like to incorporate the heating system in KNX and ioBroker. This was not done to the end from the professionalists, they just did a basic setup. In ETS-Inside I can see the actor/RTR device with address 1.1.42. I can read also the temperatures of the light switches, e.g. one with address 1.1.13. 

When I look into the ioBroker objects, I can find a temperature value with address 2.2.40. But I do not know where it comes from. If I add a function in ETS-Inside as proposed in https://support.knx.org/hc/de/articles/214497725-Funktionen-erstellen-und-mit-Ger%C3%A4ten-verbinden I get an address of e.g. 3/0/12 for the actual temperature. This I can link to the temperature sensor 1.1.13.

After adding the function in ETS-Inside, I downloaded it in ETS5 (Freeware) and then wanterd to export it to a KNXPROJ-file. But this failes as I do not have a proper license :-( 

I have to admit that now I am a little bit lost. What is the way to go? How can I add the new objects in ioBroker?

**Comment by oe8bck** [comment]
I got this message in the log:

```knx.0 | 2020-12-10 09:04:21.625 | info | (1225662) Value received on unknown GA : 3/0/12 -- | -- | -- | --```

How to create a proper object manually?

**Comment by chefkoch009** [comment]
Hello,

your log says, that the adapter has recognized a value from a GA, which it doesn't know. You can add a new object in the right place in knx.0 tree and compare the entries with other knx-adapter objects and set them into right way. Then restart the adapter. That's all.
