### ISSUE TITLE
Datentyp 7.007 Zeit (h) not working

### ISSUE THREAD

**Issue by CarminKern** [ioBroker/ioBroker.knx#130]
Unfortunately, receiving the value 7.007 does not work. IOBroker always receives the value NULL... It is worth a hexadecimal integer. Solutions?
![image](https://user-images.githubusercontent.com/38145343/101817120-393a9700-3b22-11eb-8576-20c520df6069.png)
![image](https://user-images.githubusercontent.com/38145343/101817152-435c9580-3b22-11eb-8933-0b4cf6cc727f.png)
![image](https://user-images.githubusercontent.com/38145343/101817239-625b2780-3b22-11eb-9996-1be71136c786.png)

**Comment by chefkoch009** [comment]
I'm not able to reproduce this behavior. In my environment it works as expected. Can you give me the RAW informations of "Linie_1_0_Betriebsstunden" ? Is your object set readable in ETS? Flags "KLÜ" should be set.

**Comment by CarminKern** [comment]
![image](https://user-images.githubusercontent.com/38145343/105035673-b0394880-5a5b-11eb-8422-8bedd34ca210.png)

**Comment by RESDE** [comment]
@CarminKern 
As chefkoch suggested, please post your RAW information of the relevant IOBroker object (edit section of each IO Broker object right hand side, then last tab/section with full view on this object)

**Comment by CarminKern** [comment]
Ah ok Sorry
`{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1608397909077,
  "common": {
    "name": "Betriebsstunden seit Neustart〚1/0/2〛",
    "type": "number",
    "role": "value",
    "unit": "h",
    "max": 65535,
    "min": 0,
    "read": true,
    "write": true,
    "update": true
  },
  "native": {
    "dpt": "DPT7.007",
    "address": "10/5/1",
    "addressRefId": "P-05DD-0_GA-356",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-241_R-12",
    "devName": "M-0083_A-0056-11-A826",
    "devInst": "P-05DD-0_DI-3",
    "objectSize": ""
  },
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "knx.0.Funktionen.Messfunktionen.Betriebsstunden_seit_Neustart〚1_0_2〛",
  "type": "state"
}`

**Comment by RESDE** [comment]
Hi there
the read and write flags which are both true: this is tricky... please change the read flag = false. Restart the adapter and the check out if values are lying into the IOBroker state.
Are you using this GA in any other KNX device? Please share then.

**Comment by CarminKern** [comment]
Unfortunately, this did not lead to any change.

I have tried the following combinations
R W U
1  1  1
0  1  1
0  0  1
1  0  1
0  0  0
1  0  0
0  1  0
1  1  0

Adapter restarted,
Iobroker restarted...

no change :/

**Comment by RESDE** [comment]
Please send me your ETS file I'll try to import it and analyse it then. You can find me inIOBroker forum as RES_DE user.
Regards
Reiner

**Comment by RESDE** [comment]
Any further support required?

**Comment by chefkoch009** [comment]
seems not.
