### ISSUE TITLE
File index_m.html not found

### ISSUE THREAD

**Issue by Smassard82** [ioBroker/ioBroker.knx#131]
Hi;

After an upgrade from 1.0.39, i cant access the configuration panel: File index_m.html not found.
Ver. 1.0.41. also works fine.

I tried several tips like iobroker update all, iobroker u knx etc. but without succes.

What else can i try?
Just for your information: i am running iobroker on windows 10

Thanl you very much for your help.

Regards

**Comment by chefkoch009** [comment]
Have you checked the file permissions? iobroker should have access to this file. Does the file exist in your file-tree?

**Comment by Smassard82** [comment]
Hi. Version 1.0.44 works fine
