### ISSUE TITLE
keine Datenpunkte aus ETS5.7.4

### ISSUE THREAD

**Issue by soiza** [ioBroker/ioBroker.knx#133]
Hab mein ETS geupdatet und jetzt erzeugt der KNX Adapter keine Datenpunkte mehr. 
KNX Adapter 1.0.39  -> dauerschleife beim Import
KNX Adapter 1.0.42  -> Fesnter "Es wurde 9 Objekte extrahiert" kommt aber keine Datenpunkte in knx.0

knx.0.info.connection ist vorhanden und true

Hab versucht die Datenpunkte manuell zu erstellen laut Namen der Gruppenadressen, jedoch reagiert KNX darauf nicht.
LG

**Comment by soiza** [comment]
edit: downgrade auf 1.0.20 Datenpunkte werden erzeugt

**Comment by chefkoch009** [comment]
Wie gross ist Dein Projekt? Auf welcher Hardware läuft Dein ioBroker?

**Comment by soiza** [comment]
Ziemlich klein. 9 Gruppenadressen
Mein ioBroker läuft auf einem Raspberry Pi 3 Model B Plus Rev 1.3
Habs ein paar mal nach zwei bis drei Minuten abgebrochen. Einmal aber einen Nachmittag lang (~5h)

**Comment by chefkoch009** [comment]
welche node version? sollte >= 10 sein.

**Comment by soiza** [comment]
Node.js: v12.20.0
NPM: 6.14.8

**Comment by RESDE** [comment]
@soiza: 
hast Du weitere andere Adapter laufen, mit denen Du states des KNX Adapters "verknüpft" hast sprich diese weiterverarbeitest? Bei mir "zicken" die KNX Objekt beim Neuimport ein wenig, wenn ich den SQL Adapter nicht für den KNX Import ausschalte. ebenso der JS Adapter
Falls ja diese andere Adapter mal deaktivieren beim import. Und am besten auch mal das Explorer Fenster ganz schliessen und neu einsteigen, manchmal werden auch neu angelegt Objekte nicht immer "sauber" neu dargestellt.

**Comment by chefkoch009** [comment]
ist gelöst mit adapter V2.x
