### ISSUE TITLE
Nicht möglich Werte auf den KNX-Bus zu senden

### ISSUE THREAD

**Issue by nebucatneza** [ioBroker/ioBroker.knx#135]
Es ist nicht möglich unter 1.0.39 bzw. auch bis Version 1.0.42 einen boolschen Wert auf den KNX-Bus zu schreiben. Erstellt wurde die knxproj-Datei unter ETS Version 5.7.2 bzw. auch mit 5.7.4.
Steht der Adapter auf Debug, sieht man auch, dass der Wert nicht korrekt geschrieben wird.
Lesen funktioniert ohne Probleme.

welche Infos werden noch benötigt?

**Comment by chefkoch009** [comment]
Ein RAW Auszug deines Objektes, welches Du schalten möchtest.

**Comment by nebucatneza** [comment]
Hi @chefkoch009, danke für deine Antwort.
Hier der Auszug:
`{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1610377700027,
  "common": {
    "name": "Bad Steckd. Heizkörper (braun)",
    "type": "boolean",
    "role": "value",
    "read": true,
    "write": true,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "1/1/9",
    "addressRefId": "P-02D2-0_GA-210",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-50_R-1635",
    "devName": "M-0083_A-008A-22-33A1",
    "devInst": "P-02D2-0_DI-35",
    "objectSize": "",
    "update": false
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Licht.Schalten.Bad_Steckd__Heizkörper_(braun)",
  "type": "state"
}`

**Comment by Backe03** [comment]
Hi Chefkoch009,

Habe ebenfalls das Problem.

KNX Version -> 5.7.4
iO Broker -> 4.1.11
KNX Adapter -> 1.0.39

Adapter ist verbunden. 
Aktuelles knxproj. eingeladen 
Werte werden gelesen aber er kann sie nicht schreiben.

**Comment by chefkoch009** [comment]
Macht bitte mal ein update auf Adapter Version 1.0.44.

**Comment by nebucatneza** [comment]
Hi @chefkoch009, bin heute erst dazu gekommen das nachzutesten, leider immer noch das gleiche Problem.
Hier noch der Auszug aus dem IObroker Debug-Log:
`
knx.0 | 2021-01-30 08:55:38.772 | info | (32735) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)
-- | -- | -- | --
knx.0 | 2021-01-30 08:55:38.771 | info | (32735) ( 4.b ) return to STATE_READY, processing : false
knx.0 | 2021-01-30 08:55:38.771 | info | (32735) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 04 9f 00 ChID : 4 SeqCntIN : 159 SeqCntOUT : 202 queue length : 0
knx.0 | 2021-01-30 08:55:38.770 | info | (32735) =====> STATE_TUNNELING_ACK
knx.0 | 2021-01-30 08:55:38.770 | info | (32735) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
knx.0 | 2021-01-30 08:55:38.770 | info | (32735) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
knx.0 | 2021-01-30 08:55:38.769 | info | (32735) RESPONSE single-array value : 0 auf knx.0.Licht.Schalten.Bad_Steckd__Heizkörper_(braun)
knx.0 | 2021-01-30 08:55:38.769 | info | (32735) RESPONSE : mappedName : Bad Steckd. Heizkörper (braun) dest : 1/1/9 val: 0 (DPT1.001) Bad_Steckd__Heizkörper_(braun)
knx.0 | 2021-01-30 08:55:38.768 | info | (32735) main.js: onGroupValue_Response from 1/1/9
knx.0 | 2021-01-30 08:55:38.767 | info | (32735) ( 3.3 ) Received TUNNEL_REQUEST (RESPONSE - send ACK) : 06 10 04 20 00 15 04 04 9f 00 29 00 bc e0 11 08 09 09 01 00 40 4
knx.0 | 2021-01-30 08:55:38.754 | info | (32735) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)
knx.0 | 2021-01-30 08:55:38.754 | info | (32735) ( 4.b ) return to STATE_READY, processing : false
knx.0 | 2021-01-30 08:55:38.753 | info | (32735) ( 4 ) Sending Tunnel_Request ACK : 06 10 04 21 00 0a 04 04 9e 00 ChID : 4 SeqCntIN : 158 SeqCntOUT : 202 queue length : 0
knx.0 | 2021-01-30 08:55:38.753 | info | (32735) =====> STATE_TUNNELING_ACK
knx.0 | 2021-01-30 08:55:38.752 | info | (32735) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
knx.0 | 2021-01-30 08:55:38.752 | info | (32735) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
knx.0 | 2021-01-30 08:55:38.751 | info | (32735) ( 3.6a ) Received L_DATA.con 06 10 04 20 00 15 04 04 9e 00 2e 00 bc e0 11 3c 09 09 01 00 00 was successfully processed by receiver.
knx.0 | 2021-01-30 08:55:38.729 | info | (32735) ==> easy-knx.js: signal runtime : 0s 3.600657ms
knx.0 | 2021-01-30 08:55:38.728 | info | (32735) Change state from STATE_TUNNELLING_SENT_DATA_ACK_RECV(11) to STATE_READY(7)
knx.0 | 2021-01-30 08:55:38.728 | info | (32735) ==> successful acknowledged previous package... processing next of 0
knx.0 | 2021-01-30 08:55:38.728 | info | (32735) STATE_TUNNELLING_WAIT_SENT_ACK: received ACK for previous self sent package
knx.0 | 2021-01-30 08:55:38.727 | info | (32735) Change state from STATE_TUNNELLING_WAIT_SENT_ACK(9) to STATE_TUNNELLING_SENT_DATA_ACK_RECV(11)
knx.0 | 2021-01-30 08:55:38.727 | info | (32735) ( 2 ) Received TUNNEL_ACK : 06 10 04 21 00 0a 04 04 c9 00 from 192.168.178.80:3671 SeqCntIN : 157 SeqCntOUT : 202 GA : 0/0/0
knx.0 | 2021-01-30 08:55:38.726 | info | (32735) Change state from STATE_TUNNELLING_SENDING_DATA(8) to STATE_TUNNELLING_WAIT_SENT_ACK(9)
knx.0 | 2021-01-30 08:55:38.726 | info | (32735) easy-knx: task.data : 06 10 04 20 00 15 04 04 c9 00 11 00 bc e0 11 3c 09 09 01 00 00 byteLen : 21
knx.0 | 2021-01-30 08:55:38.725 | info | (32735) ( 1 ) Sending : GroupValueRead : 06 10 04 20 00 15 04 04 c9 00 11 00 bc e0 11 3c 09 09 01 00 00 sent to 192.168.178.80:3671 ChID: 4 SeqCntIN : 157 SeqCntOUT : 201 GA : 1/1/9 conCheck.co
knx.0 | 2021-01-30 08:55:38.725 | info | (32735) Change state from STATE_READY(7) to STATE_TUNNELLING_SENDING_DATA(8)
knx.0 | 2021-01-30 08:55:38.724 | info | (32735) add to Buffer cnt: 201 : 06 10 04 20 00 15 04 04 c9 00 11 00 bc e0 11 3c 09 09 01 00 00 queue.length : 0 GA : 1/1/9
knx.0 | 2021-01-30 08:55:38.723 | info | (32735) main.js : tGA.write on Statechange : 1/1/9 P-02D2-0_GA-210 typeof val: boolean true DPT1.001

`


und das was im Busmonitor in der ETS 5.7.4 ankommt:
![image](https://user-images.githubusercontent.com/77295784/106351051-edae9900-62d9-11eb-8f07-d383e12af646.png)
Obwohl ich ein TRUE schreibe, scheint ein FALSE auf dem Bus zu anzukommen.

Vielleicht noch generell folgendes beantworten und ggf. sogar in die readme aufnehmen:
Werden knxproj-Dateien aus der 5.7.4 nun unterstützt?
Die physikalische EIB Adresse, muss das eine freie Busadresse sein oder irgendeine vergebene.

Danke für deine Unterstützung!

**Comment by RESDE** [comment]
@nebucatneza: 
die aktuelle ETS Software Version 5.7.4 (Build1093) wird unterstützt, der Owner des Adapters hält immer mit der aktuellsten Version der ETS mit.
Ja, es müsste es eine "freie" sprich nicht vergebene ETS Adresse sein, aber eben nicht die, die bereits für die IP Schnittstelle in der ETS vergeben ist (oder besser auch nicht die 2-3 ETS Adressen weiteren, die in der IP Schnittstelle vor-reserviert sind (siehe ETS Device Adressenvergabe)
Was ist die Einstellung in den Instanz Parametern "True und False anstelle von 1 und 0 verwenden", aktiviert?

**Comment by nebucatneza** [comment]
@RESDE 
Danke für deine Antwort!
ja ich habe TRUE/ FALSE statt 0/1 aktiviert

**Comment by RESDE** [comment]
@nebucatneza 
kannst Du bitte mal für den oben gepostete GA die Parametrisierung in der ETS schicken? Wo wird diese verwendet? wie sind die Flags definiert?  Schau Dir bitte mal das Stichwort Flags Vergabe in den anderen issues an die bereits gelöst wurden.

**Comment by Videonisse** [comment]
@RESDE Isn't the problem here that the Adapter sends a GroupValueRead to the bus instead of a GroupValueWrite?

**Comment by chefkoch009** [comment]
Die Flags read=true und write=true lösen auf dem Bus ein ein GroupValueRead aus. Steht so im HowTo und funktioniert auch genau so.
