### ISSUE TITLE
Fehler mit DTP5.010

### ISSUE THREAD

**Issue by Andr3asB** [ioBroker/ioBroker.knx#138]
Es scheint bei mehreren Usern Probleme beim schreiben von Werten aus KNX in IoBroker Objekte zu geben.

knx Adapter Version: 1.0.39

Objektdefinition in IoBroker nach dem Import
`{
  "_id": "knx.0.Zentraladressen.Lüftung.V_LUEFTUNG_01_Ventilation_Preset",
  "type": "state",
  "common": {
    "name": "V_LUEFTUNG_01 Ventilation Preset",
    "type": "number",
    "role": "level",
    "read": false,
    "write": true,
    "update": false,
    "unit": "counter pulses",
    "max": "",
    "min": ""
  },
  "native": {
    "dpt": "DPT5.010",
    "address": "0/5/14",
    "addressRefId": "P-07AD-0_GA-285",
    "statusGARefId": "P-07AD-0_GA-275",
    "actGARefId": "",
    "objRef": "O-1_R-1",
    "devName": "M-015B_A-0200-10-21BF",
    "devInst": "P-07AD-0_DI-92",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1611359836598,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Definition der Gruppenadresse in der ETS:
![image](https://user-images.githubusercontent.com/44557554/105560196-72fee000-5d13-11eb-90d6-2477944ce9aa.png)

Das Logfile wo der Wert (1) noch korrekt ankommt:
![image](https://user-images.githubusercontent.com/44557554/105560438-fd474400-5d13-11eb-83fd-5e628a3b5473.png)

Und hier das Objekt, wo kein Wert mehr ankommt:
![image](https://user-images.githubusercontent.com/44557554/105560539-58793680-5d14-11eb-8b0a-a45f168384b7.png)
Hier erwarte ich den Wert "1"!

**Comment by RESDE** [comment]
Hi, kannst Du mal für dieses Objekt unter "Objekt bearbeiten" den Inhalt vom Tab RAW(nur Experten) hierhin posten, dann können wir auf die Ursachenforschung starten?
Könntest Du auch nochmals den exakten DTP Typ aus der ETS posten?
Grüße

**Comment by Andr3asB** [comment]
Hi, 
kann ich gerne machen. Hier nochmal ein "leeres" Gerät wie der Hersteller es erstellt (nur nochmal zum Abgleich, dass ich bei der Fehlersuche auf meiner Seite nichts verbogen habe):
![image](https://user-images.githubusercontent.com/44557554/106737976-a8f76a80-6617-11eb-81f4-a7a13856ebe1.png)
Etwas ungewöhnlich (habe ich bisher bei anderen Herstellern nicht gesehen, dass das geht) erscheint mir hier, dass zwei Datentypen ausgewählt sind:
![image](https://user-images.githubusercontent.com/44557554/106738158-e3f99e00-6617-11eb-92d2-951f3ca45e1a.png)

Das Objekt in IoBroker sieht dann RAW so aus (auch nochmal ganz neu in eine jungfräuliche KNX-Adapter Instanz importiert):
`{
  "_id": "knx.1.Zentraladressen.Lüftung.V_LUEFTUNG_01_Ventilation_Preset",
  "type": "state",
  "common": {
    "name": "V_LUEFTUNG_01 Ventilation Preset",
    "type": "number",
    "role": "level",
    "read": false,
    "write": true,
    "update": false,
    "unit": "counter pulses",
    "max": "",
    "min": ""
  },
  "native": {
    "dpt": "DPT5.010",
    "address": "0/5/14",
    "addressRefId": "P-07AD-0_GA-285",
    "statusGARefId": "P-07AD-0_GA-275",
    "actGARefId": "",
    "objRef": "O-1_R-1",
    "devName": "M-015B_A-0200-10-21BF",
    "devInst": "P-07AD-0_DI-92",
    "objectSize": ""
  },
  "from": "system.adapter.knx.1",
  "user": "system.user.admin",
  "ts": 1612350696546,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Im Log finde ich zum Import nur folgende Zeile (obwohl ich Loglevel 'Debug most' eingestellt habe):
`
2021-02-03 12:13:37.400 - info: knx.1 (9775) DPP erstellt für : 0/5/11 V_LUEFTUNG_01 Fehlermit DPT1.002
2021-02-03 12:13:37.400 - info: knx.1 (9775) DPP erstellt für : 0/5/14 V_LUEFTUNG_01 Ventilation Presetmit DPT5.010
2021-02-03 12:13:37.401 - info: knx.1 (9775) DPP erstellt für : 2/0/52 LD_ESSEN_02 Wertmit DPT5.001
`

**Comment by Andr3asB** [comment]
@RESDE passt das so oder hattet Ihr was anderes erwartet?

**Comment by RESDE** [comment]
Das passt schon so.
Bitte Adapter auf aktuellste Version updaten.
Das ein DTP auf zwei Typen eingestellt ist, ist auch nicht normal. Hattest Du die ETS länger geöffnet, dann hab ich bei mir auch manchmal komische Anzeigen, liegt bei mir wohl an zu vielen geöffneten Applikationen auf einem gealterten Rechner...
Sofern der Wert dann immer noch nicht richtig funzt könnte ich anbieten dass Du mir Deine Projektdatei sendest, dann guck ich genauer rein. Schick mir im IOBroker eine Nachricht direkt an meinen User RES_DE.
Grüsse

**Comment by Andr3asB** [comment]
So, alles zurück auf Anfang. Habe das Gerät komplett aus der ETS entladen und komplett neu angelegt - auch unter Berücksichtigung der erwarteten Namenskonvention (auch wenn diese nicht meinem Standard entspricht ;-) ), dann alle Objekte aus IoBroker gelöscht und den neuen ETS Export nochmal geladen. Siehe da: Es funktioniert alles. Es scheint tatsächlich an der Namensgebung gelegen zu haben.

Das Ticket kann also geschlossen werden.
