### ISSUE TITLE
Projektplan

### ISSUE THREAD

**Issue by jahelo** [ioBroker/ioBroker.knx#14]
Hallo Zusammen,

ich habe mich beim durchschauen des Repos gefragt, ob es eine Art Projektplan /Kanban Board oder zumindest eine offene Punkte Liste gibt? 

Ich bin selber Software Entwickler (Node.js und C#) und bin gerade im Begriff mein Haus zu sanieren und mit KNX auszustatten. Ich hätte große Lust hier im Projekt zu unterstützen, sobald ich mit den Sanierungsmaßnahmen durch bin und wieder mehr Freizeit zur Verfügung habe. (Ich schätze mal ab Sommer 2018 wird das soweit sein)

Liebe Grüße

Jan

**Comment by GermanBluefox** [comment]
https://trello.com/b/q0SZKdfW/iobroker-whiteboard

**Comment by jahelo** [comment]
Super, Dank dir.
