### ISSUE TITLE
Bedeutung für rote oder schwarze true false Kennzeichnung

### ISSUE THREAD

**Issue by Saarblick** [ioBroker/ioBroker.knx#143]
Hallo,

ich arbeite mich langsam immer weiter zu meinen KNX Objekten durch.
Die Beleuchtung kann ich soweit in der VIS kpl. schalten, bei den Statusmeldungen passt es nicht immer.
Denke bei mir im KNX Projekt stimmt da noch was nicht..

Wonach muss ich suchen wenn das value fehlt?
Warum wird manchmal true oder false in rot bzw. schwarz angezeigt?
Manchmal steht auch gar nichts da, schalten in der VIS habe ich aber hinbekommen..
Bin auch in der ETS am Anfang, eine Erklärung warum was wie angezeigt wird würde mir die Suche in der ETS erleichtern.

Iobroker läuft auf RPI 4 mit 8GB.
KNX Adapter ist 1.0.42
Node.js ist v12.20.0

Gruss

**Comment by RESDE** [comment]
Wenn der Wert eines States bitte die L und S Flags in der ETS prüfen. Gleichzeitig auch die "schalter" Read und Write in den jeweiligen Objekten prüfen (Objekt bearbeiten, dann der Bereich RAW nur Experten) anschauen: dort sollte entsprechend das Read flag auf True/false stehen bzw. das Write flag auf true (bei Status-Objekten). 
In der ETS schaust Du das bei den KO der jeweiligen zugeordneten GA auf einen Kanal im entsprechenden Gerät nach. Neben dem L und S Flag auf jedenFall auch immer das Ü Flag aktivieren.
Da ich Deine ETS Sitaution ganz gut kenne, ist hier noch einiges an Aufräumen notwendig.
Sobald IO Broker Objekte mit beiden Schaltern auf True steht, funktioniert keine Kommunikation via Adapter. Hier heisst es die ETS Datei aufräumen sprich solche KOs mit L und S flagsetzung jeweils ein passendes Flags löschen. Dann wieder reimport und/oder Neustart des Adapters
Die frage nach der Färbung der State Werte im KNX Objektbaum zeigt eine gewisse Farblogik des IOBroker generell an: rote Werte sind entweder auf Basis eine zeitlichen Aktualisierung-Rythmus (meist in den Optionen eines Adapters festgelegt) oder aber durch andere Adapter verursacht. Wenn Du also in der VIS Statewerte verändert wird diese Aktualisierung des KNX Objektes farblich angezeigt,
Schreib mir wieder per Email bzgl. des KNX/ETS Aufräumens, dass wäre ansonsten ein Topic für das knx user forum, dort tummeln sich die System-Integratoren und Experten mit viel Hardware-Wissen der KNX Geräte Fumltionalität.
Grüße

**Comment by chefkoch009** [comment]
Ist das geklärt?

**Comment by Saarblick** [comment]
Ich werd mich die Tage nochmal an den IOBROKER setzten..
Habe erst mal alle Updates machen müssen bevor ich an den neuen KNX adapter gehe..


Gruss Thomas

**Comment by chefkoch009** [comment]
Kein Feedback.....scheint sich also geklärt zu haben.
