### ISSUE TITLE
DPT14.056

### ISSUE THREAD

**Issue by sourex83** [ioBroker/ioBroker.knx#144]
Hi, ich habe ein Problem bei der Kommunikation vom KNX zum IObroker.
Auf dem KNX Bus wird der wert 41W gesendet und wird im IOBroker auch als DPT14.056 erkannt. Es wird jedoch nur die erste Zahl im IObroker wiedergegeben --> 4W

Kann mir bitte jemand sagen wordan das liegt ?

Anbei mal das RAW 

![1598356808107-27](https://user-images.githubusercontent.com/78510038/106814073-26e85f80-6672-11eb-87de-f5eeff81e872.png)

**Comment by chefkoch009** [comment]
sehr komisch....kannst Du bitte mal testhalber diesen DP in node-red übergeben und schauen, was da heraus kommt?

**Comment by sourex83** [comment]
frühestens nächste woche, ich versuche aber dran zu denken :)

Am Fr., 5. Feb. 2021 um 00:00 Uhr schrieb chefkoch009 <
notifications@github.com>:

**Comment by sourex83** [comment]
Hi,
ich habe die Steckdose umgelegt deswegen kann ich das momentan nicht testen
mit dem Datenpunkt !
Werde ich wenn ich frei habe nochmal machen.

Ich habe ein neues Issues aufgemacht wegen der HCL Steuerung und habe es
direkt wieder geschlossen weil ich dachte ich hätte das Problem gelöst.
Das war ein Fehler den genau der DP denn ich dort genannt habe funktioniert
nach wie vor nicht.
Könntest du das Issue wieder öffnen ??

https://github.com/ioBroker/ioBroker.knx/issues/147

Danke und Grüße

Am Fr., 5. Feb. 2021 um 00:00 Uhr schrieb chefkoch009 <
notifications@github.com>:

**Comment by skrutzler** [comment]
ich habe genau das selbe problem und kann keine Daten von meinem Stromsensor auswerten. Neben "W" geht auch "A" (DPT14.019 Strom) und "V" (DPT14.027 Spannung) nicht - immer nur die erste Stelle

**Comment by Videonisse** [comment]
I have the same problem. It seems KNX Adapter (v1.0.45) have a problem with reading **GroupValueRespons**. My problem is mainly with DPT14.056 but I did some tests with other DPT14.x, and I think it's the same problem for all of them.

It's no problem if the data is sent as GroupValueWrite.

**Comment by Videonisse** [comment]
@skrutzler If you activate "Debug Most" for the KNX Adapter log, what are the values received for the DPTs where you have problems? And are they sent as groupvalueWrite or as groupvalueRespons?

Example, I sent "11,22" from ETS Groupmonitor as GroupValueWrite:

![image](https://user-images.githubusercontent.com/13684218/116374356-7fad3b80-a80e-11eb-8751-ec7d7a017ff6.png)

**Comment by Videonisse** [comment]
Could issue 169 has something to do with this issue?

https://github.com/ioBroker/ioBroker.knx/issues/169

**Comment by ingel81** [comment]
Exakt das selbe Problem. Was kann ich liefern um bei der Fehlersuche zu unterstützen?

**Comment by chefkoch009** [comment]
Please verify again with Adapter V2.x.

**Comment by Videonisse** [comment]
With v2.0.2, it works fine for me. 

I have tested DPT14.019 (A) and DPT14.056 (W).

**Comment by chefkoch009** [comment]
Thanks for response, if it works as expected please close this issue.
