### ISSUE TITLE
Messwerte auf KNX Bus senden -> Werte sind leer mit read, write & update Häkchen

### ISSUE THREAD

**Issue by domi-75** [ioBroker/ioBroker.knx#145]
Hallo,

ich sende mir schon seit längeren meine Zigbee Temperatur und Feuchte werde per Blockly Spcript auf den KNX Bus. Mit Verison 1.0.20 hat alles prima funktioniert. Mit der aktuellen Version bekomme ich nur leere Telegramme auf den Bus geliefert. Abhilfe schafft nur in dem Iobroker Objekt, read und update ab zu haken. 

Dieses habe ich auch irgendwo bereits gelesen, dass es nur so funktioniert, scheint also bereits bekannt zu sein?

**Comment by RESDE** [comment]
ist schon bekannt.

**Comment by domi-75** [comment]
Ok. Danke!


Was ich noch beobachtet habe, sobald kein MIN/Max Wert im Objekt eingetragen ist, wenn ich mir zb die Volt Zahl der Batterie des zigbee Gerätes auf die KNX Adresse schreibe per blockly, bleibt das Objekt leer.

Auch bekannt?

**Comment by RESDE** [comment]
ja auch bekannt, macht der KNX Adapter beim Import von ETS Projektdateien automatisch. 
Was Du beschreibst ist die generelle Logik im IObroker, wenn du selbst definierte Objekte und die dazugehörigen States einfügst sollten die je Nach Art/Kategeri natürlich vollständig definiert sein. Aber Danke für diesen Hinweis, hilft anderen bestimmt weiter, wenn Sie KNX Objekte anlegen, die aus anderen Adaptern und/oder per JS angelegt und mit Werten befeuert werden

**Comment by Videonisse** [comment]
Is this also a problem if a Dummy device are used in the ETS-project for simulating ioBroker as a KNX device? With GAs connected to a Dummy, I assume the Objects would be correctly created during project file import?

**Comment by domi-75** [comment]
I am only use a dummy device with GAs for temperature, humidity and other items... All GAs have the correct unit (°C, %, V,...)

**Comment by RESDE** [comment]
@Videonisse dummy device in the ETS project to have an device "allocated" works very well. Good approach

**Comment by chefkoch009** [comment]
seems to be fixed...since 9 months no new statement.
