### ISSUE TITLE
GA lassen sich nicht schalten

### ISSUE THREAD

**Issue by matze1708** [ioBroker/ioBroker.knx#146]
Guten Morgen,

ich habe das Problem, dass ich manche GA´s nicht schalten kann. Der Status kommt, Rolläden, Heizung kein Problem. 
Aber Lichter da geht so gut wie nichts. 

Habe den 1.0.44 installier und die ETS 5.7.2

Ich hatte da von alten Versionen noch was im Kopf, dass die GA´s gleich lauten sollen und am Ende mit schalten oder status enden sollen. 
Da ich meist E/A und RM verwende, habe ich in diesem Projekt alle GA´s in schalten und Status umbenannt. 

Jedoch gleiches Problem. In den Objekten kann ich nicht mal anklicken zum einschalten. Auch habe ich versucht das Objekt auf schreiben und lesen zu stellen, gleiches Problem.

Dann hatte ich noch probiert, die RefID vom schalt Objekt in das Status Objekt einzufügen, und umgekehrt, jeweils unter Status oder act.
Auch kein Erfolg.

Was ich noch nicht gemacht habe, mit dem Bus Monitor geschaut was ankommt.

Hier mal ein RAW von einem Objekt

`
{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1612803400902,
  "common": {
    "name": "Licht Essen Schalten",
    "type": "boolean",
    "role": "value",
    "read": true,
    "write": true,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "1/0/2",
    "addressRefId": "P-080F-0_GA-3",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-10_R-39",
    "devName": "M-0083_A-0024-15-EF03",
    "devInst": "P-080F-0_DI-37",
    "objectSize": ""
  },
  "acl": {
    "object": 1638,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1638
  },
  "_id": "knx.0.EG.Licht.Licht_Essen_Schalten",
  "type": "state"
}`

Danke.

Schöne Grüße 

Matthias

**Comment by matze1708** [comment]
Hallo,

ich habe mal noch etwas rum probiert und Empfehlungen hier aus den Meldungen probiert.

Es sind MDT Aktoren.  Dort sind scheinbar bei den Schalt Objekten keine Ü Flag gesetzt aber auch kein A Flag bei Status

Ich habe in der ganzen Projektdatei nun auch noch die Flags angepasst... alles was schaltet KSÜ und alles was Status hat KLA

Dann exportiert NICHT an die Geräte übertragen und in IOB die KNX.0 Objekte alle gelöscht und über den KNX Adapter neu eingelesen. 
Trotz dieser Änderung sind sehr viele Objekt einfach falsch übernommen. Schalt Objekte haben Lesen drin und Status Objekte haben Schreiben drin. 

Wie erkennt der Adpater das er von dem einen die Status Adresse nehmen muss, wenn geschalten wird?

Danke.
Liebe Grüße

**Comment by RESDE** [comment]
Hallo, alle Status KOs besser mit KLÜ, ein A ist nicht korrekt.
Der Adapter leitet aus der Smenatik der GA Adressen die passenden Pärchen ab. 
Stell mal ein paar Beispiele von den Schalt GAs/KOs ein sowie die zugehörigen Status-KP. Och habe selbst auch MDT Aktoren, sollte Dein Problem also simulieren können.
Grüße

**Comment by matze1708** [comment]
Das heißt ich muss bei Status KLÜ einstellen und bei Schalten KSÜ?

Es heißt eigentlich, alles was vom Bus abgerufen bzw gelesen werden kann bekommt ein KLA, weil alles was A hat direkt seinen Status auf den Bus senden, wenn es gebraucht wird Stichwort ViSu.

**Comment by matze1708** [comment]
Anbei 3 Bilder einmal ein Aktor und dann exemplarisch die GA´s Essen schalten und Essen Status

![Bildschirmfoto 2021-02-10 um 14 47 19](https://user-images.githubusercontent.com/28536040/107518380-381ff780-6baf-11eb-8370-ae2628b66878.png)
![Bildschirmfoto 2021-02-10 um 14 49 06](https://user-images.githubusercontent.com/28536040/107518401-3ce4ab80-6baf-11eb-9ea9-e3b732d6b585.png)
![Bildschirmfoto 2021-02-10 um 14 49 19](https://user-images.githubusercontent.com/28536040/107518405-3e15d880-6baf-11eb-866c-b013148ceae4.png)

**Comment by chefkoch009** [comment]
Wieso KLA? Entweder KLÜ für Status oder KS für Schalten/Dimmen. Bei Unklarheiten bitte nochmal die Definition der einzelnen Flags anschauen. 
für Schalten als Beispiel: "Irgendeine tolle Lampe SCHALTEN" oder "Irgendeine tolle Lampe DIMMEN WERT"
für den Status dann also: ""Irgendeine tolle Lampe SCHALTEN STATUS" oder "Irgendeine tolle Lampe DIMMEN WERT STATUS"

Das liest sich auch bedeuten schöner im Gruppenmonitor, weil man dann auch gleich weiss was damit getan wird. Gruppenadressbezeichnungen wie: "Irgendeine tolle Lampe" sind irgendwie nichtssagend....weil die Info fehlt, was ich damit gerade getan wird. Und entsprechend "Irgendeine tolle Lampe R" oder "Irgendeine tolle Lampe RM"..... was soll mit dem R oder RM gesagt werden? ..... schalten, dimmen ?

Das erleichtert auch die Fehlersuche im Projekt bedeutend.

**Comment by matze1708** [comment]
Ich habe jetzt folgednes:
auf dem Objekt Essen schalten steht im IOB true. kann es anklicken und auf false setzten. Wenn das aber gemacht ist, springt es direkt auf true zurück mit einer grünen schrift.


hier nochmal das RAW von dem Objekt

Ich bekomme noch graue Haare

```
{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1612965980891,
  "common": {
    "name": "Licht Essen Schalten",
    "type": "boolean",
    "role": "value",
    "read": true,
    "write": true,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "1/0/2",
    "addressRefId": "P-080F-0_GA-3",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-10_R-39",
    "devName": "M-0083_A-0024-15-EF03",
    "devInst": "P-080F-0_DI-37",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.EG.Licht.Licht_Essen_Schalten",
  "type": "state"
}
```

**Comment by matze1708** [comment]
@chefkoch009 

Wenn ich das so einstelle wie du mir es geschrieben hast.
KS für Schalten und KLÜ für Status, bin ich bei meinem Ausgangszustand von ganz am Anfang. 

Ich passe die 2 Adressen für Wert nochmal an.. Aber das ändert nichts daran, dass ich keine Adressen wie Essen schalten kann. Vom Taster geht es vom X1 geht es... Nur vom KNX Adpater nicht... 

Was kann ich noch nachsehen? 

Liebe Grüße

**Comment by RESDE** [comment]
Hallo, der Adapter führt einen semantischen Abgleich durch auf Basis der GA Bezeichnungen (siehe Doku), daher sollte schon eine sehr hohe Übereinstimmung zwischen der GA Bezeichnung sein, daher reicht der oben gemachte Vorschlag nicht.
Kannst Du für die oben geposteten GAs bitte ein Screenshot aus der ETS posten,
Bei mir in den MDt Aktoren und Sewnsoren/Glastastern sieht die KLSÜ Logik ganz anders aus:
Beim Blick in Deine ETS screenshots folgendes:
a) bei mir werden für die Glastaster die Standardverknüpfung für das KO "Schalten" nur das K und das Ü Flag. Du hast das L Flag definiert. Soll das so sein? Was ich von der ETS Logik verstanden habe ist, dass möglichst nur 1x das L Flag vergeben werden sollte (einer hat die Hoheit im ETS Bus als Wertgeber für alle anderen)
b) beim Schaltaktor steht bei mir als K und S, mehr nicht. Bei Dir ist zusätzlich noch das Ü Flag...

Bei mir funzt der Adapter mit diesen Flags einwandfrei....

**Comment by matze1708** [comment]
Hallo,
Es geht nun in dem Projekt auch!
Das Problem was hier ist ist was der Adapter mit sich bringt, dass er einem eine Namens Konvention aufzwängt, die so nicht üblich ist.
Bitte auch mal im KNX Leitfaden nach sehen.
Wir hatten das vor Jahren schon mal. Ich glaube da hatte ich mit chefkoch auch mal telefoniert.
Eine schalten Gruppe endet nun mal mit EA und eine Rückmeldung dazu mit RM

Für die Hobbyfraktion die es für ihr eigenes Haus macht, ist das auch ok.
Aber wenn ich hier HomeKit nutzten möchte und das bei einem Kunden einsetzte und dann die ganze ETS umstellen muss.... das ist nicht gut gelöst.

Wie die Objekte auf den Bildern stehen, ist mir gar nicht so wichtig.
Hatte davon eine Sicherung gemacht und auch nichts in die Geräte gespielt. Ich wollte nur das der Adapter endlich das macht für was er da ist.

Was macht der Adapter wenn in einem grossen Projekt, die Status Objekte in anderen Mittelgruppen stecken wie die schalt Objekte?

Danke für Eure Hilfe.

LG Matthias

**Comment by RESDE** [comment]
Hallo Matthias, faktisch läuft der Adapter bereits erfolgreich in großen Projekten und die Semantik bei der Generieung von Schalt/Status Objektpaaren schaut weniger auf die GA Hierarchie als auf die semantische Übereinstimmung der Bezeichnung. 
Da hier eine gewisse Anpassung der GA Bezeichnungen schon sehr gute Lösungen erbringt, ist in anderen gelösten Issue bereits ersichtlich. 
Sofern Du mehr über die Semantik der ETS GA mehr sprechen willst, würde ich das eher in das KNX user Forum direkt einstellen, da wimmelt es nur so von m.E. Grundsatzdiskussionen z.B. 2-3 Ebenen, Mittelgruppenlogik etc. 
Danke für den Hinweis im KNX Leitfaden nachzusehen, haben viele User auch schon gemacht.

**Comment by chefkoch009** [comment]
@matze1708 "Was macht der Adapter wenn in einem grossen Projekt, die Status Objekte in anderen Mittelgruppen stecken wie die schalt Objekte?" .... er läuft grandios. 

Für meine eigene Übersicht welche der Weiterentwicklung des Adapters dienen soll, schliesse ich diesen theologischen Issue. 
Über Hobbyprogrammierer, Leitfäden oder ab wieviel GA's man Profi ist, kann gern in einem Forum philosophiert werden.

Vielen Dank für das Verständnis.

VG chefkoch009
