### ISSUE TITLE
Adapter 0.8.6 zu 1.0.39 Unterschied?

### ISSUE THREAD

**Issue by Benni86** [ioBroker/ioBroker.knx#148]
Hallo Zusammen,

ich habe mein RPI aufgelöst und alles auf eine NAS virtuell am laufen.
Dabei habe ich versucht mit dem aktuellsten KNX Adapter die Implementierung ans laufen zu bekommen.
Leider hat der Adapter mit der Version 1.0.39 keinerlei Werte auf den KNX-Bus geschrieben oder gelesen. Der Flag blieb auch immer auf "false". Habe dann die Version 0.8.6 installiert, da diese seid einem Jahr bei mir gut läuft.
Mit dieser Version lief auch alle wieder wie zuvor. 
Daher meine Frage, worin der Unterscheid besteht, sodass ich mein ETS-Projekt auf den neuen Adapter updaten kann. 
Habe im "Info" gelsen, das die Stacks sich geändert haben. 
Was hat es damit auf sich?

lg Ben

**Comment by chefkoch009** [comment]
Hallo Benni86,

den Stack für den Adapter habe ich aus rechtlichen Gründen selbst komplett neu geschrieben. Die Version 1.0.39 is ja nun auch schon "ein paar Tage alt". Bitte versuche einmal die version 1.0.45. Beachte aber bitte, wenn du von Version 0.8.x auf 1.0.4x springst, dann muss das ETS Projekt neu import werden.

VG
chefkoch009
