### ISSUE TITLE
Gruppenadressenimport für iobroker/node-red als "Schaltaktor"

### ISSUE THREAD

**Issue by Ralf31337** [ioBroker/ioBroker.knx#151]
Hallo,

mein Schema ist:
- 1-n Taster für an/aus, jeweils mit LED für Anzeige Status an/aus
- nodered liest die Schaltadresse und führt eine API-Funktion aus
- nodered liest von der API den Status und setzt die Status-Adresse an/aus
- in der KNX-Konfiguration der ETS ist kein Aktor vorhanden, da dieser ja von nodered übernommen wird

Mein Problem dabei ist:
- Ich bekomme das alles zu funktionieren, muss aber manuell read/write im iobroker richtig setzen
- Die Flags im ETS bekomme ich nicht so gesetzt, dass im ioroker die Schalt-Adresse read=true,write=false und die Status-Adresse read=false,write=true gesetzt wird
- Nach jedem Import muss ich also nachkorrigieren

Kann mir jemand einen Tipp geben, wie ich es richtig machen muss?

Schöne Grüße,
Ralf

**Comment by RESDE** [comment]
Semantik mit hoher Übereinstimmung der Bezeichnung bei den GA Adressen sollte eingehalten werden (Siehe zahlreiche andere Beiträge zu diesem Thema) zB:
OG-Schlafen-Licht-Schalten = (Schalt-Adresse)
OG-Schlafen-Licht-Schalten-Status = (Status-Adresse)

**Comment by chefkoch009** [comment]
Hallo Ralf31337, was RESDE geschrieben hat ist soweit richtig, als das es sich um eine reine KNX Programmierung handelt. 
Wenn ich Dein Problem richtig verstehe, dann muss du jedoch der hohen Übereinstimmung genaueinmal entgegen wirken.

Also die Flags für die Taste in der ETS sind dann also KÜ und deine Status-KO am Taster KS. 
Dann benennst DU die Tast-GA und Status-GA z.B. so:
 
OG-Schlafen-Licht-S = Schalt-Adresse
OG-Schlafen-Licht-SRückm = Status-Adressse

dadurch wird die die DPP Findung "erfolgreich fehlschlagen" und du solltest das erhalten, was gefordert ist.
