### ISSUE TITLE
Szenennummer kommt nicht im Bus an

### ISSUE THREAD

**Issue by BINARYADDlCT** [ioBroker/ioBroker.knx#152]
Um meine Szenen aufzurufen kann ich an definierte GAs ("Szenennebenstellen" vom X1) eine Szenennummer senden. Leider kommt eine in ioBroker eingetragene Nummer nicht im Bus an. Ich verwende zum Testen folgenden Datenpunkt:

`

{
  "_id": "knx.0.Zentralbefehle.Szenen.Wohnbereich_SZENE",
  "type": "state",
  "common": {
    "name": "Wohnbereich SZENE",
    "type": "number",
    "role": "",
    "read": "false",
    "write": "true",
    "update": "false",
    "unit": "",
    "max": 63,
    "min": 0
  },
  "native": {
    "dpt": "DPT17.001",
    "address": "0/1/1",
    "addressRefId": "P-07AC-0_GA-404",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "",
    "devName": "",
    "devInst": "",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1614338064030,
  "acl": {
    "object": 1638,
    "state": 1638
  }
}

`

Der Datenpunkt sollte zum schreiben freigegeben sein, und eine Rückmeldung für diesen Typ gibt es nicht. Was fehlt mir bzw. was ist falsch?

VG binary

**Comment by chefkoch009** [comment]
Hallo,

sende mal Szenennummer-1 über den iobroker auf den Bus. Also wenn Deine Szene die Nummer 1 hat, dann sendest Du 1-1=0. Damit sollte es funktionieren. 

vg
chefkoch009

**Comment by BINARYADDlCT** [comment]
> Hallo,
> 
> sende mal Szenennummer-1 über den iobroker auf den Bus. Also wenn Deine Szene die Nummer 1 hat, dann sendest Du 1-1=0. Damit sollte es funktionieren.
> 
> vg
> chefkoch009

Danke für die Antwort. Leider scheint das nicht das Problem zu sein. Das Problem ist nicht, dass ich eine spezielle Szene nicht "erwische", sondern dass nichts auf dem Bus ankommt. Wenn ich in der ETS-Diagnose einen Wert zwischen 0 und 10 auf die GA 0/1/1 sende werden folgerichtig alle definierten Szenen ausgelöst, und ich sehe dann auch den "letzten Wert" bei der GA. Von ioBroker kommt keiner der Werte am Bus an. Stimmt mit dem ioBroker-Datenpunkt was nicht?

vg
binary

**Comment by chefkoch009** [comment]
Kommt der Szenen-Wert, den Du über die ETS sendest, denn im iobroker an?

**Comment by BINARYADDlCT** [comment]
Wenn ich den Wert in der ETS setze kommt dieser in ioBroker um -1 versetzt an. In die andere Richtung gehts leider noch noch nicht.

**Comment by BINARYADDlCT** [comment]
@chefkoch009 ich mach offenbar systematisch irgendwas falsch mit den Datenpunkten. Hast Du Interesse mir eine oder ein paar Coaching-Stunden zu geben? Selbstverständlich mit Gegenleistung...

**Comment by BINARYADDlCT** [comment]
@chefkoch009 hast Du eine Idee wieso ich die Zahl nicht vom ioBroker auf den Bus bekomme?

**Comment by BINARYADDlCT** [comment]
Ich habe den KNX-Adapter deinstalliert und wieder installiert. Leider ohne Erfolg. Andere Datenpunkte kann ich auf den Bus schreiben, aber diese offenbar nicht :(

**Comment by chefkoch009** [comment]
Schreib mir bitte mal eine PN im Forum.

**Comment by BINARYADDlCT** [comment]
Ich hatte die write/read/update Flags als Strings hinterlegt. My bad :(
