### ISSUE TITLE
Projekt Import ETS 5.7.5

### ISSUE THREAD

**Issue by KoljaW** [ioBroker/ioBroker.knx#154]
Ein Import ist mit der neuen ETS Version leider nicht mehr möglich. 
Ich erhalte folgende Meldung: Error: Projectimport with this ETS Version not yet possible.

**Comment by Videonisse** [comment]
I can confirm this is the case. Tested with KNX Adapter version 1.0.44.

Compared the files knx_master.xml, project.xml and 0.xml from two fresh new projects created with ETS 5.7.4 and the new 5.7.5. They are _exactly the same_ except ToolVersion has changed from "5.7.1093.38570" to "5.7.1373.39489"

@chefkoch009 I assume it should be safe for the Adapter to support the new ETS-version without any changes in the import functions?

Reference, Release Notes for ETS 5.7.5: https://support.knx.org/hc/de/articles/360016553200-ETS-v5-7-5

**Comment by Phil2877** [comment]
I have the same issue after update ETS Version to 5.7.5. Is there a workaround for the import? I have new objetcts and it would be great to get these imported soon.  thx.

**Comment by Videonisse** [comment]
Yes there is a workaround that seems to work (AT LEAST FOR ETS 5.7.5). Change ToolVersion to "5.7.1093.38570" in the file 0.xml.

1. Open the .knxproj file with a Zip-client
2. Edit the file 0.xml, change ToolVersion to "5.7.1093.38570"
3. Save 0.xml into your .knxproj file
4. Import as usual

Example using 7Zip-client:
![2021-03-19 10_35_48-7-Zip](https://user-images.githubusercontent.com/13684218/111760919-8e174780-889f-11eb-8466-9a4f31053931.png)

**Comment by Phil2877** [comment]
> 
> 
> Yes there is a workaround that seems to work (AT LEAST FOR ETS 5.7.5). Change ToolVersion to "5.7.1093.38570" in the file 0.xml.
> 
>     1. Open the .knxproj file with a Zip-client
> 
>     2. Edit the file 0.xml, change ToolVersion to "5.7.1093.38570"
> 
>     3. Save 0.xml into your .knxproj file
> 
>     4. Import as usual
> 
> 
> Example using 7Zip-client:
> ![2021-03-19 10_35_48-7-Zip](https://user-images.githubusercontent.com/13684218/111760919-8e174780-889f-11eb-8466-9a4f31053931.png)

Many thanks for your manual. I can confirm it works fine!

**Comment by RESDE** [comment]
I would not suggest to replace content in any ETS project output files as Videonesse assumes that the newest ETS version has no bigger change in the KNX project export which is not documented anywhere from KNX association so far.
My recommondation for faster success;
is to downgrade the ETS Version to 5.7.4 and export then the ETS project and upload it with the current adapter.

**Comment by chefkoch009** [comment]
The main question was in german. Thatswhy I'll try to answer in this language:
Die Versionskontrolle hat den Zweck, sicherzustellen, das der Import funktioniert. Der "Workaround" mag funktionieren, aber wer nicht genau weiss was er da tut kann damit seine Exportdatei zerstören. Dann kommen nämlich wieder neue "Issues" aus der Richtung "Import funktioniert nicht....ich habe nichts gemacht". Das soweit am Rande. 

Ab sofort ist die Version 1.0.45 online. Die kann ETS v5.7.5 importieren.
