### ISSUE TITLE
KNX Adapter in Docker verliert ständig die Verbindungen.

### ISSUE THREAD

**Issue by boarder666** [ioBroker/ioBroker.knx#156]

**Comment by boarder666** [comment]
|   |   |  
-- | -- | -- | --
knx.0 | 2021-03-17 21:30:54.331 | info | (711) STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:54.331 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:54.330 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:54.330 | info | (711) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:54.330 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:54.329 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:54.329 | info | (711) STATE_DISCONNECT_REQUEST : no defined handling for transition from State: STATE_CONNECT_RESPONSE(4) to STATE_DISCONNECT_REQUEST(15).
knx.0 | 2021-03-17 21:30:54.328 | info | (711) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 00 00 00 00 cb fd 08 01 ac 11 00 02 cb fd 04 04 02 00 sent to 192.168.188.3:3671
knx.0 | 2021-03-17 21:30:54.328 | info | (711) Connected - local UDP Server listening on 172.17.0.2:52221
knx.0 | 2021-03-17 21:30:54.328 | info | (711) Event : UDP - listening
knx.0 | 2021-03-17 21:30:54.327 | info | (711) Using UDP with local IP: 172.17.0.2
knx.0 | 2021-03-17 21:30:52.327 | info | (711) STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:52.327 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:52.327 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:52.327 | info | (711) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:52.327 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:52.326 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:52.326 | info | (711) STATE_DISCONNECT_REQUEST : no defined handling for transition from State: STATE_CONNECT_RESPONSE(4) to STATE_DISCONNECT_REQUEST(15).
knx.0 | 2021-03-17 21:30:52.325 | info | (711) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 00 00 00 00 86 17 08 01 ac 11 00 02 86 17 04 04 02 00 sent to 192.168.188.3:3671
knx.0 | 2021-03-17 21:30:52.325 | info | (711) Connected - local UDP Server listening on 172.17.0.2:34327
knx.0 | 2021-03-17 21:30:52.325 | info | (711) Event : UDP - listening
knx.0 | 2021-03-17 21:30:52.324 | info | (711) Using UDP with local IP: 172.17.0.2
knx.0 | 2021-03-17 21:30:52.318 | info | (711) checkConnectionState 192.168.188.3 State : false
knx.0 | 2021-03-17 21:30:50.325 | info | (711) STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:50.325 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:50.325 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:50.324 | info | (711) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:50.324 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:50.324 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:50.324 | info | (711) STATE_DISCONNECT_REQUEST : no defined handling for transition from State: STATE_CONNECT_RESPONSE(4) to STATE_DISCONNECT_REQUEST(15).
knx.0 | 2021-03-17 21:30:50.323 | info | (711) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 00 00 00 00 8c f7 08 01 ac 11 00 02 8c f7 04 04 02 00 sent to 192.168.188.3:3671
knx.0 | 2021-03-17 21:30:50.323 | info | (711) Connected - local UDP Server listening on 172.17.0.2:36087
knx.0 | 2021-03-17 21:30:50.322 | info | (711) Event : UDP - listening
knx.0 | 2021-03-17 21:30:50.322 | info | (711) Using UDP with local IP: 172.17.0.2
knx.0 | 2021-03-17 21:30:48.323 | info | (711) STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:48.323 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:48.323 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:48.322 | info | (711) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2021-03-17 21:30:48.322 | info | (711) ... not able to close connection, because already closed
knx.0 | 2021-03-17 21:30:48.322 | info | (711) Connection persists.....closing now
knx.0 | 2021-03-17 21:30:48.322 | info | (711) STATE_DISCONNECT_REQUEST : no defined handling for transition from State: STATE_CONNECT_RESPONSE(4) to STATE_DISCONNECT_REQUEST(15).
knx.0 | 2021-03-17 21:30:48.321 | info | (711) Send : UDP Connection Request : 06 10 02 05 00 1a 08 01 00 00 00 00 d9 d3 08 01 ac 11 00 02 d9 d3 04 04 02 00 sent to 192.168.188.3:3671
knx.0 | 2021-03-17 21:30:48.321 | info | (711) Connected - local UDP Server listening on 172.17.0.2:55763
knx.0 | 2021-03-17 21:30:48.320 | info | (711) Event : UDP - listening
knx.0 | 2021-03-17 21:30:48.320 | info | (711) Using UDP with local IP: 172.17.0.2

**Comment by chefkoch009** [comment]
Ich sehe das Problem eher irgendwo im Routing. 192.168.188.3:3671 <=> 172.17.0.2:34327. Anscheinend lässt der Docker oder eine vorgelagerte Netzwerkkomponente keine Verbindung vom KNX-GW zum iobroker.knx zu.....diese ist aber notwendig.
