### ISSUE TITLE
Add only new Objects, enable by default - Feature Request

### ISSUE THREAD

**Issue by Videonisse** [ioBroker/ioBroker.knx#157]
Most of the time, when running an import of the knxproj-file, only new objects should be added. By default, you don't want to overwrite your previous import. 

Therefore, it must be better if the setting "Add only new Objects" (German "Füge nur neue Objekte hinzu") is **enabled by default** after the first import.

![image](https://user-images.githubusercontent.com/13684218/112067936-327fdf00-8b69-11eb-8cd4-4c40920b926f.png)

_Please, use thumb-up if you like this feature request._

**Comment by MC-1984** [comment]
+1

**Comment by Videonisse** [comment]
Any chance this could be included in the next version?

**Comment by chefkoch009** [comment]
Makes sense and is already fixed.
