### ISSUE TITLE
Object has in IOBROKER only ReadOnly attributes

### ISSUE THREAD

**Issue by PerfectAnswer** [ioBroker/ioBroker.knx#16]
After importing a new .proj File, the write attributes gone lost and new ones are without write attribute.
Please make sure no existing value are altered.
This blocks the use in cloud adapter for Alexa for e.g..

I think the problem ist the bulk import. It overwrites all existing custom values.
http://forum.iobroker.net/viewtopic.php?f=20&t=11633#p122886

**Comment by chefkoch009** [comment]
Added the option to only add new objects...So existing objects won't be touched.

**Comment by PerfectAnswer** [comment]
Thank you, this is a great improvement. 👍
