### ISSUE TITLE
Problem mit schreiben / lesen auf dem KNX Bus

### ISSUE THREAD

**Issue by Bjoern3003** [ioBroker/ioBroker.knx#163]
Versuche mich nun schon stunden am einrichten des KNX Adapters.

Mit Version 1.0.39 kann ich alle Werte problemlos lesen, aber nicht schreiben.
Mit Version 1.0.45 kann ich alle Werte problemlos schreiben, aber dafür nicht lesen.

Habe schon etliche Zwischenversionen ohne großen Erfolg getestet.

Auch habe ich Version wie 1.0.20 erfolglos getestet. Dort ging dann zum Teil gar keine Richtung.

Ich nutze einen IP-Router (Wago 750-889 mit einer TP Klemme).

Da ja je Nach Version eine der beiden Richtungen klappen, kann ich in meinen Augen die Konfiguration ausschließen?!

**Comment by Videonisse** [comment]
Can you paste the raw settings for the switch of a Light object (Licht ein/aus) here?

Example:
![image](https://user-images.githubusercontent.com/13684218/113453216-cec9a180-9405-11eb-8c04-f5e46e665f70.png)

**Comment by Bjoern3003** [comment]
Neue Erkenntnis, die aber nicht neu ist. Mit der Version 1.0.20 funktionieren beide Richtungen.
