### ISSUE TITLE
Version 1.0.45 import Projektdatei wirft Fehler "cannot find start file!"

### ISSUE THREAD

**Issue by SWeckmann** [ioBroker/ioBroker.knx#166]
Import bleibt bei Ladebalken hängen.
![image](https://user-images.githubusercontent.com/58548017/114851632-563dea00-9de2-11eb-892c-6f08734b27bc.png)

Projektdatei relativ  groß (65 Geräte)

![image](https://user-images.githubusercontent.com/58548017/114851562-445c4700-9de2-11eb-8201-f2c89da6e842.png)

![image](https://user-images.githubusercontent.com/58548017/114851493-2f7fb380-9de2-11eb-97a6-61bff71a679b.png)

**Comment by Videonisse** [comment]
Have you tried with another project file? If you don't have one, create one just as a test.

**Comment by SWeckmann** [comment]
Now it gets stuck i nthe loading screen without a log entry.
I tried to use the attached project file.
[Test ioBroker.zip](https://github.com/ioBroker/ioBroker.knx/files/6318630/Test.ioBroker.zip)
![image](https://user-images.githubusercontent.com/58548017/114882928-bc3b6900-9e04-11eb-8272-3b86832a48c3.png)

**Comment by Videonisse** [comment]
It works fine when I test to import your knxproject file, see below. 

(However, don't use / in your names as for "Sperre/Alarm", use "Sperre-Alarm" instead. See Readme for reasons)

You should try to deinstall the KNX Adapter completely and re-install the latest version again. If you still have problems, try to run the Fixer for ioBroker. If still problems, ask for help in the ioBroker Forum.

![image](https://user-images.githubusercontent.com/13684218/114988277-70d19b00-9e96-11eb-87df-76e4e0813ad7.png)

**Comment by RESDE** [comment]
@Videonisse Thanx for this good recommendations.

**Comment by joha91** [comment]
I also get the error
`startInstance knx.0: cannot find start file!`
And then the import also loads infinity.

I version 1.0.39 I had no problems. But I had to update the adapter because I have new ETS version (required for ETS Home Lisenz)

Can I see somewhere an extended log or can I somehow debug the JS code? I can´t even see the knx.js file in this repo, even if it´s defined as "main" in the package.json.

Thanks for help :)

**Comment by SWeckmann** [comment]
So it did work with the test project :) Thank you very much!
![image](https://user-images.githubusercontent.com/58548017/115120612-af5a7900-9fae-11eb-9ba5-7f61b6fe89b4.png)

For others with the same issue here are the steps i did:
![image](https://user-images.githubusercontent.com/58548017/115120635-cf8a3800-9fae-11eb-8936-9a6873cf356d.png)

Delete the old instance.

Stop ioBroker and run the fixer
![image](https://user-images.githubusercontent.com/58548017/115120661-efb9f700-9fae-11eb-89ce-b0f473960583.png)

Get the newest Version
![image](https://user-images.githubusercontent.com/58548017/115120697-16782d80-9faf-11eb-90bf-b197cc0508e3.png)

Add an Instance
![image](https://user-images.githubusercontent.com/58548017/115120719-3871b000-9faf-11eb-92b3-b8029fd31645.png)

And then it worked :)
Thank you very much!! 
I'll now go by your manual and get rid of all / in the original project file.
Hopefully I can tell by Monday if it worked!

**Comment by SWeckmann** [comment]
Could not wait till Monday:
![image](https://user-images.githubusercontent.com/58548017/115121286-14639e00-9fb2-11eb-8cbe-1cdfc31a38e3.png)
Thank you!

**Comment by joha91** [comment]
I did everything you described here, but I still can´t even configure the adapter:
![image](https://user-images.githubusercontent.com/25430501/115660752-c5649280-a33c-11eb-9481-69a173cc2a8f.png)

**Comment by joha91** [comment]
For me it seemed like the problem is related with installation as github project.
Now the version 1.0.45 is released as stabel in ioBroker, and I installed it normally, the problem doesn´t appear any more.
