### ISSUE TITLE
Sending empty text blockly to 14 bytes 16.000 Zeichen (ASCII) GA crashes adapter 

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.knx#170]
I have a blocky script that send text to a 14 bytes 16.000 Zeichen (ASCII) GA. When deleting the text by simply sending empty text ("") the adapter does not recognize changed values in GAs for a couple of minutes. The adapter status is still green what makes it really hard to troubleshoot. The adapter automatically recovers after a couple of minutes.

It is just i minor error that can easily be avoided but it is really hard to find...

**Comment by chefkoch009** [comment]
does the problem still persists?

**Comment by MC-1984** [comment]
No, it does not!
