### ISSUE TITLE
After renaming of GAs old datapoints must be deleted

### ISSUE THREAD

**Issue by MC-1984** [ioBroker/ioBroker.knx#171]
I changed the structure of a GA from Temperatur (Ist) to Temperatur-Ist. The former datapoint in ioBroker worked fine, the new datapoint was not working properly. After deleting all datapoints from knx.0. and reimporting the same ETS project file again the new dataipoints worked. Not sure what it causes it. The RAW values looked almost the same. Only one value was different, I think it was "ts".

**Comment by chefkoch009** [comment]
The reason to not delete was, to prevent destroying customers settings. In your case you build 2 Datapoints with the same RefID. This will not work.
