### ISSUE TITLE
Probleme mit KNX Adapter 1.0.45

### ISSUE THREAD

**Issue by heiko66646** [ioBroker/ioBroker.knx#174]
Hallo ich habe ein Problem mit dem KNX Adapter 1.0.45. Ich kann befehle von Objekte in die KNX Welt senden aber die Werte von der KNX Welt werden nicht angezeigt oder Aktualisiert.
Also wenn ich von der ETS etwas sende kann Mann es bei den Objekten nicht sehen

Ich verwende:
Platform: linux
os: linux
Architecture: arm
CPUs: 4
Speed: 1000 MHz
Model: ARMv7 Processor rev 3 (v7l)
RAM: 3.7 GB
System uptime: 02:27:50
Node.js: v12.22.1
NPM: 6.14.12
Disk size: 29.0 GiB
Disk free: 26.8 GiB
adapters count: 341
Uptime: 02:10:50
Active instances: 6
ETS : 5.7.5 Build 1373
IoBrocker 4.2.1
Habe den Iobrocker komplett neu aufgesetzt keine Änderung.
Hat jemand auch das Problem und eine Lösung dazu?
Danke

**Comment by Videonisse** [comment]
I suggest you use the ioBroker support forum for this kind of questions.

**Comment by stonegarden-git** [comment]
Seems not to be an iobroker issue. Same on my installation (Windows) after update to knx-adapter 1.0.45 status-information are not recognized as such. Sending values to KNX from visu is no problem.

**Comment by chefkoch009** [comment]
Bitte Flags und Beschriftungen der GA's prüfen. Weitere Informationen gibt es dazu im Forum und in der README.md
