### ISSUE TITLE
KNX Adapter und Docker

### ISSUE THREAD

**Issue by Vrumfondel** [ioBroker/ioBroker.knx#175]
Hallo zusammen!

Ich hatte bisher IOBroker auf einem Raspi laufen. Nachdem mir aber jetzt zum zweiten mal die SD-Karte zerbröselt ist (vermutlich schreibt da irgend wer fleißig drauf rum) wollte ich das ganze auf meine NAS als Dockerpaket umziehen.
Nun, IOBroker ansich läuft auch, aber ich kriege den KNX Adapter nicht ans laufen. 

Ich vermute es liege an folgenden Logeinträgen:

knx.0 | 2021-05-31 16:13:26.006 | info | (2183) Connected - local UDP Server listening on 172.17.0.4:59016
-- | -- | -- | --
knx.0 | 2021-05-31 16:13:25.996 | info | (2183) Debuglevel: 0 1
knx.0 | 2021-05-31 16:13:25.985 | info | (2183) Connecting to knx GW: 10.1.1.10:3671 with phy. Adr: 1.0.0

Der Adapter hört also auf Port 59016 - und der ist nicht nach Docker gemapped.
Das Problem: Der Port ändert sich bei jedem Start des Adapters, also nutzt mir ein Mapping auf Docker-Seite nichts (und ich kann ja nicht ALLE Ports mappen, auf dem System laufen noch anderen Anwendungen).
Kann man den irgendwie fix vorgeben?

Gruß
Carsten

**Comment by Stefan592** [comment]
#199 
Bitte den passenden Netzwerkmodus wählen: Host oder MACVLAN

Multicast Verbindungen werden in Bridge Mode nicht unterstützt

**Comment by chefkoch009** [comment]
```Der Adapter hört also auf Port 59016

Dieser Port wird immer wieder dynamisch ausgehandelt. Also die Firewall- /Routingregeln auf den Host oder den Dienst beziehen.
