### ISSUE TITLE
import of ETS v5.7.5 projects not possible

### ISSUE THREAD

**Issue by mieserwicht** [ioBroker/ioBroker.knx#178]
Hello,
with the latest KNX Adapter v1.0.45 an import of ETS 5.7.6 (Build 1398) projects is not possible.
Thanks for this great adapter

Running:
Raspberry Pi OS Buster
Architektur    arm
Modell    Raspberry Pi 4 4GB
Node.js    v12.22.1
NPM    6.14.12
ioBroker (as Docker container) v5.1.6
KNX Adapter v1.0.45

ETS: 5.7.6 Build 1398
Stammdaten v202
Produkt-Erweiterungen v201
Schnittstelle v59

**Comment by HighStairs** [comment]
Hello,

I'm having the same issue. Same ETS version, but different system:

CPU  8 x Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (1 Socket)
Kernelversion; Linux 5.4.106-1-pve #1 SMP PVE 5.4.106-1
PVE Manager Version pve-manager/6.4-4/337d6701

iArchitektur     x64
CPUs     1
Geschwindigkeit     4157 MHz
Modell     Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
RAM     2 GB
Node.js     v12.22.1
NPM     6.14.12

**Comment by FrankOverIP** [comment]
Changing the tool version as described in #154 did not work for me. Although the error message regarding an unsupported version is no longer shown, the import does not seem to start.  The scroll bar below file selection immediately goes to roughly 70% and stays there. The screen is not locked and nothing seems to be working in the background. It looks like the import just aborts in a very early stage - or does not even start.

Adapter version is 1.0.45, ETS ToolVersion has been changed from 5.7.1398.39605 to 5.7.1093.38570, ETS  has version 5.7.6 Build 1398.

If the project file would be helpful, please let me know how to provide it - I just don't want to upload it here...

**Comment by romgen** [comment]
> Changing the tool version as described in #154 did not work for me. Although the error message regarding an unsupported version is no longer shown, the import does not seem to start. The scroll bar below file selection immediately goes to roughly 70% and stays there. The screen is not locked and nothing seems to be working in the background. It looks like the import just aborts in a very early stage - or does not even start.
> 
> Adapter version is 1.0.45, ETS ToolVersion has been changed from 5.7.1398.39605 to 5.7.1093.38570, ETS has version 5.7.6 Build 1398.
> 
> If the project file would be helpful, please let me know how to provide it - I just don't want to upload it here...

At least for me this workaround worked, using the following ToolVersion "5.7.1373.39489" as replacement.

**Comment by chefkoch009** [comment]
This will not work because of changes in exportfile. To fix this, I spend a lot of time ;-). But the new ETS Versions up V6 will work in new Adapter Version.
