### ISSUE TITLE
KNX Statusupdate

### ISSUE THREAD

**Issue by rhierl** [ioBroker/ioBroker.knx#179]
Komme bei dem Thema Statusupdate nicht weiter
- Gruppenadressen mit identischer Bezeichnung
  (Z.B. Buero Licht Decke schalten / Buero Licht Decke schalten Status) wird meines Erachtens auch richtig importiert und die beiden internen Adressen finde ich in den Details
- Statusupdate erfolgt in KNK wenn ich im iobroker was ändere (manuell oder z.B. über HomeKit)
- wenn ich in KNX schalte ändert sich der Status jedoch nicht. Das führt dann zu falschen Anzeigen in HomeKit und zu notwendigen doppelbefehlen in HomeKit

Hat jemand eine Idee wo ich noch ansetzen kann?

**Comment by Garfonso** [comment]
Also du siehst in den Objekten im Raw Modus bei Native sowas:

(schalten -> hier muss statusGARefId gefüllt sein)
````
"native": {
    "dpt": "DPT1.001",
    "address": "1/0/5",
    "addressRefId": "P-0454-0_GA-15",
    "statusGARefId": "P-0454-0_GA-671",
    "actGARefId": "",
    "objRef": "O-31_R-30300",
    "devName": "M-0009_A-500E-20-04D8",
    "devInst": "P-0454-0_DI-74",
    "objectSize": ""
  },
````
(status, actGARefId muss gefüllt sein)
````
"native": {
    "dpt": "DPT1.002",
    "address": "1/1/5",
    "addressRefId": "P-0454-0_GA-671",
    "statusGARefId": "",
    "actGARefId": "P-0454-0_GA-15",
    "objRef": "O-38_R-30307",
    "devName": "M-0009_A-500E-20-04D8",
    "devInst": "P-0454-0_DI-74",
    "objectSize": ""
  },
````

Wenn das so ist, dann sollte es gehen. Dazu ggf. noch beachten / testen (weiß nicht, was du alles schon versucht hast):

- den ioBroker State zur schaltGA nutzen in vis / homekit oder so -> den zur StatusGA ignorieren
- in KNX wird auf StatusGA auch gesendet?
- Verbindung zum KNX Gateway bricht nicht ab?

**Comment by rhierl** [comment]
Hallo,
danke für die schnelle ANtwort.
JA, das sieht so aus

schalten:
  "native": {
    "dpt": "DPT1.001",
    "address": "7/0/130",
    "addressRefId": "P-1080-0_GA-589",
    "statusGARefId": "P-1080-0_GA-590",
    "actGARefId": "",
    "objRef": "O-64_R-367",
    "devName": "M-0083_A-0040-23-668E",
    "devInst": "P-1080-0_DI-30",
    "objectSize": "1 Bit",
    "update": true

status
 "native": {
    "dpt": "DPT1.011",
    "address": "7/0/131",
    "addressRefId": "P-1080-0_GA-590",
    "statusGARefId": "",
    "actGARefId": "P-1080-0_GA-589",
    "objRef": "O-80_R-383",
    "devName": "M-0083_A-0040-23-668E",
    "devInst": "P-1080-0_DI-30",
    "objectSize": "1 Bit"
  },

Ich habe aber aktuell keine Visualisierung. Versuche das als erstes

Nomal danke für die schnelle Reaktion
VG

Am Do., 10. Juni 2021 um 14:31 Uhr schrieb Achim Königs <
***@***.***>:

**Comment by rhierl** [comment]
Hallo,
ich bekomme es nicht gelöst
- Habe ein separate IP-Schnittstelle angeschlossen (aktuell
IP-Schnittstelle über meine Visualisierung CIbeVision)
- Habe eine Visualisierung in VIs aufgebaut
Führt auch nicht zum Erfolg. AUch in der Visualisierung ändert sich der
Status nicht. Schalten geht
Der Status wird gesendet, da es in meiner aktuellen Visualisierung
funktioniert (Schalte ich in KNX ändert sich der Status in der Visu)

noch eine Idee?
iobroker empfängt einfach keine Änderungen aus dem KNX egal ob Schalten
oder Status. Es wird nur gesendet.

Beste Grüße


Am Do., 10. Juni 2021 um 15:56 Uhr schrieb Reinhold Hierl <
***@***.***>:

**Comment by Garfonso** [comment]
Kommen denn im Log irgendwelche Fehler? Oder überhaupt Ausgaben von KNX?

**Comment by rhierl** [comment]
Es kommen keine Meldungen. Wie gesagt schreibt Iobroker auf KNX aber
empfängt nicht.
Heute konnte ich es über den Umweg Node-Red lösen indem ich in Node red das
KNX Signal einlese und an das Iobroker KNX Objekt sende. Damit geht es. Ist
sicherlich nicht so gedacht

Achim Königs ***@***.***> schrieb am Fr. 18. Juni 2021 um
17:40:

**Comment by chefkoch009** [comment]
@rhierl: zum einen sind die Datenpunkttypen nicht identisch. dpt schalten ist 1.001 und dpt status ist 1.011. 
prüfe bitte ob bei schalten read=false UND write=true ist und beim Status read=true UND write=true. 
lösche bitte aus dem schalten object "update" : true heraus. und in der zeile darüber bitte das Komma entfernen. 
Nach dieser Änderung starte den Adapter bitte neu.

**Comment by Videonisse** [comment]
@chefkoch009 Was bedeutet eigentlich "update" : true ?

**Comment by chefkoch009** [comment]
Das gibt die knxproj her. Hab es deshalb mal mit rein genommen. Ist aber ohne Funktion.

**Comment by mdaudi1982** [comment]
> Also du siehst in den Objekten im Raw Modus bei Native sowas:
> 
> (schalten -> hier muss statusGARefId gefüllt sein)
> 
> ```
> "native": {
>     "dpt": "DPT1.001",
>     "address": "1/0/5",
>     "addressRefId": "P-0454-0_GA-15",
>     "statusGARefId": "P-0454-0_GA-671",
>     "actGARefId": "",
>     "objRef": "O-31_R-30300",
>     "devName": "M-0009_A-500E-20-04D8",
>     "devInst": "P-0454-0_DI-74",
>     "objectSize": ""
>   },
> ```
> 
> (status, actGARefId muss gefüllt sein)
> 
> ```
> "native": {
>     "dpt": "DPT1.002",
>     "address": "1/1/5",
>     "addressRefId": "P-0454-0_GA-671",
>     "statusGARefId": "",
>     "actGARefId": "P-0454-0_GA-15",
>     "objRef": "O-38_R-30307",
>     "devName": "M-0009_A-500E-20-04D8",
>     "devInst": "P-0454-0_DI-74",
>     "objectSize": ""
>   },
> ```
> 
> Wenn das so ist, dann sollte es gehen. Dazu ggf. noch beachten / testen (weiß nicht, was du alles schon versucht hast):
> 
> * den ioBroker State zur schaltGA nutzen in vis / homekit oder so -> den zur StatusGA ignorieren
> * in KNX wird auf StatusGA auch gesendet?
> * Verbindung zum KNX Gateway bricht nicht ab?

Hallo,

Ich habe das Problem, dass sowohl die status als auch die act ID leer sind. Muss ich diese vorher in der ETS irgendwie setzten, bevor ich die KNXproj Datei importiere?

Gruß,
Micha

**Comment by mdaudi1982** [comment]
Hallo,

Ich habe aktuell das Problem, dass ich gerne die Datenpunkte meiner Binäreingänge (Fensterkontakte) über den KNX Adapter in iobroker lesen möchte. Wie ich gemerkt habe, habe ich bei sämtlichen GA das Problem, die aktuellen Werte zu erhalten. Ich vermute, dass liegt an der Konfiguration der GA. 

Als Typen habe ich in der ETS lediglich die 1.001 ausgewählt, da er mir ja auch nur eine 0 oder 1 anzeigen soll. Dies funktioniert über den Gruppenmonitor und unsere Domovea hervorragend. Leider kommen die Werte aber nicht im KNX Adapter im iobroker an. 

So sehen aktuell die Objektdaten aus:

"_id": "knx.0.Fensterkontakte.Fensterkontakte_EG.Fenster_9_Auf_Zu_",
  "type": "state",
  "common": {
    "name": "Fenster 9[Auf/Zu]",
    "type": "boolean",
    "role": "value",
    "read": true,
    "write": true,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "5/0/15",
    "addressRefId": "P-06A4-0_GA-952",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-1_R-28643",
    "devName": "M-0009_A-206A-12-E24D",
    "devInst": "P-06A4-0_DI-23",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1624652972603,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"

und die GA für den Status:

"_id": "knx.0.Fensterkontakte.Fensterkontakte_EG.Fenster_9_Status_",
  "type": "state",
  "common": {
    "name": "Fenster 9[Status]",
    "type": "boolean",
    "role": "indicator",
    "read": true,
    "write": false,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "5/0/16",
    "addressRefId": "P-06A4-0_GA-953",
    "statusGARefId": "",
    "actGARefId": "",
    "update": true,
    "objRef": "O-40_R-28660",
    "devName": "M-0009_A-206A-12-E24D",
    "devInst": "P-06A4-0_DI-23",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1624652972544,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"

Hat jemand eine Idee, woran es liegen könnte?

Dank und Gruß,
Micha

**Comment by lessthanmore1** [comment]
@mdaudi1982 Die statusGARefId wie auch die actGARefId sind nicht gefüllt, da die GA nicht korrekt benannt wurden.
Die Status GA hätte bspw. Fensterkontakte.Fensterkontakte_EG.Fenster_9_Auf_Zu_Status heißen müssen.
Einfach die fehlenden Felder entsprechen pflegen und dann sollte es gehen.

Im Schalten DP bei statusGARefId P-06A4-0_GA-953 eintragen und beim Status DP bei actGARefID P-06A4-0_GA-952.

**Comment by chefkoch009** [comment]
Das geht mit Adapter Version V2.x mit den GA-Tools im knx-Admin.
