### ISSUE TITLE
Problem with datatype 13.001 

### ISSUE THREAD

**Issue by hilldefill** [ioBroker/ioBroker.knx#181]
Hi,
I have the problem that I didn`t get the value of a groupe adress in ioBroker. The datatype is 13.001 counter pulse.
If I check the value in the ETS diagnostic the value will be ok.

Is there a fix or where is my mistake.

**Comment by chefkoch009** [comment]
Please check your flags in iobroker object. For further informations for correct flagging see README.md. If all is correct, then reopen this issue.
