### ISSUE TITLE
KNX Objektbaum hält sich nicht an Standard

### ISSUE THREAD

**Issue by Bjoern3003** [ioBroker/ioBroker.knx#182]
Siehe auch: https://github.com/Zefau/ioBroker.jarvis/issues/802

Aus dem Grund kann man im jarvis leider keinerlei KNX Objekte anwählen.

**Comment by Apollon77** [comment]
It seems that no device, channel or folder objects are created

**Comment by Bjoern3003** [comment]
Wie kommst du darauf? Im zweiten Screenshot sieht man doch einen Teil des knx objektbaumes.

**Comment by Apollon77** [comment]
sorry typ ... ... fixed above

**Comment by Bjoern3003** [comment]
Sorry, ich verstehe leider immer noch Bahnhof.

**Comment by Garfonso** [comment]
ich glaube er sagt, dass du recht hast. Im Screenshot sieht man jedenfalls, dass keine Objekte für die "Ordner" existieren, sonst gäbe es dort auch das "Editieren" Icon in der Objektansicht. Das ist zwar nicht 100%ig verboten in ioBroker, könnte es aber in Zukunft sein (Admin 5 wird hier auch für den User sktrikter sein z.B.). Insofern sollte das hier geändert werden.
