### ISSUE TITLE
Tunneling: L_Data.con Frames werden nicht quittiert

### ISSUE THREAD

**Issue by boellner** [ioBroker/ioBroker.knx#184]
Wenn ein Paket vom IO Broker über Tunnel an das KNX Interface kein Acknowledge vom Empfänger bekommt, zB weil es mit keinem Gerät verknüpft ist, steigt mein MDT IP Interface SCN-IP100.03 aus, schickt einen DISCONNECT_REQUEST und ist für gewisse Zeit tot auf dem Bus so dass wichtige Informationen verloren gehen.

Hier ein paar Messungen die das Problem verdeutlichen.
(Setup: 192.168.0.103 PC mit ETS, 192.168.0.10 KNX IP Interface, 192.168.0.8 IOBroker)

Gleiche Messages ausgehend von der ETS verhalten sich korrekt, kein Disconnect vom Interface, Message wird korrekt grün in der ETS (dh problematisch ) angezeigt.
Grund: Der CEMI l_data.con frame mit confirmation error vom Interface wird von der ETS Acknowledged.
![image](https://user-images.githubusercontent.com/86853627/124321740-80e84500-db7e-11eb-8b23-1a3bb8f66ed2.png)

Der IOBroker Adapter quittiert Paket #10:47 nicht, es wird deswegen ein zweites mal geschickt. Und da es erneut nicht quittiert wird geht das Interface in DISCONNECT_REQUEST.

![image](https://user-images.githubusercontent.com/86853627/124321197-94df7700-db7d-11eb-9d40-71000db7ee87.png)

Ein anderes KNX IP Interface hat keine Probleme weil es auch ohne Confirmation ein L_Data.ind schickt welches vom IOBroker quittiert wird.

![image](https://user-images.githubusercontent.com/86853627/124321300-c0faf800-db7d-11eb-9017-3f23b82ca831.png)

Frage ist: Was fordert die Spec und kann ein ACK in den Adapter eingebaut werden für l_data.con Frames?

**Comment by Garfonso** [comment]
danke 👍

**Comment by Zelkin0815** [comment]
Habe wahrscheinlich das selbe Problem mit meinem MDT Interface, welches ANDERE Interface benutzt du denn? bzw. wie bekomme Ich den Fehler in den Griff??

**Comment by boellner** [comment]
ein Weinzierl 731

**Comment by chefkoch009** [comment]
Besteht das Problem mit V2.0.5 immer noch?

**Comment by Zelkin0815** [comment]
Ich versuche das ganze derzeit einzugrenzen! Habe bei der v2 von 30 auf 25 Telegramme gestellt! Bei 30 hatte Ich noch merkliche Probleme, derzeit läuft der Versuch. Ich habe leider einige "inkompatible" GA Bezeichnungen und dadurch für IO unbekannte GA´s Ich schreib dir über das Forum zu dem Thema nochmal, da es mehrere Themen betrifft bei denen Ich Probleme mit der V2 Festgestellt hab und das hier glaube Ich den Rahmen Sprengt
