### ISSUE TITLE
unkown Inputvalue!

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.knx#186]
knx.0 | 2021-07-16 18:09:49.462 | error | unkown Inputvalue!
-- | -- | -- | --
knx.0 | 2021-07-16 18:09:49.461 | error | Error: unkown Inputvalue! at Object._0x3c735e [as decodeVal] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:226858) at _0x307789.<computed> [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:104581) at _0x27bc2e.<computed>.<computed> [as write] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:227990) at Object._0x1f6f1b [as stateChange] (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:295848) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5706:41) at processImmediate (internal/timers.js:461:21)
knx.0 | 2021-07-16 18:09:49.443 | error | uncaught exception: unkown Inputvalue!

**Comment by trollvottel** [comment]
I see the same error, the adapter dies.

**Comment by chefkoch009** [comment]
This message means that on the one side a wrong datapoint in the ETS is declared or on the other side that you write a malformed value to this object.

**Comment by trollvottel** [comment]
Thamks, need to check with ETS Busmonitor then what's being sent at that moment. But in any case, the adapter must not die but simply ignore (or just log) such telegrams.

**Comment by chefkoch009** [comment]
You are right, I degraded the "kill" to warning.
