### ISSUE TITLE
import ETS 5.7.6 nicht möglich 

### ISSUE THREAD

**Issue by Tomtheripper** [ioBroker/ioBroker.knx#187]
Hey und Guten Abend,

ETS hat wieder geupdatet (5.7.6), jetzt ist ein Import in den KNX-Adapter nicht mehr möglich, wie schon so oft nach einem ETS-Update.
Ich bin kein Entwickler, aber warum muss man denn immer wieder am Projekt-Export "rumschrauben"?
Hoffentlich sind die Änderungen ETS-intern dann auch immer wieder sinn- und wertvoll?!

5.7.5 hat funktioniert.

BG
Tom

**Comment by mdaudi1982** [comment]
Wäre auch dankbar für ein update für den Import aus der ETS 5.7.6.

Gruß

**Comment by Videonisse** [comment]
Duplicate (but other has misspelled header): Issue #178

**Comment by mdaudi1982** [comment]
> Duplicate (but other has misspelled header): Issue #178

No duplicate! Check new Version of ETS 5.7.6 ! Import issue exists again as in previous versions

**Comment by Videonisse** [comment]
Sorry but it is in fact a duplicate. 

From the issue: "Hello,
with the latest KNX Adapter v1.0.45 an import of ETS 5.7.6 (Build 1398) projects is not possible."

**Comment by thizmo** [comment]
Hi,

seems like this here is the same as my problem: #192

**Comment by Tomtheripper** [comment]
Hi chefkoch009,

hast gerade keine Zeit bzw. Lust den Adapter auf die neue ETS anzupassen?
Das wäre echt Schade!
Ich kann mir durchaus Vorstellen, dass die Sache zeitweise tierisch nervt, v.a. wenn auch noch Job/Familie/Hobby unter einen Hut gebracht werden soll...
Aber ich bitte euch Entwickler, auch mal an uns User zu denken, die wir ein System im Haus laufen haben, das halt "einfach funktionieren" soll". 
Deswegen bitte bitte, könntest Du bzw. könntet Ihr den KNX-Adapter auf die aktuelle  ETS anpassen?

Viele Grüße
Tom

**Comment by Apollon77** [comment]
Auch wenn ich nicht der Entwickler bin: Warum müssen den User immer auf "the latest software" updaten wenn Sie gar nicht wissen ob damit die anderen Systeme die Sie brauchen funktionieren?

Daher könnte man das auch rumdrehen in "Aber ich bitte die User, auch mal an (sich selbst und) die Entwickler zu denken, da diese Zeit brauchen nach einem Software Update Dinge anzupassen. Oder wird man bei ETS gezwungen zu updaten?

**Comment by romgen** [comment]
> Auch wenn ich nicht der Entwickler bin: Warum müssen den User immer auf "the latest software" updaten wenn Sie gar nicht wissen ob damit die anderen Systeme die Sie brauchen funktionieren?
> 
> Daher könnte man das auch rumdrehen in "Aber ich bitte die User, auch mal an (sich selbst und) die Entwickler zu denken, da diese Zeit brauchen nach einem Software Update Dinge anzupassen. Oder wird man bei ETS gezwungen zu updaten?

Ich finde es echt traurig, wenn die Entwickler den KNX Adapter erst auf "closed source" setzen und sich dann darüber beschweren, dass sie mit der Arbeit nicht mehr hinterherkommen. Sogar noch schlimmer: Die Benutzer sind schuld.

**Comment by romgen** [comment]
> Hi chefkoch009,
> 
> hast gerade keine Zeit bzw. Lust den Adapter auf die neue ETS anzupassen?
> Das wäre echt Schade!

Der Adapter kann nicht angepasst werden, da die Entwickler den nicht als "Open Source" veröffentlicht haben.

**Comment by chefkoch009** [comment]
viel zu kompliziert.....ist in der neuen AdapterVersion gelöst.

**Comment by trollvottel** [comment]
Welche neue Adapterversion? Hast Du nen Link?
