### ISSUE TITLE
DPT9.002 wrong negative values

### ISSUE THREAD

**Issue by IllegalDuke** [ioBroker/ioBroker.knx#189]
Hello,

I have a few DPTs 9.002 temperature-difference. For positive values everything works fine.
Value: 2 K -> RawData: 00C8
Value: 1.5 K -> RawData: 0096

For negative values, iobroker.knx shows wrong numbers and when sending a value to the KNX bus, a wrong value is send, because the raw data is wrong.
If I send a value from the ETS it looks like this:
Value in ETS: -2 K -> RawData: 873**8** -> Value in iobroker.knx: -1.98 K
Value in ETS: -1,5 K -> RawData: 876**A** -> Value in iobroker.knx: -1.48 K

If I send a value from iobroker to knx:
Value in iobroker.knx: -2 K -> RawData: 873**5** -> Value in ETS: -2.03 K
Value in iobroker.knx: -1.5 K -> RawData: 876**7** -> Value in ETS: -1.53 K

So there has to be a issue with the translation from negative raw values of the DPT 9.002 between iobroker.knx and KNX messages.

Here an example of one of my objects:

> {
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1625598995450,
  "common": {
    "name": "AIR_K01_01 Sollwertverschiebung",
    "type": "number",
    "role": "value",
    "unit": "K",
    "max": 10,
    "min": -10,
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "DPT9.002",
    "address": "1/3/6",
    "addressRefId": "P-06B4-0_GA-89",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-0_R-1944",
    "devName": "M-0083_A-008A-13-5653",
    "devInst": "P-06B4-0_DI-68",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Keller.Lüftung.AIR_K01_01_Sollwertverschiebung",
  "type": "state"
}

I am running version 1.0.45 of the knx adapter and node: v15.14.0, js-controller: 3.2.16

Can you please check and give me feedback.

Thank you.

Daniel

**Comment by chefkoch009** [comment]
I can confirm this. It is fixed in next version.
