### ISSUE TITLE
KNX Projekt Import - Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by TheBigS1981** [ioBroker/ioBroker.knx#19]
Hallo,

nach dem Update von 0.8.6 auf 1.0.4 hatte ich einige Probleme (Blockly Scripte gingen nicht mehr), so dass ich mich dazu entschlossen habe, meine KNX-Instanz zu löschen, neu anzulegen und anschließend mein KNX-Projekt (ETS 5.6.3) neu zu importieren. Leider ist es sowohl mit der Version 1.0.4, als auch mit der Version 1.0.5 nicht mehr möglich ein Projekt zu importieren. Sobald die Projektdatei hochgeladen wurde, erhalte ich folgende Fehlermeldung:

`2018-03-03 12:54:30.633  - error: knx.0 message messagebox.system.adapter.knx.0 [object Object] Cannot read property 'nodeType' of undefined

2018-03-03 12:54:30.635  - error: knx.0 TypeError: Cannot read property 'nodeType' of undefined
    at /opt/iobroker/node_modules/iobroker.knx/knx.js:128:2133
    at _0x50fe09 (/opt/iobroker/node_modules/iobroker.knx/knx.js:128:450)
    at /opt/iobroker/node_modules/iobroker.knx/knx.js:128:215
    at null.matches (/opt/iobroker/node_modules/iobroker.knx/knx.js:128:1779)
    at Function._0x1ac0da.applyStep (/opt/iobroker/node_modules/iobroker.knx/knx.js:128:59372)
    at /opt/iobroker/node_modules/iobroker.knx/knx.js:128:59789
    at /opt/iobroker/node_modules/iobroker.knx/knx.js:128:1096
    at /opt/iobroker/node_modules/iobroker.knx/knx.js:128:661
    at _0x50fe09 (/opt/iobroker/node_modules/iobroker.knx/knx.js:128:450)
    at /opt/iobroker/node_modules/iobroker.knx/knx.js:128:1035`

Der KNX-Adapter funktioniert allerdings problemlos, da ich Values vom Bus empfange.

Da ich vermutete, dass vielleicht das KNX-Projekt zu groß ist, habe ich mein bestehendes Projekt geklont und nur noch ein paar Gruppenadressen übrig gelassen. Auch hiermit konnte ich das Projekt nicht hochladen. Ich habe das Projekt mal hochgeladen. [KNX-Projekt.zip](https://github.com/ioBroker/ioBroker.knx/files/1777451/KNX-Projekt.zip)

Übrigens, vielen Dank für die Entwicklung und den Support!

**Comment by TheBigS1981** [comment]
Hallo  @chefkoch009,

so wie ich das sehe, bist Du hier ja sehr aktiv. Hast Du vielleicht eine Idee, woran mein Problem liegen könnte? Da ich die neuste ETS Version habe, kann ich leider nicht zurück auf eine ältere iobroker.knx Version. Vielleicht hast Du ja einen Tipp für mich.

**Comment by chefkoch009** [comment]
Kontaktier mich bitte einmal per PN in http://forum.iobroker.net/viewtopic.php?f=36&t=3934&sid=83c2dc6f5b5581ef123deece44089623&start=500

**Comment by chefkoch009** [comment]
Das war ein Problem mit dem Sequenzcounter. Ist in der 1.0.9 behoben.

**Comment by thorsten-gehrig** [comment]
ich krieg die krise... hab gerade den iobroker aktualisiert und jetzt bekomme ich: Cannot read property 'write' of undefined (bei KNX). Ich habe den Raspberry schon 2x komplett neu aufgesetzt.
Die repos sind auf "latest" - KNX auf 1.0.20 (also weit neuer als der 1.0.9).
Das KNX gateway wird gefunden.

Irgendwelche tips?
Hier die volle fehlermeldung:

knx.0 | 2019-06-08 17:16:14.523 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
knx.0 | 2019-06-08 17:16:14.523 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
knx.0 | 2019-06-08 17:16:14.523 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-06-08 17:16:14.523 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2019-06-08 17:16:14.523 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
knx.0 | 2019-06-08 17:16:14.523 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:278:10)
knx.0 | 2019-06-08 17:16:14.523 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-06-08 17:16:14.523 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
knx.0 | 2019-06-08 17:16:14.523 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
knx.0 | 2019-06-08 17:16:14.523 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:2708)
knx.0 | 2019-06-08 17:16:14.523 | error | TypeError: Cannot read property 'write' of undefined

**Comment by psychos4** [comment]
Ich muss mich auch @thorsten-gehrig anschließen ich bekomme mit Version 1.0.20 auch immer die Fehlermeldung: 

TypeError: Cannot read property 'write'
message knx.0.Türen__Tore__Fenster.XXXX [object Object] Cannot read property 'write' of undefined

Komischerweise funktioniert es bei manchen Objekten / Adressen zu schreiben, aber beim Großteil nicht.
