### ISSUE TITLE
Immer wieder Exception

### ISSUE THREAD

**Issue by Automatisierer0** [ioBroker/ioBroker.knx#190]
In unregelmäßigen Abständen macht der KNX-Adapter eine Exception.

![Exception_01 - in github gemeldet](https://user-images.githubusercontent.com/88152701/127517307-d6b315cf-c8f0-4e3c-9919-dc8fe89e2ef2.jpg)
![Exception_02 _- in github gemeldet](https://user-images.githubusercontent.com/88152701/127517321-6608c739-4073-4fe2-bf9f-dd5040f66d29.jpg)

**Comment by chefkoch009** [comment]
Dieser Fehler ist in der kommenden Version behoben. Ursache kann falscher DPT sein oder es wird ein ungültiger Wert übergeben.
