### ISSUE TITLE
Error: Projectimport with this ETS Version not yet possible.

### ISSUE THREAD

**Issue by joergheilig** [ioBroker/ioBroker.knx#192]
I have tried to import a file created with ETS 5.7.6 and I got the popup message: "Error: Projectimport with this ETS Version not yet possible." I am happy to provide the file by email if you contact me directly.

**Comment by thizmo** [comment]
Same here. Tried the different solution to modify 0.xml with ToolsVersion. 
I could then import it. Yet it seems that i can not use it.

**Comment by maba2402** [comment]
I am facing the same issue. 
Unfortunately, I do not see the sources of this adapter in the repo. Did I miss somehting?
Is there a way to contribute? 

BTW, thanks a lot for the excellent work so far.

**Comment by Stefan592** [comment]
Same problem with new ETS V6.

If desired, a project export can be provided.

**Comment by chefkoch009** [comment]
The upcoming Major Release will be able to import projects from every ETS Version incl ETS-V6.

The "timekillers" are the changes in ETS exports between different Versions. Thatswhy it often takes a little longer to build the next Version.

**Comment by MartinMohr** [comment]
Gentle Question:
Is there already a Release Date?
