### ISSUE TITLE
Immer weider Exception III

### ISSUE THREAD

**Issue by Automatisierer0** [ioBroker/ioBroker.knx#194]
In unregelmäßigen Abständen macht der KNX-Adapter eine Exception.

![Exception - in github gemeldet](https://user-images.githubusercontent.com/88152701/130261064-1bdbc037-7657-401c-9fb2-0c94917c8a89.jpg)

**Comment by chefkoch009** [comment]
Was hat 12/4/229 für ein datenpunkttypen?

**Comment by Automatisierer0** [comment]
Vielen Dank für Ihre Rückmeldung bzw. Rückfrage !

**Ich habe es mr angeschaut und habe folgendes Problem identifiziert:**

Der Adapter wirft eine Exception aufgrund der GA 12/4/229
Dies GA kommt von einer VISU und diese sendet diese GA an ein anderes KNX-Spezialdevice. Dies funktioniert auch problemlos.
Nur ist es so, dass diese GA nicht im Importfile enthalten ist (Projekt.knxproj) und daher auch nicht in den KNX-Adapter importiert wird. D.h. der KNX-Adapter kennt diese GA nicht.
Ich kann diese Adresse natürlich ins Importfile projekt.knxproj-aufnehmen.

**Vorschlag:**
Ich würde vorschlagen, der KNX-Adapter verhält sich wie jedes andere KNX-Gerät und verwirft einfach GAs welche er nicht kennt und feuert keine Exception. Meine MDT-Geräte machen ja auch keine Exception aufgrund der ihnen nicht bekannten GA 12/4/229
Es würde meiner Meinung nach ausreichen, wenn der KNX-Adapter eine Fehlermeldung ins IOBroker-Logflie schreibt.

**Comment by Automatisierer0** [comment]
Ich glaube ich habe hier etwas falsch bedient.
Ich wollte das Issue nicht closen !!!
SORRY
Ich weiss jetzt nicht was ich tun muss damit dieses wieder geöffnet wird !!

**Comment by Automatisierer0** [comment]
Sorry für die Verwirrung!
Habe es weider angelegt.

**Comment by boellner** [comment]
Macht er ja auch nicht. Deswegen die Frage welcher DPT und Welche version vom Adapter`?

**Comment by Automatisierer0** [comment]
Hier die Infos:

Adapterversion:
![12_4_229 -Adapter Version](https://user-images.githubusercontent.com/88152701/131569579-f2ea1192-1216-453a-9b85-96180d189041.jpg)

Die Frage mit dem DPT kann ich nicht beantworten, weil ja 12/4/229 nicht in der ETS enthalten ist.
Vielleicht hilft dieser ETS Monitor Screenshot weiter:
![12_4_229 - ETS Sceenshot](https://user-images.githubusercontent.com/88152701/131569754-dfc8ae87-598d-40af-867b-c2ca617635c4.jpg)

Zur Sicherheit hier auch der Auszug aus dem LOG:
![12_4_229 -Log mit neuen Admin](https://user-images.githubusercontent.com/88152701/131569900-45eade38-6a6b-41a3-9138-4e80a2acc927.jpg)

Was mir auch aufgefallen ist: 
Der Adapter restartet dann nicht mehr von selber, weil er meint Restart LOOP Detected
PS: Ich habe vor dieser Exception ungefähr in den letzten 2-3 Minuten 4 mal diese Exception gehabt.

**Comment by chefkoch009** [comment]
ist in der kommenden Version behoben.
