### ISSUE TITLE
Exception bei falschen Übergabeparameter

### ISSUE THREAD

**Issue by Automatisierer0** [ioBroker/ioBroker.knx#195]
Der KNX Adapter macht bei einem falschen Übergabeparameter eine Exception.

Es wird - durch einen Fehler in einem anderen Adapter - bei “STEUERE“ NULL an den KNX-Adapter übergeben.
Hier der Script:
++++++++++++ Screenshot: Blockly - mit Kommentar.jpg++++++++++++++++
![Blockly - mit Kommentar](https://user-images.githubusercontent.com/88152701/130319906-17560704-24e3-4489-9f8c-fcfa295ca862.jpg)

Dieser Übergabeparameter wird vom KNX-Adapter scheinbar nicht explizit geprüft und daher kommt es zu einer Exception.
++++++++++++ Screenshot: LOG - mit Kommentar.jpg ++++++++++++++++
![LOG - mit Kommentar](https://user-images.githubusercontent.com/88152701/130319912-166b5d65-ae27-419f-93b1-cd43aae18bcd.jpg)

Ich weiß schon, dass dies ein Folgeproblem eines anderen Adapters ist, aber als Vorschlag könnte der KNX-Adapter auf NULL-Pointer abfragen und nur eine Fehlermeldung ausgeben statt gleich eine Exception zu werfen.

**Comment by chefkoch009** [comment]
Vielen Dank für die sehr gute Info. Diese Exception darf nicht auftreten und wird in der kommenden Version behoben sein.

**Comment by Automatisierer0** [comment]
Herzlichen Dank !

**Comment by chefkoch009** [comment]
Habe es auf ein "Warning" klassifiziert. BTW. diese Meldung kann auch kommen, wenn der DPT falsch gesetzt ist.
