### ISSUE TITLE
Warum bekommt man hier kein Feedback auf Fehlermedungen II

### ISSUE THREAD

**Issue by Automatisierer0** [ioBroker/ioBroker.knx#198]
Sehr geehrter Herr “Maintainer“ des KNX-Adapter,

Vielen Dank für Ihren Gedankenanreiz.

Ich habe nicht behauptet, dass hier eine Verpflichtung besteht, ich habe Sie um Feedback gebeten.
Ich finde es toll von Ihnen, dass Sie die Entwicklung in privater Zeit und mit privaten Mitteln durchführen.
Ich bin gerne bereit, Sie in welcher Form auch immer zu unterstützen und damit bei der Weiterentwicklung zu helfen.
Wenn Sie daran Interesse haben, lassen sie mich das wissen.
Meine email Adresse ist: harald@voglerhome.at

Leider habe ich keine andere Möglichkeit als über diesen Weg in Kontakt zu kommen, falls Interesse besteht bitte um Ihre Kontaktadresse.

Bezüglich des Ersuchens um Feedback für ein eingebrachtes Issue, kann ich Ihnen nur sagen dass es einem als Einbringer wirklich helfen würde, dass man weiss wie es mit diesem gemeldeten Issue weitergeht und was damit geplant ist.

**Comment by Micheagle** [comment]
Hallo zusammen,

ich behaupte mal, dass es daran liegt, dass hier Menschen am Werk sind, die das hobbiemäßig betreiben.
Sprich, mal hat man Zeit und Motivation, dann geht es voran.
Mal hat man Familie, dann geht es hier langsamer ...

Und ich habe hier bisher immer gute Erfahrungen gesammelt, insbesondere wenn man Geduld hat, den Ton trifft und selbst auch bereit ist, Zeit zu investieren um bspw. Fehler zu finden.

Die meisten Punkte sind mir in ihrem Eintrag schon aufgefallen.
Also etwas Geduld mitbringen, (und das darf dann auch mal ein paar Tage dauern oder auch mehr), 
dann wird dir/Ihnen/uns sicher wieder weiter geholfen.

Viele freundliche Grüße
Micheagle

**Comment by chefkoch009** [comment]
@Micheagle  Danke, genau das ist es.

Ich schließe diesen Issue, weil er keiner ist, somit gibt es dafür nichts zu tun.
