### ISSUE TITLE
newer version available

### ISSUE THREAD

**Issue by ekarak** [ioBroker/ioBroker.knx#2]
Hi ioBroker team,

I've just released version 2.0 of knx.js which contains multiple features incl. throttling (when writing to TP1, you should restrain yourself to 9600bps)

Please link to the knx package as a npm dependency instead of raw copying the package under lib/connector. In 1.2.0 there's a nasty race condition that prevents writing multiple telegrams to the wire, which especially affects slower devices like the Raspberry. Please see:
https://bitbucket.org/ekarak/knx.js/issues/15/fsm-not-transitioning-into-waitack-after

You can keep package stability by using a absolute version in the package.json dependency section:
```
  "dependencies": {
    "knx": "2.0.0",
```

Thanks

**Comment by chefkoch009** [comment]
Hi ekarak,

it is not a real copy of your package. There are some modifications inside. This was necessary, because some dpt's didn't work as expected. It also wasn't possible to change the phys adr.

chefkoch009

**Comment by chefkoch009** [comment]
implemented usage of knx package

**Comment by chefkoch009** [comment]
more and more dpt's where supported by knx package
