### ISSUE TITLE
knx lizenz eingeben geht nicht

### ISSUE THREAD

**Issue by axelrathey** [ioBroker/ioBroker.knx#20]
Hallo,

nach dem Update auf iobroker.knx 1.0.5 und vorher auf iobroker.admin 3.2.4 kann ist bei mir der Lizenzeintrag vom knx weg und die KNX-Instanz startet daher nicht. In der Konfiguration der KNX-Instanz gibt es ein Lizenzfeld. Dort kann ich auch die Lizenz hereinkopieren. Der Button "Lizenz prüfen" und "help" bleibt aber grau. Die Buttons Speichern und auch Speichern und Schließen reagieren nicht. Wenn ich anders herausgehe, kommt eine Nachricht, dass die Angaben im Dialog nicht gespeichert sind, was ich dann mit OK bestätigen kann. Den Lizenzschlüssel hatte ich direkt aus dem Browser kopiert und eingefügt. Der ist ja recht lang.
Daraus ergibt sich die Frage wie/wo ich den KNX-Lizenz Schlüssel eingeben kann. 
Im https://iobroker.net/accountLicenses hatte ich mir die private knx Lizenz erstellt. Dort steht bei Version < 2. Bezieht sich das auf die iobroker.knx version oder auf die iobroker.admin version?
Kann man die Lizenz vielleicht irgendwie zunächst mal manuell einfügen in eine Config-Datei? Wenn ja in welchem Pfad steht diese?

Danke für die Hilfe
Axel

**Comment by chefkoch009** [comment]
Hallo Axel,

schau bitte hier einmal nach : http://forum.iobroker.net/viewtopic.php?f=36&t=3934&start=480#p129587

Dann sollte es mit Deiner Lizens auch funktionieren. Die Lizens bezieht sich auf die Adapterversion des knx Adapters.

VG

**Comment by axelrathey** [comment]
Hallo chefkoch,
jetzt geht es, war noch was beim Firefox im Cache. Den musste ich erst löschen. Dann konnte ich die Lizenz auch speichern.
Allerdings habe ich jetzt keinen Schreibzugriff mehr auf die knx.Objekte. Es änder sich zwar der Zustand in der Visualisierung aber nicht in der Realität. Wenn ich in der Realität schalte, erfolgt aber die Anzeige in der Visualisierung.
Ist da seit 0.8.6 was geändert worden?
