### ISSUE TITLE
Keine Verbindung ab 1.0.38

### ISSUE THREAD

**Issue by iobroker99** [ioBroker/ioBroker.knx#201]
Habe ein Update von 1.0.20 auf 1.0.45 gemacht, seitdem gibt es keine Verbindung mehr ("Verbunden mit Gerät oder Dienst" rot). Rollbacks bis auf 1.0.38 mit gleichem Resultat. Bei Rollback auf 1.0.20 gehts wieder
ioBroker läuft auf Synology mit Docker, macvlan. Auf meiner Testbüchse, andere Synology aber gleiche Config funktioniert 1.0.45 problemlos. 
Any ideas?

**Comment by chefkoch009** [comment]
Zwischen den Einzelnen Versionen gibt es Unterschiede in der Art und Weise, wie die Objekte erzeugt werden. So kann es sein, das bei Sprüngen zwischen den Versionen die Objekte nicht richtig gelesen werden können. In diesem Fall hilft auf jeden Fall ein Neuimport des Projektes.
