### ISSUE TITLE
Object of state "knx.0.info.connection" is missing the required property "common.type"

### ISSUE THREAD

**Issue by ElRedef** [ioBroker/ioBroker.knx#203]
Hello,

i get the following warning:
`Object of state "knx.0.info.connection" is missing the required property "common.type"`

If i add this state manually it disappears.  But after some time it comes back.

I use v1.0.45

**Comment by chefkoch009** [comment]
Is this message from knx.0? Can you give some more informations? Did you make update, is your system a fresh build,....?

**Comment by ElRedef** [comment]
Hey,

i get this message since, hmmm .... 2 month or so? I don't know if there was an update at this time. 
To fix it i started to add the attribute manually as type boolean. Then the error message disappears. After some time it comes back. In the past I just added the attribute again (In the hope that someone else will make the bug report ;-) )

The message is from knx.0:
`knx.0 (692) Object of state "knx.0.info.connection" is missing the required property "common.type"`

**Comment by chefkoch009** [comment]
Is your admin AND js-controller at latest version? this could be the reason.

**Comment by chefkoch009** [comment]
This is fixed in V2.x

**Comment by ElRedef** [comment]
Ah okay.
What was the root cause? What is the exact Code Change?
