### ISSUE TITLE
DPT9.000 wird falsch umgerechnet

### ISSUE THREAD

**Issue by Automatisierer0** [ioBroker/ioBroker.knx#205]
Die Verarbeitung im IO-Broker ist beim Datenpunkttyp DPT9.000 falsch.

**Beispiel:**
In der ETS ist für einen Datenpunkt als Datenpunkttyp DPT9.000 eingestellt. Das Einlesen in den IO-Broker funktioniert, in den Objekten des IO-Broker ist der zugehörige Datenpunkttyp richtig eingelesen und hat ebenfalls DPT9.000.
Ich sende nun dieses Telegramm von der externen VISU mit dem Wert 15. 
Die ETS zeigt im Gruppenmonitor unter DPT an: DPT = 9 * 2 Byte Gleitkommawert, Wert= 05 DC | 15
Im IO-Broker wird beim Datenpunkt als Wert nun angezeigt: 1500
--> Es wird falsch umgerechnet (DPT9.000 ist ein 16 Bit FLOAT-Wert und kein 16Bit INT)
--> Der Wert “5DC“ ist 1500 bei 16 Bit INT, es ist aber ein 16 Bit FLOAT und daher ist “5DC“ umgerechnet der Wert 15 und nicht 1500 !!

Wenn ich den Datenpunkttyp auf 9.010 stelle dann funktioniert es.
Es wird dann richtigerweise 15 als Wert im IO-Broker angezeigt.

**Comment by chefkoch009** [comment]
can you please check with Adapter V2?

**Comment by chefkoch009** [comment]
seems so
