### ISSUE TITLE
Error: Projectimport with this ETS Version not yet possible.

### ISSUE THREAD

**Issue by ChrisDuck87** [ioBroker/ioBroker.knx#206]
Ich bekomme obengenannte Fehlermeldung beim Einlesen meiner .knxproj-Datei. 

Installierte Version ist 5.7.6
Unter den Bewertungen im IO-Broker habe ich gesehen das ich hier nicht alleine bin, allerdings habe ich in GitHub keinen Fehler dazu gefunden, deshalb hab ich diesen hier geöffnet. 

Solltest jemand die Datei von mir benötigen jederzeit gerne.

**Comment by chefkoch009** [comment]
der Release der neuen Version ist für den 1.12.2021 geplant.

**Comment by ChrisDuck87** [comment]
Super Danke! Finde euren Support super!!

**Comment by chefkoch009** [comment]
Danke, ist aber noch ausbaufähig. Für Fragen rings um den Adapter kann man hier: https://forum.iobroker.net/topic/49696/test-adapter-knx-v2-x nachschauen. Da sind viele "Forumer" mit hervorragender Expertise unterwegs.

**Comment by ChrisDuck87** [comment]
Hey,

hab grad das Update aufgeführt. 

Allerdings bekomme ich zwar die Version 2.0 angezeigt

![image](https://user-images.githubusercontent.com/88966869/144312565-139f4f36-91d5-483e-a3c8-916156da9179.png)

Allerdings wenn ich draufgeh krieg ich die "alte" Oberfläche angezeigt.
![image](https://user-images.githubusercontent.com/88966869/144312716-7b183f2c-3b55-4c05-a813-981d01a5b72d.png)
an was kann das liegen?

**Comment by ChrisDuck87** [comment]
Js-Controller und Iobroker.admin habe ich upgedatet

**Comment by chefkoch009** [comment]
gib mal bitte in der console folgendes ein:

iobroker u knx

**Comment by chefkoch009** [comment]
prüfe bitte weiterhin, ob der Besitzer des iobroker.knx Verzeichnisses und aller enthaltenen Elemente passt.

**Comment by ChrisDuck87** [comment]
hat nichts gebracht. ich hab jetzt alles zurückgesetzt und wart bis es im IoBroker offiziell verfügbar ist.

**Comment by ChrisDuck87** [comment]
aber danke für den Support :)

**Comment by ChrisDuck87** [comment]
Hat jetzt funktioniert! Top danke!
