### ISSUE TITLE
Exception im KNX.Adapter

### ISSUE THREAD

**Issue by Automatisierer0** [ioBroker/ioBroker.knx#207]
Der KNX. Adapter macht die folgende Exception:

![Exeption](https://user-images.githubusercontent.com/88152701/143782848-5c5526aa-777c-4c6b-b728-9d3c53dff8af.jpg)
:

**Comment by chefkoch009** [comment]
die exception kommt vom javascript adapter. Ausser in der Hostbezeichnung kann ich leider nirgends "knx" sehen. Ich denke ein Ansatz zur Fehlersuche bei Deinem problem ist "max-old-space-size".
