### ISSUE TITLE
Keine Verbindung über GiraX1

### ISSUE THREAD

**Issue by p980privat** [ioBroker/ioBroker.knx#210]
Ich verwende als KNX IP Schnittstelle den Gira X1. Seit Version 2.0 baut iobroker keine Verbindung mehr über Port 3671 auf. Gibt es hierfür eine Lösung?

**Comment by chefkoch009** [comment]
schreib mir bitte eine PN im iobroker Forum.

**Comment by chefkoch009** [comment]
Scheint sich gelöst zu haben.
