### ISSUE TITLE
Falsche Fehlermeldung No license found for knx

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#211]
Wenn man die kostenlose 500 Lizenz verwendet kommt fälschlicherweise die Fehlermeldung

error | No license found for knx. Please get one on https://iobroker.net/accountLicenses !

**Comment by Missenberger79** [comment]
Hast du im Lzenzfenster die alte Lizenz gelöscht? 
es darf nichts drin stehen. 
Dann auf speichern. Danach ging es bei mir!

**Comment by TA2k** [comment]
Es geht auch alles, aber der Adapter gibt trotzdem den Fehler beim Start aus

**Comment by chefkoch009** [comment]
bitte update auf Version 2.0.2 machen. sind der js-controller und der admin aktuell?

**Comment by TA2k** [comment]
Alles aktuell
<img width="783" alt="image" src="https://user-images.githubusercontent.com/1307684/144567931-7a6257fc-6f98-4e71-85ea-c4aa3eca340c.png">

**Comment by chefkoch009** [comment]
kannst du mir bitte eine PN im iobroker forum schicken?

**Comment by Videonisse** [comment]
If anyone else has this Problem when upgrading from 1.0.xx to v2.x, for me the Solution was:

1. Start KNX Adapter
2. Open KNX Adapter Configuration page
3. What until you see the message below:
4. Click the Highlighted text
5. Delete the old License
6. Save and close

![image](https://user-images.githubusercontent.com/13684218/144707753-9098020f-fa06-4c2e-8e07-4d70c2a24d85.png)

**Comment by Videonisse** [comment]
A suggestion to @chefkoch009 is to avoid this error and instead ask the User if the old license should be deleted, or just automatically delete it during the upgrade.

**Comment by chefkoch009** [comment]
You are right. I haven't seen this as problem, yet. But in fact, it confuses. I'll fix this.

**Comment by chefkoch009** [comment]
is fixed in 2.0.3

**Comment by FF-Ibb-PD** [comment]
Leider tritt der Fehler bei mir nach wie vor auf.
![grafik](https://user-images.githubusercontent.com/11741795/144767157-a7bd2002-9ce3-4e04-b925-fe3368268fe5.png)

**Comment by chefkoch009** [comment]
Hast du auf V2.0.3 aktualisiert?.....in dieser gibt es diese Fehlermeldung nicht mehr.

**Comment by FF-Ibb-PD** [comment]
Ja, siehe Log unter dem Error. "Version 2.0.3"

**Comment by m4tze-smart** [comment]
habe bei mir auch das Problem ... bei mir lief der Adapter allerdings mit 2.0.2 noch und seit 2.0.3 Dauerrebootschleife.

`
knx.0 | 2021-12-06 23:36:49.232 | info | Connecting to knx GW: 192.168.180.4:3671 with phy. Adr: 1.1.202
-- | -- | -- | --
knx.0 | 2021-12-06 23:36:49.230 | warn | No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
knx.0 | 2021-12-06 23:36:49.188 | info | starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.knx, node: v14.18.1, js-controller: 3.3.21
knx.0 | 2021-12-06 23:36:45.429 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
knx.0 | 2021-12-06 23:36:45.428 | info | terminating
knx.0 | 2021-12-06 23:36:45.427 | info | Got terminate signal TERMINATE_YOURSELF
knx.0 | 2021-12-06 23:36:45.389 | info | Connecting to knx GW: 192.168.180.4:3671 with phy. Adr: 1.1.202

`

**Comment by chefkoch009** [comment]
Schreib mir bitte eine PN im Forum.

**Comment by Videonisse** [comment]
@chefkoch009 When installing a new Instance, I get 16 error messages (!) in the log before the Adapter understands that a license is not needed. I would prefer that no errors are logged before a project file has been imported and the number of DPs has been verified.

Example: 
`No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !`

**Comment by chefkoch009** [comment]
fixed in V2.0.5, can you verify and close this issue?

**Comment by FF-Ibb-PD** [comment]
In V2.0.5 this issue seems to be closed!

**Comment by chefkoch009** [comment]
thanks for response. I close this issue now.
