### ISSUE TITLE
UUID des iobroker Server

### ISSUE THREAD

**Issue by mdaudi1982** [ioBroker/ioBroker.knx#212]
Hallo,

Um die neue Lizenz für den KNX Adapter zu bestellen, benötige ich die UUID des iobroker Server.
Wo finde ich diese?

Dank und Gruss,

Micha

**Comment by Garfonso** [comment]
in den Einstellungen vom vis Adapter, z.B..

@chefkoch009 wenn noch nicht geschehen, sollte sie auch in den Einstellungen vom knx Adapter auftauchen (hab 2.x noch nicht installiert)

**Comment by chefkoch009** [comment]
Hallo,

ist hier zu finden: https://github.com/ioBroker/ioBroker.knx#configuration-interface unter Punkt 9.
