### ISSUE TITLE
Can't install KNX V2.x 

### ISSUE THREAD

**Issue by eddymc3** [ioBroker/ioBroker.knx#213]
Hello, my ioBroker is installed on an Intel NUC with Proxmox and Unbuntu
nodejs 14.18.2, npm 6.14.15, ioBroker 3.3.21

In iobroker/Adapter I can not find the new interface. 
Here is the debug from the installation:

$ iobroker url iobroker.knx --host ioBroker --debug

install iobroker.knx

NPM version: 6.14.15

npm install iobroker.knx --prefix "/opt/iobroker" (System call)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.7 (node_modules/osx-temperature-sensor):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman-converters/node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/zigbee-herdsman/node_modules/fsevents):npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.knx@1.0.45updated 1 package in 10.951s

123 packages are looking for funding run `npm fund` for details

upload [7] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/zip/zip.js zip/zip.js application/javascript

upload [6] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/zip/zip-ext.js zip/zip-ext.js application/javascript

upload [5] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/zip/z-worker.js zip/z-worker.js application/javascript

upload [4] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/zip/inflate.js zip/inflate.js application/javascript

upload [3] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/words.js words.js application/javascript

upload [2] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/knx.png knx.png image/png

upload [1] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/index_m.html index_m.html text/html

upload [0] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/index.html index.html text/html

Adapter "system.adapter.knx.0" restarted.

Update "system.adapter.knx.0"

Process exited with code 0

Thanks and best regards
Stefan

**Comment by chefkoch009** [comment]
To install the latest version you can:
1) change in admin your repository from stable to latest or
2) from /opt/iobroker type npm install iobroker.knx@latest

**Comment by eddymc3** [comment]
Thank you, works fine.
The problem was the admin adaptor
