### ISSUE TITLE
DPT9.024 falsche Wertübertragung

### ISSUE THREAD

**Issue by 93schlucko** [ioBroker/ioBroker.knx#214]
Erst seit der Version v2 - Aktuelle installierte Version: 2.0.3
Wenn ich einen Wert über den Adapter vom ioBroker auf den KNX-Bus (DPT9.024) schreibe wird dieser um ca. 0,02 kleiner, das heißt: Wenn ich zB. den Wert 5 schreibe, kommt 4,98 im Gruppenmonitor an -> an meinem Glastaster wird die 4 angezeigt. Bei z.B. Wert 0 wird dann -655,36 angezeigt.
..
![Clipboard01](https://user-images.githubusercontent.com/95643805/144889093-091e4bbb-889d-498c-8abc-bbeea11bf33e.jpg)
..
![Clipboard02](https://user-images.githubusercontent.com/95643805/144889100-ffb2fe2a-38fd-4645-bbba-7294c8cfe972.jpg)

**Comment by Videonisse** [comment]
I can confirm this issue. It seems ALL DPT9 values that are sent from KNX Adapter to the Bus get the wrong value.

From Bus to ioBroker works fine.

**Comment by chefkoch009** [comment]
I also confirm this. Solution is still in process.

**Comment by chefkoch009** [comment]
die neue Version ist online. bitte den Issue schliessen, wenn gelöst.

**Comment by Videonisse** [comment]
Issue solved in v.2.0.4, I have verified.
