### ISSUE TITLE
knxprod import ohne Funktion

### ISSUE THREAD

**Issue by an-klam** [ioBroker/ioBroker.knx#215]
Wie schon im Forum erwähnt erhalte ich beim Import der knxprod Fehler und es werden keine neuen Objekte angelegt.
ETS4.1.6
admin mittlerweile 5.2.1
Einige Gruppenadressen sind angelegt aber noch nicht mit KO verknüpft.

Adapter und Instanz komplett gelöscht und neu installiert. Hat leider auch nicht geholfen.

<html>
<body>

knx.0 | 2021-12-08 08:46:27.976 | info | Connecting to knx GW: 192.168.100.20:3674 with phy. Adr: 0.0.1
-- | -- | -- | --
knx.0 | 2021-12-08 08:46:27.973 | warn | No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
knx.0 | 2021-12-08 08:46:27.900 | info | starting. Version 2.0.4 in /opt/iobroker/node_modules/iobroker.knx, node: v14.17.6, js-controller: 3.3.21
host.raspberrypi | 2021-12-08 08:46:25.715 | info | instance system.adapter.knx.0 started with pid 11474
host.raspberrypi | 2021-12-08 08:45:55.680 | info | Restart adapter system.adapter.knx.0 because enabled
host.raspberrypi | 2021-12-08 08:45:55.673 | error | instance system.adapter.knx.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
knx.0 | 2021-12-08 08:45:55.065 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
knx.0 | 2021-12-08 08:45:55.064 | info | terminating
knx.0 | 2021-12-08 08:45:55.060 | debug | Adapter close
knx.0 | 2021-12-08 08:45:55.057 | error | Cannot read property 'read' of undefined
knx.0 | 2021-12-08 08:45:55.057 | error | TypeError: Cannot read property 'read' of undefined at /opt/iobroker/node_modules/iobroker.knx/knx.js:1:290108 at Function.each (/opt/iobroker/node_modules/underscore/underscore-node-f.cjs:1323:7) at _0x4fef10 (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:289649) at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:297868) at listOnTimeout (internal/timers.js:559:11) at processTimers (internal/timers.js:500:7)
knx.0 | 2021-12-08 08:45:55.054 | error | uncaught exception: Cannot read property 'read' of undefined
knx.0 | 2021-12-08 08:45:53.302 | debug | knx.js Time fillProject STOP : 0s 468.1205ms
knx.0 | 2021-12-08 08:45:52.833 | debug | knx.js Time fillProject start.
knx.0 | 2021-12-08 08:45:52.833 | debug | knx.js Zeitmessung parseProject STOPP :
knx.0 | 2021-12-08 08:45:52.822 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.814 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.806 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.797 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.785 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.772 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.763 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.751 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.740 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.731 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.722 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.715 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.693 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.680 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.668 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.626 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.614 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.606 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.598 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.589 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.574 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.566 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.558 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.546 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.520 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.512 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.504 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.496 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.470 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.462 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.427 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.424 | debug | sendTo "verifyLicense" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.389 | debug | sendTo "projectDeviceFile" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:52.178 | debug | sendTo "projectKnxMaster" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:51.169 | debug | sendTo "projectXml0" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:50.637 | debug | sendTo "projectStart" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:45.927 | debug | sendTo "verifyLicense" to system.adapter.admin.0 from system.adapter.knx.0
knx.0 | 2021-12-08 08:45:45.906 | debug | sendTo "verifyLicense" to system.adapter.admin.0 from system.adapter.knx.0

</body>
</html>

**Comment by chefkoch009** [comment]
Kann ich zur Fehlersuche die Projektdatei zur Verfügung gestellt bekommen?

**Comment by an-klam** [comment]
gerne per email.

**Comment by chefkoch009** [comment]
Muss kleiner als 10mb sein.

**Comment by an-klam** [comment]
ist kleiner.
gibst du mir eine email-adresse oder soll ich es dir irgendwie im Forum schicken?

**Comment by chefkoch009** [comment]
Info@punktnetzwerk.net

**Comment by an-klam** [comment]
Funktioniert mit V2.0.5
