### ISSUE TITLE
wrong amount of datapoints after reimport ETS project ?

### ISSUE THREAD

**Issue by marlan99** [ioBroker/ioBroker.knx#216]
i had a correct running KNX instance with 457 datapoints.
i then updated it to the version 2.0.4 and it was still working correct. old licence was removed and and in the log i could see the instance started with 457 datapoints.

Now i imported again my ETS project including unmarking the option "only import new ones".
I got the message 457 objects imported successfully.
It then started the instance still fine but with the following logentry

`
knx.0 | 2021-12-08 13:59:00.075 | info | Connected! with 193 datapoints of 925 Datapoints over all.
-- | -- | -- | --
knx.0 | 2021-12-08 13:59:00.051 | info | Connected - local UDP Server listening on 192.168.1.79:50841
knx.0 | 2021-12-08 13:59:00.040 | info | Debuglevel: 0 1
knx.0 | 2021-12-08 13:59:00.027 | info | Connecting to knx GW: 192.168.1.82:3671 with phy. Adr: 1.1.249
`

i stopped the instance. deleted every KNX objects, started again and imported the ETS project again.
message appears 457 objects imported successfully but still the wrong amount in the log:

`
knx.0 | 2021-12-08 14:20:20.525 | info | Connected! with 183 datapoints of 905 Datapoints over all.
-- | -- | -- | --
knx.0 | 2021-12-08 14:20:20.505 | info | Connected - local UDP Server listening on 192.168.1.79:49737
knx.0 | 2021-12-08 14:20:20.481 | info | Debuglevel: 0 1
knx.0 | 2021-12-08 14:20:20.464 | info | Connecting to knx GW: 192.168.1.82:3671 with phy. Adr: 1.1.249
`

**Comment by marlan99** [comment]
information in addition:

in the overview of the instance the amount of datapoints is correct:

`Lizenz gültig.
Anzahl der maximalen Datenpunkte:460 / 500`

**Comment by chefkoch009** [comment]
this info contains not the amount of GA's. This is a historical info for me, I'll change it in next release.

**Comment by chefkoch009** [comment]
is done. since version 2.0.5
