### ISSUE TITLE
GA-Tools Anzeige der GA-Zustand-Aktor Beziehung

### ISSUE THREAD

**Issue by uelpenich** [ioBroker/ioBroker.knx#217]
Danke für die neue 2er Version, endlich sind die Zustand - Aktor Beziehungen im Klartext lesbar dargestellt. 

Es gibt unteschiedliche Vorschläge, welche Bedeutung man den Haupt- und Mittelgruppen Gruppenadressen geben sollte. Ich habe die Möglichkeit gewählt, die Werte und Zustände unterschiedlichen Mittelgruppen zuzuordnen. Damit erfolgt der Projektimport fehlerfrei. 
**Beispiel**:
![grafik](https://user-images.githubusercontent.com/63613798/146675672-6037f17e-86f1-4ac8-9315-5b8a95c91373.png)
**Problem**: Da sich die Bezeichnungen der GA nicht mehr unterscheiden (müssen si ja nicht, da die Unterscheidung durch die Mittelgruppe gegeben ist), ist die GA-Zustand-Aktor Beziehung im GA-Tool nicht interpretierbar. 
![grafik](https://user-images.githubusercontent.com/63613798/146676058-c2d7c01b-7efb-4021-a71e-f76ca1b72a65.png)
Vorschlag / Bitte:
Ich bitte um die Erweiterung der Felder "Actor GA" und "State GA" in der "GA-Zustand - Aktuator-Beziehung" um die Bezeichnung der Haupt- und Mittelgruppe.

**Comment by chefkoch009** [comment]
Danke für den Tipp. Das ist eine gute Idee.

**Comment by chefkoch009** [comment]
ist im kommenden Release drin.

**Comment by chefkoch009** [comment]
Feature Request wurde in V2.0.9 umgesetzt.

**Comment by uelpenich** [comment]
Sieht gut aus. Danke.
![grafik](https://user-images.githubusercontent.com/63613798/150872346-aebafa7c-cf9b-43ff-92af-5d8def2b5461.png)
