### ISSUE TITLE
Mit Update auf 2.0.5 funktioniert der Adapter nicht mehr (davor 2.0.2)

### ISSUE THREAD

**Issue by ChrisDuck87** [ioBroker/ioBroker.knx#218]
![image](https://user-images.githubusercontent.com/88966869/146692549-f899bbd4-cbd4-45dc-9aaf-291411b63426.png)

![image](https://user-images.githubusercontent.com/88966869/146692597-94b2f1d4-c19d-4355-8ee4-87a2397b4b19.png)

Umstellen auf 2.x hatte bereits erfolgreich funktioniert. 
Mit Update auf 2.0.5 habe ich nun obengenanntes Problem.

- Reboot
- Deinstallation und Neuinstallation des Adapters/Instanz
- Ältere Version zurücksetzen brachte auch keine Besserung...

**Comment by chefkoch009** [comment]
Was sagt denn der log dazu? welche Version hat dein js-controller und der Admin?

**Comment by ChrisDuck87** [comment]
log zeigt keinen Fehler (du meinst denke ich mal die Installation)
Bei den Protokollen sehe ich keine Einträge
Admin ist v5.1.25
Node.js v14.18.2
NPM 6.14.15

![image](https://user-images.githubusercontent.com/88966869/146694501-e6ff938c-375a-45ca-9a01-291e3ee0d70b.png)

**Comment by ChrisDuck87** [comment]
aktuell zeigt er folgendes Bild: 
![image](https://user-images.githubusercontent.com/88966869/146694524-b5ea4ace-f40b-4d76-a714-41efd0733602.png)

**Comment by chefkoch009** [comment]
Aktualisiere mal bitte den admin auf mindestens 5.1.28. hab dazu auch schon im Forum geschrieben. siehe: https://forum.iobroker.net/topic/49696/test-adapter-knx-v2-x/5?_=1639408001368

**Comment by ChrisDuck87** [comment]
erstmal vielen lieben Dank für die superschnelle Hilfe:
falls du das meinst: 
![image](https://user-images.githubusercontent.com/88966869/146695022-f516a8a5-de37-469b-8fa3-04330413a99a.png)

habe ich durchgeführt, läuft 5 min...bleibt aber dann weiter bei version 5.1.25

**Comment by LuxBibi** [comment]
Hallo alle ... 
Habe auf meiner Synology gerade meinen Buanet/ioBroker Docker auf "latest.V6" geupdatet. KNX update war der Anlass, weswegen _ioBroker.admin_ und _ioBroker.KNX_ geupdatet wurden.

- ioBroker.admin von **v5.1.25** auf **5.1.28** hochgezogen
- ioBroker.KNX von v1.0.45 auf **2.0.5** hochgezogen

Nach dem Restore hatte ich +/- "gleiches Problem" wie @ChrisDuck87 .. :-( ...  ioBroker.KNX instanz "flappte" hin und her.

Hatte Anfangs nicht mitbekommen, dass jetzt unter KNX >2.0 die Lizenzthematik geändert wurde, und "alte" Lizenz von iobroker.net nicht mehr gültig ist?! So wie ich es gelesen habe, so scheint es mir, dass aktueller Adapter überhaupt keine Lizenz von iobroker.net mehr braucht, so wie weniger als 500 GA genutzt werden?

Weswegen ich kurzerhand, den ioBroker.KNX adapter über ioBroker admin (web) gelöscht, und neu instaliert habe (_Achtung: **ALLE** KNX.Objekte werden gelöscht_)

Nach neuinstalation einer KNX.0 (2.0.5) Instanz ist diese jetzt stabil. So weit so gut ... KNX instanz bleibt jetzt grün und aktiv und zeigt im log;

<html>
<body>


knx.0 | 2021-12-20 01:35:30.778 | info | Connected! :-)
-- | -- | -- | --
knx.0 | 2021-12-20 01:35:30.753 | info | Connected - local UDP Server listening on 192.168.178.200:60848
knx.0 | 2021-12-20 01:35:30.747 | info | Event : UDP - listening
knx.0 | 2021-12-20 01:35:30.743 | info | Debuglevel: 1 2
knx.0 | 2021-12-20 01:35:30.726 | info | Connecting to knx GW: 192.168.178.2:3671 with phy. Adr: 1.0.2
knx.0 | 2021-12-20 01:35:30.723 | warn | No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
knx.0 | 2021-12-20 01:35:30.571 | info | starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.knx, node: v14.18.2, js-controller: 3.3.21


</body>
</html>

**JEDOCH !! :-(**

Ich habe keine Kommunikation (In und Out) vom ioBroker.KNX(v2.0.5) <-> Weinzierl IP 730/Gateway(192.168.178.2 - GA:1.0.2), was mit vorriger ioBroker.KNX(v1.0.45) Instanz mit gleichem IP/Gateway Set-Up (192.168.178.2 - GA:1.0.2) funktionierte.

Beim hochfahren des "alten" docker.container mit der Instanz iobroker.KNX(v1.0.45) sah ich gleich in der "experten view" beim aufgeklappten iobroker.KNX(v1.0.45), dass Events rein und raus gehen, und die Objekte werden geupdatet (Meteo Station und temperatur bei Schaltern). Ich kann Lichter an- und aus-schalten, und meine Automatisationen laufen alle.

Jedoch mit iobroker.KNX(v2.0.5) kommen keine Events an, und keine Steuerung auf dem KNX.BUS übers Weinzierl Gateway ist möglich. Zu sehen, dass keine einziges Objekt geupdatet wird, und ich kann nichts im KNX schalten. ioBroker.KNX(v1.0.45) Instanz lief über ein Jahr (falls nicht länger ;-) ) perfekt. Zu sehen an den täglichen Automatisationen.

Zu Bemerken, dass jeweils nur ein docker.Container aktiv ist!


**Vorriger Docker/Container: iobV4PROD** (Mit KNX v1.0.45)
Platformoperating system:linux
Architecture:x64
CPUs:4
Speed:2400 MHz
Model:Intel(R) Atom(TM) CPU  C2538  @ 2.40GHz
RAM:15.6 GB
System uptime:32 d. 09:01:33
Node.js:v12.22.8
NPM:6.14.15
Disk size:3572.5 GB
Disk free:1096.9 GB
adapters count:364
Uptime:00:00:29
Active instances:6
Path:/opt/iobroker/ -> SYNOLOGY:/docker/ioBroker/**data_BefUpdate**


**Neuer Docker/Container: iobV6PROD** (Mit KNX v2.0.5)
Platformoperating system:linux
Architecture:x64
CPUs:4
Speed:2400 MHz
Model:Intel(R) Atom(TM) CPU  C2538  @ 2.40GHz
RAM:15.6 GB
System uptime:32 d. 08:45:17
Node.js:v14.18.2
NPM:6.14.15
Disk size:3572.5 GB
Disk free:1096.9 GB
adapters count:364
Uptime:00:21:44
Active instances:37
Path:/opt/iobroker/ -> SYNOLOGY:/docker/ioBroker/**data**


Was könnte ich als nächsten Schritt starten, um zu sehen, woran es hängt, dass der neue iobroker.KNX Adapter nicht mehr mit dem IP/Gateway kommuniziert?

Danke im Voraus,
Luc/Luxembourg

**Comment by chefkoch009** [comment]
Was docker angeht kann ich leider überhaupt nicht helfen, aber ich meine das es da Probleme mit dem Netzwerk gab. Prüfe bitte ob das routing richtig funktioniert, also 3671 udp out scheint zu funktionieren, jedoch udp * in anscheinend nicht.

**Comment by ChrisDuck87** [comment]
@chefkoch009: habe mit "iobroker upgrade admin@5.1.28 -y" das Upgrade jetzt nochmal durchgeführt. 5.1.28 ist installiert und klappt. (warum geht ihr hier nicht auf die last stable 5.1.25? Denke das der Fehler somit noch bei vielen vorkommen wird)

Danach funktioniert der Adapter wieder (habe diesen nochmals neuinstalliert).
Danke euch für die Hinweise :)

Nach mir kann man das Issue schließen. @LuxBibi: Da ich nicht weiß ob dein Problem noch besteht lass ich ihn offen.

**Comment by chefkoch009** [comment]
> warum geht ihr hier nicht auf die last stable 5.1.25
hab ich schon im Forum geschrieben. Da war ich etwas vorschnell. Dieses Abhängigkeitsproblem sollte aber spätestens am 21.12.2021 behoben sein.

**Comment by LuxBibi** [comment]
@chefkoch009 : Danke für die Rückmeldung ... 
Eine letzte Frage ehe ich mit dem Debuggen los leg .. 
Wieso soll ich dies mit 3671 udp mir näher anschauen? .. Beide Docker laufen auf der gleichen Synology und mit der gleichen Buanet docker image (latest.v6)
Hat sich zum KNX(v1.0.45) und dem neuen KNX(v2.0.5) etwas geändert hinsichtlich Netzwerk, da in meinen Augen "der einzige Unterschied" die ioBroker.KNX ist .. Oder?

@ChrisDuck87 : Danke für die Rückmeldung. Nehme an, dass du dein ioBroker auf was anderes laufen hast. Raspberry pi? 

Danke im Voraus,
Luc/Luxembourg

**Comment by LuxBibi** [comment]
Hallo @chefkoch009 
Hier mein Feedback. Geht ja super schnell mittels Docker, um verschiedene Konfigs zu testen ..Nimmt mehr Zeit ein dies zu dokumentieren .. ;-) .. zumal in einer Fremdsprache (Sorry für möglich Rechtschreibfehler)

1. Habe ein neues Docker Container (iobB1045) erstellt mit
   - Buanet.ioBroker(latest.v6)
   - Altes "Synology Daten Verzeichnis(iobV4PROD)" der perfekt mit der Buanet.ioBroker(latest.v4), also iobroker.**KNX(v1.0.45)** all die Monate perfekt lief
   - **KNX in diesem Set-Up funktioniert !!** Daten kommen in die Objekte rein, und KNX GA können geschaltet werden.

2. Docker Container (iobV6PROD) mit
   - Buanet.ioBroker(latest.v6)
   - Neues "Synology Daten Verzeichnis(iobV6PROD)", also iobroker.**KNX(v2.0.5)** mit neuem KNX import
      - Zu Bemerken, dass dieses Daten Verzeichnis, wie von André empfohln, mittels "_iobroker restore_" von der "alten" iobV4PROD zurückgespielt wurde.
   - **KNX funktioniert in diesem Set-Up NICHT**

Jetz war für mich noch ein letzter Test wichtig. Wie unter "2. iobV6PROD" jedoch mit downgrade des iobroker.KNX adapter von v2.0.5 auf v1.0.45. (Neuer docker Container iobV6TEST) .. da fiel mir auf, dass im LOG der iobV6PROD extrem viele KNX Datenpunkte unbekannt waren! Beim genauerem hinschauen, so habe ich gesehen, dass all die überprüften DPT in der iobV4PROD gesetzt waren, wobei in der iobV6PROD verschiedene Felder "leer" waren :-(

**iobV6PROD**
_DPT.js: unknown datapoint type :                                                                           
                                                                                                           
DPT.js: unknown datapoint type :_                                                                           
                                                                                                           
                                                                    
Hier eine GA meiner Lampe im Büro.
**KNX.v1.0.45)**                                                                                                           
{
  "_id": "knx.0.1ER_LAMPES.ON-OFF.L-BUR-Plafond",
  "type": "state",
  "common": {
    "name": "L-BUR-Plafond",
    "type": "boolean",
    "read": false,
    "write": true,
    "role": "switch",
    "min": false,
    "max": true
  },
  "native": {
    "dpt": "**DPT1.001**",
    "address": "10/0/15",
    "addressRefId": "P-0209-0_GA-13",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "from": "**system.adapter.knx.0**",
  "user": "system.user.admin",
  "ts": 1597147689259,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**KNX.V2.'0.5**
{
  "_id": "knx.0.1ER_LAMPES.ON-OFF.L-BUR-Plafond",
  "type": "state",
  "common": {
    "name": "L-BUR-Plafond",
    "type": "boolean",
    "role": "switch"
  },
  "native": {
    "dpt": "",
    "address": "10/0/15",
    "addressRefId": "P-0209-0_GA-13",
    "statusGARefId": "",
    "actGARefId": "",
    "update": "",
    "objRef": "",
    "devName": "",
    "devInst": "",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1639959979997
}

Habe beide BOLD markierte Einträge in der iobV6PROD + KNX instanz restart ... und siehe da .... Funktioniert .. ;-) !

Next:
- KNX instanz auf der iobV6PROD gestoppt
- Alle KNX Objekte gelöscht
- KNX Instanz gestartet
- Neues export aus ETS V6
- Neues import dieser Datei in iobroker.KNX(v2.0.5)
   - Resultat ist "falsches Import!"
   - {
  "_id": "knx.0.1ER_LAMPES.ON-OFF.L-BUR-Plafond",
  "type": "state",
  "common": {
    "name": "L-BUR-Plafond",
    "type": "mixed",
    "role": ""
  },
  "native": {
    "dpt": "",
    "address": "10/0/15",
    "addressRefId": "P-0209-0_GA-13",
    "statusGARefId": "",
    "actGARefId": "",
    "update": "",
    "objRef": "",
    "devName": "",
    "devInst": "",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1639998183864,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Somit ..

What next ... ?

Danke für die Hilfe ..
Luc

**Comment by chefkoch009** [comment]
Ich kann es nicht nachvollziehen, schreib mir bitte ein PN im iobroker forum.

**Comment by ChrisDuck87** [comment]
@LuxBibi: Jep, habe einen Raspberry 4

**Comment by LuxBibi** [comment]
Hallo @Chefkoch,
Bin nicht so oft unterwegs im iobroker forum. ioBroker läuft einfach gut seit langem ;-)

Da ich nicht gefunden hab, wie im ioBroker Forum Dir eine PN schicken zu können (Google hat auch nicht richtig geholfen :-( ) so hab ich einen Chat im Forum heute Nachmittag geschickt, zwecks Kontaktaufnahme. Ist ggfls. nicht angekommen. Scheint jedoch persistent zu sein. (War dies ggfls. die Kontaktaufnahme die du angefragt hast ? ;-) )

Lass es mich sonst wissen. Möchte gerne helfen, sollte noch ein Sandkern im Adapter sein .. 

Danke so weit für die Unterstützung und Hilfe,
Luc

**Comment by LuxBibi** [comment]
Hallo @chefkoch009 ,
Kurzes Update .. Habe letzte Nacht auf iobroker Forum eine PN meiner "Findings" gemacht.

iobroker.KNX(v2.0.5) läuft seit letze Nacht ... !!!
Lag am ETS6.0.0 PRO export -> Die *.knxproj Datei ist aktuell nicht in der Instanz einzulesen! Führt zu den genannten Problemen, das keine **DPT's** und "from": **"system.adapter.knx.0" nicht** richtig gesetzt werden.

Meine vorrige ETS4 version exportiert das Format was nach wie vor funktioniert! Import zur aktuellen iobroker.KNX(v2.0.5) version ist OK!

Habe noch alle Container, wo ich alles nachspielen kann. Up2You, solltest du gemeinsam Dir was anschauen ... Helfe gerne Deinen adapter an ET6 anzupassen .. 
Luc

**Comment by LuxBibi** [comment]
Hi @chefkoch009 .
Wetransfert link der ETS4 & ETS5 Dateien hab ich Dir per chat geschickt.
Lass es mich wissen, solltest du weitere Info benötigen. Stehe gerne zur Verfügung, um ggfls Tests für dich durchzuführen.

**Comment by chefkoch009** [comment]
Vielen Dank für die Hilfe. Mit 2.0.7 sollte der Import funktionieren.

**Comment by LuxBibi** [comment]
@chefkoch009 : So wie ich getestet hab, so melde ich mich zurück ....  Siehe, dass gerade die 2.0.8 bereits "verfügbar" ist .... Schau mir dies morgen genauer an ....  Danke so weit ...

**Comment by chefkoch009** [comment]
Vielen Dank, ich freue mich auf die Rückmeldung.

**Comment by LuxBibi** [comment]
Hi @chefkoch009: Bereits vorne weg eine kurzes Feedback ....  Habe mit der 2.0.7, **ohne neues Import**, mehrere Einträge pro Sekunde in der Log die wie folgende ein Warnings zeigen ...

![image](https://user-images.githubusercontent.com/45201013/147992591-8431b195-d6b0-477a-9f45-0ed179cd1b1c.png)

Bin für die Nacht wieder auf 2.0.5 sonst. 

Meld mich morgen nach neuem Import ... um zu sehen, ob dies ggfls einen Impakt hat ... 

See you,
Luc

**Comment by LuxBibi** [comment]
Hallo @chefkoch009 ,

Sorry .. Hat ein bisschen gedauert .. COVID hat sich schlussendlich doch noch bei uns eingeladen. Wir sind alle 3 hier zu Hause "gesund" .. Nur ein "3 tägiger kleiner Schnupfen"! Zum Glück bin ich als Booster geimpft ;-) ...  Bekannte im Dorf haben einen Todesfall :-( .. jedoch ohne Impfung gewesen .. 

Somit hat sich mein Testen etwas verzögert ... Wir mussten und ein bisschen um-organisieren .. 

Hier jedoch die Resultate so weit ... 
Raspberry war mein TEST System 

Bin auf node.js version v14.18.2 "hochgezogen", da Deine Version knx@2.0.8 dies als Voraussetzung hatte.

$ iobroker info
Platform       : linux
os             : linux
Architecture   : arm
CPUs           : 4
Speed          : 1000 MHz
Model          : ARMv7 Processor rev 3 (v7l)
RAM            : 7.7 GB 
System uptime  : 00:24:52
Node.js        : v14.18.2
Disk size      : 116.6 GiB
Disk free      : 99.8 GiB
adapters count : 362
NPM            : v6.14.15

$ iobroker version knx
2.0.8

Neue Projektdatei aus der ETS 6 exportiert .. und im KNX@2.0.8 importiert
KNX instanz wurde, so nehme ich an in Deinem import Prozess integriert, neu gestartet?
Auf jeden Fall, im Log sieht es nun weitaus "ruhiger" aus ;-) ..  (Keine "Read-Only State Einträge mehr) !

Zu den initialen Probleme: 
-> from is tjetzt richtig gesetzt auf "_system.adapter.knx.0_"
-> 

Einige DPT's sind noch immer auf "", was diesmal jedoch normal ist, da beim Überprüfen in meiner ETS, jedes der leeredn DPT's im ioBroker ebenfalls leer in der ETS sind ... Sieht also sehr gut aus! Ich bin dabei in meiner ETS6 alle DPT zu setzen ...da ich gesehn hab, dass viele nicht im ETS automatisch gesetzt wurden ... 

Danke Dir so weit ...  Bin wie in Deiner Doku beschrieben ETS am überprüfen .. Danach werde ich dann ETS überprüfen ... ;-) .. 

Solltest Du noch weitere Info benötigen, die ich hier nicht eingefügt habe, so einfach melden .. 

Luc

P.S.:  Ich hab ja auf meiner "Produktion" ioBroker mittels BUANET/Docker am laufen ... Weiss, dass dies nicht Deine Welt ist. Nicht schlimm, da die Frage die ich habe, so glaub ich, generel von Interesse ist. Ich sehe auf der Docker/Terminal Konsole viele **"DPT.js: unknown datapoint type :"** die ja auf meine leeren DPT referenzieren .. Mich würde natürlich interessieren, die jeweiligen GA's dazu zu wissen .. Kommt dieser Log-Text von dir? Und falls ja, wo kann man anfragen, dass hier jeweils die GA mit angezeigt wird? Eine Alternative hierzu wäre, in Deinem Adapter alls GA's in einer Liste anzuzeigen die ein leeres DPT haben. Diese werden nämlich zu fast 100% Sicherheit, nicht steuerbar aus ioBroker sein ...

**Comment by chefkoch009** [comment]
Unbekannte GAs werden ab Version 2.0.9 mit der Gruppenadresse angezeigt. GA's ohne DPT kommen in der nächsten Version.

**Comment by LuxBibi** [comment]
For my part all is clear! Thanks a lot to Chefkoch for your very suportive help, to have thi solved, and even enhanced in functionalities in the future! IThis closes: #218
