### ISSUE TITLE
Lizenz wird nicht erkannt

### ISSUE THREAD

**Issue by Smassard82** [ioBroker/ioBroker.knx#219]
Hallo,

Nachdem ich eine Lizenz für den neuen Adapter gekauft habe wird diese nicht erkannt. Weder NET Sync. klappt noch das manuelle kopieren des Lizenzschlüssels!

![image](https://user-images.githubusercontent.com/76007920/147419349-78bf7561-dce5-4e7c-957c-12332095a4da.png)

![image](https://user-images.githubusercontent.com/76007920/147419359-c698dc35-7357-4c59-b439-e73dffae7f31.png)

**Comment by chefkoch009** [comment]
Welche Version vom admin-adapter, js-controller und knx-adapter sind installiert?

**Comment by Smassard82** [comment]
Jeweils die neusten: KNX 2.0.5, Admin 5.2.2, js 5.2.13

**Comment by Smassard82** [comment]
Wo könnte das Problem liegen?
Welche Infos werden noch benötigt?

**Comment by chefkoch009** [comment]
Welche node Version hast du? Hast du Host also js-Controller aktualisiert? Admin Adapter muss mindestens 5.1.28 haben. Hast du versucht über die console :

iobroker u admin
iobroker u knx

**Comment by Smassard82** [comment]
Admin ist mittlerweile  5.2.3 > 5.1.28 
Node ist 14.18.2
JS Controller würde wie gesagt auf  5.2.3 aktualisiert

**Comment by chefkoch009** [comment]
schreib mir mal bitte eine PN im iobroker Forum, oder nimm mal bitte per Mail Kontakt mit mir auf.

**Comment by chefkoch009** [comment]
Besteht das Problem noch, weil ich bis jetzt kein Feedback erhalten habe?

**Comment by chefkoch009** [comment]
scheint sich gelöst zu haben.

**Comment by Smassard82** [comment]
Hab nun eine Update auf 2.0.8 gemacht. Jetzt scheint es zu gehen.

**Comment by Smassard82** [comment]
Hallo nochmal,

Leider zu früh gefreut.
Beim Update auf 2.0.8 startet der KNX adapter nicht mehr.
Bei Version 2.0.5 läuft er jetzt scheinbar, aber die Lizenz scheint nicht
korrekt: es werden nur 500 Datenpunkte erlaubt, obwohl 2000 da sein müssten:
[image: image.png]
[image: image.png]

Vielen Dank im Voraus für die Rückmeldung.

MfG


Am Mi., 5. Jan. 2022 um 13:11 Uhr schrieb Steve MASSARD <
***@***.***>:
