### ISSUE TITLE
Uncaught, unspecified "error" event. (no connection to KNX Bus)

### ISSUE THREAD

**Issue by danielrie** [ioBroker/ioBroker.knx#22]
Error: Uncaught, unspecified "error" event. (no connection to KNX Bus) at _0x23f245.emit (events.js:163:17) at _0x23f245.groupValueWrite (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:3734

pmessage io.knx.0.Beleuchtung.OG.Licht_Decke_Schalten {"val":true,"ack":false,"ts":1523221207226,"q":0,"from":"system.adapter.yahka.0","lc":1523221207226} Uncaught, unspecified "error" event.

Sometimes, I can't switch the lights - and sometimes, everything works like a charm. Why does it only work sometimes? (Connected to a Siemens KNX IP Controller N305E)

**Comment by chefkoch009** [comment]
Problem im Sequenzcounter behoben in V1.0.9.
