### ISSUE TITLE
Kein Steuerung mehr möglich nach Update auf 2.0.6 von 2.0.5

### ISSUE THREAD

**Issue by barni** [ioBroker/ioBroker.knx#220]
Hallo zusammen,

nach dem Update auf 2.0.6 von 2.0.5 funktioniert die Steuerung über die Visu reproduzierbar nicht mehr. Habe 2 mal wieder die 2.0.5 über einen SNAPSHOT der VM aufgespielt, damit geht alles wieder. Sobald ich auf die 2.0.6 update geht die Steuerung über die Visu nicht mehr.

Logfile sagt nicht viel ausser diverse Meldungen dieser Art, welche nur mit der Version 2.0.6 auftauchen:

Object knx.0.Beleuchtung.Erdgeschoss.Li_Decke_Büro_RM_Wert is invalid: obj.common.write has an invalid type! Expected "boolean", received "string"

Irgendwelche Idee ?

Node.js v14.18.2
NPM 6.14.15

**Comment by chefkoch009** [comment]
Fehler ist bestätigt. Update 2.0.7 ist online

**Comment by barni** [comment]
Geht wieder stimmt wobei trotzdem viele Warnings der Art:
Read-only state "knx.0.Steckdosen.Untergeschoss.Steckd__Trockner_RM_Stromwert" has been written without ack-flag with value "0"
Ich vermute da die Geräte zyklisch updates senden

**Comment by chefkoch009** [comment]
Schau ich mir gleich an.

**Comment by chefkoch009** [comment]
Fehler ist bestätigt und in V2.0.7 behoben. Das warning "has been written without ack-flag with value "0"" ist in der kommenden Version behoben.

**Comment by barni** [comment]
Perfekt mit 2.0.7 geht die Steuerung wieder mit 2.0.8 sind die Warnings weg.

Merci
