### ISSUE TITLE
Adapter 2.05 keine Verbindung mit Geräte oder Dienst 

### ISSUE THREAD

**Issue by e-pasch** [ioBroker/ioBroker.knx#222]
Hi,

ich bekomme keine Verbindung mit 
![image](https://user-images.githubusercontent.com/97129349/148123219-fbcfa137-1abc-4293-876c-20b6fdf4011d.png)

Protokoll
![image](https://user-images.githubusercontent.com/97129349/148123503-cafa3503-22a0-4950-b662-4286ce5ef19d.png)

KNX Gateway ist eine Hager Domovea.

Versionen (installiert)
- ioBroker v5.2.3
- Admin 5.2.3
- js-controller 3.3.22
- node 14.18.2
- Adapter 2.0.5

Lizenz
- bei iobroker.net erworben und synchronisiert

Firewall auf dem Host ist aus.

Irgendein Tipp für mich?

Danke.

**Comment by e-pasch** [comment]
Nachdem ich nun hunderte Hager Dokumente durchgeschaute habe, habe ich einmal die KNX Adresse aus einem Handbuch ausprobiert.
Es ist also nicht die KNX Adresse wie sie im Hager Pilot ist sondern war bei mir 1.1.210

Ich schließe die Anfrage wieder

**Comment by chefkoch009** [comment]
Da muss man erst mal drauf kommen. Vielen Dank für die Erklärung und die Lösung.

**Comment by e-pasch** [comment]
Um mein Wissen an den Entwickler weiterzugeben, dieser Post:

Nachdem ich endlich, das Ding zu laufen bekommen habe, sollte der Projectfileimport vollzogen werden.
Logfile meldet fleißig: _Value received on unknown GA : 0/7/26_
GA-Tool ist und bleibt leer
Upload oder Verarbeitung der Datei scheint nicht zu funktionieren.

Dann habe ich mit den Versionen rumgespielt und siehe da
Die Version 2.0.2 kann sich dann auch auf der eigentlichen physikalische KNX-Adresse, wie sie auch im Hager-Pilot konfiguriert ist verbinden. Instanz ist somit vollständig grün.
Könnte also ein Problem mit der Version 2.0.5 sein?!

Aber leider:
Projektimport geht weiterhin bei mir nicht. Ich suche weiter.

Auf jeden Fall, danke dir für die obige Reaktion
