### ISSUE TITLE
3000 DP reichen nicht

### ISSUE THREAD

**Issue by githubtzzz** [ioBroker/ioBroker.knx#223]
Hallo,

ich habe mir gerade eine 2000er 1 Jahres Lizenz gekauft. Jetzt habe ich gesehen, dass mein EFH mehr als 3000 DPs nutzt. Gibt es eine Möglichkeit auf mehr als 3000 DPs zu gehen? Eventuell 4000 oder unlimited?

**Comment by chefkoch009** [comment]
Die wird es demnächst geben. Das ist in Arbeit.

**Comment by githubtzzz** [comment]
Perfect. Kann ich meine bestehende 2000er Lizenz dann erweitern oder muss ich komplett neu kaufen?

**Comment by Stefan592** [comment]
Wie kommt man bitte bei einem Einfamilienhaus auf >1000 GA?

Ich selber bin Softwareentwickler, Automatisierter in der Industrie und projektiere KNX Einfamilienhäuser für den Ortsansässigen Elektrikerbetrieb.

Selbst bei großen Projekten (EFH komplett automatisiert, >100 KNX Geräte) komme ich nicht über 1000 Gruppenadressen. 
 Könnte ich mir so ein großes Projekt einmal ansehen?

**Comment by TA2k** [comment]
Es gibt auch ioBroker Adapter die nicht auf 3000 DP begrenzt sind

**Comment by chefkoch009** [comment]
Hör bitte auf damit!

**Comment by trollvottel** [comment]
> Es gibt auch ioBroker Adapter die nicht auf 3000 DP begrenzt sind
Interessant! Leider würde das alle existierenden Scripte brechen, weil der andere Adapter einen anderen Objektbaum generiert.

Mein EFH Projekt hat übrigens rund 1600 GA. Mit gescheiten KNX-Geräten, die eine mächtige Applikation mitbringen, erreicht man das problemlos. Ich persönlich fände ein Licensing, was sich z.B. auf zu beschreibende GAs reduziert fairer (von ioBroker heraus), aber so ist es nun. Der kleine Bauherr ist es ja inzwischen gewohnt, für jeden Kleinscheiß eine Subscription zu kaufen: Amazon, Spotify, Netflix, Office365 usw. und nun halt noch dafür, dass er sein neues Häuschen abends softwaremässig auch tatsächlich ansteuern kann.

**Comment by chefkoch009** [comment]
Lizenz steht zur Verfügung.
