### ISSUE TITLE
2.0.8 - GA Tools - Properties werden nicht gespeichert?

### ISSUE THREAD

**Issue by iobroker99** [ioBroker/ioBroker.knx#224]
eben update auf 2.0.8. gemacht. Wenn ich in den GA Tools eine GA von lesen/aktualisiern auf schreiben ändere wird es nicht gespeichert. DPT Änderung hingegen schon.

**Comment by uelpenich** [comment]
Das Update von 2.05 auf 2.08 ist fehlgeschlagen. Die Instanz kann mit der Fehlermeldung **"startinstance knx.0: cannot find start file"** nicht gestartet werden. Raspberry pi 4 reboot hilft nicht. 
![grafik](https://user-images.githubusercontent.com/63613798/148380950-890f83a5-b346-4fb5-a2a0-04192c77830c.png)

Adapter löschen und neu installieren hilft nicht. Der neu installierte Adapter findet / erstellt keine Instanz. 
Manuelles Erstellen einer neuen Instanz führt zu **"File index_m.html not found"**
![grafik](https://user-images.githubusercontent.com/63613798/148381208-5a0f44c3-b656-4c82-8023-83aa3c2e0822.png)
Ich bin zurück auf 2.0.5. Gut wenn man eine Datensicherung hat.

**Comment by chefkoch009** [comment]
zum issue-header: das ist seit 2.0.9 behoben. 
Die andere Fehlermeldung kommt, wenn irgendetwas beim update nicht geklappt hat (anbei: der Adapter lässt sich NICHT über github installieren!!!). In solch einem Fehlermeldungsfall sollte ein "iobroker u knx" helfen.

**Comment by uelpenich** [comment]
Das Update auf 2.0.9 funktioniert. Danke.
>>  (anbei: der Adapter lässt sich NICHT über github installieren!!!)
genau das war mein Problem, icht hatte die Version 2.0.8 direkt über Github installiert. Vielleicht nehmen Sie die Warnung noch in das Read.me auf.

**Comment by chefkoch009** [comment]
Danke für die Info....wird im nächsten Update korrigiert sein.
