### ISSUE TITLE
"admin" has wrong version

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.knx#226]
I am getting this error message:
`startInstance system.adapter.knx.2: required adapter "admin" has wrong version. Installed "5.1.25", required ">=5.1.28"!`
But I have 5.2.3 admin installed, which is clearly more than 5.1.25. Why does the adapter think that 5.1.25 is installed? And how to let him know that a later version is installed?
Maybe it's because I restored the backup to a different machine and then updated all the adapters and the controller?

**Comment by chefkoch009** [comment]
Please verify, that at least the required versions of js-controller and admin are installed (admin seams to be right as you described). Then do a "iobroker u knx". This will upload the installed adapter versions to iobroker config.

**Comment by Apollon77** [comment]
Please execute "iob upload admin" ... fixed then?

**Comment by Anzic23** [comment]
iobroker u knx and iob upload admin fix the problem
