### ISSUE TITLE
KNX adapter STATE_NOT_CONNECTED : Try to connect / reconnect 

### ISSUE THREAD

**Issue by Mekki1402** [ioBroker/ioBroker.knx#227]
Hallo Zusammen,
ich habe iobroker mit dem knx adapter auf einem raspberry pi3+ im Einsatz, um per blockly script meinen WLED Controller für die Garagen-LED-Beleuchtung zu steuern.
Folgende Konfiguration und Versionen sind im Einsatz:
![image](https://user-images.githubusercontent.com/97730476/149558486-8492cb4a-df69-4b54-81b9-0b2189de87a8.png)
![image](https://user-images.githubusercontent.com/97730476/149558664-0d01e515-d54d-4812-ac5e-d135febf6fae.png)
![image](https://user-images.githubusercontent.com/97730476/149558611-1fd464f8-a724-4a49-a74a-5cdf6f818ccb.png)
hatte zuvor auch schon v.2.0.3 im Einsatz

im Einsatz: KNX IP-Interface von MDT, Typ: SCN-IP000.03 IP, 4 Tunnelverbindungen möglich
IP-Adresse vom KNX-Gateway: 192.168.178.100
IP-Adresse vom raspberry: 192.168.178.56

Folgendes Problem:
In unregelmäßigen Abständen bricht die Tunnelverbindung zum KNX-Interface ab und es werden keine Gruppenadressen mehr aktualisiert. Ein Neustart des KNX Adapter's behebt den Fehler. Nachfolgend habe ich einen Auszug aus meinem Log-File angefügt:
Der Fehler tritt um 02:48:12 ein, danach werden keine GA empfangen und Tunnel bricht ab.
Ein manueller Neustart habe ich dann um 06:24:07 durchgeführt, danach konnten wieder GA's empfangen werden,

![2022](https://user-images.githubusercontent.com/97730476/149559857-b492a8fb-c05c-46ae-a502-e36c5f5a6e1f.jpg)

Auszug vom Web-KNX-Interface bei bestehender Tunnelverbindung:
![image](https://user-images.githubusercontent.com/97730476/149574256-30cf7db0-e951-4f44-b1c0-3ee5f7f3fa80.png)
IP-Adresse vom raspberry: 192.168.178.56
IP-Adresse vom Tablet mit KNX-Visu: 192.168.178.33

Hat jemand ein Tipp, woran es liegen könnte?

Danke vorab und Gruß
Mekki

**Comment by chefkoch009** [comment]
Ist das eine WLAN Verbindung?

**Comment by Mekki1402** [comment]
Nein, der RaspberryPi, als auch das KNX Interface sind direkt per LAN an die Fritzbox angeschlossen.

**Comment by chefkoch009** [comment]
Ist auf dem Raspi irgendeine Energiesparoption aktiv, welche unter Umständen die Netzwerkschnittstellen deaktiviert?

**Comment by Mekki1402** [comment]
Nein, es sind keine Energiesparoptionen aktiviert.

**Comment by trollvottel** [comment]
Ich kenne das Problem, wenn man mehrere Netzwerkadapter / IPs hat. Ist das bei Dir der Fall? Da half bei mir immer temporär in der Adapterkonfiguration auf das andere Device umzuschalten.

**Comment by chefkoch009** [comment]
Danke für den Tipp @trollvottel. 
War dieser Tipp für Dich zutreffend/hilfreich? @Mekki1402

**Comment by Mekki1402** [comment]
@chefkoch009 Leider traf das bei mir nicht zu, da ich nicht mehrere Netzwerkadapter/IP's hatte. Ich nutze den KNXadapter nicht mehr, da ich das Problem nicht beheben konnte

**Comment by chefkoch009** [comment]
@Mekki1402 Das ist schade....wir hätten da gemeinsam den Fehler suchen und finden können. so kann ich leider den Fehler nicht beheben, sollte es am Adapter liegen.

Trotzdem vielen Dank für Dein reporting und die Rückmeldung. 

Ich schließe diesen Issue. Ob es am Adapter oder an Deinem Netzwerk lag ist nicht nachstellbar.
