### ISSUE TITLE
Mit 2.0.9 werden scheinbar nach kurzer Zeit keine Werte mehr empfangen

### ISSUE THREAD

**Issue by barni** [ioBroker/ioBroker.knx#229]
Hallo zusammen,

nach dem Update von 2.0.8 auf 2.0.9 scheint es wieder vorzukommen das nach gewisser Zeit keine Werte mehr vom Bus verarbeitet werden.
Leider ist Log nichts auffälliges und auch ansonsten scheint der Adapter eigentlich noch zu laufen, d.h. Steuerung geht noch aber Empfang von msg welche ich nicht angefordert habe sondern zyklisch gesendet werden scheint nicht mehr zu gehen. 

Mit 2.0.8 hatte ich das Problem (glaube ich :-)) nicht.

Grüße,
Stephan

**Comment by chefkoch009** [comment]
Tritt es auf wenn du die gleichen oder geänderte Werte sendest?

**Comment by barni** [comment]
> Tritt es auf wenn du die gleichen oder geänderte Werte sendest?

Auch geänderte leider

**Comment by barni** [comment]
Ok ich bin verwirrt. Ich werde glaube ich nochmal auf 2.0.9 update und versuchen es zu reproduzieren.
1) Sicher ist die GUI als auch die Scripte haben keinen aktuellen Status mehr bekommen.
2) Ich dachte in der Admin Console um ca 15 Uhr gesehen zu haben das der letzte Wert der Wetterstation um 12 Uhr empfangen wurde.
3) Was aber komisch ist, ich schreibe über ioBroker über den Adapter die Werte in eine influxDB, hier scheinen aber durchgängig Werte empfangen worden zu sein. Das verstehe ich nicht.

Ich versuche es nochmal zu reproduzieren, dabei dachte ich das nach dem Update nach ca. 2h immer wieder zu sehen. mit 2.0.8 aber nicht

**Comment by barni** [comment]
Vielleicht hilft das bekomme folgende Warnings:

knx.0 | 2022-01-30 21:26:08.511 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
knx.0 | 2022-01-30 21:26:08.511 | warn | Object knx.0.Zentral.Sonneschutz.Roll__Sonnenschutz_Wert_Höhe is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
knx.0 | 2022-01-30 21:26:08.510 | warn | This object will not be created in future versions. Please report this to the developer.
knx.0 | 2022-01-30 21:26:08.510 | warn | Object knx.0.Zentral.Sonneschutz.Roll__Sonnenschutz_Wert_Lamelle is invalid: obj.common.read has an invalid type! Expected "boolean", received "string"
knx.0 | 2022-01-30 21:26:08.510 | warn | This object will not be created in future versions. Please report this to the developer.

**Comment by chefkoch009** [comment]
Doch glaube ich schon, denn in deiner raw object steht hinter read das Wort "True" bzw "false" mit "Gänsefüßchen" es muss aber ohne dastehen. 
Falsch:
read: "true"

Richtig:
read: true

**Comment by barni** [comment]
Ok ignoriere das. Tatsächlich sind das alles GAs die ich nicht selber erstellt habe sonder uralte vom Elektriker. Ich werde die entfernen, die ergeben sowieso keinen Sinn.

Habe seid gestern wieder die 2.0.9 drauf und bisher keine Probleme. Schließe das Ticket ich mach ein neues wenns wieder auftritt. Und ich hoffe das ich dann mehr Infos habe.
