### ISSUE TITLE
Import teilweise oder vollständig mit Fehler fehlgeschlagen:Falsches Passwort

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/ioBroker.knx#233]
Is the password import already supported or may their occur problems with special chars? ;-)

**Comment by foxriver76** [comment]
Without special chars it is also failing

**Comment by chefkoch009** [comment]
Ab ETS6.x wurde das Verfahren für die Verschlüsselung geändert. Ich arbeite gerade an dem Update dazu.

**Comment by chefkoch009** [comment]
Ist in Adapter Version 2.0.10 behoben.

**Comment by foxriver76** [comment]
Bekomme leider noch den selben Fehler 2.0.10 ETS Projekt frisch exportiert mit 6.0.2

**Comment by chefkoch009** [comment]
Kann ich deine Projektdatei bitte haben?

**Comment by foxriver76** [comment]
Klar, soll ich dir ein Standard-PW drauf setzen oder bringt es dir schon was wenn du das PW nicht weißt?

**Comment by foxriver76** [comment]
PW: Testing

**Comment by chefkoch009** [comment]
Super, vielen Dank. Schau ich mir an.

**Comment by foxriver76** [comment]
Super, läuft nun.

**Comment by Filou2000** [comment]
Hallo, ich hab die Version 2.0.11 installiert und wollte mein Projekt aus der ETS 6.0.2 importieren.
Leider bekomme ich folgende Fehlermeldung: "Import teilweise oder vollständig mit Fehler fehlgeschlagen:Falsches Passwort"
Ich habe das Passwort schon geändert, so dass keine Sonderzeichen oder Zahlen vorhanden sind.

**Comment by Nusseis635** [comment]
Hallo, ich habe die Version 2.0.15 installiert und habe auch die Meldung "Falsches Passwort" beim importieren der Projektdatei. Habe das Passwort auch schon einmal geändert, das Problem besteht weiterhin...

**Comment by chefkoch009** [comment]
Bitte einmal die ETS aktualisieren. Es gab da Unterschiede beim Export bezüglich der Behandlung des Passwortes.

**Comment by Filou2000** [comment]
Ich hab es gerade mit einem neuem Projekt ausprobiert. ETS 6.0.4, Build 4543 und der Adapter hat die Version 2.0.15. Ich bekomme weiterhin den Fehler "Falsches Passwort". Zum Test habe ich ein Passwort mit nur Buchstaben genommen.

**Comment by chefkoch009** [comment]
Kannst du mir mal einen Export von deinem Projekt per Mail zukommen lassen?

**Comment by Filou2000** [comment]
[Test.zip](https://github.com/ioBroker/ioBroker.knx/files/9282496/Test.zip)

PW: test

Ist nur ein einfaches Testprojekt mit einem Aktor.

**Comment by chefkoch009** [comment]
Habe es getestet....Dein Projekt ließ sich problemlos importieren.
![import](https://user-images.githubusercontent.com/20514664/184340050-47c8ddee-e304-4c23-ba79-5093be882fcd.JPG)
![import-GA-structure](https://user-images.githubusercontent.com/20514664/184340052-c8ccbd7f-65d6-4ae8-8fda-f63ccd08c005.JPG)


Was war der Fehler, weshalb es sich bei Dir nicht importieren ließ?

VG 
chefkoch009

**Comment by Shorts154** [comment]
Hej chefkoch009,
mein mit ETS6 6.04 (Build 4543) exportiertes Projekt lässt sich ebenfalls nicht importieren, es kam die obige Fehlermeldung mit dem falschen Passwort. Der neueste Adapter, den ich finde, ist allerdings 2.0.13. In dem Projekt ist auch der MDT-Router mit aktivierter Secure-Funktion, kann es daran liegen?

**Comment by chefkoch009** [comment]
Die letzte Version liegt im Beta-repo das ist die 2.0.15.

Die knx Secure Funktion hat nichts mit dem Import UND dem Gateway zu tun. Der Import muss so funktionieren. Welche ist die erste ETS Version mit der du dein Projekt erstellt hast?

**Comment by Shorts154** [comment]
OK, die 15 kann ich dann ja nochmal ausprobieren.

Das Projekt habe ich glaube ich mit der ETS inside erstellt, das wurde dann mal geupgraded, als die inside eingestellt wurde. Eventuell war es aber auch mit der ETS 5, dann Export zu ETS inside, dann Export zu ETS 6

Danke für die schnelle Antwort!

**Comment by Filou2000** [comment]
Ich hatte mit der 2.0.15 weiterhin den Fehler: "Import teilweise oder vollständig mit Fehler fehlgeschlagen:Falsches Passwort"

**Comment by Shorts154** [comment]
Moin,
also ich bekomme mit Version 2.0.15 den Adapter nicht mal mehr gelb, also da zeigt er mir dann gar keine Verbindung an. Mit 2.0.13. ist aber auch immer ein rotes Kreuzchen vor "Verbunden mit Gerät oder Dienst". Aber: wenn ich ein Testprojekt erstelle mit einem Aktor und einem Taster, beginnt er irgendwie mit dem Import und sagt dann: "Import teilweise oder vollständig mit Fehler fehlgeschlagen:Projectimport with this ETS Version not yet possible." Bisschen nervig, hatte ich mir einfacher vorgestellt - sogar schon mutig 40€ für das ganze Jahr gezahlt. Ich würde mich freuen, wenn ich das mit deiner/eurer Hilfe noch hinbekomme. :)
Beste Grüße!

**Comment by chefkoch009** [comment]
@Shorts154 Kannst Du mir mal bitte eine PN im iobroker Forum schreiben?

**Comment by RoadrunnerBF** [comment]
Hallo zusammen - ich habe bei mir die Adapterversion 2.0.16 installiert - ETS habe ich die Version 6.0.5 (4939) und leider kommt bei mir auch die Meldung - "Import teilweise oder vollständig mit Fehler fehlgeschlagen: Falsches Passwort" - das Passwort ist 100% richtig da copy-paste.

Gibt es hier ein bekanntes Problem ?

Danke euch ! :) Viele grüße

**Comment by chefkoch009** [comment]
Ich kann irgendwie nicht herausfinden warum es nicht funktioniert. Kannst du bitte den Adapter deinstallieren und neu installieren und dann eine neue Instanz anlegen und nocheinmal importieren?

**Comment by Shorts154** [comment]
OK, die 15 kann ich dann ja nochmal ausprobieren.Das Projekt habe ich glaube ich mit der ETS inside erstellt, das wurde dann mal geupgraded, als die inside eingestellt wurde. Eventuell war es aber auch mit der ETS 5, dann Export zu ETS inside, dann Export zu ETS 6Danke für die schnelle Antwort!--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 14.08.22, 18:39 schrieb chefkoch009 ***@***.***>:

   
  Die letzte Version liegt im Beta-repo das ist die 2.0.15. 
  Die knx Secure Funktion hat nichts mit dem Import UND dem Gateway zu tun. Der Import muss so funktionieren. Welche ist die erste ETS Version mit der du dein Projekt erstellt hast?

**Comment by franksch99** [comment]
Auch ich habe das gleiche Problem, dass ich die KNX nicht importieren kann und die besagte Fehlermeldung auftritt.
Bei mir ist seit heute früh die Adapterversion 2.0.16 installiert. Die Projektdatei habe ich ursprünglich mit der ETS 6.04 erstellt, die letzte Sicherung erfolgte jedoch mit der aktuellen, 6.06.

Vielleicht habt ihr ja eine Idee

**Comment by chefkoch009** [comment]
Ich arbeite gerade mit Hochdruck am ETSv6.0.6 Import.

**Comment by mattle1957** [comment]
Wie ist denn mittlerweile der Stand zur Anpassung? Ich kann mein KNX-Projekt nicht importieren.

**Comment by chefkoch009** [comment]
Bei mir funktioniert es. Ich habe dankenswerter Weise eine ioBroker Instanz bekommen, bei der es nicht funktioniert. Da suche ich nach der Ursache.

**Comment by Hal100000** [comment]
ETS 6.06, KNX Adapter 2.0.16, Passwort mit 20 Buchstaben und Zahlen (keine Sonderzeichen) und leider auch die Fehlermeldung: "Import teilweise oder vollständig mit Fehler fehlgeschlagen:Falsches Passwort"

**Comment by chefkoch009** [comment]
Bitte den Admin auf https umstellen. Dann sollte es funktionieren.

Please change admin from http to https and try again.

**Comment by Hal100000** [comment]
Funktioniert besser - jetzt bekomme ich folgende Fehlermeldung: Import teilweise oder vollständig mit Fehler fehlgeschlagen:Projectimport with this ETS Version not yet possible.

**Comment by foxriver76** [comment]
Try adapter version 2.0.17 if you use ETS 6.0.6

**Comment by Shorts154** [comment]
Worked for me - deactivated the secure-features to avoid that first problem and Adapter 2.0.17 for the import from ETS 6.0.6. :-)--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.11.22, 09:32 schrieb Max Hauser ***@***.***>:

   
  Try adapter version 2.0.17 if you use ETS 6.0.6

**Comment by Freakisch** [comment]
Hello,

do get the message:

Importstate
Import teilweise oder vollständig mit Fehler fehlgeschlagen: Projectimport with this ETS Version not yet possible.

Trying to import my file named 221123.knxproj and that does not have a password. The original project started with ETS 2 but is now running on ETS6.1.1.

I see the 2.0.23 Adaptor instellad but under Version on the bottom I do not see a version number like 2.0.23

There is an note on the host I have not upgraded not to get another problem. Is 6.1.1. to new and not supported yet?

![Zwischenablage03](https://github.com/ioBroker/ioBroker.knx/assets/151881956/2678b30f-8112-47bc-a81a-7f9a813443c5)
![Zwischenablage02](https://github.com/ioBroker/ioBroker.knx/assets/151881956/2ba44e47-4ed5-47e4-a2d1-0a30ff05e32e)

**Comment by chefkoch009** [comment]
The new ETs version came this week. I'm working on new adapter version for importing new project files.

**Comment by Freakisch** [comment]
> The new ETs version came this week. I'm working on new adapter version for importing new project files.

Thank you so much and yes it was rather new.

I was not aware that the ETS upgrade did require the adaptor import to be code modified. If you need my latest ETS project for testing please let me know.

**Comment by chefkoch009** [comment]
Thanks for your response. I'll check it first with my own testprojects. 

While processing the import, I do a lot of things with the project content. Therefore I must be sure to match the right version.

**Comment by chefkoch009** [comment]
The new version 2.0.24 is online in beta-repo. Maybe you have to install it via console otherwise you'll see it tomorrow in admin.
