### ISSUE TITLE
Adapter crash since v2.0.11

### ISSUE THREAD

**Issue by trollvottel** [ioBroker/ioBroker.knx#234]
The adapter crashes since update to v2.0.11:

<html><body>

host.iobroker | 2022-02-11 12:28:09.333 | error | instance system.adapter.knx.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
knx.0 | 2022-02-11 12:28:08.769 | error | Cannot read property 'native' of undefined
knx.0 | 2022-02-11 12:28:08.769 | error | TypeError:  Cannot read property 'native' of undefined    at  _0x144bc5.<anonymous>  (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:315125)    at  _0x144bc5.emit (events.js:400:28)    at Socket.<anonymous>  (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:70180)    at  Socket.emit (events.js:400:28)    at UDP.onMessage [as onmessage]  (dgram.js:931:8)
knx.0 | 2022-02-11 12:28:08.767 | error | uncaught exception: Cannot read property 'native' of undefined
host.iobroker | 2022-02-11 12:20:52.627 | error | instance system.adapter.knx.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
knx.0 | 2022-02-11 12:20:52.078 | error | Cannot read property 'native' of undefined
knx.0 | 2022-02-11 12:20:52.077 | error | TypeError:  Cannot read property 'native' of undefined    at  _0x144bc5.<anonymous>  (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:315125)    at  _0x144bc5.emit (events.js:400:28)    at Socket.<anonymous>  (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:70180)    at  Socket.emit (events.js:400:28)    at UDP.onMessage [as onmessage]  (dgram.js:931:8)
knx.0 | 2022-02-11 12:20:52.076 | error | uncaught exception: Cannot read property 'native' of undefined

</body>
</html>

**Comment by chefkoch009** [comment]
Prüfe bitte einmal, ob Deine Objekte ok sind. Es scheint, das in mindestens einem der "native" Block fehlt.

**Comment by trollvottel** [comment]
Ich habe mal den ganzen knx Objektbaum gelöscht und neu erzeugen lassen, Problem beseitigt!

**Comment by trollvottel** [comment]
Occured again :(

<html><body>


knx.0 | 2022-02-15 15:21:34.541 | error | Cannot read property 'native' of undefined
-- | -- | -- | --
knx.0 | 2022-02-15 15:21:34.541 | error | TypeError:  Cannot read property 'native' of undefined    at  _0x144bc5.<anonymous>  (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:315125)    at  _0x144bc5.emit (events.js:400:28)    at Socket.<anonymous>  (/opt/iobroker/node_modules/iobroker.knx/knx.js:1:70180)    at  Socket.emit (events.js:400:28)    at UDP.onMessage [as onmessage]  (dgram.js:931:8)
knx.0 | 2022-02-15 15:21:34.539 | error | uncaught exception: Cannot read property 'native' of undefined


</body>
</html>

**Comment by soho737** [comment]
Same happening here - maybe as a hotfix check for a null reference before trying to access the property native so it doen't take the whole adapter down. Stuck in a restart loop here...

**Comment by chefkoch009** [comment]
Sollte in der V2.0.12 behoben sein.

**Comment by chefkoch009** [comment]
Does the problem persists?

**Comment by soho737** [comment]
Will check on Monday - wife would kill me if I bring down the home automation on a weekend

**Comment by trollvottel** [comment]
Haven't seen this since the update, would re-open the issue if it occurs again.
