### ISSUE TITLE
Negative numerical value triggers warning

### ISSUE THREAD

**Issue by trollvottel** [ioBroker/ioBroker.knx#236]
Datatype in ETS is DPT 14.056 "Leistung (W)" (4-Byte Gleitkommawert)

The value is updated correctly, though. The warning is unnecessary I guess.

<html><body>

knx.0 | 2022-02-26 18:48:10.482 | warn | State  value to set for  "knx.0.Hauptfunktionen.Energiemanagement.Hauptfunktionen_Energiemanagement_E3_DC_Batteriebezug_(Leistung__W_)"  has value "-807" less than min "0"
-- | -- | -- | --

</body>
</html>

**Comment by chefkoch009** [comment]
is fixed in v2.0.13. Otherwise please re-open this issue.
