### ISSUE TITLE
KNX import error with ETS 6.0.2

### ISSUE THREAD

**Issue by Beerterd** [ioBroker/ioBroker.knx#238]
When importing the knxproj I get an error that the file cannot be imported because the version is not supported.

**Comment by chefkoch009** [comment]
Please try Adapter Version 2.0.13. This is in Beta repository.

**Comment by quorle** [comment]
Füge auch hinzu, bei ETS 6.0.3 das selbe Problem. Adapter habe ich bereits auf 2.0.13 installiert.

**Comment by chefkoch009** [comment]
Bitte ETS auf v6.0.4 aktualisieren und den Adapter auf 2.0.14, dann wird es wieder funktionieren.
