### ISSUE TITLE
KNX import issue with ETS 5.7.7

### ISSUE THREAD

**Issue by DeHaal** [ioBroker/ioBroker.knx#239]
Hi, i tried to import a project file today, but I got an error message. I used ioBroker.knx Version 2.0.5.
Afterwards I did an upgrade to 2.0.12, but the error message stayed.

![Screenshot 2022-03-07 201704](https://user-images.githubusercontent.com/101138084/157102576-5a3fa07e-e2a3-402e-9d83-b1ec41cf4385.png)

**Comment by chefkoch009** [comment]
With ETS5.7.7? Did they made an update of ETS5.x.x I did not recognise? If so I'll fix it soon as possible.

**Comment by DeHaal** [comment]
Yes they did :) Thank you very much

![Unbenannt](https://user-images.githubusercontent.com/101138084/157311201-eab7f68a-b6ec-45ce-b14f-7dc050730cb4.jpg)

**Comment by chefkoch009** [comment]
Thank you for your information. I added this into adapter Version 5.7.7. So I close this issue. If it does not work, please reopen this issue.

**Comment by DeHaal** [comment]
Thanks a lot! Works fine again
