### ISSUE TITLE
2.0.13 Import ETS5.7.7 bleibt stehen / friert ein

### ISSUE THREAD

**Issue by Tomtheripper** [ioBroker/ioBroker.knx#241]
Hallo,
der Proj.-Import von ETS 5.7.7 friert ein / funktioniert nicht.
Der Import will starten, der Balken bewegt sich etwa 10 % und bleibt dann stehen.
Ins Fehler-Protokoll wird nichts geschrieben (oder ich mach was falsch...)

Wie kann ich zur Problemlösung beitragen bwz. was ist zu tun?

Gruß
Thomas

**Comment by chefkoch009** [comment]
Klingt so als ob der Export kaputt ist. Kannst du bitte nochmal neu exportieren? Wenn das nicht funktioniert, würde ich mich freuen, wenn du mir die Datei zur Verfügung stellen könntest.

**Comment by Tomtheripper** [comment]
Hi Chefkoch,

Datei als E-Mail - Antwort. Hat das geklappt?

(Symptom besteht auch nach einem Neu-Export in der ETS)

**Comment by chefkoch009** [comment]
Hat leider nicht geklappt. Schreib mir bitte mal eine PN im Forum.

**Comment by Tomtheripper** [comment]
Das selbe Fehlerbild habe ich auch beim Import meines ETS6-Projektes - Import-Balken bleibt nach ca. 10% stehen und es rührt sich nix mehr.

**Comment by chefkoch009** [comment]
An einer bestimmten Stelle kommt es zu einem timeout. Bei meinen Projekten nicht. Die Unterschiede schaue ich mir an.

**Comment by chefkoch009** [comment]
Kurzer Zwischenstand: die Konfig von Deinem TBW mit der 1.1.200 ist so dermaßen groß, das es dadurch zu einem timeout kommt. Ich konnte noch nicht herausfinden an welcher Stelle genau es passiert, bin aber dran.

**Comment by Tomtheripper** [comment]
Zur Info: mit der neuen V 2.0.14 klappts auch noch nicht...

**Comment by chefkoch009** [comment]
Ich weiß...da arbeite ich noch dran. Ist ein wenig knifflig. Es liegt an der Produktdatei vom Timberwolf. Die ist etwas extrem groß.

**Comment by Tomtheripper** [comment]
Soll ich den TWB-Hersteller über deren Supportforum mit Einbeziehen?

**Comment by chefkoch009** [comment]
Danke für die Idee, aber der Anspruch ist alles importieren zu können. Ich weiß ja woran es kaputt geht. An der Lösung arbeite ich.

**Comment by Tomtheripper** [comment]
Hey chefkoch009,

darf ich nochmal an diesen Issue erinnern?
(Du weißt ja....jetzt, wo der Adapter was kostet....).

Bin ich der einzige mit 'nem Timberwolf-Server mit seinen 2000 Universalobjekten und diesem Problem?

**Comment by chefkoch009** [comment]
Ja, bist Du. Mit der 2.0.15 kann ich Dein Projekt problemlos importieren.

**Comment by Tomtheripper** [comment]
Juhuu, es klappt!
Großen Dank an Dich!!!

(ich war zu ungeduldig: Der Balken bleibt bei ca. 90% ein paar Minuten stehen)
