### ISSUE TITLE
Lizenzproblem

### ISSUE THREAD

**Issue by iobroker99** [ioBroker/ioBroker.knx#242]
Hallo,
habe eine 1000er Lizenz. Nach Update von iobroker und adapter zeigt mir der knx Adapter wechselnd an, dass die Lizenz nicht gültig sei oder zeigt sie als gültig an, aber nur für 500/581 Datenpunkten. 
Bei iobroker ist in der Lizenz eine Seriennummer hinterlegt die ich nicht kenne. Hardware etc wurde nicht gewechselt, die Seriennummer dürfte sich daher nicht geändert haben?

**Comment by chefkoch009** [comment]
Kannst Du mir bitte mal eine PN im iobroker forum senden?
