### ISSUE TITLE
Jalousie/Raffstore nur via Absolutem Wert steuerbar

### ISSUE THREAD

**Issue by MikeW83** [ioBroker/ioBroker.knx#243]
Guten Morgen,

aktuell habe ich das Problem, dass ich meine Raffstore nur über den Wert für die Absolute Position hoch- und runterfahren kann. Möchte ich direkt eine Fahrt auslösen findet sich im Log folgendes:
`Read-only state "knx.0.Beschattung.Fahren.EG-Esszimmer-Raffstore-Fahren" has been written without ack-flag with value "1"`
In der ETS ist eigentlich alles richtig gesetzt, da die Funktionen über unsere Taster und die Wetterstation einwandfrei funktionieren.

Danke & Lg, Michael

**Comment by chefkoch009** [comment]
Hallo Michael,

Bitte setze einmal für diesen Datenpunkt über die GA-Tools das Write-Flag und nimm das Read-Flag weg.

**Comment by MikeW83** [comment]
Sehr komisch, da ist garnichts angehakt...
![image](https://user-images.githubusercontent.com/35097389/165692303-0be2b95a-1fdc-473d-93a9-f280db1f9d6e.png)
