### ISSUE TITLE
Adapter grün aber die Datenpunkte reagieren nicht 

### ISSUE THREAD

**Issue by Pauli29** [ioBroker/ioBroker.knx#245]
Ich habe seit einiger Zeit, kann leider nicht sagen seit welcher Version, folgendes Problem:

Der Adapter ist eingerichtet und funktioniert einwandfrei. Jedoch nach einigen Stunden reagiert er plötzlich nicht mehr und ich kann nichts mehr steuern. Er ist jedoch weiterhin grün und im Log steht trotz debug nichts. Das ganze lässt sich nur durch einen Neustart des Adapter beheben, dann geht er wieder für kurze Zeit.

Adapter: 2.0.13
Ja: 4.0.19
Node.js: 14.19.0

**Comment by Alex0176** [comment]
Hab das gleiche Problem - leider meine Version ist 2.0.14

**Comment by Pauli29** [comment]
Kannst du noch sagen seit welcher Version? Ist das ab V2 oder später? Ich bin mir leider nicht mehr sicher.

**Comment by barni** [comment]
ich habe seid Version 2 auch das Problem habe sogar schon den KNX IP Router getauscht. Bei mir lässt sich das Problem reproduzieren indem ich dafür sorge das kurz der KNX IP Router nicht erreichbar ist zb indem alle IP Routen vom Iobrooker zum KNX Ip Router entferne. ein ausstecken des Kabels führt nicht zu dem Problem.

**Comment by chefkoch009** [comment]
Kommt es ggf. zu Verbindungsabbrüchen wegen Netzwerk?

**Comment by barni** [comment]
> Kommt es ggf. zu Verbindungsabbrüchen wegen Netzwerk?

Bei mir auf jeden Fall ja ! Aber diese werden nicht erkannt, alles ist angeblich weiterhin grün und auch geht das System nicht wieder wenn alle Verbindungen wieder OK sind.

**Comment by chefkoch009** [comment]
Hast du noch andere Komponenten die über das Netzwerk auf die LAN Schnittstelle zugreifen? Die LAN Gateways Stellen nur eine kleine Anzahl an Verbindungen zur Verfügung z.B. 4. Wenn die Verbindung nun unterbrochen wird, so hält das GW diese Verbindung dennoch offen für eine gewisse Zeit (abhängig vom GW bis zu 5 Min) weil es kein "disconnect_request" gehört hat. Wenn dies nun in dem Fall 4 mal in kurzer Zeit passiert ist das GW für Verbindungsanfragen tot. Ich müsste einen periodischen Verbindungstest in den Adapter einbauen.

**Comment by Pauli29** [comment]
> Kommt es ggf. zu Verbindungsabbrüchen wegen Netzwerk?

Bei mir kann ich keine Verbindungsabbrüche erkennen. Der ioBroker läuft auf einem Raspberry Pi 4 der per Kabel im Netzwerk hängt. Mit der Version 1.x hat es auch ohne Probleme funktioniert.

**Comment by barni** [comment]
> 



> Hast du noch andere Komponenten die über das Netzwerk auf die LAN Schnittstelle zugreifen? Die LAN Gateways Stellen nur eine kleine Anzahl an Verbindungen zur Verfügung z.B. 4. Wenn die Verbindung nun unterbrochen wird, so hält das GW diese Verbindung dennoch offen für eine gewisse Zeit (abhängig vom GW bis zu 5 Min) weil es kein "disconnect_request" gehört hat. Wenn dies nun in dem Fall 4 mal in kurzer Zeit passiert ist das GW für Verbindungsanfragen tot. Ich müsste einen periodischen Verbindungstest in den Adapter einbauen.

Hi,
also habe es gerade nochmal reproduziert in dem ich dem Host (proxmos) das Netzwerk entzogen habe. D.h. die VM für iobroker hat zwar nich Netz aber keine Verbindung mehr.
Der KNX Router reported dann alle channels closed
Tunnels open: 0/8
1: 01.00.001, closed
2: 01.00.002, closed
3: 01.00.003, closed
4: 01.00.004, closed
5: 01.00.005, closed
6: 01.00.006, closed
7: 01.00.007, closed
8: 01.00.008, closed

Aber der KNX Adapter merkt das nicht, auch nach Minuten sieht alles gut aus aber weder gehen Events raus noch werden welche empfangen.

Grüße,
Stephan

**Comment by Pauli29** [comment]
> > 
> 
> > Hast du noch andere Komponenten die über das Netzwerk auf die LAN Schnittstelle zugreifen? Die LAN-Gateways stellen nur eine kleine Anzahl an Verbindungen zur Verfügung, zB 4. Wenn die Verbindung nun unterbrochen WIRD, so hält das GW diese Verbindung trotzdem offen für eine gewisse Zeit (abhängig vom GW bis zu 5 Min), weil es kein "disconnect_request" gehört Hut. Wenn dies nun in dem Fall 4 mal in kurzer Zeit passiert ist das GW für Verbindungsanfragen tot. Ich müsste einen periodischen Verbindungstest in den Adapter einbauen.
> 
> Hi, auch habe es gerade nochmal reproduziert in dem ich dem Host (proxmox) das Netzwerk entzogen habe. Dh die VM für iobroker hat zwar noch Netz aber keine Verbindung mehr. Der KNX Router meldet dann alle Kanäle geschlossen Tunnel offen: 0/8 1: 01.00.001, geschlossen 2: 01.00.002, geschlossen 3: 01.00.003, geschlossen 4: 01.00.004, geschlossen 5: 01.00.005, geschlossen 6 : 01.00.006, geschlossen 7: 01.00.007, geschlossen 8: 01.00.008, geschlossen
> 
> Aber der iobroker-KNX-Adapter merkt das nicht, auch nach Minuten sieht alles gut aus, aber weder gehen Events raus noch werden welche empfangen.
> 
> Grüße Stephan

Was passiert nachdem die Verbindung wieder verfügbar ist? Funktioniert der Adapter dann gleich wieder oder musst du ihn zuerst neu starten?

**Comment by barni** [comment]
> Was passiert nachdem die Verbindung wieder verfügbar ist? Funktioniert der Adapter dann gleich wieder oder musst du ihn zuerst neu starten?

Ich muss ihn neu starten. Ohne bleibt der Zustand so, das alles gut aussieht aber nichts geht.

**Comment by Garfonso** [comment]
Ja, das hab ich hier auch so. Wenn die Netzwerkverbindung getrennt wurde, bleibt der KNX Adapter grün, aber die Verbindung geht nicht mehr. Die Erkennung, dass die Verbindung unterbrochen wurde, funktioniert scheinbar nicht mehr. 

Z.T. fällt mir das dann leider erst einige Stunden später auf... :-/

**Comment by CrEaK** [comment]
Habe leider genau das gleiche Problem. Kurzer Netzwerk-Schluckauf und schon ist die KNX-Verbindung weg und es fällt gar nicht auf. Kein Error im Log oder sonstiges. Es hilft ein kurzer Neustart von der Instanz.
Wäre es nicht möglich ein automatischen Retry einzubauen?

**Comment by chefkoch009** [comment]
Ist 2.0.15 behoben sein. Nach 2Sek nachdem das letzte Paket gehört wurde wird ein connStateReq durchgeführt. Wenn der OK ist, dann ist halt gerade nichts los auf dem Bus. Sonst wird die Verbindung neu aufgebaut.

**Comment by CrEaK** [comment]
Leider habe ich auch mit 2.0.15 weiterhin das Problem, dass bei einem kurzem Netzwerk-Schluckauf die KNX Verbindung verloren ist und der Adapter trotzdem grün anzeigt. Ich kann gut an der Uhrzeit-GA sehen, das es auf einmal stehen bleibt. Ein Restart vom Adapter hilft und alle GAs funktionieren wieder.
