### ISSUE TITLE
Feature Request - Projektimport ETS6

### ISSUE THREAD

**Issue by Vertigo1206** [ioBroker/ioBroker.knx#249]
Es wäre echt toll wenn man Projekt aus der neuen ETS Version 6 importieren könnte.
Es steigen langsam immer mehr Leute auf die neue Version um bzw. Neu-Einsteiger fangen mit der ETS 6 an

Ich habe bereits die ETS6 und würde, soweit möglich, auch dann gerne unterstützen

**Comment by chefkoch009** [comment]
Man kann ETS6 Projekte importieren. Bitte einmal mit Adapter Version 2.0.15 Testen.

**Comment by Vertigo1206** [comment]
Sorry, mein Fehler hab die letzte Version hier auf GitHub übersehen.
Im iobroker wird mir nur die 2.013 als letzte Version angeboten.
Nach manuellem Update auf 2.0.15 funktionieren auch die ETS6 Projekte
