### ISSUE TITLE
ioBroker steuert Jalousieaktor falsch an

### ISSUE THREAD

**Issue by fkieling** [ioBroker/ioBroker.knx#252]
Die Zielposition des Jalousieaktors wird über den Channel "Absolute Position" gesteuert. Dieser kann Werte von 0% (ganz oben) bis 100% (ganz unten) annehmen. 

- Setze ich dies zum Testen ETS funktioniert es.
- Setze ich dies mit ioBroker.knx wird dies nicht korrekt an KNX gesendet - der Rollladen bewegt sich nicht.

![image](https://user-images.githubusercontent.com/13314382/184326666-ba65fc19-b20c-4b88-8c4e-5312ee050e0b.png)

Scheinbar ist das Telegram nicht vollständig, das an den KNX-Bus gesendet wird. Im Screenshot sind 5 Telegramme zu sehen. 
Nr 1 und 3 sind korrekt gesendete Telegramme - einmal mit 45% und einmal mit 80% als Zielposition. 
Nr 5 ist das Telegramm aus ioBroker.knx, in dem zwei Informationen fehlen bzw. falsch sind:

1. DPT ist immer leer. Hier müßte "5.001 Prozent (0..100%)" stehen.
2. Info ist fehlerhaft. Hier steht immer "$00 | 0 %" - statt dessen müßte hier eine Info wie "$73 | 45 %" stehen.

Bitte dieses Problem beseitigen, damit Jalousien / Rollläden gesteuert werden können.

**Comment by chefkoch009** [comment]
Hallo, 

Wie sehen die RAW Daten von den Jalousie pos absolut aus?

**Comment by fkieling** [comment]
Wie ermittel ich die Raw-Daten?

**Comment by chefkoch009** [comment]
Im Objektbrowser suchst du den entsprechenden Datenpunkt heraus und klickst links auf den Stift und wählst im nächsten Fenster "Objektdaten" aus. Dort solltest Du ein JSON Objekt sehen. ungefähr so:
{
  "_id": "knx.0.Jalousie.WP_Einhausung.WP_Einhausung_Front_Position",
  "type": "state",
  "common": {
    "name": "WP Einhausung Front Position",
    "type": "number",
    "role": "level",
    "read": false,
    "write": true,
    "min": 0,
    "max": 100
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "2/0/4",
    "addressRefId": "P-033A-0_GA-71",
    "statusGARefId": "P-033A-0_GA-69",
    "actGARefId": "",
    "update": false,
    "objRef": "O-54_R-694",
    "devName": "M-0004_A-2078-12-0340-O000A",
    "devInst": "P-033A-0_DI-4",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1612122040333,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Diese Information brauch ich mal.

**Comment by fkieling** [comment]
Moin,

die Raw-Daten sehen wie folgt aus:

{
  "_id": "knx.0.Haus.Bad.Rollladen_Abs_Position",
  "type": "state",
  "common": {
    "name": "Rollladen Abs Position",
    "type": "number",
    "role": "state",
    "read": false,
    "write": true,
    "max": 100,
    "min": 0
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "0/1/1",
    "addressRefId": "P-050E-0_GA-24",
    "statusGARefId": "",
    "actGARefId": "",
    "update": false,
    "objRef": "O-30_R-103",
    "devName": "M-0083_A-0029-38-E50A",
    "devInst": "P-050E-0_DI-5",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1660294587737
}

**Comment by chefkoch009** [comment]
also "role" wird zu level und Du hast keine Statusadresse hinterlegt. Ansonsten soweit ok. Kannst Du mal bitte den Mitschnitt vom Busmonitor zeigen, wenn du den Rolladen über das Objekt im Objektbaum, zeigen?

**Comment by fkieling** [comment]
"Die Schnittstelle unterstützt den Verbindungsmodus (Busmonitor?) nicht". 
Scheinbar kann ich den Busmonitor nicht nutzen.

**Comment by chefkoch009** [comment]
Oh tut mir leid, ich meinte den Gruppenmonitor. Da hab ich Mal ich mich falsch ausgedrückt.

**Comment by fkieling** [comment]
![grafik](https://user-images.githubusercontent.com/13314382/184547434-9fe45850-0ed5-4ddf-bebc-dc10e105f1f1.png)
Im Screenshot siehst Du Einträge.
Pos 2 ist ein Eintrag aus dem KNX-Adapter im ioBroker, der fehlerhaft ist. 
Pos 3 ist ein Eintrag, den ich durch das setzen eines Wertes im ETS erzeugt habe.
In beiden Fällen sollte der Rollladen auf 30% herunterfahren.

**Comment by chefkoch009** [comment]
Die Adresse des Adapters darf nicht 1.1.0 sein! x.y.0 ist immer ein Router. 
Schreib mir über das iobroker Forum mal bitte eine PN.

**Comment by fkieling** [comment]
Ich habe Dir im ioBroker Forum eine PN geschrieben.

**Comment by fkieling** [comment]
Moin. Leider tritt der Fehler trotz der korrigierten Adresse weiterhin auf. Wie kann der Fehler beseitigt werden?

**Comment by fkieling** [comment]
Ursache war nicht der Adapter sondern ein Fehler in der im ETS angelegten Gruppe. Vielen Dank für die super Unterstützung @chefkoch009. Nebenbei noch einiges über KNX und ioBroker gelernt :)

**Comment by tetzlav** [comment]
> Ursache war nicht der Adapter sondern ein Fehler in der im ETS angelegten Gruppe.
Sorry wenn ich das hier nochmal hoch hole, aber ich habe exakt das gleiche Problem. Ich finde jedoch keinen Fehler in meiner Gruppenadresse. Es ist dort als DPT5.001 konfiguriert.

**Comment by chefkoch009** [comment]
Das kannst du leicht über die GA-Tools in der Adapterkonfiguration ändern. Ein re-import bringt an der Stelle nichts, wenn die GA schon existiert.

**Comment by tetzlav** [comment]
Anpassungen über den GA-Editor habe ich versucht. Jedoch finde ich keinen Fehler. Laut ETS Gruppenmonitor wird immer "$00 | Aus" gesendet (Telegramm 9). Wenn ich von der ETS aus 10% auf die GA schreibe funktioniert alles bestens (Telegramm 25-28).

Mit dem gleichen Aktor anderer Rollladen/GA funktioniert es via iobroker.knx wiederum ohne Probleme (Telegramm #82-185), außer das beim Senden via iobroker.knx im Log der DPT "5.001 Prozent (0..100%)" fehlt:

```
#	Zeit	Dienst	Flags 	Prio	Quelladresse	Quellname	Zieladresse	Zielname	Rout	Typ	DPT	Info
9	10.12.2024 08:10:48,018	vom Bus		Niedrig	1.1.101		3/1/15		6	GroupValueWrite					$00 | Aus
25	10.12.2024 08:11:21,149	zum Bus		Niedrig	15.15.243	3/1/15		6	GroupValueWrite	  5.001 Prozent (0..100%)	$1A | 10 %
26	10.12.2024 08:11:21,193	vom Bus		Niedrig	1.1.10		3/1/16		6	GroupValueWrite					$01 | Ein
27	10.12.2024 08:11:21,277	vom Bus		Niedrig	1.1.10		3/1/2		6	GroupValueWrite					$1A | 10 %
28	10.12.2024 08:11:21,327	vom Bus		Niedrig	1.1.10		3/1/16		6	GroupValueWrite					$00 | Aus
182	10.12.2024 08:17:42,947	vom Bus		Niedrig	1.1.101		3/1/9		6	GroupValueWrite					$33 | 20 %
183	10.12.2024 08:17:43,003	vom Bus		Niedrig	1.1.10		3/1/11		6	GroupValueWrite					$01 | Ein
184	10.12.2024 08:17:44,937	vom Bus		Niedrig	1.1.10		3/1/8		6	GroupValueWrite					$33 | 20 %
185	10.12.2024 08:17:44,985	vom Bus		Niedrig	1.1.10		3/1/11		6	GroupValueWrite					$00 | Aus

```
Hier mein Datenpunkt des nicht funktionierenden Rolladen:
```
{
  "_id": "knx.0.Rollladen.EG.Wohnzimmer_Tür_Pos_abs",
  "type": "state",
  "common": {
    "name": "Wohnzimmer Tür Pos abs",
    "type": "number",
    "role": "level",
    "read": false,
    "write": true,
    "max": 100,
    "min": 0,
    "unit": "%"
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "3/1/17",
    "addressRefId": "P-04FA-0_GA-375",
    "statusGARefId": "P-04FA-0_GA-55",
    "actGARefId": "",
    "update": false,
    "objRef": "O-59_R-39",
    "devName": "M-0083_A-0029-35-A650",
    "devInst": "P-04FA-0_DI-11",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1733780022058
}
```

Hier der funtktionierende - ich sehe keinen Unterschied:
```
{
  "_id": "knx.0.Rollladen.EG.Küche_Fenster_Pos_abs",
  "type": "state",
  "common": {
    "name": "Küche Fenster Pos abs",
    "type": "number",
    "role": "level",
    "read": false,
    "write": true,
    "max": 100,
    "min": 0,
    "unit": "%"
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "3/1/9",
    "addressRefId": "P-04FA-0_GA-207",
    "statusGARefId": "P-04FA-0_GA-58",
    "actGARefId": "",
    "update": false,
    "objRef": "O-88_R-237",
    "devName": "M-0083_A-0029-35-A650",
    "devInst": "P-04FA-0_DI-11",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1733815469008
}
```
Auch im GA-Editor sieht alles gleich aus:
![screenshot_2024-12-10 (1)](https://github.com/user-attachments/assets/2b3a1ef8-1a40-4406-af78-366077650e2f)
![screenshot_2024-12-10](https://github.com/user-attachments/assets/29d84f90-81d3-466c-8671-a5b95a0052ff)
