### ISSUE TITLE
Anzahl maximaler Datenpunkte wird falsch berechnet?

### ISSUE THREAD

**Issue by Moridin80** [ioBroker/ioBroker.knx#254]
Hallo,

ich finde den KNX Adapter wirklich toll und werde, wenn es so weit ist (wennich soweit bin) eine Version wählen, die mehr als 500 Datenpunkte zulässt. Das ist ok für mich, ich möchte den die Entwicklung des Adapters auch gerne unterstützen! 
Wirklich toll was Ihr da macht! Aktuell ist dies nur noch nicht notwendig und ich lerne noch sehr viel im Umgang 
mit KNX/iobroker & Co!

**Das Problem:**
Die Projektdatei hat laut ETS 5:    **482 Gruppenadressen**
Der KNX Adapter meldet: **525 Gruppenadressen**

Wie ist das m
![GA](https://user-images.githubusercontent.com/111463771/185243224-9cc1a110-16ac-486c-8fdf-216e08386a6b.jpg)
öglich / was mache ich falsch?
Aktuell läuft der Adapter noch, ich möcht einfach vermeiden, dass meine gültige Lizenz nicht einfach mal erlischt...ich bin auch beruflich viel Unterwegs, es wäre echt schlecht wenn das passiert - wenn ich nicht daheim bin :)

**Comment by chefkoch009** [comment]
Welche Adapter Version verwendest du?

**Comment by Moridin80** [comment]
Hallo,

Sorry hätte ich gleich schreiben soll: v2.0.13 
Sonst ist der ioBroker auf aktuellem Stand.

**Comment by chefkoch009** [comment]
Hi, 

Hast Du eventuell manuell Objekte im ioBroker KNX Objektbaum angelegt? Wieviele Objekte zeigt er Dir in dem Fenster an, nachdem der Importvorgang abgeschlossen ist?

**Comment by Moridin80** [comment]
Hallo,

nein hatte. Ich nicht, zumindest nicht im KNX Bereich. Es gibt ein paar Variablen, diese sind aber im ioBroker und es sind auch noch nicht so viele…

Nach dem Importvorgang werde die 482 Adressen korrekt angezeigt. Erst wenn ich später noch einmal in den Adapter gehe, sehe ich die rote Meldung. Wenn ich im Adapter die Gruppenadressen anschaue, sehe ich auch keine doppelten oder so….

muss ich damit rechnen, dass der Adapter sich sperrt?

**Comment by chefkoch009** [comment]
Das verstehe ich nicht. Wo kommen die denn her? Bitte einmal folgendes Vorgehen:
1) Adapter stoppen
2) im Objektbaum in der Hauptebene den knx komplett löschen
3) Adapter starten => muß nun 0/500 anzeigen
4) Dein Projekt neu importieren

wieviel zeigt er nun an?

**Comment by Moridin80** [comment]
Ok, ich kann das probieren. Wird aber dauern, bin nächste Woche nicht daheim!

Zusatzfrage: muss ich dann in Blockly alle Objekte wieder neu auswählen?

**Comment by Moridin80** [comment]
Hallo, 

Sorry für die späte Antwort. Alles mein Fehler! Ich hatte tatsächlich noch doppelte Datenpunkte welche schwer zu erkennen waren. Wenn man diese löscht, passen die Datenpunkte im KNX Adapter!!

**Comment by chefkoch009** [comment]
Vielen Dank für die Rückmeldung und die entsprechende Erklärung der Ursache.
Damit schließe ich den Fall.

**Comment by bejayl** [comment]
Hallo, ich habe ein ähnliches Problem.
Mein Projekt hat im ETS (6.0.6) 293 Gruppenadressen, wenn ich es im KNX Adapter(v2.0.17) importieren will, kommt die Fehlermeldung:

"Import teilweise oder vollständig mit Fehler fehlgeschlagen: maximum of licensed datapoints reached." 
Es werden 552/500 Datenpunkte angezeigt.

Ich habe auch den Baum bei den Objekten gelöscht, danach weiterhin die gleiche Meldung.
Wo liegt mein Denkfehler?

**Comment by Moridin80** [comment]
Hallo,bei mir war es einfach so, dass ich einen Teil in der Struktur übersehen hatte.Sprich die Aussage vom Adapter hatte gestimmt, es waren noch mehr Gruppenadressen vorhanden…vielleicht nochmal die komplette Struktur löschen und neu einfügen?Mit freundlichen GrüßenM. Jantschik Am 09.04.2023 um 10:14 schrieb bejayl ***@***.***>:﻿
Hallo, ich habe ein ähnliches Problem.
Mein Projekt hat im ETS (6.0.6) 293 Gruppenadressen, wenn ich es im KNX Adapter(v2.0.17) importieren will, kommt die Fehlermeldung:
"Import teilweise oder vollständig mit Fehler fehlgeschlagen: maximum of licensed datapoints reached."
Es werden 552/500 Datenpunkte angezeigt.
Ich habe auch den Baum bei den Objekten gelöscht, danach weiterhin die gleiche Meldung.
Wo liegt mein Denkfehler?
