### ISSUE TITLE
Import bei ETS 6.0.5 schlägt fehl

### ISSUE THREAD

**Issue by quorle** [ioBroker/ioBroker.knx#256]
Wollte heute einen Import meines geänderten Projektes machen, jedoch schlägt dies mit folgender Fehlermeldung fehl.

Importstate
Import teilweise oder vollständig mit Fehler fehlgeschlagen:Projectimport with this ETS Version not yet possible.

**Comment by chefkoch009** [comment]
Hab die 2.0.16 heute rausgebracht.

**Comment by quorle** [comment]
> Hab die 2.0.16 heute rausgebracht.

Habe gerade aktualisiert, klappt wieder alles bestens. Danke für die schnelle Reaktion deinerseits.
Update wurde nur noch nicht angezeigt.
