### ISSUE TITLE
Port-einstellungen werden nicht angewendet

### ISSUE THREAD

**Issue by Tampenwalli** [ioBroker/ioBroker.knx#257]
Hallo, trotz eingestelltem Port 3700 versucht der Adapter sich auf 3671 zu verbinden.
Log zeigt ebenso den verwendeten Port 3671 an.

Kleines Edit: 
Admin 6.2.20
NPM: 6.14.16
Node.JS: 14.19.0
js-controller: 4.0.23
KNX Adapter 2.0.13 / 2.0.16

**Comment by chefkoch009** [comment]
Schau ich mir an.

**Comment by Tampenwalli** [comment]
Dankeschön, Vielleicht ist das auch des Rätsels Lösung für das Connect Problem.

**Comment by chefkoch009** [comment]
Hab den Fehler gefunden. Ist in der kommenden Version behoben.

**Comment by Tampenwalli** [comment]
Supi, Dankeschön.
