### ISSUE TITLE
ETS 6.0.6 *.proj Import - Fehler

### ISSUE THREAD

**Issue by Tomtheripper** [ioBroker/ioBroker.knx#260]
Hi,

eine Projektdatei aus der **ETS 6.0.6** lässt sich in den KNX-Adapter **2.0.16** nicht importieren.
Fehlermeldung: nicht kompatibel

Grüße
Thomas

**Comment by chefkoch009** [comment]
Danke für die Info. Arbeite bereits daran.

**Comment by chefkoch009** [comment]
ist in 2.0.17 drin.
