### ISSUE TITLE
keine Verbindung mehr mit V2.0.17 (update von 2.0.16)

### ISSUE THREAD

**Issue by marlan99** [ioBroker/ioBroker.knx#262]
Habe eben auf meinem Testsystem von 2.0.16 auf 2.0.17 updated.
Damit verbindet er jedoch nicht mehr mit dem GW und die Instanz bleibt gelb.

pi@iobroker-test:~ $ nodejs -v
v16.17.1
pi@iobroker-test:~ $ npm -v
8.15.0

Logs im debug mode zeigen leider keine Details:
`

knx.0 | 2022-10-20 12:53:48.150 | info | Connecting to knx GW: 192.168.1.82:3674 with phy. Adr: 1.1.248
-- | -- | -- | --
knx.0 | 2022-10-20 12:53:48.144 | warn | No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
knx.0 | 2022-10-20 12:53:47.814 | info | starting. Version 2.0.17 in /opt/iobroker/node_modules/iobroker.knx, node: v16.17.1, js-controller: 4.0.23
knx.0 | 2022-10-20 12:53:47.179 | debug | Plugin sentry Initialize Plugin (enabled=true)
knx.0 | 2022-10-20 12:53:47.065 | debug | States connected to redis: 127.0.0.1:9000
knx.0 | 2022-10-20 12:53:47.033 | debug | States create User PubSub Client
knx.0 | 2022-10-20 12:53:47.029 | debug | States create System PubSub Client
knx.0 | 2022-10-20 12:53:47.003 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
knx.0 | 2022-10-20 12:53:46.953 | debug | Objects connected to redis: 127.0.0.1:9001
knx.0 | 2022-10-20 12:53:46.941 | debug | Objects client initialize lua scripts
knx.0 | 2022-10-20 12:53:46.841 | debug | Objects create User PubSub Client
knx.0 | 2022-10-20 12:53:46.838 | debug | Objects create System PubSub Client
knx.0 | 2022-10-20 12:53:46.832 | debug | Objects client ready ... initialize now
knx.0 | 2022-10-20 12:53:46.754 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.iobroker-test | 2022-10-20 12:53:43.656 | info | iobroker exit 0
host.iobroker-test | 2022-10-20 12:53:43.389 | info | instance system.adapter.knx.0 started with pid 5540
host.iobroker-test | 2022-10-20 12:53:42.595 | info | iobroker upload [0] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/zip/zip-fs.min.js zip/zip-fs.min.js application/javascript
host.iobroker-test | 2022-10-20 12:53:42.379 | info | iobroker upload [1] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/zip/zip-fs.js zip/zip-fs.js application/javascript
host.iobroker-test | 2022-10-20 12:53:40.994 | info | instance system.adapter.knx.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.iobroker-test | 2022-10-20 12:53:40.834 | info | iobroker upload [2] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/static/js/main.90bbf343.js.map static/js/main.90bbf343.js.map application/json
host.iobroker-test | 2022-10-20 12:53:40.722 | info | iobroker upload [3] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/static/js/main.90bbf343.js.LICENSE.txt static/js/main.90bbf343.js.LICENSE.txt text/plain
host.iobroker-test | 2022-10-20 12:53:40.508 | info | iobroker upload [4] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/static/js/main.90bbf343.js static/js/main.90bbf343.js application/javascript
host.iobroker-test | 2022-10-20 12:53:40.493 | info | iobroker upload [5] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/static/css/main.96b3c861.css.map static/css/main.96b3c861.css.map application/json
host.iobroker-test | 2022-10-20 12:53:40.479 | info | iobroker upload [6] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/static/css/main.96b3c861.css static/css/main.96b3c861.css text/css
host.iobroker-test | 2022-10-20 12:53:40.462 | info | iobroker upload [7] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/manifest.json manifest.json application/json
host.iobroker-test | 2022-10-20 12:53:40.446 | info | iobroker upload [8] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/knx.png knx.png image/png
host.iobroker-test | 2022-10-20 12:53:40.430 | info | iobroker upload [9] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/index_m.html index_m.html text/html
host.iobroker-test | 2022-10-20 12:53:40.409 | info | iobroker upload [10] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/favicon.ico favicon.ico image/vnd.microsoft.icon
host.iobroker-test | 2022-10-20 12:53:40.317 | info | iobroker upload [11] knx.admin /opt/iobroker/node_modules/iobroker.knx/admin/asset-manifest.json asset-manifest.json application/json
knx.0 | 2022-10-20 12:53:40.278 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
knx.0 | 2022-10-20 12:53:40.276 | debug | Plugin sentry destroyed
knx.0 | 2022-10-20 12:53:40.273 | info | terminating
knx.0 | 2022-10-20 12:53:40.265 | debug | Adapter close

`

**Comment by marlan99** [comment]
![Bildschirmfoto 2022-10-20 um 13 19 49](https://user-images.githubusercontent.com/42575841/196935089-ddc27fcf-a57d-429a-8326-067d2472a281.png)

zur Ergänzung

**Comment by lykane1337** [comment]
Hi zusammen,

ich habe die gleichen Probleme mit der Version.
Verbindet sich nicht mit dem Gerät oder Dienst.
In meinem Log steht folgende Zeile:
`STATE_CONNECTION_STATE_REQUEST : no defined handling for transition from State: STATE_CONNECT_REQUEST(3) to STATE_CONNECTION_STATE_REQUEST(5)`
Über Rückmeldung würde ich mich sehr freuen.

Viele Grüße und Danke für die tolle Arbeit
Lykane

**Comment by chefkoch009** [comment]
Wie lauten die nächsten log-Zeilen? Hast du knx-secure aktiviert? Was hast du für ein Gateway?

**Comment by lykane1337** [comment]
Danke für deine schnelle Antwort.

Ich habe ein MDT SCN-IP000.03 Gateway [https://www.mdt.de/produkte/produktdetail/systemkomponenten/systemgeraete/ip-interface.html](url).

![Screenshot_317](https://user-images.githubusercontent.com/64777033/202197434-17f55827-7253-4a52-9932-73d04056a978.png)

Secure ist zwar möglich, habe ich aber nicht aktiv.

Die Logs kann ich gerade nicht auslesen, da ich den alten Stand des Systems wiederhergestellt habe. Um die Logs zu erhalten muss ich viele Datenpunkte wieder neu einrichten. Daher dauert das Update immer etwas. Vielleicht hast du noch eine Idee, wie ich die Rollen und die Grenzbereiche von Temperaturen mitsichern kann. Dann würde ein Restore etwas schneller gehen.

![Screenshot_318](https://user-images.githubusercontent.com/64777033/202198471-8ed93bfd-7eea-475f-beee-5c9ee5a296e0.png)

Nochmals Danke und einen schönen Tag

**Comment by marlan99** [comment]
ich benutze dasselbe GW und ebenfalls ohne Secure

**Comment by marlan99** [comment]
zumindest seit V2.0.21 keine Verbindungsprobleme mehr
