### ISSUE TITLE
true/false insteat of 0/1 for binary values

### ISSUE THREAD

**Issue by AndyBauer119** [ioBroker/ioBroker.knx#268]
Hello,

since version 1.0.30 a switch should be implemented for the user to decide to use "true" and "false" or "0" or "1" for binary values. 

Unfortunately I cannot find this switch in version 2.0.13. 
Can i tell the adapter to use "true" and "false" again?

Thanks for your help.

**Comment by chefkoch009** [comment]
Yes you can. Please use "GA-Tools" in knx-adapter config. For more information please read README.

**Comment by AndyBauer119** [comment]
Hello chefkoch009,

thanks for your quick help. Unfortunately, I did not find any menu item in the GA tools that helped me further. Unfortunately, I couldn't find any reference to it in the Readme how it is possible to switch to true/false.
I don't want to overwhelm you, but could you please give me a little hint on how to proceed.

Here is an example of a GA pair i use:
{
  "_id": "knx.0.Beleuchtung.Ein_Aus.EG_Vorraum_Licht",
  "type": "state",
  "common": {
    "name": "EG Vorraum Licht",
    "type": "boolean",
    "role": "switch",
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "1/0/0",
    "addressRefId": "P-0640-0_GA-177",
    "statusGARefId": "P-0640-0_GA-144",
    "actGARefId": "",
    "objRef": "O-5_R-11029",
    "devName": "M-0083_A-002C-16-8430",
    "devInst": "P-0640-0_DI-32",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1675527271738
}



{
  "_id": "knx.0.Beleuchtung.Status_Ein_Aus.EG_Vorraum_Licht_Status",
  "type": "state",
  "common": {
    "name": "EG Vorraum Licht Status",
    "type": "boolean",
    "role": "indicator",
    "read": true,
    "write": false,
    "unit": "",
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.011",
    "address": "1/1/0",
    "addressRefId": "P-0640-0_GA-144",
    "statusGARefId": "",
    "actGARefId": "P-0640-0_GA-177",
    "update": false,
    "objRef": "O-6_R-11039",
    "devName": "M-0083_A-002C-16-8430",
    "devInst": "P-0640-0_DI-32",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1675530525923
}



thank you for your patience

**Comment by AndyBauer119** [comment]
It's me again: If you meant that I should set the DPT to 1.002 boolean - I tried that several times, unfortunately without success. I also couldn't find any information in the Readme that helped me further.

**Comment by chefkoch009** [comment]
thank you very much for your feedback and your solution to solve this problem.
