### ISSUE TITLE
KNX Adapter funktioniert nach einigen Tagen nicht mehr 

### ISSUE THREAD

**Issue by petkoh85** [ioBroker/ioBroker.knx#27]
Hallo, 
in unregelmäßigen Abständen muss ich den KNX Adapter neu starten, da die Geräte auf einmal nicht mehr reagieren. Ich nutze Version 1.0.11. Mir ist auch aufgefallen, dass ab und zu 1 von 5 Geräten nicht reagiert, wenn diese zugleich betätigt werden. Funktioniert dann nach einigen Minuten oder eben nach einem Neustart des KNX Adapters wieder. Unter Log gibt es keinen Eintrag. 
Was mir nebenbei aufgefallen ist, dass bei den Adaptern unter KNX die aktuelle Version 1.0.11 ist, bei verfügbare Version steht jedoch 0.8.6. Ist das normal?

Viele Grüße 
Peter

**Comment by chefkoch009** [comment]
Hallo petkoh85,

an dem von Dir beschriebenen Problem ist mir bekannt und ich bin da mit Hochdruck dran. 

Bei der 2. Sache musst du Deine Repository Einstellungen im ioBroker von "stable" auf "latest" ändern. Dann siehst Du die aktuellsten Versionen.

**Comment by chefkoch009** [comment]
Ist behoben in 1.0.12
