### ISSUE TITLE
Schreibfehler?

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.knx#274]
Sollte es nicht heißen: "Ziehen Sie die Datei hierhin und legen sie diese hier ab"?

3x ODER ist in dem Satz etwas "Komisch" :D

<img width="757" alt="image" src="https://user-images.githubusercontent.com/50423935/226121327-8e93914e-139a-421b-81eb-b449696b62ce.png">

**Comment by chefkoch009** [comment]
Sind zwar nur 2xODER 😉, aber ja ist komisch.

**Comment by unstressable** [comment]
> Sind zwar nur 2xODER 😉, aber ja ist komisch.

Stimmt haha 👯

**Comment by chefkoch009** [comment]
ist in der nächsten Version behoben.
