### ISSUE TITLE
Update von 2.0.13 auf 2.0.17 zerschießt config

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.knx#276]
Nach dem Upgrade war bei mir plötzlich eine andere Gruppenadresse vom IP Gateway und ein anderer Port eingetragen.
Hab mich erst gewundet, wieso die Lampe nicht grün wird. Bin nur drauf gekommen, weil ich die Config mit einer anderen Installation vergleichen habe, im log kam nichts, was mich auf die richtige Spur geführt hätte.

**Comment by chefkoch009** [comment]
Den Port habe ich in der letzten Verison korrigiert.

**Comment by unstressable** [comment]
> Den Port habe ich in der letzten Verison korrigiert.

Danke!
Jetzt noch die Geschwindigkeit optimieren und der Adapter läuft (bei mir).

**Comment by chefkoch009** [comment]
Sollte auch gefixt sein.

**Comment by unstressable** [comment]
> Sollte auch gefixt sein.

Bei der 2.0.18?
Dann probier ich die mal aus.

**Comment by chefkoch009** [comment]
ist das Problem gelöst?

**Comment by unstressable** [comment]
> ist das Problem gelöst?

Denke ja, bin auf der aktuellsten Version und hab keinerlei Probleme.

**Comment by mcm1957** [comment]
Da offensichtlich gelöst und ca 10 Versionen veraltet kann hier wohl geschlossen werden.
