### ISSUE TITLE
Update 2.0.13 auf 2.0.17 große Verzögerung beim Senden auf Bus

### ISSUE THREAD

**Issue by damiensky** [ioBroker/ioBroker.knx#278]
Seit dem update auf 2.0.17 werden Befehle sehr verzögert (bis zu 10s) auf den Bus geschrieben und auch Status-Rückmeldungen vom Bus werden sehr spät im iobroker registriert oder gehen teilweise sogar verloren.

**Comment by R0gerWilc0** [comment]
Ich kann das Problem bestätigen. Die Zeit vom Ändern eines Datenpunktes bis zum tatsächlichen Senden des Befehls auf den Bus schwankt sehr stark und kann mitunter über 30 s betragen. Das ist nicht alltagstauglich. Auch ein Downgrade auf die Version 2.0.13 macht das Problem leider nicht mehr rückgängig.
Bitte dringend beheben!

**Comment by foxriver76** [comment]
Bitte 2.0.18 testen

**Comment by R0gerWilc0** [comment]
Habe ich gemacht und tatsächlich scheint es bisher so, als ob das Problem damit erfolgreich beseitigt wurde. Danke sehr!

**Comment by unstressable** [comment]
Jap 2.0.18 läuft, bitte schließen.
