### ISSUE TITLE
KNX 2.0.17 total langsam

### ISSUE THREAD

**Issue by unstressable** [ioBroker/ioBroker.knx#280]
Ich habe von 2.0.13 auf 2.0.17 upgegradet und musste feststellen, dass die Reaktionsgeschwindigkeit stark gesunken ist!

Wenn ich normale Befehle ausführe wie "Licht EIN" oder "Licht AUS" hat es vorher sofort reagiert und jetzt dauert es oft bis zu ca. 6 Sekunden.

Ist das nur bei mir so, oder habt ihr das auch?
Wie sollte ich hier vorgehen?

**Comment by MikeW83** [comment]
+1

Ich habe das gleiche Problem.

**Comment by chefkoch009** [comment]
habe die 2.0.18 im Beta-Repo online gestellt. Bitte einmal mit dieser Version testen.

**Comment by peer69** [comment]
Mit 2.0.18 scheint bei mir auf den ersten Blick wieder alles zu funktionieren. Zuvor war ich auf 2.0.13 geblieben, weil mit 2.0.17 auch bei mir die Commands ewig gebraucht haben.

**Comment by ZeroQool007** [comment]
Welche Ursache hatte das Ganze, weil ich bspw keine Performance Probleme hatte. Gruß

**Comment by peer69** [comment]
Ich vermute es lag an Änderungen an der Kommunikation mit dem IP-Gateway, zumindest hatten das meine kurzen Debugging-Versuche vor einiger Zeit vermuten lassen. Da 2.0.13 aber problemlos lief, hatte ich damit nicht weiter gemacht. Mich würde auch interessieren, was genau das jetzt verursacht hat. Ich nutze das PoE-IP-Gateway von eibmarkt, vielleicht trat das auch nur für bestimmte Gateways auf.

**Comment by foxriver76** [comment]
> Welche Ursache hatte das Ganze, weil ich bspw keine Performance Probleme hatte. Gruß

Hat sich nur auf Installationen ausgewirkt bei denen mal 10 Sekunden am Stück Ruhe auf dem Bus ist.

**Comment by unstressable** [comment]
10 Sekunden ist aber nicht lange. Das sollte doch bei jedem Haus vorkommen.

Ich habe das MDT IP Interface.
2.0.18 geht einwandfrei!

**Comment by MikeW83** [comment]
Ah, deswegen hat zB das Ausschalten von Licht oder das Hochfahren der Raffstore umgehend funktioniert.

War das Problem abhängig vom Interface? Habe nämlich auf das von MDT.
________________________________

**Comment by unstressable** [comment]
Mit 2.0.18 behoben

**Comment by unstressable** [comment]
Mit 2.0.18 behoben
