### ISSUE TITLE
KNX components react delayed 

### ISSUE THREAD

**Issue by LukasFiniarel** [ioBroker/ioBroker.knx#282]
I have updated my KNX Adapter from 1.0.46 to 2.0.17.

I have noticed that executed commands are only executed with a considerable delay.
For example, when I turn on a lamp, it takes a moment before the lamp actually turns on.

In the old version the commands were executed almost immediately. 
In the newest version there is a delay of about 5-10 seconds.

No changes were made to the KNX configuration in the meantime.

ioBroker/System configuration:
System: RaspberryPi 4
NodeJS: 18.15.0
NPM: 9.5.0
KNX Adapter Settings: 
 - Packets per second: 30

KNX components are all from MDT

**Comment by chefkoch009** [comment]
Please try 2.0.18 from beta-repo.

**Comment by LukasFiniarel** [comment]
Thank you very much.
Error is fixed in the 2.0.18.

**Comment by FabianEKS** [comment]
Works fine with V2.0.18. Thanks for the fix.
