### ISSUE TITLE
Update 2.0.19 schlägt fehl

### ISSUE THREAD

**Issue by Tomtheripper** [ioBroker/ioBroker.knx#285]
Hallo,
Update von 2.0.18 auf 2.0.19 schlägt fehl: Das Update Fenster kommt, ein paar Meldungen werden eingeblendet, dann verschwindet es ohne weiteren Kommentar/Einblendung.
[IOB-Log-2023-06-09.pdf](https://github.com/ioBroker/ioBroker.knx/files/11707786/IOB-Log-2023-06-09.pdf)
Log ist nach einem Neustart des Timberwolf-Server, direkt nach dem fehlgeschl. Update.
IOB läuft im Container, Node.js 14.18.2, NPM 6.14.15
 
Das Update wollte ich durchführen, da wieder (ständig) state_not_connected auftritt.

Grüße
Thomas

**Comment by chefkoch009** [comment]
Hi, ein gutes logging ist ja richtig und wichtig, aber 3700 Seiten ist etwas to much. 
Aktualisiere mal bitte deine Node-Version.

**Comment by Tomtheripper** [comment]
Hi chefkoch009,
das Update hat geholfen, Problem gelöst!!
Danke!
(Ich war der Meinung, dass die verfügbaren Updates im ioBroker angezeigt werden...., wieder dazu gelernt :-)   ) 

Beste Grüße
Thomas
