### ISSUE TITLE
2.0.19 Projekt - Import Fehler, ETS 6.0.6

### ISSUE THREAD

**Issue by Tomtheripper** [ioBroker/ioBroker.knx#286]
2.0.19
Node 18.16.0
NPM 9.5.1
v 6.5.7
ETS 6.0.6

Hi, ich schon wieder
(der mit dem Riesen-Projekt-File wegen den 2000 Universalobjekten des Timberwolf-Servers),

das aktuelle ETS-Projekt wird nicht importiert, der Ladebalken hängt auch nach 6 Stunden noch bei 90% fest.
Ich kann Dir gerne die Projekt-Datei per Mail zukommen lassen.

Gruß
Thomas

**Comment by chefkoch009** [comment]
Schick es mir mal bitte.

**Comment by Tomtheripper** [comment]
Hi,
ist die *.knxproj.-Datei angekommen? (Mail am 11.06.2023)

Ich habe nun ioBroker aktualisiert auf:
Node v20.3.0
NPM v9.6.7
KNX 2.0.20

und ETS auf 6.1.0.

Neue Projektdatei schick' ich wieder per Mail.

Auch hier bleibt der *knxproj-Datei-Import hängen bei ca. 90%.

Und wichtig: nach dem Import-Versuch: Adapter-Fehler  "nicht mit Dienst oder Gerät verbunden".
Den Fehler krieg' ich jetzt nicht mehr weg...

Gruß
Thomas

**Comment by Tomtheripper** [comment]
Fehler "nicht mit Dienst oder Gerät verbunden" tritt auch nach einer Neuinstallation des Adapters auf.
(...was ist denn jetzt wieder los...)

**Comment by chefkoch009** [comment]
Melde dich mal per Mail.

**Comment by Tomtheripper** [comment]
Klappt das mit den E-Mail-Antworten? Bekommst Du die?

**Comment by chefkoch009** [comment]
Bis jetzt nicht. Nur eine Mail ohne Anhang.

**Comment by Tomtheripper** [comment]
ok, Antwort auf die github-Mail klappt also nicht immer, sollten 3 Mails mit Anhang sein.
Dann schick' mir bitte 'ne Mail an 
knx@e-mail.de
Dann hab' ich die richtige...

**Comment by Tomtheripper** [comment]
Die Lizenzierung mit 2.0.21 funktioniert wieder!
Danke!

**Comment by Tomtheripper** [comment]
Hi chefkoch009, w
warum schließt Du diesen issue?
Der (ursprüngliche) Fehler ist nicht behoben, ich kann das Projekt noch nicht importieren...

**Comment by chefkoch009** [comment]
Oh...sry.... hatte nur die Lizenzierung im Blick. Was den Import angeht besteht der issue natürlich noch.
