### ISSUE TITLE
Update auf js-controller 5

### ISSUE THREAD

**Issue by mpl1337** [ioBroker/ioBroker.knx#287]
Hallo,

seit dem Update auf JS V5 wird die Lizenz nicht mehr erkannt

`
knx.0
--
  | 1522719	2023-06-14 21:11:24.180	error	This license is not valid for this iobroker host
  |  
  | knx.0
  | 1523091	2023-06-14 21:14:57.335	warn	No license found for knx. You can use 500DP for free or you can get a license on https://iobroker.net/accountLicenses !
`

**Comment by chefkoch009** [comment]
Hast du die Lizenz mal neu importiert?

**Comment by mpl1337** [comment]
ja eben nochmals:

```
<html>
<body>
<!--StartFragment-->

knx.0 | 1606559 | 2023-06-15 22:10:52.224 | error | This license is not valid for this iobroker host
-- | -- | -- | -- | --
knx.0 | 1606559 | 2023-06-15 22:10:52.224 | error | This license is not valid for this iobroker host

<!--EndFragment-->
</body>
</html>
```

**Comment by chefkoch009** [comment]
Ist in der neuen Version 2.0.20 behoben. Bitte prüfen.

**Comment by mpl1337** [comment]
mir wird kein Update angeboten Kann ich das händisch auslösen?

**Comment by chefkoch009** [comment]
Die Information über eine neue adapterversion wird m.E. nachts erzeugt. Also hast du die Info ca 1tag später. Du kannst es auch per console erzwingen mit
_npm i iobroker.knx@latest_

Heute sollte dir aber das Update angezeigt werden.

**Comment by Tomtheripper** [comment]
2.0.21 funktioniert nun bezüglich Lizenzierung!

Danke!
