### ISSUE TITLE
This license is not valid for this iobroker host

### ISSUE THREAD

**Issue by barni** [ioBroker/ioBroker.knx#288]
After updating iobroker I got following error:
This license is not valid for this iobroker host

I have updated the license again direct or via copy and paste both doesnt work

Remark Serial isnt changed.

**Comment by chefkoch009** [comment]
The problem is already solved in v2.0.20. 

Try this version.

**Comment by barni** [comment]
Hallo ich habe nun auf 2.0.20 ein update durchgeführt. Fehler "This license is not valid for this iobroker host" bleibt. Lizenz habe ich neu installiert iob neugestartet.
Node.js
v18.16.0
js controller 
5.0.4

Spiele ich ein Backup glaub 5.0.2 ein gehts wieder.

**Comment by Horgul123** [comment]
Hier auch noch mit 4er js controller:

 This license is not valid for this iobroker host

starting. Version 2.0.20 in /opt/iobroker/node_modules/iobroker.knx, node: v18.15.0, js-controller: 4.0.24

**Comment by chefkoch009** [comment]
Bitte mal 2.0.21 Testen.

**Comment by Horgul123** [comment]
Funktioniert :)  Danke!

**Comment by barni** [comment]
Geht perfekt danke

**Comment by chefkoch009** [comment]
Danke für die Rückmeldung. Problem gelöst. 

thanks for feedback. problem solved.
