### ISSUE TITLE
Probleme mit js-controller 5.0.12

### ISSUE THREAD

**Issue by JVF2** [ioBroker/ioBroker.knx#296]
Ich habe die neue Version vom "js-controller" installiert.
Alle Adapter - bis auf den KNX-Adapter - laufen problemlos.

Bereits durchgeführte Maßnahmen:
1. iobroker fix
2. Neustart des Servers
3. Neuinstallation des KNX-Adapters

Hier die Fehlermeldungen:
<html><body>

host.iobroker | 2023-09-16 11:07:47.500 | error | instance system.adapter.knx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]: Node.js v18.17.1
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]: }
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]:   ]
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.knx/knx.js'
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.knx/lib/utils.js',
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]:   requireStack: [
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-09-16 11:07:47.499 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19) {
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:960:12)
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/lib/utils.js:67:25)
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:121:18)
host.iobroker | 2023-09-16 11:07:47.498 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:922:27)
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.knx/knx.js
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.knx/lib/utils.js
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.iobroker | 2023-09-16 11:07:47.497 | error | Caught by controller[0]:   ^
host.iobroker | 2023-09-16 11:07:47.496 | error | Caught by controller[0]:   throw err;
host.iobroker | 2023-09-16 11:07:47.496 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1080
host.iobroker | 2023-09-16 11:07:45.450 | info | instance system.adapter.knx.0 started with pid 9964
host.iobroker | 2023-09-16 11:07:43.052 | info | instance system.adapter.knx.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobroker | 2023-09-16 11:07:43.052 | error | Caught by controller[0]: Node.js v18.17.1
host.iobroker | 2023-09-16 11:07:43.052 | error | Caught by controller[0]: }
host.iobroker | 2023-09-16 11:07:43.052 | error | Caught by controller[0]:   ]
host.iobroker | 2023-09-16 11:07:43.052 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.knx/knx.js'
host.iobroker | 2023-09-16 11:07:43.052 | error | Caught by controller[0]:     '/opt/iobroker/node_modules/iobroker.knx/lib/utils.js',
host.iobroker | 2023-09-16 11:07:43.052 | error | Caught by controller[0]:   requireStack: [
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19) {
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:960:12)
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:     at Module.load (node:internal/modules/cjs/loader:1119:32)
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:     at Module._compile (node:internal/modules/cjs/loader:1256:14)
host.iobroker | 2023-09-16 11:07:43.051 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/lib/utils.js:67:25)
host.iobroker | 2023-09-16 11:07:43.050 | error | Caught by controller[0]:     at require (node:internal/modules/cjs/helpers:121:18)
host.iobroker | 2023-09-16 11:07:43.050 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1143:19)
host.iobroker | 2023-09-16 11:07:43.050 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:922:27)
host.iobroker | 2023-09-16 11:07:43.050 | error | Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
host.iobroker | 2023-09-16 11:07:43.049 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.knx/knx.js
host.iobroker | 2023-09-16 11:07:43.049 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.knx/lib/utils.js
host.iobroker | 2023-09-16 11:07:43.049 | error | Caught by controller[0]: Require stack:
host.iobroker | 2023-09-16 11:07:43.049 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js'
host.iobroker | 2023-09-16 11:07:43.049 | error | Caught by controller[0]:   ^
host.iobroker | 2023-09-16 11:07:43.049 | error | Caught by controller[0]:   throw err;
host.iobroker | 2023-09-16 11:07:43.048 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1080

</body>
</html>

Ich freue mich auf eure Hilfe.

**Comment by foxriver76** [comment]
Und was ist die adapter version?

**Comment by JVF2** [comment]
2.0.17

**Comment by JVF2** [comment]
Danke!
Der kleine Hinweis hat mein Problem gelöst.
Unter "stable" wurde nur "2.0.17" angezeigt. Über "beta" konnte ich das notwendige Update installieren.

**Comment by foxriver76** [comment]
Updated stable version to 2.0.22
