### ISSUE TITLE
Keine Verbindung zu KNX Gateway nach Update

### ISSUE THREAD

**Issue by icegixxe** [ioBroker/ioBroker.knx#297]
Update des JS Controller auf 5.0.12 durchgeführt
Daher notwendiges Update des KNX Adapters auf 2.0.22
Seit diesem keine Verbindung mehr zum Gateway. Logauszug anbei. Vor dem Update des JS Controllers und des Adapters war alles in Ordnung. Keine Veränderung der KNX Hardware.
<img width="999" alt="log" src="https://github.com/ioBroker/ioBroker.knx/assets/128325313/150d2321-1fa7-4077-afc6-1838286eec34">

**Comment by mmcgn** [comment]
Hier ebenso. Konkrete Infos findet man leider nicht.

**Comment by ThomasBahn** [comment]
Plattform: Debian GNU/Linux 11 (bullseye)
Node.js: v18.18.0
NPM: 9.8.1

ioBroker
Used repository: beta
Adapter    "admin"        : 6.10.4   , installed 6.10.4
...
Controller "js-controller": 5.0.12   , installed 5.0.12
Adapter    "knx"          : 2.0.22   , installed 2.0.22
...

Bei mir läuft es. Also zumindest kein solcher Fehler, dass es prinzipiell nicht läuft.

**Comment by chefkoch009** [comment]
Bitte in den adaptereinstellungen den Port auf 3671 ändern….das ist ein Fehler, der wird in der kommenden Version raus sein.

**Comment by mmcgn** [comment]
> Bitte in den adaptereinstellungen den Port auf 3671 ändern….das ist ein Fehler, der wird in der kommenden Version raus sein.

Das war die Lösung, vielen Dank.

**Comment by icegixxe** [comment]
> Bitte in den adaptereinstellungen den Port auf 3671 ändern….das ist ein Fehler, der wird in der kommenden Version raus sein.

Auch bei mir die Lösung des Problems, danke für die schnelle Rückmeldung.
