### ISSUE TITLE
Probleme knxproj File zu laden

### ISSUE THREAD

**Issue by ufahrbach** [ioBroker/ioBroker.knx#3]
Habe eine ziemlich umfangreiche KNX-Installation und habe zunächst versucht das komplette Projekt zu laden. Scheiterte aber mit der Meldung Error: File " " not exists.
Habe dann versucht ein reduziertes Projekt zu laden, aber die gleiche Meldung.
Nachfolgend mal mein reduziertes knxproj-File:

[Fahrbach - reduziert.knxproj.zip](https://github.com/ioBroker/ioBroker.knx/files/680580/Fahrbach.-.reduziert.knxproj.zip)

**Comment by ufahrbach** [comment]
Ach ja, ich verwende die aktuelle 0.7.3 vom knx-Adapter und meine ETS ist die Version 4.1.6

**Comment by ekarak** [comment]
I'm also affected by the same error.

**Comment by ekarak** [comment]
*UPDATE*: I've managed to upload my knxproj file successfully with Chromium 55 on Linux. The aforementioned error still occurs with Firefox.

**Comment by ufahrbach** [comment]
I didn't think about changing the browser... And yep, now I managed to upload my reduced project file from above with Chrome on Windows and 50 States have been imported.
I've also tried my full project file and even that worked fine for me (more than 450 States have been imported).
Thanks so much! :-)

**Comment by chefkoch009** [comment]
Thanks for your feedback. I'm on Chrome because its fast and stable. Will try Firefox to reproduce the problem.

**Comment by ekarak** [comment]
I've had issues with file uploads API on Firefox in the past, that's why I tested with Chrome :)  I think you should add a warning/notice for the time being, and add the bugfix in your backlog... (not the highest priority I guess...)

**Comment by ufahrbach** [comment]
Just an update: Reduced file worked for me with some small errors, but that might be caused by my project where data types weren't set correctly.
But my full project was indeed importet, but the the knx process wasn't able to restart again. I'll now first set all data types correctly before importing this one again.

**Comment by ChrisHawk1** [comment]
Hallo chefkoch009,
vielen Dank erst einmal für die Mühe und den Dienst an den Nutzern dieses PlugIn gemacht zu haben und zu pflegen.
Da ich gelesen habe, dass Du noch an ein paar Problemen arbeitest, würde ich hier auch noch einwerfen wollen, dass ich auch Probleme habe mein Projektfile einzulesen. Man sieht, dass das PlugIn beim einlesen an Größe zunimmt, allerdings fällt die Größe dann wieder auf die übliche Größe zurück ohne Meldung. (es wird auch nichts eingefügt)
Das Fahrbach Projekt habe ich einmal eingelesen und versuchsweise durch ein paar Gruppenadressen von mir abgeändert. Diese werden nicht auf den Bus übertragen, nichts passiert. Im Log Fenster kann ich live mitlesen, allerdings kommt bei jeder Zeile die Meldung unbekannter Wert oder so ähnlich.
Außerdem habe ich noch eine Frage zu den Einstellungen der IP Schnittstelle, hier habe ich in der ETS kein Port vergeben und bei deinem PlugIn habe ich daher die 0 stehen, passt das so?! BTW ich habe ein ABB KNX IP Gateway.

Gruß Christoph

**Comment by chefkoch009** [comment]
Hallo Christoph,

momentan dauert der Einlesevorgang je nach Projektgrösse bis zu einer halben Minute ( leider noch ohne Benutzerfeedback). Nach erfolgreichem Einlesen erscheint eine Meldung, wie viele Objekte erkannt wurden. Anschliessend ist die Gruppenadressstruktur unter "Objekte" verfügbar. Gib die IP des GW's an und den Port 3671 und starte den Adapter neu.

VG
chefkoch009

**Comment by ChrisHawk1** [comment]
Hallo chefkoch009,

danke für die schnelle Rückmeldung. Leider hat sich nach dem vorgeschlagen Vorgehen nichts zum positiven verändert. Es wird auch nach 2 min warten nichts eingelesen und die Meldungen aus dem Log Fenster sehen nach wie vor so aus.

knx.0	2017-01-24 20:04:17.149	warn	knx.0 Value recieved on unknown GA : 1/2/0
knx.0	2017-01-24 20:04:15.356	warn	knx.0 Value recieved on unknown GA : 3/1/69
knx.0	2017-01-24 20:04:07.962	warn	knx.0 Value recieved on unknown GA : 1/2/0
knx.0	2017-01-24 20:04:06.233	warn	knx.0 Value recieved on unknown GA : 3/1/100
knx.0	2017-01-24 20:04:00.961	warn	knx.0 Value recieved on unknown GA : 1/1/71
knx.0	2017-01-24 20:04:00.943	warn	knx.0 Value recieved on unknown GA : 1/1/70
knx.0	2017-01-24 20:03:21.432	warn	stateChange: not ready
knx.0	2017-01-24 20:03:21.418	info	C:/ioBroker/node_modules/iobroker.js-controller
knx.0	2017-01-24 20:03:21.417	info	Connecting to knx GW: 192.168.0.3:3671 with phy. Adr: 1.1.251
knx.0	2017-01-24 20:03:21.409	info	starting. Version 0.7.3 in C:/ioBroker/node_modules/iobroker.knx, node: v6.9.4
host.Asus-i3-Laptop	2017-01-24 20:03:20.173	info	instance system.adapter.knx.0 started with pid 6440

**Comment by ChrisHawk1** [comment]
Bei dem Versuch einer geänderten Gruppenadresse von der oben aufgeführten Fahrbach Datei zu senden erscheint dies:
TypeError:	2017-01-24 20:08:38.319	error	at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
TypeError:	2017-01-24 20:08:38.319	error	at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
TypeError:	2017-01-24 20:08:38.319	error	at Manager. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
TypeError:	2017-01-24 20:08:38.319	error	at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:228:12)
TypeError:	2017-01-24 20:08:38.319	error	at Socket.onevent (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:270:10)
TypeError:	2017-01-24 20:08:38.319	error	at Socket.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
TypeError:	2017-01-24 20:08:38.319	error	at Socket. (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:45:30)
TypeError:	2017-01-24 20:08:38.319	error	at Object.change (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:2226:37)
TypeError:	2017-01-24 20:08:38.319	error	at Object.stateChange (C:\ioBroker\node_modules\iobroker.knx\knx.js:51:41)
TypeError:	2017-01-24 20:08:38.319	error	at convertDPTtype (C:\ioBroker\node_modules\iobroker.knx\knx.js:217:12)
TypeError:	2017-01-24 20:08:38.319	error	Cannot read property 'indexOf' of undefined
message	2017-01-24 20:08:38.319	error	knx.0.Schalten.Licht_schalten.EG_Durchgangslicht_schalten [object Object] Cannot read property 'indexOf' of undefined
TypeError:	2017-01-24 20:08:36.578	error	at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
TypeError:	2017-01-24 20:08:36.578	error	at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
TypeError:	2017-01-24 20:08:36.578	error	at Manager. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
TypeError:	2017-01-24 20:08:36.578	error	at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:228:12)
TypeError:	2017-01-24 20:08:36.578	error	at Socket.onevent (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:270:10)
TypeError:	2017-01-24 20:08:36.578	error	at Socket.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
TypeError:	2017-01-24 20:08:36.578	error	at Socket. (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:45:30)
TypeError:	2017-01-24 20:08:36.578	error	at Object.change (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:2226:37)
TypeError:	2017-01-24 20:08:36.578	error	at Object.stateChange (C:\ioBroker\node_modules\iobroker.knx\knx.js:51:41)
TypeError:	2017-01-24 20:08:36.578	error	at convertDPTtype (C:\ioBroker\node_modules\iobroker.knx\knx.js:217:12)
TypeError:	2017-01-24 20:08:36.578	error	Cannot read property 'indexOf' of undefined
message	2017-01-24 20:08:36.577	error	knx.0.Schalten.Licht_schalten.EG_Durchgangslicht_schalten [object Object] Cannot read property 'indexOf' of undefined
TypeError:	2017-01-24 20:08:30.987	error	at Manager.ondecoded (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\manager.js:332:8)
TypeError:	2017-01-24 20:08:30.987	error	at Manager.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
TypeError:	2017-01-24 20:08:30.987	error	at Manager. (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\component-bind\index.js:21:15)
TypeError:	2017-01-24 20:08:30.987	error	at Socket.onpacket (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:228:12)
TypeError:	2017-01-24 20:08:30.987	error	at Socket.onevent (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\lib\socket.js:270:10)
TypeError:	2017-01-24 20:08:30.987	error	at Socket.Emitter.emit (C:\ioBroker\node_modules\iobroker.js-controller\node_modules\socket.io-client\node_modules\component-emitter\index.js:133:20)
TypeError:	2017-01-24 20:08:30.987	error	at Socket. (C:\ioBroker\node_modules\iobroker.js-controller\lib\states\statesInMemClient.js:45:30)
TypeError:	2017-01-24 20:08:30.987	error	at Object.change (C:\ioBroker\node_modules\iobroker.js-controller\lib\adapter.js:2226:37)
TypeError:	2017-01-24 20:08:30.987	error	at Object.stateChange (C:\ioBroker\node_modules\iobroker.knx\knx.js:51:41)
TypeError:	2017-01-24 20:08:30.987	error	at convertDPTtype (C:\ioBroker\node_modules\iobroker.knx\knx.js:217:12)
TypeError:	2017-01-24 20:08:30.987	error	Cannot read property 'indexOf' of undefined
message	2017-01-24 20:08:30.982	error	knx.0.Schalten.Licht_schalten.EG_Durchgangslicht_schalten [object Object] Cannot read property 'indexOf' of undefined

**Comment by chefkoch009** [comment]
Es sieht so aus als ob in der ETS für die GA Schalten/Licht_Schalten/EG_Durchgangslicht_schalten kein DPT hinterlegt ist. Das sollte eigentlich DPT1.001 sein. Bitte weiterhin prüfen, ob das Paket knx installiert ist, also "npm install knx" durchgeführt wurde.

**Comment by ChrisHawk1** [comment]
Also wie gesagt, ich verwende das File von Fahrbach, da meines nicht funktioniert. Von einem KNX Paket weiß ich nichts, habe nur den Adapter von Dir installiert und eben noch einmal bei "installieren aus URL" nach knx gefiltert und dies auch installiert. Vielleicht meinst du ja das. 
Ich denke ich das ich es zur Zeit aufgebe das Ganze zum Laufen zu bringen. 
Vielen dank aber auf jeden Fall für deine Unterstützung.

**Comment by chefkoch009** [comment]
schade....hätte sonst per TV mal draufgeschaut.

**Comment by ChrisHawk1** [comment]
Das klingt gut, das Angebot würde ich annehmen. Ich schicke Dir eine email.

Gruß Christoph

**Comment by fl-berger** [comment]
Hallo Chefkoch009,

ich habe gestern auf einem Pi mit ioBroker zu spielen begonnen, und habe gleich versucht deinen KNX-Adapter zum Laufen zu bringen.

Konfig soweit unkompliziert, jedoch erhalte ich nach hochladen des KNX-Projekts ähnliche Fehlermeldungen wie  ChrisHawk1.

> [object Object] Cannot read property 'indexOf' of undefined

Datentypen sind soweit hinterlegt. Gibt es bei Christoph's Problem bereits Erkenntnisse?

Gruß,
Florian

**Comment by chefkoch009** [comment]
https://github.com/ioBroker/ioBroker.knx/issues/4

**Comment by perfSE** [comment]
Es gelingt mir nicht, mein knxproj zu laden. Ich bekomme überhaupt keine Meldung. Ich habe sowohl Chrome als Edge probiert. knxproj attached.
[F11.zip](https://github.com/ioBroker/ioBroker.knx/files/751781/F11.zip)

**Comment by ChrisHawk1** [comment]
Hallo, schaut nach Windows 10 aus. Dies scheint zur zeit nicht zu funktionieren.

**Comment by perfSE** [comment]
Ist Windows 10 ein Problem bei ETS/knxproj, oder Iobroker.knx?

**Comment by ChrisHawk1** [comment]
Bei mir habe ich es unter Windows 10 nicht zum laufen gebracht. Aber ich denke das daran gearbeitet wird.

**Comment by perfSE** [comment]
Heisst das, dass ein knxproj von ETS bei Windows 10 anders ist als ein knxproj von ETS bei Windows 7?

**Comment by ChrisHawk1** [comment]
Nein natürlich nicht, sorry wenn das missverstanden wurde. Ich hatte aber auch versucht IO Broker inkl. KNX zum Laufen zu bringen. Leider funktioniert dies aber noch nicht. Chefkoch hat sich freundlicherweise per Remote an meinem Win 10 Computer versucht, leider auch ohne Erfolg. Daher vermute ich/wir das es unter Win 10 nicht 100%ig läuft. Auf der Entwicklungsumgebung von chefkoch lies sich meine Projektdatei installieren!

**Comment by chefkoch009** [comment]
Hi @all

Die oben beschriebenen Fehler deuten auf fehlende Abhängigkeiten hin. Diese werden bei einem GIT checkout nicht aufgelöst! Ich werde die aktuelle Version heute/morgen Nacht finalisieren sodass sie am Montag als npm zur Verfügung steht. 

VG
chefkoch009

**Comment by perfSE** [comment]
Ich habe jetzt iobroker auch bei Debian installiert, und ich habe genau dasselbe Problem.

**Comment by perfSE** [comment]
I have these errors:
`TypeError:	2017-02-04 15:36:31.290	error	at closeTag (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7)
TypeError:	2017-02-04 15:36:31.290	error	at emitNode (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5)
TypeError:	2017-02-04 15:36:31.290	error	at emit (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35)
TypeError:	2017-02-04 15:36:31.290	error	at Object.onclosetag (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/lib/xml2js.js:447:26)
TypeError:	2017-02-04 15:36:31.290	error	at Parser.emit (events.js:169:7)
TypeError:	2017-02-04 15:36:31.290	error	at emitOne (events.js:77:13)
TypeError:	2017-02-04 15:36:31.290	error	at Parser. (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/lib/xml2js.js:489:18)
TypeError:	2017-02-04 15:36:31.290	error	at /usr/local/node_modules/iobroker.knx/lib/generateGAS.js:94:49
TypeError:	2017-02-04 15:36:31.290	error	at Array.map (native)
TypeError:	2017-02-04 15:36:31.290	error	at /usr/local/node_modules/iobroker.knx/lib/generateGAS.js:95:66
TypeError:	2017-02-04 15:36:31.290	error	Cannot read property '0' of undefined
message	2017-02-04 15:36:31.288	error	messagebox.system.adapter.knx.0 [object Object] Cannot read property '0' of undefined`

**Comment by chefkoch009** [comment]
Hallo perfSE, 

ich konnte Deine Datei problemlos importieren. (jetzt hab ich auch das "SE" in deinem Namen verstanden ;-) ). 

Ich biete auch Dir eine TV-Session zur Fehlersuche an. 

VG chefkoch009 


Von: "perfSE" <notifications@github.com> 
An: "ioBroker/ioBroker.knx" <ioBroker.knx@noreply.github.com> 
CC: "chefkoch009" <info@punktnetzwerk.net>, "Comment" <comment@noreply.github.com> 
Gesendet: Samstag, 4. Februar 2017 15:52:46 
Betreff: Re: [ioBroker/ioBroker.knx] Probleme knxproj File zu laden (#3) 



I have these errors: 
TypeError: 2017-02-04 15:36:31.290 error at closeTag (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/node_modules/sax/lib/sax.js:905:7) TypeError: 2017-02-04 15:36:31.290 error at emitNode (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/node_modules/sax/lib/sax.js:645:5) TypeError: 2017-02-04 15:36:31.290 error at emit (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/node_modules/sax/lib/sax.js:640:35) TypeError: 2017-02-04 15:36:31.290 error at Object.onclosetag (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/lib/xml2js.js:447:26) TypeError: 2017-02-04 15:36:31.290 error at Parser.emit (events.js:169:7) TypeError: 2017-02-04 15:36:31.290 error at emitOne (events.js:77:13) TypeError: 2017-02-04 15:36:31.290 error at Parser. (/usr/local/node_modules/iobroker.knx/node_modules/xml2js/lib/xml2js.js:489:18) TypeError: 2017-02-04 15:36:31.290 error at /usr/local/node_modules/iobroker.knx/lib/generateGAS.js:94:49 TypeError: 2017-02-04 15:36:31.290 error at Array.map (native) TypeError: 2017-02-04 15:36:31.290 error at /usr/local/node_modules/iobroker.knx/lib/generateGAS.js:95:66 TypeError: 2017-02-04 15:36:31.290 error Cannot read property '0' of undefined message 2017-02-04 15:36:31.288 error messagebox.system.adapter.knx.0 [object Object] Cannot read property '0' of undefined

**Comment by perfSE** [comment]
Ja, gerne - soll ich meine TV-angaben zu Dir schicken? Gibt es eine PM-Funktion hier?

**Comment by chefkoch009** [comment]
info@punktnetzwerk.net

**Comment by PerfectAnswer** [comment]
Hallo Chefkoch,
der Export aus ETS 5.06 und der anschließende Import in Dein Plugin läuft bei mir (um auch ein positives Feedback zu geben).  ;)

Ich hätte allerdings einen Wunsch 🏷 
Beim Importieren wird die Struktur sauber mit übertragen und ich finde unter dem knx.0 Objekt sauber aufgegliedert meine Struktur wieder. Vermutlich ist es ein Feature das lere Gruppenadressen nicht übertragen werden, aber ich hätte gerne die leeren Adressen um mit Hilfe der Visualisierung leere Gruppenadressen abzufeuern.
Darauf kann ich dann im Script reagieren und dann am Raspi GPIOs schalten, die wiederum z.B. das Garagentor öffnen oder anderen SchnickSchnack.
Diese Gruppenadressen verwende ich also über die Visualisierung als Trigger.

Habe ich da Chancen das mein Wunsch erhört wird?
Besten Gruß
Bernd

**Comment by chefkoch009** [comment]
Hallo Bernd,

In der Tat ignoriere ich die leeren GA's. Das hatte ich Mal gemacht um Projektoverhead zu vermeiden. In manchen Fällen macht es aber Sinn, diese mit zunehmen, wie du ja anschaulich formuliert hast. 

Für jeden Verbesserungsvorschlag bin ich sehr dankbar. Ich werde demnächst eine neue Version rausbringen. Gern nehme ich deinen Vorschlag an und Versuche dies wieder mit zu implementieren.

Viele Grüße
Kay

**Comment by PerfectAnswer** [comment]
wow!
Bei einer sauber aufgesetzten KNX Installation gibt es ja eigentlich keine leeren Gruppenadressen :)
Falls Du mal einen Tester brauchst, kann ich gerne eine neue Instanz anlegen und zur Verfügung stellen.

Besten Gruß
Bernd

**Comment by chefkoch009** [comment]
Du hast es richtig angemerkt....."bei einer sauber aufgesetzten KNX Installation". Aber hier treffen Praxis und Theorie knallhart aufeinander. Eins der Probleme sind unter anderem "historisch gewachsene Projekte". Ich bin in der glücklichen Lage auf eine handvoll akribischer Tester zurück greifen zu können.

http://forum.iobroker.net/viewtopic.php?f=36&t=3934

Hier hilft auch gern die Community weiter.

Viele Grüsse 
Kay

**Comment by chefkoch009** [comment]
Hallo Bernd,

kannst Du mir mal deine knxproj zukommen lassen, bzw. einen Screenshot der leeren Gruppenadressen?

VG
Kay

**Comment by PerfectAnswer** [comment]
Habe ich gerade versucht übers ioBroker forum, die Datei ist aber zu groß (11mb zip)
Ich schicke dir übers forum einen dropbox link zum downloaden.

**Comment by derandiunddasbo** [comment]
Ich habe ein ähnliches Fehlerbild, wie @perfSE, d.h. ich bekomme überhaupt keine (sichtbare) Reaktion nach Auswahl einer knxproj-Datei im Konfig-Fenster des knx-Adapters. Der Adapter oder ioBroker zeigen ebenfalls keine sichtbare Reaktion, d.h. auch der RAM-Verbrauch ändert sich nicht merklich, auch nicht nach mehreren Minuten.

Ich habe den Upload mit mehreren Browsern und Betriebssystemen ausprobiert (Win 10: Chrome & Edge, Win 7: Chrome & Firefox, Debian: Firefox), jedesmal mit dem gleichen Ergebnis. Auch mit den hier im Thread geposteten Projektdateien funktioniert es nicht.

ioBroker läuft bei mir in einem [Docker-Container](https://hub.docker.com/r/iobroker/iobroker/) unter Alpine Linux:

bash-4.3# uname -a
Linux DerHamster 3.10.102 #15152 SMP Fri Sep 1 11:15:09 CST 2017 x86_64 Linux

bash-4.3# cat /etc/*release
3.4.6
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.6
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"

bash-4.3# iobroker version
0.15.3
bash-4.3# iobroker version admin
1.6.11

Hat jemand eine Idee, woran es sonst noch liegen könnte?

**Comment by chefkoch009** [comment]
* loader refactored, RAM Problem solved with serial loading of objects.
