### ISSUE TITLE
Regression with KNX + history + admin 3.x: Objekte im KNX Adapter lassen sich nicht für history wählen

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.knx#30]
Fehler wurde in https://forum.iobroker.net/viewtopic.php?f=22&t=14734&p=154213#p154213 gemeldet. Objekte im KNX Adapter können für history nicht gewählt werden. Betrifft nicht alle Objekte, Objekt 'knx.0.info.connection' funktioniert zum Beispiel, andere nicht.  

Testsystem: jr-controller 1.4.2, KNX 1.0.12, admin 3.4.7, history 1.8.4

Beobachtungen:

- Alle Objekte im ersten Zweig von knx.0 (hier 'Dimmen') lassen sich wählen, alle der folgenden Zweige nicht mehr, außer Zweig 'info', da funktioniert es auch wieder.

![admin snip](https://user-images.githubusercontent.com/40452508/42124856-d2a2a942-7c6a-11e8-8d83-4052cc29b3ce.PNG)

- Der Dialog um ein Objekt für history auszuwählen öffnet sich immer, die Einstellungen können vorgenommen werden und der Dialog lässt sich mit 'Save' schließen, bei manchen Objekten wird er jedoch ergebnislos geschlossen. Bei den Objekten, bei denen es nicht funktioniert, zeigt der Dialog zum Aktivieren des Objektes für history nicht die 'default settings' des history adapters an.
- Fehler lässt sich mit Objekten aus anderen Adaptern nicht nachvollziehen.
- downgrade auf admin 2.0.9 löst das Problem.

**Comment by GermanBluefox** [comment]
Liegt an ":"
Vermutlich.

сб, 30 июн. 2018 г., 13:42 Breisgauer <notifications@github.com>:

**Comment by Apollon77** [comment]
Admin 3 ist ein fast komplette Rewrite.

@GermanBluefox Also Admin3 issue?!

@Breisgauer Im Screenshot sehe ich auch Objekte ohne Doppelpunkt. Die gehen korrekt ?!

**Comment by GermanBluefox** [comment]
Bitte Browser Konsole aufmachen und Fehler hier berichten.

**Comment by GermanBluefox** [comment]
Und Ja, Admin2 und Admin3 sind zwei unterschiedliche Programme

**Comment by chefkoch009** [comment]
Kein Feedback vom Reporter ?!? Also doch kein Problem?

**Comment by Breisgauer** [comment]
doch, doch, noch Problem. Ich habe Doppelpunkte entfernt und noch mal getestet.

Der Doppelpunkt spielt keine Rolle, Objekte ohne Doppelpunkt gehen nicht.
Siehe Screenshot. Unter '/Dimmen/OG' ist ein Objekt erfolgreich für history.0 gewählt, ab /Heizung...' geht nichts mehr.

![capture](https://user-images.githubusercontent.com/40452508/42219790-63eb5eee-7ecd-11e8-8b0e-b885880f96e2.PNG)

**Comment by Breisgauer** [comment]
@GermanBluefox, fehler habe ich an den drei beteiligten Komponenten berichtet, inkl. Verweise. Wo sollte ich noch berichten?

**Comment by Apollon77** [comment]
Ok then I would suspect the "," in the "Heizung,_Lüftung" ...

**Comment by Apollon77** [comment]
Kannst Du bitte auch mal schauen ob die Browser-JavaScript-Konsole Fehler anzeigt?

**Comment by Breisgauer** [comment]
Kein Fehler in der Konsole.
Ich habe bei ein Objekt zu history.0 hinzugefügt, bei dem es funiktioniert. Dann eines, bei dem es nicht geht. Bei letzterem keine Einträge in den Logs. 
![debug_l1](https://user-images.githubusercontent.com/40452508/42220844-775f9f6e-7ed0-11e8-92c9-afb0454b8ccc.PNG)

**Comment by Apollon77** [comment]
Gemeint ist wirklich die JavaScript-Konsole deines Browsers und nicht die Log-Ansicht von iobroker :-)

Je nach Browser meistens was mit "Web-Developer" menü oder so

**Comment by Breisgauer** [comment]
ich habe chrome/dev tools genommen und in die Konsole geschaut. dann einmal ein Objekt zu history.0 hinzugefügt, bei dem es funktioniert, und eimal bei dem es nicht funktioniert.

Wo es fehlschlägt, sehe ich als Unterschied folgende beide Meldungen:

> adminCustoms.js:751 Null object: _Lüftung.DG.DG_-Bad-_Heizung_Betriebsart_Komfort
Customs.init @ adminCustoms.js:751
(anonymous) @ admin.js:1581
y.navigateCheckDialog @ admin.js:1460
y.navigateDo @ admin.js:1496
window.onhashchange @ admin.js:769
hashchange (async)
y.navigate @ admin.js:1486
click @ adminObjects.js:488
(anonymous) @ selectID.js:2431
dispatch @ jquery-3.2.1.min.js:3
m.handle @ jquery-3.2.1.min.js:3

> adminCustoms.js:751` Null object: knx.0.Heizung
Customs.init @ adminCustoms.js:751
(anonymous) @ admin.js:1581
y.navigateCheckDialog @ admin.js:1460
y.navigateDo @ admin.js:1496
window.onhashchange @ admin.js:769
hashchange (async)
y.navigate @ admin.js:1486
click @ adminObjects.js:488
(anonymous) @ selectID.js:2431
dispatch @ jquery-3.2.1.min.js:3
m.handle @ jquery-3.2.1.min.js:3

**Comment by Apollon77** [comment]
Kannst Du ma lversuchen das "," aus dem "Heizung,_Lüftung" rauszubekommen? Geht es dann? Dann liegt es am Komma !

**Comment by Breisgauer** [comment]
Bestätigt, das Komma in den GA Namen verursacht das Problem.
Wie geschrieben, mit ioBroker.admin 2.0.9 tritt das Problem nicht auf, mit ioBroker.admin 3.x schon.
Ein Komma in GA Namen steht meines Wissens nicht im Konflikt mit KNX Richtlinien, insofern gehe ich davon aus, dass viele KNX Projekte ein "Komma" in den Namen haben. Daher wäre es schön, wenn das Problem gefixt werden könnte.

**Comment by chefkoch009** [comment]
Vielen Dank für die Verifikation. Du hast auch Recht, das ein Komma nicht gegen die Richtlinien verstösst. Jedoch sind Sonderzeichen in KNX Projekten eher die Seltenheit. Aus diesem Grund ist Dir dankenswerter Weise das Problem aufgefallen. Natürlich werde ich dies in der nächsten Version fixen.

**Comment by Breisgauer** [comment]
VIELEN DANK, chefkoch009!
Bin gespannt, in welcher Komponente gefixt werden muss, KNX oder admin oder history.

**Comment by Apollon77** [comment]
Basierend auf https://github.com/ioBroker/ioBroker.js-controller/issues/198 muss der Fix im KNX Adapter stattfinden weil sonst ab js-controller 1.5.0 Probleme kommen werden

**Comment by chefkoch009** [comment]
Habe soeben die neue Version online gestellt.

**Comment by Breisgauer** [comment]
Getestet. auf meinem Testsystem: Debian 9.4 in Hyper-V; node 8.11.3; npm 6.1.0; js-controller 1.4.2; admin 3.4.7; KNX 1.0.13; History 1.8.5
Funktioniert! Herzlichen Dank!
