### ISSUE TITLE
DPT 16.001 wrong encoding

### ISSUE THREAD

**Issue by trollvottel** [ioBroker/ioBroker.knx#302]
DPT 16.001 (ISO 8859-1) has wrong encoding. Sending "Restmüll" through adapter results in wrong encoded string on the bus:
![grafik](https://github.com/ioBroker/ioBroker.knx/assets/9528457/a104b00c-0cca-44a0-9709-217f75fb1bd9)

Sending "Restmüll" through ETS works fine, KNX devices display it correct (DPT supports umlauts), but the adapter handles it wrong either:
![grafik](https://github.com/ioBroker/ioBroker.knx/assets/9528457/1f9d94c8-a3a8-468a-8ef4-ae50612c7597)

**Comment by trollvottel** [comment]
![grafik](https://github.com/ioBroker/ioBroker.knx/assets/9528457/bda68710-47eb-437d-a667-379926ebc92f)

**Comment by chefkoch009** [comment]
this is fixed in next version

**Comment by trollvottel** [comment]
May I ask which version version will be "next"?

**Comment by trollvottel** [comment]
I can confirm fixed in 2.0.27 (beta)
