### ISSUE TITLE
keine Verbindung zum IP-Interface

### ISSUE THREAD

**Issue by Sandzeroo** [ioBroker/ioBroker.knx#305]
Hallo,

ich habe soeben versucht den Adapter mit meinem KNX IP-Interface zu verbinden. Klappt aber irgendwie nicht.

Der Open-KNX Adapter verbindet sich ohne Probleme. Nun habe ich diesen deinstalliert um auszuschließen, das der irgendwie Probleme macht. Trotzdem ohne Erfolg.

![Adapter-KNX](https://github.com/ioBroker/ioBroker.knx/assets/155386961/2fea26e0-5819-450a-955c-f3b9c610183c)

![Log-KNX](https://github.com/ioBroker/ioBroker.knx/assets/155386961/9b5af9c2-b28b-409a-b555-c4d892b0dc94)

Vielleicht sagt jemanden das Log-File mehr als mir :D

Beste Grüße
Hari

**Comment by chefkoch009** [comment]
Die physikalische Adresse in der Adapter config muss eine freie Adresse sein, nicht die des knx-LAN Gateway. Prüfe bitte auch, wie viele Verbindungen dein Gateway zulässt und das mind. 1frei ist.

**Comment by Sandzeroo** [comment]
Also die physikalische Adresse habe ich umgeändert auf eine freie Adresse. Es kommt weiterhin zu keiner Verbindung.

Benutze den IP-Viewer N151 von Siemens. Sollte eigentlich funktioniern mit dem.

Hier ein Screenshot vom Open-KNX der eine Verbindung hat
![Objekt](https://github.com/ioBroker/ioBroker.knx/assets/155386961/a3359cc1-2885-4fd2-8cb6-df8392291bd4)

**Comment by chefkoch009** [comment]
Es sieht so aus, als ob deine GW nichts mit einem description_request anfangen kann.....könntest Du mir bitte einen vollständigen Consolen log zur Verfügung stellen? Bei Fragen, schreib mir gern eine Mail.

**Comment by Sandzeroo** [comment]
Das Problem war ziemlich einfach und schnell gelöst dank chefkoch009. Ein großes Dankeschön!

Eine Ziffer in der IP-Adresse wurde ausgebessert und siehe da, es funktioniert fantastisch! Wie man so schön sagt, man sieht oft den Wald nicht vor lauter Bäumen.

Beste Grüße Hari
