### ISSUE TITLE
Probleme im GA Tool mit Aufklappen von Hierarchiestufe

### ISSUE THREAD

**Issue by starauschek** [ioBroker/ioBroker.knx#309]
Hallo,

ich möchte über das GA Tool eine Adresse zu einem Objekt aus dem WLED Adapter hinzufügen, kann aber die relevanten Hierarchiestufe im Browser nicht öffnen. Sie lässt sich nicht aufklappen, das Symbol dafür fehlt. 
Über ioBroker Browser für Objekte kann ich ohne Probleme darauf zugreifen und auch die enthaltenen Objekte modifizieren.

Das Objekt hieße wie folgt: led.0.308398a26128.seg.0.col.0_HEX

Vielleicht zu viele Hierarchie-Ebenen?

Gibt es die Möglichkeit, die Konfiguration irgendwo manuell zu setzen?

<img width="1329" alt="image" src="https://github.com/ioBroker/ioBroker.knx/assets/149327074/f8e58be3-305b-4f1e-9e9f-46d9bd730bb8">

<img width="1536" alt="image" src="https://github.com/ioBroker/ioBroker.knx/assets/149327074/5e7e7264-80db-41ef-adb8-065742778fc0">

**Comment by chefkoch009** [comment]
konnte ich nachstellen und muss es prüfen.

**Comment by starauschek** [comment]
Hallo, kannst du schon absehen wann es gelöst sein wird?
VG

**Comment by chefkoch009** [comment]
Das ist schon gelöst aber noch nicht im stable. Das müsstest du mit der Beta testen.
