### ISSUE TITLE
Úpload neuer KNX Projektdatei - Importstate

### ISSUE THREAD

**Issue by felkep** [ioBroker/ioBroker.knx#312]
Guten Abend ich wollte mal wieder die KNX Datei mit dem IO Broker abgleichen. Leider kommt seit neuesten immer die Fehlermeldung:
Iportstate
Import teilweise oder vollständig mit Fehler fehlgeschlagen: Projectimport with this ETS Version not yet possible.

Ich habe aktuell die ETS 6.2.2 installiert. Ab wann wird diese Version voraussichtlich wieder unterstütz?

Vielen Dank!

VG Pascale

**Comment by chefkoch009** [comment]
Also es gibt aktuell keine Version 6.2.2. Die letzte Version ist 6.2.1 und diese wird unterstützt.

**Comment by chefkoch009** [comment]
Naja..."seit neuesten" kann ja erst ab heute sein, denn der Release für die 6.2.2 war ja heute am 2.Mai. Macht aber nix, hab die neue Version schon fertig und bereitgestellt. Sollte also spätestens morgen bei den Updates aus dem Beta-Repo angezeigt werden.

**Comment by felkep** [comment]
Perfekt, vielen Dank hat geklappt!Dass ich so ein Timing mit dem Update hatte war mir nicht klar.VG PascaleAm 02.05.2024 um 23:27 schrieb chefkoch009 ***@***.***>:﻿
Naja..."seit neuesten" kann ja erst ab heute sein, denn der Release für die 6.2.2 war ja heute am 2.Mai. Macht aber nix, hab die neue Version schon fertig und bereitgestellt. Sollte also spätestens morgen bei den Updates aus dem Beta-Repo angezeigt werden.

**Comment by chefkoch009** [comment]
Danke für die Rückmeldung.

fixed and confirmed
