### ISSUE TITLE
Is this adapter still maintained? - Please fix LICENSE information -  Review / merge PR.

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.knx#315]
@chefkoch009

Please let us know if this adapter is stimm maintained. I assume it is :-) - but I am missing any reaction for PR #313 and the corresponding PR at ioBroker.repositories.

**Fixing the license information is required for updating stable repository.** A PR exists (https://github.com/ioBroker/ioBroker.knx/pull/313) but is neither merged nor commented. Multiple contact tries at ioBroker repositories die not result in an reaction. See https://github.com/ioBroker/ioBroker.repositories/pull/3564

Please respond.

**Comment by chefkoch009** [comment]
Is fixed.

**Comment by mcm1957** [comment]
THANKS a lot !
