### ISSUE TITLE
STATE_NOT_CONNECTED : Stop connection

### ISSUE THREAD

**Issue by Horgul123** [ioBroker/ioBroker.knx#317]
Adapter Version 2.0.28
js-controller 6.0.8
Node: 20.15.1

Jetzt hat es mich auch erwischt und ich habe die Verbindung zum Bus großteils verloren. Vereinzelt geht etwas, aber nicht zuverlässig.

`

knx.0 | 2024-07-18 22:03:03.667 | info | Connected - local UDP Server listening on 192.168.0.251:37088
-- | -- | -- | --
knx.0 | 2024-07-18 22:03:03.667 | info | Event : UDP - listening
knx.0 | 2024-07-18 22:03:03.666 | info | Using UDP with local IP: 192.168.0.251
knx.0 | 2024-07-18 22:03:01.668 | info | STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2024-07-18 22:03:01.667 | info | STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2024-07-18 22:03:01.666 | info | STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2024-07-18 22:01:00.640 | info | READ : received unknown GA 6/1/5
knx.0 | 2024-07-18 22:00:33.666 | info | Connected - local UDP Server listening on 192.168.0.251:52397
knx.0 | 2024-07-18 22:00:33.666 | info | Event : UDP - listening
knx.0 | 2024-07-18 22:00:33.666 | info | Using UDP with local IP: 192.168.0.251
knx.0 | 2024-07-18 22:00:31.667 | info | STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2024-07-18 22:00:31.667 | info | STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2024-07-18 22:00:31.666 | info | STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).

`

Ich habe ähnliche Issues gesehen, aber keine Lösung entdeckt. 
Eine Firewall habe ich nicht im Einsatz, Ping von iobroker auf das IP Interface geht, Habe weder was am Adapter noch am IP Interface geändert. Der Fehler trat heute das erste Mal auf, hab nicht bewusst etwas seit gestern geändert.

**Comment by Horgul123** [comment]
Update:
Ich habe mal eine Proxmox Sicherung von vor 5 Tagen eingespielt, da lief alles noch.
Leider habe ich da das gleiche Problem. Kann also ein Softwareproblem eher ausschließen vermute ich.

Ich werde heute nochmal das Netzwerk "zerlegen". Ich vermute, da werden die UDP Pakete nicht sauber geroutet.

**Comment by chefkoch009** [comment]
Schau mal bitte nach, ob UDP Richtung Iobroker funktioniert. Weiterhin ob deine Firewall/Router die Verbindungen offen hält.

**Comment by Horgul123** [comment]
@chefkoch009 wie ich bei der Fritzbox das sehe weiß ich leider nicht. War aber in der Vergangenheit kein Thema.

UDP Test:

iobroker Server:
# The primary network interface
# allow-hotplug ens18
# iface ens18 inet dhcp

auto ens18
iface ens18  inet static
 address 192.168.0.251
 netmask 255.255.0.0
 gateway 192.168.0.1
 dns-domain fritz.box
 dns-nameservers 192.168.0.1


Wenn ich mit nc einen UDP Listener auf dem iobroker Server öffne kann ich in einem anderen Fenster UDP Pakete an den Port schicken.
Ich versuche:< auf dem iobroker Server (192.168.0.251)
netstat | grep udp
-> keine Ausgabe
nc -u -l -p 9999
-> startet
aus einem anderen Fenster:
nc -u 192.168.0.217 9999
-> Wartet auf Eingabe
"test"
-> wird im Fenster des listner angezeigt, kann weitere Eingaben machen die ankommen
Breche ich das Eingabefenster mit CTRL-C ab und starte das senden erneut kann ich etwas eingeben, das kommt aber nicht mehr an und er springt zur Eingabeaufforderung

Von einem anderen Server im Netzerk (da läuft EVCC, 192.168.1.33):
nc -u 192.168.0.217 9999
-> Wartet auf Eingabe
"test"
-> kommt an.

Meine Server laufen alle unter Proxmox. iobroker und EVCC auf verschiedener HArdware, beide Hardwareserver hängen am gleichen Switch.

MDT IP Interface 
DHCP: Off
IP 192.168.0.112
Subnet: 255.255.0.0
Gateway 192.168.0.1
DNS: 192.168.0.1
http Port 8080

UDP vom Windows Laptop (hängt via WLAN im Netz)
Testpaket kommt via UDP an


Sieht jetzt erstmal so aus, als ob UDP durchkommt, oder?

**Comment by chefkoch009** [comment]
Du hast aber eine ziemlich große Maske gewählt. Normal wäre 255.255.255.0 für den heimanwender.

**Comment by Horgul123** [comment]
naja... bei  192.168er Netz darf man 255.255.0.0 wählen.
Mir haben die 192.168.0.x nicht mehr gereicht. Und als ich die eh ändern musste bin ich von 255.255.255.0 auf 255.255.0.0 gegangen um meine Ruhe zu haben.
Die Maske habe ich aber schon lange. War bisher kein Thema.

**Comment by Horgul123** [comment]
So... Weiterer Test:
Ich habe auf meinem 2. Server einen neuen Proxmox Container mit Debian installiert, dort iobroker und den KNX Adapter. Sonst nix, alles gelassen, wie es installiert wurde. Alles aus dem stable.
Folgende Daten:
KNX Adapter 2.0.28
js-controller 5.0.19
node.js 20.15.1

Leider exakt das gleiche Verhalten.

**Comment by Horgul123** [comment]
Hab jetzt nochmal die Firmware des IP Interfaces aktualisiert und das neu programmiert....  Dann hat es die ersten paar Minuten geklappt, dann wieder das gleiche Verhalten :(

**Comment by chefkoch009** [comment]
Mit wieviel Geräten (ETS, giraHS, x1,....) verbindest du dich auf das Gateway? M.E. sind nur 4verbindungen zulässig. Prüfe mal in den adaptereinstellungen 3671 als Port eingetragen ist.

**Comment by Horgul123** [comment]
Nur mit dem  KNX Adapter und der ETS.
Hab es auch probiert als nur der KNX Adapter angemeldet war.

![Screenshot_20240720_221100_Chrome](https://github.com/user-attachments/assets/5037d6e4-9ba6-4f0d-9f5b-e6e6d93d4c6e)


Einstellungen sollten stimmen

**Comment by Horgul123** [comment]
Hab jetzt nochmal das Netz isoliert:
Anderer Switch (ganz anderes Modell)
nur Ip Interface, Proxmox Server 
ein Laptop
drangehängt.

Gleiches Problem. Zumindest kann ich jetzt alle anderen Störungen im Netzwerk ausschließen

**Comment by Horgul123** [comment]
@chefkoch009 

Problem (anscheinend) gelöst:
Nachdem ich wirklich alles andere ausgeschlossen habe (hab sogar ne neue IP Schnittstelle geholt), habe ich mal nur die Busspannungsversorgung und das Interface angeschlossen.
Kein Fehler mehr!
Hab dann nach und nach die einzelnen Bereiche vom KNX Bus wieder angeschlossen.
Weiterhin kein Fehler mehr.

Ich versteh es nicht. Die Busspannungsversorgung hatte ich auch mehrfach abgeschaltet, das war also nicht das Problem. Irgendwas KNX Seitig muss die IP Interfaces gestört haben..
