### ISSUE TITLE
Objekte lassen sich nicht mehr anzeigen

### ISSUE THREAD

**Issue by mpl1337** [ioBroker/ioBroker.knx#318]
Hallo,

habe eben mein KNX Projekt neu importiert (wegen Erweiterung) und nun lässt sich der Objekte Reiter nicht mehr öffnen.

wenige Klicks davor ging es noch.

Log sagt 1001 Objekte, Adapter sagt 1000 Objekte. Wer kann nicht zählen? Fehler kommt genau seit dem Import.

![Screenshot 2024-07-20 233035](https://github.com/user-attachments/assets/3c616738-a78e-4985-9ca2-2cfc4ccdb1bb)
![Screenshot 2024-07-20 233148](https://github.com/user-attachments/assets/b06ff5bb-e86f-4a1b-b74b-45c897cf4454)
![Screenshot 2024-07-20 233302](https://github.com/user-attachments/assets/9d65be39-4ac6-48f5-a41f-b899f7496552)
![Screenshot 2024-07-20 233708](https://github.com/user-attachments/assets/4d5096e1-7323-4d6c-beb3-9d7575d6d8d1)

Ich kann jetzt mein KNX in der Visu nicht benutzen bis ich Hilfe bekomme,.

**Comment by chefkoch009** [comment]
Der Adapter muss über npm installiert werden. Bitte prüfen. Dann den objektbaum knx sicherheitshalber einmal in eine Datei exportieren und den objektbaum löschen. Anschließend neu importieren.

**Comment by mpl1337** [comment]
Ich soll den Adapter deinstallieren und dann per Npm neu installieren? Ich kann den Objektbaum erst garnicht öffnen... Wie kann ich exportieren?

**Comment by chefkoch009** [comment]
Auf der linken Seite unter Instanzen steht "Objekte", dort steht knx.0. Diesen teilbaum exportierst du.

**Comment by mpl1337** [comment]
Sobald ich auf "Objekte" klicke stürzt es ab. 

![Screenshot 2024-07-20 233148](https://github.com/user-attachments/assets/f5a1aade-5c1b-49bd-ab47-706be3b35524)
![Screenshot 2024-07-20 233302](https://github.com/user-attachments/assets/158b93c5-2662-464f-8e86-9795e99d9c40)

**Comment by mpl1337** [comment]
![image](https://github.com/user-attachments/assets/d8180479-aea5-4504-b738-122767453a5a)

**Comment by mpl1337** [comment]
reboot und iob upload all bereits durchgeführt

**Comment by chefkoch009** [comment]
Das ist kein Problem vom knxAdapter. Kannst du mal "iob u all" versuchen über die Shell.

**Comment by mpl1337** [comment]
habe ich...

ich habe gestern Abend mehrmals ETS Projekte importiert und da ging alles. Als ich das 1000DP Limit überschritten hatte ging das los. Jetzt habe ich zu viele DPs und kann diese nicht löschen und kann deshalb auch den KNX Adapter nicht nutzen.

**Comment by chefkoch009** [comment]
Hast du mal einen anderen Browser versucht? Sonst Ticket erstellen für den admin.

**Comment by mpl1337** [comment]
Habe ein Backup von vor 3 Tagen eingespielt. Geht wieder.
