### ISSUE TITLE
Verknüpfung von STATUS Objekt und AKTIONs-Objekten nicht korrekt

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.knx#32]
Ich habe einen Dimmer und die Objekte passend zu https://github.com/ioBroker/ioBroker.knx/ angelegt, so dass Schalt- und Statusaddressen entsprechend identifiziert werden können

Es gibt 5 GAs/KOs, die für Dimmen und Schalten des Dimmerkanals zuständig sind, zwei davon sind STATUS Objekte. 

1. **Schalten AKTION**: Schaltet EIN/AUS
2. **Schalten STATUS:** Gibt den Schaltstatus auf dem KNX Bus aus.
3. **Dimmen ABSOLUT:** Erhöht/verringert den Dimmwert
4. **Dimmen RELATIV:** Setzt einen Dimmwert
5. **Dimmen STATUS:** Gibt den aktuellen/geänderten Dimmwert auf dem KNX Bus aus

So sieht das in ioBroker aus:
![dimmer objects](https://user-images.githubusercontent.com/40452508/42620712-03f77e96-85bc-11e8-88cb-2cc0b2cf7dfd.PNG)
Unten zeige ich die RAW Werte.

Beim Dimmen wird eine Änderung von "Dimmen STATUS" (5.) mit dem falschen Aktionsobjekt verbunden, mit (4.) statt mit (3.)
Wie kann das korrigiert werden?

**Schalten AKTION**: Schaltet EIN/AUS

> {
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1531377225145,
  "common": {
    "name": "DG -Bad- Deckenauslass SCHALTEN",
    "type": "boolean",
    "role": "level",
    "min": 0,
    "max": 1,
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "1/4/50",
    "addressRefId": "P-08AB-0_GA-179",
    "statusGARefId": "P-08AB-0_GA-918",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Schalten.DG.DG_-Bad-_Deckenauslass_SCHALTEN",
  "type": "state"
}

**Schalten STATUS:** Gibt den Schaltstatus auf dem KNX Bus aus.

> {
  "_id": "knx.0.Schalten.DG.DG_-Bad-_Deckenauslass_SCHALTEN_STATUS",
  "type": "state",
  "common": {
    "name": "DG -Bad- Deckenauslass SCHALTEN STATUS",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator",
    "min": 0,
    "max": 1
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "1/4/51",
    "addressRefId": "P-08AB-0_GA-918",
    "statusGARefId": "",
    "actGARefId": "P-08AB-0_GA-179"
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1531377225149,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Dimmen ABSOLUT:** Erhöht/verringert den Dimmwert

> {
  "_id": "knx.0.Dimmen.DG.DG_-Bad-_Deckenauslass_DIMMEN_ABSOLUT",
  "type": "state",
  "common": {
    "name": "DG -Bad- Deckenauslass DIMMEN ABSOLUT",
    "type": "number",
    "read": false,
    "write": true,
    "role": "level.dimmer",
    "min": 0,
    "max": 100
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "2/4/52",
    "addressRefId": "P-08AB-0_GA-182",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1531377226373,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Dimmen RELATIV:** Setzt einen Dimmwert

> {
  "_id": "knx.0.Dimmen.DG.DG_-Bad-_Deckenauslass_DIMMEN_RELATIV",
  "type": "state",
  "common": {
    "name": "DG -Bad- Deckenauslass DIMMEN RELATIV",
    "type": "",
    "read": false,
    "write": true,
    "role": "level",
    "min": 0,
    "max": 1
  },
  "native": {
    "dpt": "DPT3.007",
    "address": "2/4/51",
    "addressRefId": "P-08AB-0_GA-181",
    "statusGARefId": "P-08AB-0_GA-1063",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1531377226367,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Dimmen STATUS:** Gibt den aktuellen/geänderten Dimmwert auf dem KNX Bus aus

> {
  "_id": "knx.0.Dimmen.DG.DG_-Bad-_Deckenauslass_DIMMEN_STATUS",
  "type": "state",
  "common": {
    "name": "DG -Bad- Deckenauslass DIMMEN STATUS",
    "type": "number",
    "read": true,
    "write": false,
    "role": "indicator.dimmer",
    "min": 0,
    "max": 100
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "2/4/53",
    "addressRefId": "P-08AB-0_GA-1063",
    "statusGARefId": "",
    "actGARefId": "P-08AB-0_GA-181"
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1531377226379,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by TheBigS1981** [comment]
@Breisgauer Ich kann Deinen Fehler bestätigen. Bei mir ist das Verhalten absolut identisch. Auch ich habe fünf GAs für eine Lampe mit Dimmer (MDT Dimmaktor).

**Comment by thomasklosinsky** [comment]
Hm... gibts hierzu schon News???
Ich bin dabei ein Projekt einzurichten und würde auf selbiges Problem stoßen...

**Comment by Breisgauer** [comment]
Ich habe schon lange nichts mehr gehört. Chefkoch ist "verschwunden", wahrscheinlich Urlaub. Und andere scheinen den Adapter nicht zu pflegen. Source Code ist auch nicht offen.
Im Moment mache ich auch nichts mehr mit ioBroker, da ich nach jedem re-import eines KNX Projektes alle Objekte händisch nachpflegen müsste.

**Comment by Breisgauer** [comment]
@chefkoch009, Danke! Das wird es zuverlässiger machen. Du hast viel Arbeit in die automatische Erkennung gesteckt und die deckt auch viel ab. Aber der KNX Zoo ist so groß, da wird die manuelle Zuordnung zuverlässiger sein, und Dir weniger Arbeit im Adapter machen.

Bzgl. Source Code hatte ich in [https://forum.iobroker.net/viewtopic.php?f=36&t=3934&p=152318#p152318](url) nur gesehen, dass keine Fragen zur Entscheidung gewünscht werden. Aber das ist ein anderes Issue -> Issue #36.

**Comment by thomasklosinsky** [comment]
@chefkoch009 gibt es einen groben Zeitplan für die nächsten Versionen?

**Comment by Breisgauer** [comment]
Version 1.0.19 getestet. Auch hier klappt die Zuordnung von STATUS und AKTION nicht. 

Eine GA für AKTION: DG -Büro- Deckenauslass EIN/AUS
Eine GA für STATUS: DG -Büro- Deckenauslass STATUS

Eine Zuordnung der GAs findet nicht statt. 

Den GA für AKTION in "DG -Büro- Deckenauslass EIN-AUS" umzubenennen ändert nichts.

**Comment by Breisgauer** [comment]
Ich habe noch mal die Umbenennung der GAs getestet: 

GA für AKTION: DG -Büro- Deckenauslass SCHALTEN
GA für STATUS: DG -Büro- Deckenauslass SCHALTEN STATUS

Damit funktioniert die automatische Zuordnung.

Somit schließe ich dieses Issue.

Da es jedoch schwer zumutbar ist, bestehende Projekte komplett zu überarbeiten und die GAs anzupassen, möchte ich die Wichtigkeit von Issue #33 noch mal unterstreichen.

**Comment by chefkoch009** [comment]
Siehe dazu im README:

> Vermeidung von Problemen
... einheitliche Beschriftung der GA-Namen (z.B "EG Wohnen Decke Licht **schalten**" und "EG Wohnen Decke Licht **schalten status**" )

In Deinem Fall:
DG -Büro- Deckenauslass EIN/AUS
DG -Büro- Deckenauslass EIN/AUS Status

Um das mal zu erklären:
1. Fall Schaltaktor: 
=>DG -Büro- Deckenauslass EIN/AUS
=>DG -Büro- Deckenauslass STATUS
... also kein Problem

2. Fall Dimmaktor
=>DG -Büro- Deckenauslass EIN/AUS
=>DG -Büro- Deckenauslass Dimmen Wert
=>DG -Büro- Deckenauslass Dimmen Schritt
=>DG -Büro- Deckenauslass STATUS <=== Was repräsentiert nun dieser Status?

3. Fall Jalousieaktor
siehe 2.Fall

4. Fall Heizaktor
siehe 2.Fall
...

**Comment by chefkoch009** [comment]
bzw.
=>DG -Büro- Deckenauslass EIN/AUS
=>DG -Büro- Deckenauslass EIN/AUS Status

oder 
=>DG -Büro- Deckenauslass dimmen Wert
=>DG -Büro- Deckenauslass dimmen Wert Status

oder 
=> Gartenbeet Möhrenbewässerung            Wassermarsch
=> Gartenbeet Möhrenbewässerung            Wassermarsch Status

**Comment by Breisgauer** [comment]
@chefkoch009, damit hast Du es korrekt zusammengefasst. Mit der README kam ich bis Ende letzten Jahres auch zu keinem Ergebnis, daher auch die Posts zu diesem Issue seit Juli 2018. Aber jetzt ist es geklärt und funktioniert bei mir mit knx 1.0.19 so wie Du es beschrieben hast.

Über die von Dir im Post oben beschriebenen Fälle 2-4 stolpere ich ebenso. Eine Lösung für Issue #33 würde hier helfen.
Mir ist aufgefallen, dass man beim Editieren der Objekte (inzwischen?) nicht mehr in Reiter "RAW" die Zuordnungen von STATUS und AKTIOM vornehmen muss, sondern das unter "NATIVE" machen kann. Ist mir erst mit Admin v3.5.10 und knx v1.0.19 aufgefallen. Damit gestaltet sich die Nacharbeit etwas komfortabler. Besser wäre eine Lösung für #33., die einen Reimport der Objekte aus einem aktualisierten KNX Projekt überlebt.

**Comment by StukaAss** [comment]
Hallo könnte mir jemand helfen ich betreibe einen Raspberry pi 3 mit openhub und steure die lampen mit alexa , ich bin jetzt zu iobroker gewechselt bzw das läuft jetzt auf einem pi 4, aber ich blicke absolut nicht durch wie ich dort meinen mdt dimmer zum laufen bekomme bzw die damit verbunden lampen. ich habe open hub vom pi3 eingebunden und damit kann ich auch meine lampen in alexa einbinden nur stehe ich total auf dem schlauch wenn es darum geht die lampen ohne den openhub adapter einzubinden.
wäre total nett wenn sich jemand erbarmen könnte mir zu helfen
Gruss Tobi

**Comment by chefkoch009** [comment]
Diese Frage bitte ins ioBroker Forum.
