### ISSUE TITLE
No Scrolling in Adapter Settings / GA Tools - Issue appeared with beta Version of Admin Adapter

### ISSUE THREAD

**Issue by bergteam** [ioBroker/ioBroker.knx#330]
**Issue**
Some weeks ago I was able to scroll in Instanzen=>KNXAdapter=>Settings=>Configuration and GA-Tools with Microsoft Edge Browser. 
This does not work any more:
   + scrolling by mouse
   + scrolling with keyboard

**Steps**
Nothing changed on Browser. Tried also Firefox, same behavior.
Only relevant changes may be the new beta versions of Admin Adapter.

**Versions** (all latest from beta Repo)
Admin Adapter v7.4.7
Knx Adapter v2.0.29
JS Controller 7.0.6
Node.js v20.18.1

**Screenshot**
The issue prevents reaching GroupAddresses further down in the GA-Tools list. When scrolled with the keyboard the following screen appears:

![IssueKnxAdapter](https://github.com/user-attachments/assets/727dd383-2832-4bee-8d12-37f674337c51)

**Comment by chefkoch009** [comment]
problem confirmed

**Comment by bergteam** [comment]
Confirmed fixed. Many Thanks!

**Comment by chefkoch009** [comment]
Ticket Colosseum
