### ISSUE TITLE
Beim re-import eines KNX Projektes manuelle Konfigurationen im Adapter erhalten

### ISSUE THREAD

**Issue by Breisgauer** [ioBroker/ioBroker.knx#37]
**Feature Request:** Wenn im ioBroker Objekte des KNX Adapters manuell geändert wurden, bleiben diese Änderungen beim reimport der knxproj Datein erhalten.

Details: Siehe [https://forum.iobroker.net/viewtopic.php?f=36&t=3934&p=157854#p157854](url).

Das würde auch für Issue #32 helfen, dann wäre eine manuelle Verknüpfung, die mit Adapter Version 1.0.9 auch schon über die RAW Daten möglich ist, erhalten bleiben.

**Comment by thomasklosinsky** [comment]
Das wäre ein sehr sinnvolles Feature!

**Comment by chefkoch009** [comment]
ist korrigiert.
