### ISSUE TITLE
Übersetzungstabelle für GA Import einführen

### ISSUE THREAD

**Issue by muetzli** [ioBroker/ioBroker.knx#38]
Hallo,

da es bei dem Import der knxproj Datei immer wieder zu Fehlern beim Import kommt, wäre es vielleicht sinnvoll die Zuordnung nicht fix im Code zu hinterlegen, sondern eine Zuordnungstabelle zu haben.

Sprich der Anwender kann die Tabelle vor dem Import an sein Projekt anpassen, damit die GA´s richtig zugeordnet werden. Dann muss man auch bei einem erneuten Import nicht wieder alles prüfen.

Bsp. "Licht <Raum> Schalten" wird zum Schalten verwendet und auch erkannt. Die Rückmeldung trägt den Namen "Licht <Raum> RM" und wird vom Adapter nicht als solche erkannt, da nach "Status" gesucht wird. Wenn ein Sperrobjekt zwischen der Gruppenadresse Schalten und Status liegt, läuft der Import völlig schief. 
Wenn man im Vorfeld eine Tabelle anlegen könnte und dem Adapter die Vorgabe machen könnte, dass RM (Rückmeldung) = Status ist und SP (Sperren) ein Sperrobjekt usw. könnte der Adapter das Projekt fehlerfrei importieren.
Ebenso könnte man die Objekte für Rollläden, Jalousien usw. hinterlegen um den Import sauber gestalten zu können.

**Comment by Garfonso** [comment]
Ich bin auch sehr dafür. 

Zumindest sollte sauberer dokumentiert werden, was denn da genau beim Import versucht wird zu erkennen... So habe ich erst beim lesen von altem Code (den aktuellen kann man nicht lesen?) herausgefunden, dass "ähnlich" nur folgendes regexp ist: /stat(e|us)|rückmeldung\s|\svalue|rm|r\/:*/ -> da mein Elektriker aber oft nur "ST" für Status genommen hat, fällt das wohl raus... trotzdem gehen manche Dinge anscheinend. Oder auch nicht...

**Comment by 1704eu** [comment]
Wenn der Import nochmal überarbeitet werden sollte, dann wäre auch schön wenn die Erkennung auch über die Struktur funktioniert. Bei mir heissen Status und Schaltadresse exakt gleich, sind aber in eigenen Mittelgruppen.
![image](https://user-images.githubusercontent.com/36085512/57183513-87030e00-6eae-11e9-8492-9631e6740f4d.png)
Vielleicht auch in der oben vorgeschlagenen Mapping Tabelle?

**Comment by chefkoch009** [comment]
Das mapping kann man selbst (wenn auch etwas umständlich) ändern. Nichts desto trotz werde ich das mapping in der kommenden Version für ETS5.7.x Projekte so ändern, das Act und Status vom selben Gerät kommen müssen.

**Comment by chefkoch009** [comment]
Hallo,
ich habe die Zuordnung nun über die gesammte Struktur, wie gewünscht, geändert. Wenn das Thema damit erledigt ist, dann diesen Issue bitte schliessen.

**Comment by tseroo** [comment]
Hallo,
bei mir funktioniert es leider nicht wie gewünscht. Meine Schalt-GAs sind z.B. 1/1/45 und die zugehörigen Status GAs starten immer mit 5, d.h. 5/1/45. Beim Import mit Adapter 1.0.40 von ETS 5.7.2 werden diese nicht als zusammengehörig erkannt:

```
  "native": {
    "dpt": "DPT1.001",
    "address": "1/1/45",
    "addressRefId": "P-01EC-0_GA-116",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-11_R-12",
    "devName": "M-0001_A-981C-01-43F5",
    "devInst": "P-01EC-0_DI-414",
    "objectSize": ""
  },
```
Das sind die beiden DPs:
```
knx.0.1_Schalten.1_1_EG.EG_Bad_Hauptlicht__E8_1
knx.0.5_Status.5_1_EG.Status_EG_Bad_Hauptlicht__E8_1
```

Die Zuordnung funktioniert allerdings schon, wenn sich sowohl Schalt- als auch Status-GA in der gleichen Gruppe befinden. Zu Testzwecken habe ich eine Status GA geändert - Schalten 1/1/70 und Status 1/1/71:
```
  "native": {
    "dpt": "DPT1.001",
    "address": "1/1/70",
    "addressRefId": "P-01EC-0_GA-121",
    "statusGARefId": "P-01EC-0_GA-369",
    "actGARefId": "",
    "objRef": "O-23_R-272",
    "devName": "M-0001_A-981C-01-43F5",
    "devInst": "P-01EC-0_DI-415",
    "objectSize": ""
  },
```
bzw:
```
  "native": {
    "dpt": "DPT1.011",
    "address": "1/1/71",
    "addressRefId": "P-01EC-0_GA-369",
    "statusGARefId": "",
    "actGARefId": "P-01EC-0_GA-121",
    "objRef": "O-25_R-73",
    "devName": "M-0001_A-981C-01-43F5",
    "devInst": "P-01EC-0_DI-415",
    "objectSize": ""
  },
```
Sollte das mit 1.0.40 funktionieren? Bzw. wie bekomme ich das hin, dass es funktioniert?

**Comment by Garfonso** [comment]
Die Zuordnung funktioniert über eine Ähnlichkeitsanalyse der Namen der Datenpunkte, wenn ich es richtig verstanden habe, inklusive Gruppennamen.

Bei mir geht die Zuordnung auch in verschiedenen Gruppen (bzw. ging in der Vergangenheit? Muss sagen, dass ich es nicht ganz neu getestet habe).

Eine Idee wäre daher aber, dass du die Namen der Gruppen angleichst. Das müsste ja relativ schnell getestet sein und dann kannst du damit experimentieren. Vermutlich ist besonders das 1_Schalten und 5_Status zu weit auseinander bzw. es ist zu wenig gemeinsames da...?

**Comment by tseroo** [comment]
Danke für den Tipp ... habe die Gruppen Namen angepasst und in meinem Test-Container ausprobiert: 1_Schalten -> Schalten und 5_Status -> Status_Schalten sowie 1_1_EG -> EG und 5_1_EG -> EG ... und schon funktioniert es !! Dann noch ein paar unterschiedliche Bezeichnung korrigiert und schlussendlich passt alles.

Aber jetzt kommts ... ich gehe zurück zu meinem produktiven ioBroker und siehe da, auf einmal wird auch hier die Rolle als 'Switch' angezeigt und die Status GAs sind korrekt zugewiesen ... ohne dass ich irgendetwas getan hätte! Das Beispiel von oben sieht jetzt so aus:
```
"native": {
    "dpt": "DPT1.001",
    "address": "1/1/45",
    "addressRefId": "P-01EC-0_GA-116",
    "statusGARefId": "P-01EC-0_GA-322",
    "actGARefId": ""
  },
```
Die Struktur ist immer noch wie zuvor 
![image](https://user-images.githubusercontent.com/10330889/78692391-19e7cc00-78fa-11ea-84cb-5214f02d8d4b.png)

Also original Projekt nochmals im Test-ioBroker eingespielt ... wieder keine Zuordnung. Ich versteh nicht was da abgeht.
Dann wieder das Projekt mit den korrigierten Gruppen Namen im Test-ioBroker eingespielt, und adhoc alles korrekt zugewiesen.

Was lerne ich daraus ... wie empfohlen auch die Gruppen-Namen ähnlich halten und nur mit 'Status' erweitern und gut isses.

Jetzt habe ich eigentlich nur mehr das Problem, dass mit der 1.0.40 sämtliche Status-Werte true anzeigen, egal wie der eigentlich Status der GA ist ... mal sehen, ob sich das auch noch beheben lässt.

**Comment by chefkoch009** [comment]
Hallo,
Die Rückmeldung ist in der kommenden Version korrigiert.

**Comment by tseroo** [comment]
Cool! Danke für die Info! Und natürlich auch für die Arbeit, die du in den Adapter rein steckst !!
