### ISSUE TITLE
Lizenzhinweis-Fehler 404

### ISSUE THREAD

**Issue by muetzli** [ioBroker/ioBroker.knx#39]
Bei der Installation wird zwar ein Fenster geöffnet um den Lizenzhinweis zu zeigen, jedoch scheint die Verlinkung nicht mehr aktuell zu sein. Hier bekommt man als Information nur "Fehler 404".

**Comment by chefkoch009** [comment]
Ist korrigiert. Hatte die falsche Dateiendung angegeben.
