### ISSUE TITLE
Type of state must be predefined.

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.knx#40]
After import of KNX project I have many states without known type of state (e.g. number or boolean).
This field is required for normal functionality of ioBroker.
Please fill it automatically.

**Comment by chefkoch009** [comment]
In case of correct defined DPT's in ETS, I'll implement this in next version(s).

**Comment by chefkoch009** [comment]
Fixed for number, string and boolean. But the result of import depends on the values programmed in ETS.
