### ISSUE TITLE
DPT 9 falscher Multiplikator

### ISSUE THREAD

**Issue by fuchs1978** [ioBroker/ioBroker.knx#41]
Ich bin von Version 0.8.3 auf die aktuelle umgestiegen 1.0.17. hierdurch sind meine DPT 9 Datenpunkte um den Faktor 100 größer geworden. Statt 20 Grad 2000 Grad. Der Wert auf dem Bus ist weiterhin korrekt.

**Comment by chefkoch009** [comment]
Grund war die alte objektstruktur.
