### ISSUE TITLE
Nach Umstieg auf iobroker.knx version 1.0.17 klappt Einlesen der Projektdatei nicht

### ISSUE THREAD

**Issue by axelrathey** [ioBroker/ioBroker.knx#42]
Hallo,
hatte bisher die version 0.8.6 wo sich die knxproj einlesen ließ. Hatte nun auf version 1.0.17 upgedated und den knx Adapter sowie die Instanz komplett neu installiert.
Beim Hochladen der knxproj Datei, die unter 0.8.6 klaglos eingelesen wurde, gibt es nun scheinbar Probleme. Das Hochladen findet keinen Abschluss. Es gibt 1502 Objekte und selbst nach einer 1/2 Stunde ist das Einlesen nicht abgeschlossen. Es erscheint weiterhin der waagerechte Rollbalken der andeutet, dass der Einlesevorgang noch stattfindet.
Wenn ich dann aus dem Dialog mit "schließen" herausgehe, wurde offenbar überhaupt kein Objekt angelegt.
Es ist nur das "connection" Objekt im Ordner Info von knx.0 vorhanden.
Eine Fehlermeldung erschien dabei nicht. Woran kann das liegen?

Lizenz ist Eingetragen wird als ok bestätigt. Die Verbindung zum TCPIP Bus via KNX2TCPIP Gateway scheint zu funktionieren. Im Log erscheinen Warnungen über Werte die vom KNX kommen, für die es aber keine Objekte gibt, da sich die halt nicht einlesen lassen.
Gibt es einen Debug Modus beim Einlesen?

Admin ist bei mir Version 3.4.7
javascript ist 3.6.4
Node.js ist Version 8.11.4
npm ist Version 4.6.1

Danke für jede Hilfe, Gruß
Axel

**Comment by axelrathey** [comment]
Hallo Chefkoch,

npm 6.4.0 habe ich nun drauf. Und auch "iobroker u knx" ausgeführt.

Das KNX Gateway ist ein IPS S 3.1.1 von ABB

Es werden nun eine Reihe Objekten eingelesen, aber bei weitem nicht alle. Folgende Dinge habe ich im LOG gefunden, die wohl mit KNX im Zusammenhang stehen. 

Gruß Axel

host.bananapi | 2018-08-28 13:01:43.914 | info | Restart adapter system.adapter.knx.0 because enabled
-- | -- | -- | --
host.bananapi | 2018-08-28 13:01:43.912 | error | instance system.adapter.knx.0 terminated with code 7 (Adapter already running)
knx.0 | 2018-08-28 13:01:43.744 | info | STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:01:43.694 | info | Connected - local UDP Server listening on 192.168.0.6:55731
knx.0 | 2018-08-28 13:01:43.693 | info | Using UDP with local IP: 192.168.0.6
knx.0 | 2018-08-28 13:01:43.693 | info | STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:00:47.912 | info | STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:00:47.912 | info | STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_TUNNELLING_REQUEST(13) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:00:47.912 | info | Value received on unknown GA : 13/6/3
knx.0 | 2018-08-28 13:00:47.912 | info | Value received on unknown GA : 13/6/3
knx.0 | 2018-08-28 13:00:17.366 | info | Connected - local UDP Server listening on 192.168.0.6:38884
knx.0 | 2018-08-28 13:00:17.365 | info | Using UDP with local IP: 192.168.0.6
knx.0 | 2018-08-28 13:00:15.369 | info | STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:00:14.632 | warn | Reconnection to DB.
knx.0 | 2018-08-28 13:00:14.622 | warn | Reconnection to DB.
knx.0 | 2018-08-28 13:00:13.369 | info | STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:00:13.368 | info | STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_TUNNELLING_REQUEST(13) to STATE_NOT_CONNECTED(0).
knx.0 | 2018-08-28 13:00:13.368 | info | Value received on unknown GA : 11/4/3
knx.0

**Comment by chefkoch009** [comment]
Habe den Importer überarbeitet in V1.0.18. Damit sollte es funktionieren.

**Comment by chefkoch009** [comment]
no userfeedback ... so marking as solved

**Comment by axelrathey** [comment]
Hallo Chefkoch, 
Einlesen meiner proj Datei erzeugt nach wie vor bei mir keine Objekte. Wenn ich neue Objekte habe, gehe ich vorübergehend auf die 0.86 Version, um sie einzulesen. 
Die Zuordnung der Schreib und Leserechte anhand der Status Bezeichnung funktioniert nur, wenn der iobroker die Bedienung ist und im knx Netz der Aktor steht. Habe hier ein paar zigbee Lampen am tradfri Gateway zu laufen, die von einem knx Schalter an der Wand +Javascript geschaltet werden. Umgekehrt erhält der Schalter den Status dann vom tradfri Gateway. Da braucht man die Schreib/Leserechte genau anders herum. Ich kann dir meine proj Datei gern nochmal schicken.
Viele Grüße Axel
