### ISSUE TITLE
File index_m.html not found

### ISSUE THREAD

**Issue by phv80** [ioBroker/ioBroker.knx#43]
Hallo, ich versuche den Adapter zu installieren und immer kommt danach die Meldung File index_m.html not found.
Ich habe hier noch niemanden mit dem selben Problem gesehen, was mache ich falsch.

lg
Philipp

**Comment by chefkoch009** [comment]
Hallo Phiipp,

Hast du schon ein „iobroker upload knx“ versucht?

Vg
Chefkoch009

**Comment by Apollon77** [comment]
Und sicherstellen das du Admin 3.x nutzt!!

**Comment by phv80** [comment]
Ich habe Admin 3.4.7.

@chefkoch was genau meinst du damit? Wenn ich die Instanz vom knx Adapter öffne, kommt gleich die angeführte Meldung und ich kann dort nichts machen

**Comment by chefkoch009** [comment]
Schau Mal hier:
https://forum.iobroker.net/viewtopic.php?f=36&t=3934&start=480#p129587

Da hatte ich das schon mal beschrieben.

VG
chefkoch009

**Comment by phv80** [comment]
@chefkoch009 
danke für diesen Tip, es funktioniert jetzt!

lg
Philipp
