### ISSUE TITLE
Datatype 7.600 Color Temperature K is not working

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#44]
Datatype 7.600 Color Temperature K is not working not sending or receiving of  the Datatype possible
```
{
  "_id": "knx.0.EG.WZ-2-FK",
  "type": "state",
  "common": {
    "name": "WZ-2-FK",
    "type": "",
    "read": false,
    "write": true,
    "role": "level",
    "min": 2000,
    "max": 6000
  },
  "native": {
    "dpt": "DPT7.600",
    "address": "2/0/57",
    "addressRefId": "P-02D7-0_GA-371",
    "statusGARefId": "P-02D7-0_GA-377",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1539459026925,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

adapter also crashes after import:
```
2018-10-13 21:15:13.431 - error: Caught by controller[1]: DPT.js isDPT undefined : DPT[12.000]
--
2018-10-13 21:15:13.432 - error: Caught by controller[2]: DPT.js isDPT undefined : DPT[7.600]
2018-10-13 21:15:13.432 - error: Caught by controller[3]: DPT.js isDPT undefined : DPT[249.600]
2018-10-13 21:15:13.432 - error: Caught by controller[4]: DPT.js isDPT undefined : DPT[7.600]


2018-10-13 21:15:13.437 - error: Caught by controller[49]: DPT.js isDPT undefined : DPT[7.600]
2018-10-13 21:15:13.437 - error: host.raspberrypi instance system.adapter.knx.0 terminated with code 156 ()
```

**Comment by chefkoch009** [comment]
Hello TA2k,

as I wrote in the README.md under "Datapoint Types" all DPT's described in "System Specifications, Interworking, Datapointtypes" are supported. In your case:
1) DPT 12.000 does not exist. This is DPT12.001
2) DPT 7.600 does not exist. => this comes up with newer Versions, so I've to add this in the next Adapter release.
3) DPT 249.600 the same like 2)

Furthermore there is an error in your raw-data: "_id": "knx.0.EG.WZ-2-FK" indicates, that you have a 2-level structure, but  "address": "2/0/57" shows a 3-level structure. 
So I need more informations:
1) ETS Version
2) npm-Version
3) node-Version
4) js-controller Version
5) admin Version
6) csv-export of your ETS-Project

kind regards 
chefkoch009

**Comment by TA2k** [comment]
Hi,
ok it autoselect 12.*
With the level structures everything is fine. I anonymous the id sorry for the inconvenience.

**Comment by Garfonso** [comment]
May I ask, when the next update that will include the 7.600 datapoint will be released? I'd like to start using this with ioBroker, soon. 
Do you need beta testers or similar help?

**Comment by Garfonso** [comment]
I switched ioBroker to the latest branch and got some updates of the KNX adapter, now on version 1.0.20.
But I still get this error: `Caught | 2019-03-25 17:56:02.360 | error | by controller[23]:           DPT.js isDPT  undefined : DPT[7.600] -- | -- | -- | --` during project import.

Also, if I try to set color temperature I get these errors in the log:
`knx.0 | 2019-03-25 17:59:47.551 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:228:12)
-- | -- | -- | --
knx.0 | 2019-03-25 17:59:47.551 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:270:10)
knx.0 | 2019-03-25 17:59:47.551 | error | at Socket.Emitter.emit  (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-03-25 17:59:47.551 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
knx.0 | 2019-03-25 17:59:47.551 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3705:37)
knx.0 | 2019-03-25 17:59:47.551 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:2726)
knx.0 | 2019-03-25 17:59:47.551 | error | at _0x336508.write (/opt/iobroker/node_modules/iobroker.knx/knx.js:43:798)
knx.0 | 2019-03-25 17:59:47.551 | error | at _0x4ad005.(anonymous function) [as groupValueWrite] (/opt/iobroker/node_modules/iobroker.knx/knx.js:17:49991)
knx.0 | 2019-03-25 17:59:47.551 | error | at Object._0x331276.(anonymous function) [as valueBitLength] (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:25481)
knx.0 | 2019-03-25 17:59:47.551 | error | at _0x5868fb (/opt/iobroker/node_modules/iobroker.knx/knx.js:31:19803)
knx.0 | 2019-03-25 17:59:47.551 | error | TypeError: Cannot read property 'hasOwnProperty' of null
knx.0 | 2019-03-25 17:59:47.547 | error | message knx.0.Beleuchtung.Farbe.Deckenleuchte_DG_Bad_Farbe [object Object] Cannot read property 'hasOwnProperty' of null`
