### ISSUE TITLE
System macht sich selbstständig

### ISSUE THREAD

**Issue by berkols** [ioBroker/ioBroker.knx#45]
Nach dem Einlesen der KNX Projektdatei (noch nichts programmiert) schalten Lichtszenen schon los.
Eine Aufgaben übernimmt mein Homeserver, aber irgendwie beisst sich da was

**Comment by Garfonso** [comment]
Vermutlich ein ähnliches Problem wie in #49. Vielleicht hilft dir die Erklärung da weiter.

**Comment by chefkoch009** [comment]
Behoben ab Version 1.0.32
