### ISSUE TITLE
KNX-Projekt wird nicht korrekt eingelesen - Räume sind da, Funktionen nicht, roles und read/write werden "falsch" zugewiesen

### ISSUE THREAD

**Issue by JamesKowalski** [ioBroker/ioBroker.knx#48]
Hallo Chefkoch,

zunächst einmal herzlichen Dank für den Enthusiasmus und den Aufwand, den Du in die (Weiter-)Entwicklung des iobroker.knx-Adapters steckst!

Noch bin ich Anfänger in der Nutzung von ioBroker, von daher weiß ich nicht, was die Ursache des folgenden Problems ist/sein könnte: beim Einlesen meines KNX-Projektes werden alle 614 enthaltenen GAs eingelesen und auch alle definierten Räume erkannt; soweit so gut. Funktionen werden aber keine angezeigt. 

Wenn ich mir nun die 284 "lichtrelevanten" GAs (zu erkennen an der GA-Notation x/1/x mit den 142 "Schalten"-GAs (Notation x/1/..0) mit DPT 1.001 und den 142 "Status"-GAs (Notation x/1/..1) mit DPT 1.011) anschaue, dann wurden die "Schalten"-GAs mit "type": "boolean", "role": "value", "read": true und "write": false sowie die "Status"-GAs mit "type": "boolean", "read": false, "write": true und "role": "indicator" importiert - also die read/write genau falsch herum und die roles nicht korrekt. Wenn ich diese Daten manuell im ioBroker im Tab "Objekte" korrigiere, dann kann ich sie dort anschließend auch "schalten", das Signal wird korrekt auf den KNX-Bus übertragen und auch die Statusmeldung vom KNX-Bus zurück in den ioBroker erfolgt korrekt.

Ich konnte weder hier noch im ioBroker-Forum etwas finden, das mir weitergeholfen hat. Hast Du eine Idee, was ich - ggf. schon beim Aufsetzen der GA-Struktur in KNX - falsch oder ungeschickt mache oder wo sonst das Problem liegt, warum die Objekte nicht korrekt in den ioBroker importiert werden? Und müssten nicht neben den Räumen auch die Funktionen in ioBroker erkannt/angezeigt werden?

Ich nutze den ioBroker.knx in der aktuellen Version 1.0.17, die ETS in Version 5.6.6 und eine dreistufige GA-Struktur mit Raum/Gewerk/"Objekt", z.B. 
- GA = 24/1/0 mit dem Namen "24_1_000 ELW EG Gäste-WC / Licht E/A / Spiegelschrank - Schalten"
- GA = 24/1/1 mit dem Namen "24_1_001 ELW EG Gäste-WC / Licht E/A / Spiegelschrank - Status"

Wie man sieht verwende ich im GA-Namen (und auch in der GA-Beschreibung) fleißig Sonderzeichen wie _-/() und auch Umlaute. Dies scheint aber alles "sauber" in ioBroker eingelesen bzw. beim Einlesen durch "_" ersetzt zu werden (siehe diese unveränderten ioBroker-Original-RAWs nach dem Einlesen):

{
  "_id": "knx.0.24_ELW_EG_Gäste-WC.24_1_ELW_EG_Gäste-WC___Licht_E_A.24_1_000_ELW_EG_Gäste-WC___Lichte_E_A___Spiegelschrank_-_Schalten",
  "type": "state",
  "common": {
    "name": "24_1_000 ELW EG Gäste-WC / Lichte E/A / Spiegelschrank - Schalten",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "value",
    "min": 0,
    "max": 1
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "24/1/0",
    "addressRefId": "P-0716-0_GA-201",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "ts": 1546214212429,
  "acl": {
    "object": 1638,
    "state": 1638
  }
}

bzw.

{
  "_id": "knx.0.24_ELW_EG_Gäste-WC.24_1_ELW_EG_Gäste-WC___Licht_E_A.24_1_001_ELW_EG_Gäste-WC___Lichte_E_A___Spiegelschrank_-_Status",
  "type": "state",
  "common": {
    "name": "24_1_001 ELW EG Gäste-WC / Lichte E/A / Spiegelschrank - Status",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "value",
    "min": 0,
    "max": 1
  },
  "native": {
    "dpt": "DPT1.011",
    "address": "24/1/1",
    "addressRefId": "P-0716-0_GA-202",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "ts": 1546214212437,
  "acl": {
    "object": 1638,
    "state": 1638
  }
}

Allen GAs ist zudem ein DPT zugeordnet. Gerne schicke ich bei Bedarf die *.knxproj oder aber den CSV-Export der GAs.

Danke vorab und einen guten Rutsch in die Runde - ich freue mich auf Feedback und lerne gerne dazu!

Gruß,

JamesKowalski

**Comment by Garfonso** [comment]
Hi,
zu deinem eigentlichen Problem kann ich nicht viel sagen (außer ggf. dass es bei mir nicht auftritt, außerdem vielleicht mal die Flags prüfen, wie hier erklärt:  https://github.com/ioBroker/ioBroker.knx/issues/49#issuecomment-450887767 ).

Aber ich kann einen Tipp geben. In den RAW Objekten, die du gepostet hast, sieht man, dass der KNX Adapter die nicht zueinander zu ordnen kann, er weiß also nicht welches Schalten zu welchem Status gehört.
Das kann man auch händisch reparieren indem man für das Schaltobjekt die "statusGARefId" mit dem  befüllt "addressRefId" des Statusobjekts und beim Statusobjekt die "actGARefId" mit der "addressRefId" des Schaltobjekts. 
Der Adapter bekommt das (in der aktuellen Version, das soll wohl nochmal überarbeitet werden, so dass man da besser eingreifen kann) auch hin, wenn die GA Namen exakt identisch sind bis auf das Status, also wenn du deine Namen änderst, z.B. wenn du den Status GA umbenennst in "24_1_001 ELW EG Gäste-WC / Licht E/A / Spiegelschrank - Schalten Status". Das liest sich etwas umständlich, dann klappt aber die automatische Zuordnung (und wenn noch ein Dimmer oder ggf. Farbe mit im Spiel ist, ergibt es sogar Sinn :-)).

**Comment by JamesKowalski** [comment]
Hallo nochmals,

ist es korrekt, dass die "Schalten"-GA (mit DPT 1.001) im Adapter die Rolle "level" und die dazugehörige "Schalten Status"-GA (mit DPT 1.011) die Rolle "indicator" erhält? Ich hätte hier eher "switch" und "status" erwartet.

Gruß,

JamesKowalski

**Comment by chefkoch009** [comment]
in Version 1.0.18 ist für DPT1.x die actGA mit der Rolle "switch" und die statusGA mit "indicator.switch" belegt. Ausserdem wurde 1 und 0 nun auf true und false geändert.

@JamesKowalski: Du verwendest "24_1_001 ELW EG Gäste-WC / Lichte E/A / Spiegelschrank - Status" und "24_1_000 ELW EG Gäste-WC / Lichte E/A / Spiegelschrank - Schalten". Das ist ungünstig, denn es gibt ja auch Dimmaktoren die ein Schalten- und Dimmenobjekt haben. Somit ist nicht klar, was für einen Status Du haben möchtest. Um die Trefferrate zu erhöhen, wäre "schalten" und "schalten status" oder "dimmern wert" und "dimmen wert status" bedeutend besser.

VG
chefkoch009

**Comment by JamesKowalski** [comment]
@chefkoch009: Danke für die Infos und die neue Version 1.0.19. Meine GAs habe ich inzwischen angepasst, wie von Dir und auch Garfonso angemerkt.

Müssten nach dem Laden des KNX-Projektes neben den "Räumen" auch direkt die "Funktionen" befüllt sein oder bin ich hier falsch unterwegs? Bei mir ist der Funktionsreiter/die Funktionsspalte komplett leer. Ist das so korrekt?

Danke und Gruß,
JamesKowalski
