### ISSUE TITLE
KNX-Adapter-Neustart löst Rollläden-Fahrt aus

### ISSUE THREAD

**Issue by kruegertee** [ioBroker/ioBroker.knx#49]
Hallo,

jedes Mal wenn der KNX-Adapter neu startet bewegen sich nahezu alle Rollläden im Haus. Dieses Phänomen trat das erste Mal beim Import der Projektdatei auf und danach immer dann, wenn der Adapter neu startet bzw. natürlich auch dann, wenn der gesamte ioBroker neu gestartet wird.

Ich verwende die neueste Version 1.017, hatte das Problem aber auch bei den Vorgängern.

Das Thema wurde schon einmal im ioBroker-Forum andiskutiert: https://forum.iobroker.net/viewtopic.php?p=212075#p212075

Gruß
Timo

**Comment by Apollon77** [comment]
Sind da noch zusätzliche Skripte im Spiel oder nur der knx adapter?

**Comment by chefkoch009** [comment]
Hallo Timo,
das von Dir beschriebene Verhalten kann entstehen, wenn auf den GA's welche beschrieben werden auch das Lese-Flag gesetzt ist. Also z.B. "EG Jal fahren" mit KSLÜ (sollte aber sein KS), denn die Rückmeldung kommt ja über die Status GA welche "KLÜ" hat (haben sollte). Beim Einlesen deines Projektes wird nämlich auf diese Flags geparst. 
Wenn der Adapter startet, dann schaut er nach allen Objekten im knx.0, welche das "Lesen" gesetzt haben und schickt eine "1" dahin. Bei Richtiger Vergabe ist das ein GroupValueRead und der Aktor antwortet mit seinem Status. Das heisst vermutlich nun in deinem Fall das die eigentliche "Lese-1" auf ein Aktor-KO geschrieben wird und demzufolge setzen sich bei jedem Neustart des Adapters deine Rolläden in Bewegung. 

1) Möglichkeit: prüfen/ändern der Flags in der ETS und dann Neuimport
2) im ioBroker unter knx.0 bei den betroffenen Objekten das Lesen deaktivieren.

VG
Kay

**Comment by kruegertee** [comment]
Hallo Kay,

das hört sich plausibel an, ich werde das prüfen. Danke für die Info!

VG
Timo

**Comment by chefkoch009** [comment]
Hallo Timo,

hast Du es geprüft?

**Comment by kruegertee** [comment]
Hallo Kay,

tut mir leid, ich bin nicht mehr zum Testen gekommen und habe den ioBroker mittlerweile deinstalliert. Ich arbeite jetzt mit openHAB. Ich hatte dazu aber im ioBroker-Forum einen Thread eröffnet und mindestens zwei andere User hatten sich mit ähnlichen Problemen gemeldet: https://forum.iobroker.net/viewtopic.php?f=20&t=18678&p=212149#p212149

Ggf. könnte von denen jemand testen, ob das Problem gelöst werden kann.

Gruß
Timo

**Comment by motto1973** [comment]
Hallo Zusammen, 

ich hatte Anfang des Jahres das gleiche Problem, immer wenn ich ein Proxmox Backup meiner ioBroker VM gemacht haben (also mit einem ioBroker stop, und damit natürlich auch einem restart des KNX Adapters) hatte ich das gleiche Phänomen. 
Ich habe dann mal nur den KNX Adapter neu gestartet und die Raffstores fuhren ebenfalls hoch.
Nachdem ich das Lese Flag im knx.0 wie von @chefkoch009 beschrieben deaktiviert hatte, trat das Problem nicht mehr auf. 

hth,
Gruß, Michael

**Comment by mghomedev** [comment]
Ich habe das Problem seit kurzem auch. Vorher bestand es einen Monat lang nicht.
Es liegt definitiv nicht daran, dass auf dem KNX-Bus Werte gelesen werden, denn wenn ich dasselbe mit der original KNX-ETS-Software mache, passiert nichts. Aus meiner Sicht könnte es einfach ein Timing bug sein, nämlich dass der KNX-Adapter beim Start erst Werte ausliesst und dann versucht anhand des Positions-STATUS-Wertes den Original-Positions-Wert zu beschreiben, aber er benutzt den alten "0"-Wert anstatt den neu gelesenen. 
Ich sehe nämlich in der KNX-ETS-Software im Gruppenmonitor, dass beim Neustart des Knx-Adapters irgendwann eine 0 als "Position" auf dem Bus geschrieben werden.

**Comment by chefkoch009** [comment]
Hallo,

lange hat es gedauert. Bitte die neue Version testen. Dann diesen issue schliessen.
Danke.

**Comment by mghomedev** [comment]
Bei mir trat das Problem jetzt nicht mehr auf, Danke!

**Comment by chefkoch009** [comment]
Danke für das Feedback....ich schließe jetzt diesen issue.
