### ISSUE TITLE
Iobroker sendet keine Werte unter 28%

### ISSUE THREAD

**Issue by Timo1706** [ioBroker/ioBroker.knx#5]
Hallo. Super Arbeit.
Eins treibt mich aber in den Wahnsinn.
Schalten funktioniert super. Aber wenn ich meine Leuchten auf einen Wert setzen will (Alexa Sprachsteuerung), der unter 28% liegt, passiert gar nichts. Alle werte drüber gehen. Das gleiche passiert, wenn ich meine Rollläden auf eine bestimmte höhe fahren will.
Gebe ich einen Wert in die ETS ein und sende ihn, klappt alles super.
Wenn ich den Wert, den ioBroker sendet im Busmonitor beobachte, ist der niedrigste angezeigte Wert 29.95%. Was mache ich falsch?

**Comment by chefkoch009** [comment]
Hallo Timo1706,

keine Panik, Du machst nichts falsch. Das ist ebenfalls noch eine Baustelle,, die ich habe. Das hängt mit dem DPT5.xxx zusammen. Einige werden von 0-100% bemessen, andere von 0-255 und wiederum andere von 0-360°. Ich weiss darum und arbeite an dem Problem.

**Comment by Timo1706** [comment]
Wow, danke für die schnelle Antwort.
Allergrössten Respekt vor deiner Arbeit. Würde das auch gerne können. Aber dafür ist mein Wissen in diese Richtung dann doch leider zu beschränkt.

**Comment by chefkoch009** [comment]
Ich habe den Fehler gefunden. Die Lösung hierzu findest Du hier:

https://github.com/ioBroker/ioBroker.knx/issues/4
