### ISSUE TITLE
keine Verbindung von iobroker zu KNX

### ISSUE THREAD

**Issue by paidmueller74** [ioBroker/ioBroker.knx#54]
Hallo,

bei mir wird leider keine Verbindung vom KNX-Adapter zu meinem Gateway aufgebaut (Ampel gelb). Als solches fungiert ein Wiregate mit einer eibd-Instanz, ersatzweise ein Raspberry ebenfalls mit eibd. Beide wurden mit den Parametern Tunneling und Routing gestartet. Der Port 3671 UDP ist erreichbar, dies wurde mit dem Portscanner Nmap soweit geprüft, ebenso ist eine Verbindung der ETS via Wiregate Port 3671 auf den Bus problemlos möglich. FHEM läuft ebenfalls, bin mir aber nicht sicher über welchen Port. Lizenz ist eingepflegt.

Folgendes findet sich im Log:

knx.0 | 2019-04-06 15:05:39.781 | info | ... not able to close connection, because already closed
-- | -- | -- | --
knx.0 | 2019-04-06 15:05:39.781 | info | Connection persists.....closing now
knx.0 | 2019-04-06 15:05:39.780 | info | Change state from STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0)
knx.0 | 2019-04-06 15:05:38.283 | info | Change state from STATE_PORT_OPENED(2) to STATE_CONNECT_REQUEST(3)
knx.0 | 2019-04-06 15:05:38.280 | info | Send  : UDP Connection Request :        06 10 02 05 00 1a 08 01 ac 11 00 02  9b 0d 08 01 ac 11 00 02 9b 0d 04 04 02 00        sent to  192.168.88.13:3671
knx.0 | 2019-04-06 15:05:38.280 | info | Connected  - local UDP Server listening on 172.17.0.2:39693
knx.0 | 2019-04-06 15:05:38.280 | info | Change state from STATE_OPENING_PORT(1) to STATE_PORT_OPENED(2)
knx.0 | 2019-04-06 15:05:38.280 | info | Event : UDP - listening
knx.0 | 2019-04-06 15:05:38.280 | info | Change state from STATE_NOT_CONNECTED(0) to STATE_OPENING_PORT(1)
knx.0 | 2019-04-06 15:05:38.276 | info | Using UDP with local IP: 172.17.0.2
knx.0 | 2019-04-06 15:05:34.270 | info | STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).

Es gab im iobroker Forum schon mal einen ähnlichen Fall, dieses hat sich aber wohl von selber erledigt. Ich habe iobroker sowohl auf einem Raspberry 3 mittels Image als auch als buanet Docker Container (Syonlogy als auch direkt auf Debian) installiert, alle mit dem gleichen Ergebnis. Ist der eibd hier das Problem?

Danke und viele Grüße

Thorsten

**Comment by chefkoch009** [comment]
Wie viele LAN Schnittstellen hat dein System wo der ioBroker drauf läuft? Du versuchst von der 172.17.0.2 auf die 192.168.88.13 zuzugreifen. A priori funktioniert das nicht ohne entsprechende Routing Regeln.

**Comment by p-r-o-m-e-t-h-e-u-s** [comment]
Liegt wohl daran, dass es aus einem Docker Container gemacht wird. Ich habe gerade auch das Problem. Konnte es jemand schonmal lösen?

**Comment by chefkoch009** [comment]
Ich habe im neuen Adapter die Möglichkeit geschaffen, die Schnittstelle auszuwählen. Bitte beachten: der adapter kommuniziert über udp 3671!

**Comment by chefkoch009** [comment]
Keine Rückmeldung, ich gehe davon aus das das Problem gelöst ist.
