### ISSUE TITLE
Einlesen aus der ETS 5.7.1 fehlerhaft

### ISSUE THREAD

**Issue by matze1708** [ioBroker/ioBroker.knx#55]
Hallo,
ich habe eben den KNX Adapter 1.0.20 installiert.

Ich nutzte die ETS 5.7.1 und habe auch daher den KNXPROJ Datei exportiert.

Beim einlesen der Datei in den Adapter bekomme ich folgenden Fehler:

knx.0	2019-04-26 19:29:00.852	error	at Socket.<anonymous> (/opt/iobroker/node_modules/redis/index.js:274:27)
knx.0	2019-04-26 19:29:00.852	error	at JavascriptRedisParser.execute (/opt/iobroker/node_modules/redis-parser/lib/parser.js:553:10)
knx.0	2019-04-26 19:29:00.852	error	at JavascriptRedisParser.returnReply (/opt/iobroker/node_modules/redis/index.js:192:18)
knx.0	2019-04-26 19:29:00.852	error	at RedisClient.return_reply (/opt/iobroker/node_modules/redis/index.js:833:9)
knx.0	2019-04-26 19:29:00.852	error	at return_pub_sub (/opt/iobroker/node_modules/redis/index.js:794:18)
knx.0	2019-04-26 19:29:00.852	error	at RedisClient.emit (events.js:189:13)
knx.0	2019-04-26 19:29:00.852	error	at RedisClient.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:605:25)
knx.0	2019-04-26 19:29:00.852	error	at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3680:34)
knx.0	2019-04-26 19:29:00.852	error	at Adapter.emit (events.js:189:13)
knx.0	2019-04-26 19:29:00.852	error	at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:5730)
knx.0	2019-04-26 19:29:00.852	error	TypeError: Cannot read property 'replace' of undefined
Ich weiss das auf umstieg zur 5.7 der Export von ETS seiten geändert worden ist.

Kann es sein das es hier dran liegt?

Danke und Liebe Grüße

**Comment by chefkoch009** [comment]
Hallo,

mich wundern die redis Einträge. Funktioniert dein redis richtig?

VG 
chefkoch009

**Comment by matze1708** [comment]
Danke für deine Info,

Kannst du mir mal helfen, wie ich das prüfe.

**Comment by Apollon77** [comment]
Redis ist ok. Lies von unten. Der Fehler passiert in Knx.js

**Comment by matze1708** [comment]
Soll mir das was sagen? Als Anwender oder ging das an den Entwickler?

**Comment by chefkoch009** [comment]
Berechtigter Weise an den Entwickler.

Ich schau mir das an.

**Comment by matze1708** [comment]
Ok, lieben Dank.

Wenn du meine Datei mal wieder brauchst, sag bescheid ☺️

**Comment by thorsten-gehrig** [comment]
Hi
ist das problem mittlerweile gelöst?
Vielleicht kommen daher meine aktuellen Probleme bei einer neu aufgesetzten instanz ... und ich habe ETS 5.7.1 installiert...
Ich kriege die Datenpunkte wohl eingelesen - kann aber nichts schreiben...

Gruß
Thorsten

**Comment by chefkoch009** [comment]
Hi,  
Ich komme ohne Projektdatei nicht weiter :-(.

Kann mir jemand eine zur Verfügung stellen?

VG
chefkoch009

**Comment by matze1708** [comment]
Ich schicke dir gern eine, komme aber erst die Tage dazu.

**Comment by thorsten-gehrig** [comment]
Gerne. Wohin?

**Comment by thorsten-gehrig** [comment]
ich hab eine (schön kleine) Projektdatei hier abgelegt:
https://www.gehrig.info/share/Neu2.knxproj
Hilft das?
Gruß
Thorsten

**Comment by chefkoch009** [comment]
Danke für das Projekt. Teste mal bitte die 0/3/0 "Beleuchtung außen schalten" und die 0/0/20 "Decke An/aus".  Meine Vermutung: die 0/3/0 wird schalten aber die 0/0/20 nicht. Ist das richtig?

Wenn das so stimmt, dann sind das mal wieder ne ganze Menge Hausaufgaben.

VG
chefkoch009

**Comment by thorsten-gehrig** [comment]
Das Problem ist eher das gar kein schreiben möglich ist. Bei jedem Schreib-Befehl kommt der Fehler den ich im anderen Thread gepostet habe...
(ob er das falsche element Anspricht kann ich daher garnicht sagen)

**Comment by thorsten-gehrig** [comment]
Ich finde gerade nicht meinen anderen Post (vielleicht nicht gesendet? :-( ).
Daher hier nochmal:

knx.0 | 2019-06-10 12:20:39.043 | error | at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
-- | -- | -- | --
knx.0 | 2019-06-10 12:20:39.043 | error | at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
knx.0 | 2019-06-10 12:20:39.043 | error | at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-06-10 12:20:39.043 | error | at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
knx.0 | 2019-06-10 12:20:39.043 | error | at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
knx.0 | 2019-06-10 12:20:39.043 | error | at Socket.onevent (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:278:10)
knx.0 | 2019-06-10 12:20:39.043 | error | at Socket.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
knx.0 | 2019-06-10 12:20:39.043 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInMemClient.js:52:30)
knx.0 | 2019-06-10 12:20:39.043 | error | at Object.change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3425:37)
knx.0 | 2019-06-10 12:20:39.043 | error | at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:79:2708)
knx.0 | 2019-06-10 12:20:39.043 | error | TypeError: Cannot read property 'write' of undefined
knx.0 | 2019-06-10 12:20:39.017 | error | message knx.0.Beleuchtung.Keller_(-2)_und_Außen.Beleuchtung_außen [object Object] Cannot read property 'write' of undefined

Ich denke er kann nicht schreiben: read property "write" of undefined  - klingt schon sehr schräg...
Hilft das?
Gruß
Thorsten

**Comment by chefkoch009** [comment]
Ich habe mich mit den Angaben auf dein testprojekt bezogen. In den Objekten fehlt das „read“ und das „Write“. Bin noch am schauen, warum es nicht eingefügt wurde.

Kannst du mal die object raws Posten von den beiden Objekten?

**Comment by thorsten-gehrig** [comment]
Hi
hier (0/3/0)
{
  "from": "system.adapter.knx.0",
  "ts": 1560008912857,
  "common": {
    "name": "Beleuchtung außen",
    "type": "boolean",
    "role": "level",
    "min": 0,
    "max": 1,
    "read": false,
    "write": true
  },
  "native": {
    "dpt": "",
    "address": "0/3/0",
    "addressRefId": "P-0406-0_GA-74",
    "statusGARefId": "P-0406-0_GA-75",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Beleuchtung.Keller_(-2)_und_Außen.Beleuchtung_außen",
  "type": "state"
}


und 0/0/20:
{
  "_id": "knx.0.Beleuchtung.Obergeschoss_(1).Decke_An_aus",
  "type": "state",
  "common": {
    "name": "Decke An/aus",
    "type": "boolean",
    "role": "value",
    "min": false,
    "max": true
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "0/0/20",
    "addressRefId": "P-0406-0_GA-6",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "from": "system.adapter.knx.0",
  "ts": 1560008912829,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Gruß
Thorsten

**Comment by thorsten-gehrig** [comment]
Wenn ich mir das so durchlese wundert mich das:
bei 0/3/0 Role=level?? sollte das nicht switch sein?
und der DPT fehlt
bei 0/0/20 Role=level?? Sollte auch switch sein?
DPT ist aber dabei...

Beides erklärt mir aber nicht die Fehlermeldung "Cannot read property 'write' of undefined" - weil zumindest 0/3/0 hat deutlich "write: true"

Irgendwie alles komisch...

**Comment by jensfr1** [comment]
Mit 5.7.2 hängt es bei mir auch. Keine Chance das Projekt hochzuladen... 
![image](https://user-images.githubusercontent.com/12272992/59755864-f713fa80-9288-11e9-90f2-b246d48e7f75.png)

**Comment by chefkoch009** [comment]
Hallo jensfr1,

Ich kenne die Problematik. Kannst du mir deine projektdatei zur Verfügung stellen?

Vg chefkoch009

**Comment by jensfr1** [comment]
@chefkoch009  Ja gerne. Wie?

**Comment by chefkoch009** [comment]
Schreib mal eine PN im Forum an mich.

**Comment by gspiliopoulou** [comment]
Στις Σάβ, 27 Απρ 2019, 22:48 ο χρήστης matze1708 <notifications@github.com>
έγραψε:

**Comment by chefkoch009** [comment]
genau daran liegt es.....ich arbeite mit Hochdruck an der neuen Version. Als Referenz habe ich ein Projekt der ETS Version 5.7.2. Es wäre erstklassig, wenn ich ETS Projekte >5.6.x bekommen könnte, wo Räume und Funktionen über mehrere Ebenen verknüpft sind.

VG 
Chefkoch009

**Comment by jensfr1** [comment]
Auch mit der neusten Version funktioniert das einlesen der project datei in iobroker nicht. (ets 5.7.2)

**Comment by matze1708** [comment]
Da muss der Chefkoch noch etwas in der Suppe rühren 😋

Also ich kann dir gern auch noch Dateien senden, wenn du die zum Analysieren brauchst

**Comment by Polo1501** [comment]
Habe auch das Problem, gibt es mittlerweile eine Lösung?

**Comment by sla89** [comment]
Ich erhalte folgenden Fehler in der Console:

```
?0:151 Uncaught TypeError: Cannot read property 'getData' of undefined
    at getData (?0:151)
    at Object.getEntryFile (?0:158)
    at readFiles (?0:336)
    at ?0:327
    at zip.js:669
    at FileReader.reader.onload (zip.js:180)
```

ioBroker 3.7.8
knx adapter: 0.8.6
ETS 5.7.2

**Comment by obodeldog** [comment]
Mach mal ein update des knx-Adapter. Der ist ja uralt. -------- Ursprüngliche Nachricht --------Von: sla89 <notifications@github.com>Datum: Di., 4. Feb. 2020, 21:54An: "ioBroker/ioBroker.knx" <ioBroker.knx@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Betreff: Re: [ioBroker/ioBroker.knx] Einlesen aus der ETS 5.7.1 fehlerhaft (#55)Ich erhalte folgenden Fehler in der Console:
?0:151 Uncaught TypeError: Cannot read property 'getData' of undefined
    at getData (?0:151)
    at Object.getEntryFile (?0:158)
    at readFiles (?0:336)
    at ?0:327
    at zip.js:669
    at FileReader.reader.onload (zip.js:180)

ioBroker 3.7.8
knx adapter: 0.8.6
ETS 5.7.2

**Comment by Simpson75** [comment]
Hallo,
seit dem Update der ETS auf 5.7.4 kann ich die Projektdatei nicht mehr einlesen....
Gibts schon Lösungen dafür?
knx 0.8.6
Grüße

**Comment by TA2k** [comment]
Den Verwahrungsort im iobroker auf latest stellen und dann die 1.0.37 installieren

**Comment by Simpson75** [comment]
Habe neue Version...
bekomme den knx nicht mehr auf grün
und die Datei lässt sich nicht einlesen... :-(

**Comment by TA2k** [comment]
Welche Version hast du installiert? Was sagt der Log?

**Comment by Simpson75** [comment]
9314) starting. Version 1.0.37 in /opt/iobroker/node_modules/iobroker.knx, node: v8.16.1

Adapter jetzt grün - hat die lizenz rausgeschmissen...

Ältere Datei lässt sich einlesen
Bei der neueren läuft der untere "Balken" nicht ganz durch ...

**Comment by Simpson75** [comment]
So habe festgestellt das die Datei ein Passwort benötigt...
Kann man die Datei auch ohne Passwort speichern?

**Comment by Simpson75** [comment]
Habe ohne Passwort gespeichert...
Einlesen läuft nun durch...
Objekte fehlen trotzdem :-(

**Comment by chefkoch009** [comment]
Habe so eben die Anpassungen auf ETS Projekte für 5.7.4 durchgeführt. Bitte einmal testen.

**Comment by samot13** [comment]
Auch mit der 1.0.39 Version funktionieren die Objekte nicht richtig.
Das Projekt kann ohne Fehler eingelesen werden aber nur die "Schalt" Objekte
0/1 bzw. true/ false werden auf den Bus gesendet.
Ein neu importiertes Temperatur Objekt (DPT 9.001) wird nicht richtig interpretiert und es wird auch nur 0 oder 1 gesendet.
Alte DPT 9.001 Objekte erstellt und importiert mit (ETS 5.6.6 und Adapter 1.0.20) funktionieren und die Temperatur wird auf den Bus gesendet. (auch mit 1.0.39)
Genau so verhält es sich mit allen nicht schalt Objekten z.b. auch mit Dimmwerte 0 .. 100% oder 4bit Objekten.

**Comment by chefkoch009** [comment]
Wurden die Objekte im ioBroker vorher gelöscht? Lässt sich die Projektdatei nach einem update der ETS auf die letzte Version importieren? Es hat sich zwischen den ETS-Versionen in der Projektdatei ziemlich viel getan.

**Comment by samot13** [comment]
Ja, die Objekte wurden vorher gelöscht. Ich habe die ETS von 5.6.6 auf 5.7.2 upgedatet und damit lässt sich die Projektdatei mit dem Adapter Importieren. Ich habe auch schon versucht in einer neuen KNX Instanz das Projekt neu zu importieren aber dann gehen die "alten" Objekte bis auf die "Schalt Objekte" auch nicht mehr.
Ist das Projekt Datei für alle 5.7.X Projekte gleich? Leider komme ich nicht mehr zu 5.6.6 zurück.

**Comment by chefkoch009** [comment]
bitte neue version testen

**Comment by Percy2Live** [comment]
> bitte neue version testen

Leider scheint auch die neue Version nicht zu funktionieren. Import eines ETS 5.7.2 Projekts funktioniert nicht. Lesender Zugriff ist möglich, schreiben scheinbar nicht. Im Log tauchen nur vereinzelt warnings auf, aber kein Error. Hilft es dir, wenn ich dir mein Projekt zur Verfügung stelle?

**Comment by Percy2Live** [comment]
Die Probleme mit der aktuellen ETS Version bestehen scheinbar nach wie vor. Kann ich etwas tun, um hier weiterzuhelfen? Ich stelle auch gerne mein Projekt zur Verfügung

**Comment by githubtzzz** [comment]
Problem mit 5.7.4 export und import in Iobroker kann ich bestätigen. Haben jetzt auf 5.7.4 upgedated. Davor gings ohne PRobleme.Jetzt ist nur noch lesen möglich. Schreiben auf den Bus geht nicht mehr.

**Comment by Percy2Live** [comment]
@chefkoch009 sind die Probleme bekannt und eine Lösung in Arbeit oder können wir durch zusätzliche Logs / Projektdateien / etc. irgendwie bei der Ursachenfindung unterstützen?

**Comment by vonCartman** [comment]
Heute habe ich festgestellt das der Adapter stellt her die Objekte wenn das KNX Projekt mit ProjektAssistant im ETS erstellt wurde. 

ETS v.5.7.4

Vielleicht hilft euch diese Information.

**Comment by baerengraben** [comment]
Auch ich habe das Problem, dass das Schreiben auf den KNX-Bus nicht mehr geht. Lesen geht noch. Bis vor kurzem ging alles noch ohne Probleme. Dann habe ich einen neuen Projekt-Import aus ETS 5.7.4 gemach. Seit dem geht das Schreiben auf den KNX-Bus nicht mehr.
Habe sogar testeshalber einen komplett neuen iobroker aufgebaut, mit allen Updates, etc. Auch auf diesem ganz neu aufgebauten Raspi geht das Schreiben auf den KNX-Bus nicht.
Ist Abhilfe in Sicht? Kann ich unterstützen?

**Comment by Percy2Live** [comment]
Ich konnte bei mir ein paar der Probleme lösen (nicht alle), indem ich mir die read/write Einstellungen der GA-Objekte im ioBroker angeschaut habe. Chefkoch hat das mal in einem anderen Beitrag beschrieben, hier hat sich das Verhalten des Adapters bei irgendeinem Update mal geändert, sodass man sich diese Einstellungen genauer ansehen muss.

Schau dir mal eine der Adressen, welche sich nicht schreiben lässt, mit dem Busmonitor an. Was geschieht, wenn der ioBroker versucht, die Adresse zu schreiben? Falls du hier ein GroupValueRead statt eines GroupValueWrite siehst, hängt der Fehler mit dem Read/Write Zugriffsrechten im ioBroker zusammen. In diesem Fall hat es mir geholfen, bei dem entsprechenden Objekt den Haken für den lesenden Zugriff zu entfernen (nur noch schreibender Zugriff). Danach die KNX Adapter Instanz einmal neustarten. Bei mir konnte ich danach im Busmonitor sehen, dass der Adapter jetzt ein GroupValueWrite verwendet, was dann auch endlich funktionierte.

**Comment by baerengraben** [comment]
@Percy2Live : Vielen Dank! Genau das ist/war mein Problem. Wenn ich den lesenden Zugriff entferne und die Instanz neu starte, wird der Wert tatsächlich wieder korrekt auf den Bus geschrieben :)
Leider habe ich über 3000 Objekte. Aber die wichtigsten kann ich so sicher zurechtbiegen. 
Hoffe es kommt bald ein Patch.

**Comment by chefkoch009** [comment]
Die Lösung dieses Problems ist leider nicht trivial. Der Grund:
Es gibt Hersteller, die setzen pauschal KLSÜ Flags auf alle KO‘s. Normaler Weise gibt es ein Schaltobjekt und ein separates Statusobjekt. So das das Schaltobjekt mit KS und das Statusobjekt mit KL bzw KLÜ belegt werden. Das wäre der elegantere Weg. Es gibt auch KO‘s da wird der Status durch anhängen der lesenden Adresse an die schreibende übermittelt. Und das macht die Sache beliebig kompliziert. Nach welchem Kriterium soll beim Import nun ausgewählt werden ob es sich um einen Status handelt oder nicht. Also: 
Wenn ich davon ausgehe, das KLSÜ durch den Hersteller gesetzt wurden. Dann weiß ich nicht, ob das das ein Schalt- oder Statusobjekt ist. 1) ich nehme an es ist ein Schaltobjekt. Dann folgt, diese Adressen werden beim Start nicht abgefragt und können nicht gelesen werden.
2) ich nehme an, diese Adressen sind ein Statusobjekt. Dann folgt, diese Adressen können gelesen werden und werden beim Start abgefragt.

Insgesamt also: wenn das KO tatsächlich ein Schaltobjekt ist und falsch bewertet wurde also als Statusobjekt, dann wird es beim Adapter Start „durch eine 1 gelesen“. Heißt der aktor interpretiert das als einschaltsignal. Für DPT1.xxx grenzwertig gültig. Alle anderen DPTs werden ignoriert. 

Aus diesem Grund habe ich mich dafür entschieden die Auswertung auf Statusobjekt zu setzen, denn mit einem Schaltaktor kann man ja auch andere Sachen schalten außer Licht.

**Comment by baerengraben** [comment]
@chefkoch009 : Vielen Dank für die Zusatzinfos. Das kann ich so nachvollziehen. 

Verwirrend war für mich vorallem, dass der Import ja mal tadellos funktioniert hat und nach einer Neuinstallation, mit den allerneuesten Version, plötzlich nicht mehr. Das ist evtl. jetzt etwas OffTopic. Aber ich habe in der Zwischenzeit noch einen weiteren Test gemacht, auf den ich im ioBroker-Forum aufmerksam geworden bin:

- Komplette Deinstallation des Adapters
- Neu installiert, mit Version 1.0.20
- Import der ETS 5.7.4 Projekt-Datenbank

Resultat:
- Bis jetzt scheint alles wieder zu funktionieren. Die besagten Objekte werden jetzt wieder auf den Bus geschrieben

Anschliessend habe noch ich ein Update auf die Version 1.0.39 durchgeführt. Auch damit jetzt funktioniert der KNX-Adapter weiterhin wie gewünscht. 

Einzig ein Projekt-Import mit Version 1.0.39 ergaben also die besagten Probleme. 

Habe ich mir evtl. mit diesem Vorgehen jetzt andere Probleme eingehandelt, welche ich bis jetzt noch nicht erkannt habe? :)

**Comment by Videonisse** [comment]
@matze1708 Could you close this Issue or what is your status?

**Comment by Videonisse** [comment]
As a reference, I have created two new Feature Request as Issues related to some of the above discussions:

https://github.com/ioBroker/ioBroker.knx/issues/160
https://github.com/ioBroker/ioBroker.knx/issues/158
