### ISSUE TITLE
Unbekannter Datentyp beim Schalten

### ISSUE THREAD

**Issue by bassball** [ioBroker/ioBroker.knx#6]
Hallo!

Habe eine iobroker Instanz auf einem Ubuntu 16.04 laufen und eine KNX Anbindung über einen Raspi mit USB Schnittstelle auf dem knxd läuft.
Der Import vom ETS4 Projekt funktionierte problemlos, ich seh auch alle Datenpunkte, aber ich bekomms nicht hin dass ich einen Schaltbefehl auf eine Gruppenadresse schicke. Egal ob ich über die MobileUI was sende oder direkt über den iobroker-Objekte-Tab einen Wert sende: Es schaltet nichts und im Log seh ich nur folgenden Eintrag:

Cannot control "knx.0.Haupthaus.Beleuchtung.Bel_Lagerraum_klein_SCH", because invalid type: 

Ich habe bei der Konfig sämtliche  Datentypen durchprobiert, aber das Resultat ist dass selbe. Die KNX Status Elemente funktionieren anstandslos, also an der eigentlichen Bus Anbindung kanns eigentlich nicht liegen. 
Setzte ich den Schaltbefehl gegen die Status-Gruppenadresse des Aktors funktioniert es, allerdings wird dann nur in der Visu umgeschaltet, das Licht bleibt klarerweise trotzdem finster.
Ich habs auch alternativ über einen Loxone Miniserver als IP Schnittstelle probiert, mit dem gleichen Resultat.

Ich vermute den Fehler in meinem KNX Projekt, allerdings weiß ich mittlerweile nicht mehr wo ich noch schauen sollte.

**Comment by chefkoch009** [comment]
Hallo bassball,

sind in der ETS alle Datenpunkttypen hinterlegt? Wenn nicht, dann ist das was Du beschreibst das entsprechende Verhalten.

**Comment by bassball** [comment]
Vielen Dank! Ich bin bisher davon ausgegangen dass es reicht wenn der Aktor den richtigen Datentyp hat und das hab ich auch mehrmals geprüft.
Nach deiner Antwort ist mir eingefallen das in meiner Gruppenadresse auch ein Taster hinterlegt ist, und der hatte keinen Datentyp hinterlegt.
Da der Taster an erster Stelle war, nahm der Import offenbar den leeren Datentyp.
