### ISSUE TITLE
KNX Verbindungsprobleme bei mehreren Netzwerkadaptern

### ISSUE THREAD

**Issue by FoxRo** [ioBroker/ioBroker.knx#60]
Hallo
Hatte mir in den letzten Tagen die Zähne ausgebissen, den KNX Adapter für ioBroker zum laufen zu kriegen.
Immer stand die KNX Verbindung auf "Gelb"
Grund war, dass ich an meinem Laptop mehrere LAN Adressen habe (Wireshark Treiber, VirtualBox und eine WIFI) Alle haben eine eigene IPv4 - wie sich das gehört.
Beim Start des KNX Adapters scheint dieser sich aber bei mir immer die anderen Adapter als der korrekte WIFI Adapter zu schnappen, was dann promt ins "Elend" führt.
Nachdem ich die anderen Adapter deaktiviert hatte, hat sich dann der KNX Adapter die korrekte LAN Verbindung geschnappt und auch sauber die Verbindung zum KNX aufgebaut.
Resultat ist jetzt, dass ich parallel weder Wireshark noch VirtualBox laufen lassen kann - ziemlich unschön!
Frage: Gibts irgendwo eine Möglichkeit, dass ich die zu verwendende LAN "Schnitte" für den KNX Adapter irgendwo fix setzen kann? (zb. So wie im Admin Adapter?)
Falls nicht, wäre es wirklich hilfreich, wenn dies für eine nächste Version vom KNX Adapter vorgesehen werden könnte.
Vielen Dank!
..... und Danke für die grossartige Arbeit!

**Comment by dreamdancer27** [comment]
Hallöchen, ich habe einen Intel NUC mit zwei NICs laufen, der eine für mein normales Netzwerk, der andere in einem anderen VLAN speziell für KNX aus Sicherheitsgründen.
Mein Problem ist an der stelle das gleiche :(

..... und auch von hier ein grosses Dankeschön, für die tolle Arbeit :+1:

**Comment by chefkoch009** [comment]
Das Argument ist berechtigt. Vielen Dank für den Tipp....mein Raspi hatte immer nur 1 Schnittstelle. ;-)
Ob ich es noch im nächsten Release schaffe, kann ich noch nicht sagen.

**Comment by chefkoch009** [comment]
Hallo,

lange hat es gedauert. Bitte die neue Version testen. Dann diesen issue schliessen.
Danke.

**Comment by dreamdancer27** [comment]
Guten Morgen,
und vielen Dank :)

Leider ist nichts zu sehen, wo ich eine andere Lokale Netzwerkkarte wählen könnte.

Wenn ich das richtig sehe, soll eine Option in der Adapterkonfiguration sein, über "nur neue Objekte zulassen", dort ist leider aber nichts.

**Comment by chefkoch009** [comment]
Hallo, hast du Version 1.0.30 installiert? Wenn der adapter Dialog noch genauso aussieht wie vorher, dann mal Browser Cache löschen und Seite neu laden.

**Comment by dreamdancer27** [comment]
Hey,
er sieht noch genau so aus.

Beides gerade noch einmal überprüft, es ist Version 1.0.30, den Cache habe ich geleert, auch einen Browser verwendet, auf dem ich die Seite vorher nie geöffnet hatte.

**Comment by chefkoch009** [comment]
Dann führe bitte folgendes aus:
1) cd /opt/iobroker
2) iobroker u knx 

Anschließend Seite im Browser neu laden.

**Comment by dreamdancer27** [comment]
Entschuldige die späte Antwort :(

Dennoch, wir haben einen Gewinner, it works like a charm :+1: 
Eine Frage habe ich noch ... was genau bewirkt dieser Befehl?
Ich werde das in den nächsten Tagen dann mal in der VLAN Umgebung testen, ob die KNX IP Seite dann so in trockene Tücher gebracht werden kann ... was gehen sollte ;)

Kann / Soll ich das Issue schliessen?

Vielen Vielen Dank :+1:

**Comment by chefkoch009** [comment]
Schön das es funktioniert hat.

Die Adapter Konfiguration ist eine „Webseite“ die in den IoBroker eingebunden wird. Wenn ich als Programmierer diese ändere, dann muss der IoBroker das auch mitbekommen. Dieser Befehl triggert das an. 

Wenn das mit dem VLAN bei dir läuft, dann bitte kurze Info und dann den case schließen.

**Comment by FoxRo** [comment]
Hallo chefkoch009
Habe es gerade auch auf meinem Laptop mit den aktivierten virtuellen NICs getestet und es läuft auf Anhieb .. den richtigen Adapter gewählt und aus Ampel "Gelb" wird Ampel "Grün"! 
Aus meiner Sicht kann dieses Issue geschlossen werden, sobald das VLAN auch bestätigt ist.
Coole Arbeit! Danke Dir vielmals!

**Comment by dreamdancer27** [comment]
VLAN ist bestätigt, ein seperates Netz für KNX, steht und läuft stabil :+1: 
Also zu ...
