### ISSUE TITLE
Error DPT.js isDPT undefined : DPT[12.000]

### ISSUE THREAD

**Issue by mghomedev** [ioBroker/ioBroker.knx#61]
error	instance system.adapter.knx.0 Caught	2019-07-20 15:53:46.266	
error	by controller[0]: DPT.js isDPT undefined : DPT[12.000]

What do you need to fix that?

**Comment by Apollon77** [comment]
I think the full error message could help much

**Comment by mghomedev** [comment]
> 
> 
> I think the full error message could help much

That is the problem. More information is not obviously visible in the log display, not even when I set log mode to debug/silly. It happens during import of my ".knxproj" but the error does not seem to matter. 

Seems like the code just writes these two lines into the error log.

Since the wohle knx-adapter seems to be closed-source, I can also not look where this is shown. I have seen in older code that not all KNX-data types are defined, so it is probably just ignored. You might want to check if this data type is defined, and add it, since it seems to be used in practice.

I would do it myself if the source code would be available...

**Comment by chefkoch009** [comment]
The DPT12.000 is unspecified. Please choose a more concrete DPT like:
DPT 12.001 - DPT_Value_4_Ucount
DPT 12.100 - DPT_LongTimePeriod_Sec
DPT 12.101 - DPT_LongTimePeriod_Min
DPT 12.102 - DPT_LongTimePeriod_Hrs

But I also implement DPT12.000, as you requested, as 4-byte unsigned value. This will be available in the next release.

**Comment by TA2k** [comment]
Thanks because some devices use this unspecified dpt by default.

**Comment by mghomedev** [comment]
Ah, good to know. Indeed I did not choose DPT12.000 but the device suggested it by default.

> But I also implement DPT12.000, as you requested, as 4-byte unsigned value. This will be available in the next release.

Thanks, that sounds good.

**Comment by mghomedev** [comment]
P.S. It is a device that encodes error codes into a 4-byte bitfield, so none of the DPT-12 selections make sense. It is simply a plain unsigned 4-byte .

**Comment by chefkoch009** [comment]
Hallo,

lange hat es gedauert. Bitte die neue Version testen. Dann diesen issue schliessen.
Danke.

**Comment by mghomedev** [comment]
Der Fehler scheint weg zu sein, danke!
Dafür gibt es einen neuen vermutlich völlig unabhängig davon --> habe neues Issue aufgemacht: 
https://github.com/ioBroker/ioBroker.knx/issues/66#issue-484853792
