### ISSUE TITLE
Fehler beim schreiben - Cannot read property 'write' of undefined (ETS 5.7)

### ISSUE THREAD

**Issue by psychos4** [ioBroker/ioBroker.knx#63]
Ich habe den aktuellen KNX-Adapter 1.0.20 installiert, die erste Lampe kann darüber auch schon geschaltet sowie der Status visualisiert werden.

ABER: Bei manchen Objekten bzw. Adressen kann ich keine Werte auf den Bus senden, folgende Fehlermeldung im Log z. B. wenn ich das Garagentor öffnen möchte:

> TypeError: Cannot read property 'write'
> message knx.0.Türen__Tore__Fenster.Garage_Öffnen [object Object] Cannot read property 'write' of undefined

Was könnte das Problem / Ursache sein? Ich komme einfach nicht weiter. 😕

**Comment by TA2k** [comment]
Bitte immer die ETS Version angeben mit der du exportiert hast.

**Comment by psychos4** [comment]
ETS 5.7.2 (Build 743) ist derzeit die neuste.

**Comment by TA2k** [comment]
ETS 5.7 wird noch nicht unterstützt. Erst in der nächsten Version. Entweder mit 5.6 exportieren oder abwarten.

**Comment by chefkoch009** [comment]
Hallo,
der ETS-Export aus der Version 5.7.2 hat leider nicht mehr viel mit den Exporten der Vorgängerversionen zu tun. Ich arbeite mit Hochdruck an einem Update. Dabei lasse ich so um die 20 verschiedenen Exporte durchlaufen und bei jedem Durchlauf gibt es eine andere Überraschung.

Du kannst versuchen die bei Dir angelegten Objekte manuell anzupassen. In  deinem Fall fehlt im state die Property "write". Anbei....hast Du eine 2-stufige Architektur?

**Comment by psychos4** [comment]
3-stufige. 
Hatte Glücklicherweise noch einen Export aus der 5.6.6 Version, damit hat es nun geklappt. 
Vielen Dank! :)

**Comment by chefkoch009** [comment]
Hallo,

lange hat es gedauert. Bitte die neue Version testen. Dann diesen issue schliessen.
Danke.

**Comment by chefkoch009** [comment]
Keine Info, das es nicht funktioniert. Deshalb schliesse ich den issue.

**Comment by TheBigS1981** [comment]
Hallo chefkoch009,

ich habe gerade bei mir alles auf den neusten Stand (ETS und KNX-Adapter) gebracht und hab dann auch dieses Fehlverhalten feststellen können. Kannst Du das Issue wieder öffnen?

Ich erhalte folgende Fehlermeldung, wenn ich z. B. ein Rolladen steuern möchte oder ein Dimmbares-Licht schalte:

```
knx.0	2019-09-08 14:51:53.533	error	TypeError: Cannot read property 'write' of undefined at Object.stateChange (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:2799) at Object.change (/opt/iobroker/node_modules/iobroker.js-con
knx.0	2019-09-08 14:51:53.533	error	message knx.0.OG_Buero.Rolladen.OG_Buero_Rolladen_Bestimmte_Position [object Object] Cannot read property 'write' of undefined
```

Ein normales Licht kann ich problemlos schalten.

Das ganze tritt allerdings nur mit der Version 1.0.32 auf. Mit der Version 1.0.31 habe ich damit keine Probleme. Mein Projekt hat die ETS Version 5.7.2.
