### ISSUE TITLE
knxproj wird nicht eingelesen

### ISSUE THREAD

**Issue by mschluet** [ioBroker/ioBroker.knx#64]
Hallo,

ich versuche mein knxproj einzulesen aber ohne Erfolg.
Das Bild wechselt zum Import aber bewegt sich nicht weiter, im Log erscheint auch keine Ausgabe.

Hier meine installation:
{
  "language": "de",
  "hosts": [
    {
      "version": "1.4.2",
      "platform": "Javascript/Node.js",
      "type": "linux"
    }
  ],
  "node": "v12.8.1",
  "arch": "x64",
  "adapters": {
    "admin": {
      "version": "3.6.4",
      "platform": "Javascript/Node.js"
    },
    "discovery": {
      "version": "2.0.0",
      "platform": "Javascript/Node.js"
    },
    "tr-064": {
      "version": "0.4.18",
      "platform": "Javascript/Node.js"
    },
    "feiertage": {
      "version": "1.0.11",
      "platform": "javascript/Node.js"
    },
    "web": {
      "version": "2.4.1",
      "platform": "Javascript/Node.js"
    },
    "vis": {
      "version": "1.2.0",
      "platform": "Javascript/Node.js"
    },
    "daswetter": {
      "version": "2.8.0",
      "platform": "Javascript/Node.js"
    },
    "tankerkoenig": {
      "version": "2.0.6",
      "platform": "javascript/Node.js"
    },
    "vis-bars": {
      "version": "0.1.4",
      "platform": "Javascript/Node.js"
    },
    "vis-canvas-gauges": {
      "version": "0.1.5",
      "platform": "Javascript/Node.js"
    },
    "vis-weather": {
      "version": "2.3.0",
      "platform": "Javascript/Node.js"
    },
    "vis-hqwidgets": {
      "version": "1.1.2",
      "platform": "Javascript/Node.js"
    },
    "icons-ultimate-png": {
      "version": "1.0.1",
      "platform": "javascript/Node.js"
    },
    "vis-google-fonts": {
      "version": "0.1.0",
      "platform": "Javascript/Node.js"
    },
    "vis-fancyswitch": {
      "version": "1.1.0",
      "platform": "Javascript/Node.js"
    },
    "info": {
      "version": "1.4.1",
      "platform": "Javascript/Node.js"
    },
    "dwd": {
      "version": "2.4.3",
      "platform": "javascript/Node.js"
    },
    "backitup": {
      "version": "1.2.0",
      "platform": "Javascript/Node.js"
    },
    "sony-bravia": {
      "version": "1.0.1",
      "platform": "Javascript/Node.js"
    },
    "ical": {
      "version": "1.7.0",
      "platform": "Javascript/Node.js"
    },
    "vis-timeandweather": {
      "version": "1.1.7",
      "platform": "Javascript/Node.js"
    },
    "cloud": {
      "version": "2.6.2",
      "platform": "Javascript/Node.js"
    },
    "javascript": {
      "version": "4.1.14",
      "platform": "Javascript/Node.js"
    },
    "scenes": {
      "version": "1.1.0",
      "platform": "Javascript/Node.js"
    },
    "flot": {
      "version": "1.9.2",
      "platform": "javascript/Node.js"
    },
    "doorbird": {
      "version": "0.1.5",
      "platform": "Javascript/Node.js"
    },
    "knx": {
      "version": "1.0.20",
      "platform": "Javascript/Node.js"
    }
  },
  "vis": 350
}

Irgendeiner ne Idee?

**Comment by TA2k** [comment]
Zur Zeit gehen nur ets 5.6 exports

**Comment by mschluet** [comment]
Besser erstmal ein downgrade machen oder noch warten?

**Comment by TA2k** [comment]
Downgrade geht nur wenn das Projekt als ets 5.6 vorliegen hast.

**Comment by mschluet** [comment]
ok dann heisst es wohl warten :)

**Comment by chefkoch009** [comment]
Hallo,

lange hat es gedauert. Bitte die neue Version testen. Dann diesen issue schliessen.
Danke.

**Comment by mschluet** [comment]
Hallo,

vielen Dank für die neue Version, allerdings genau das selbe.
Es kommen keine Ausgaben und der Balken bewegt sich nicht.
Browsercache habe ich gelöscht.

**Comment by chefkoch009** [comment]
hallo mschluet,
melde Dich mal im Forum unter https://forum.iobroker.net/topic/3580/knx-adapter-%C3%BCberholt bei mir.

VG
chefkoch009

**Comment by mschluet** [comment]
ok dann mache ich hier mal zu :)
