### ISSUE TITLE
Adapter only sending "GroupValueRead" despite S flag

### ISSUE THREAD

**Issue by Garfonso** [ioBroker/ioBroker.knx#67]
Hi,
adapter 1.0.31 only sends GroupValueRead on some of my GAs. 1.0.20 did issue commands to them. I checked the flags and they were wrong (L was set but not S). So I changed them, did a new export and import but still no change. 

What ioBroker.knx sends to the bus:
`1057 | 24.08.2019 21:20:06,140 | vom Bus |   | Niedrig | 1.1.255 | - | 2/0/9 | J OG Spielzimmer auf/ab | 6 | GroupValueRead | `

The GA:
![ProblematicGA](https://user-images.githubusercontent.com/620860/63641905-66a5cc00-c6b6-11e9-823d-c34331b1d1ba.JPG)
`
  | Objekt | Gerät | Senden | Datentyp | K | L | S | Ü | A | Produkt | Applikation | Länge | Priorität | Gruppenadresse | Beschreibung
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | 40: Ausgänge 5-6 - Auf/Ab | 1.1.11 D2 Schaltausgang 20-fach, 16A C-Last | S | Auf/Ab | K | - | S | Ü | - | Schaltausgang 20-fach, 16A C-Last | STXM620D | 1 bit | Niedrig | 2/0/9 | J OG Spielzimmer auf/ab
  | 10: Bewegobjekt - Eingang 4 | 1.1.26 1.OG Flur Fenster Tasterschnittstelle 4fach plus | S |   | K | - | - | Ü | - | Tasterschnittstelle 4fach plus | Multifunktion.Zähler.LED 122A/1.2 | 1 bit | Niedrig | 2/0/9 | J OG Spielzimmer auf/ab
  | 7: Bewegobjekt - Eingang 3 | 1.1.26 1.OG Flur Fenster Tasterschnittstelle 4fach plus | S |   | K | - | - | Ü | - | Tasterschnittstelle 4fach plus | Multifunktion.Zähler.LED 122A/1.2 | 1 bit | Niedrig | 2/0/9 | J OG Spielzimmer auf/ab
`
The object in ioBroker:
`{
  "_id": "knx.0.Beschattung.auf_ab.J_OG_Spielzimmer_auf_ab",
  "type": "state",
  "common": {
    "name": "J OG Spielzimmer auf/ab",
    "type": "boolean",
    "role": "value",
    "read": true,
    "write": true,
    "update": false,
    "max": true,
    "min": false
  },
  "native": {
    "dpt": "DPT1.008",
    "address": "2/0/9",
    "addressRefId": "P-0454-0_GA-63",
    "statusGARefId": "",
    "actGARefId": "",
    "objRef": "O-10_R-374",
    "devName": "M-000C_A-122A-12-5131",
    "devInst": "P-0454-0_DI-27",
    "objectSize": ""
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1566674604766,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

What is confusing the adapter? And why did the behaviour change so much? Goal would be that it sends a boolean value to the first device, ie Schaltausgang 20-fach. 

Is there a way for me to revert to 1.0.20 for the time being?

**Comment by chefkoch009** [comment]
Hi,

I've seen the problem. Short explanation: on KNX a KO can send a value by itself on the Bus (Ü-Flag) or you can trigger it by sending a groupValue-Read (L-Flag). But ioBroker can Change the value or read a value. But in the read- Case you are Not able to trigger a READ. So the question for me was, how to make a read-trigger possible vor ioBroker. It Happens, If the READ AND WRITE Flags in the ioBroker objects are Set. That means If you Set the read-flag to false and the WRITE flag to true, then you will have the expected behaviour.

Read=true, WRITE=true =>you are able to trigger a groupValue READ
Read=false,WRITE =true=> write the given value on KNX-bus
Read=true, WRITE=false=> receive a value-change, but Not able to trigger a read

At the Moment i don't know how realize that in a better way.....so i'll be happy about suggestions.

**Comment by Garfonso** [comment]
Ok, now I understand how it is meant to work (but I'm not sure why the problem arose after an adapter update. Is this new behaviour?). So the idea is to make the status GA read & write = true, so if it is set in ioBroker, GroupValueRead is sent on the bus. And then you can configure the act GA and set read = false and write = true and write values with it, right? Ok.

From what I see, I do not really need the GroupValueRead a lot. But that might be different in other setups.

**Comment by chefkoch009** [comment]
Well you understood right. An active read should ideally only needed in Startup. But i want to apply the knx-features. If you Bridge KNX with other iot components it is Sometimes nessesary to have this Feature.

**Comment by Garfonso** [comment]
But so it is currently not possible with ioBroker to react to a GroupValueRead or fill a status GA. Like I have some zigbee lamps I switch with KNX controls. I created "empty" GAs for them and if something is written to the act GA ioBroker switches the zigbee lamps accordingly. But I can not write the status to a status GA, right? So I currently write the status to the act GA with ioBroker.

**Comment by chefkoch009** [comment]
I don't know If zigbee hast dedicated act and state channels. Generate 2GA's. One for act and one for state. And configure them crosswise with actGA and statusGA. Then write a Logic(f.e. with node-red,) that Points to the actGA and stateGA.

**Comment by Garfonso** [comment]
No, zigbee does not have dedicated act and state channels. But that is not so much the issue. 
I have small displays in my rooms which are connected to the KNX bus. I can tap on them and they send commands on an act GA. But they'll listen on a state GA for changes and display the state of eg. a lamp. So you can see if the lamp is on or off on the display and if you tap on the lamp you can switch it off/on and the command will be the "right" one (i.e. off, if the lamp is on and on, if the lamp is off).
If I switch the lamp from KNX, I have a script in iobroker which listens to the act GA and switches the zigbee lamp accordingly. But the other way round is not as trivial. If I switch the zigbee lamp in iobroker, I'd like to send something to the KNX bus so that the displays will know the state, too, and display the right state (and issue the right command, when tapped). 
Currently I have the script subscribe to the zigbee-state and just send on the act GA in KNX when the zigbee lamp is switched and it works ok. But from my understanding it would be more "KNX-like" to send on the state GA, but that is currently not possible from ioBroker (and a script), right?

**Comment by chefkoch009** [comment]
No, thats not right. You are able to "update" the stateGA without sending a read. You Just only have to Set the write flag to false and then Set the value of the statusGA with your Script. This will Update the value in actGA. That's the way. 
Oh by the way, you should change the value for stateGA If your zigbee sends the value AND ACK=true.

**Comment by Garfonso** [comment]
> No, thats not right. You are able to "update" the stateGA without sending a read. You Just only have to Set the write flag to false and then Set the value of the statusGA with your Script. This will Update the value in actGA. That's the way.

That is exactly, what is not working for me. I tripple checked the write flag (it is false, read flag is true, btw). If my script writes to the statusGA, I see a GroupValueRead on the KNX Bus on the statusGA. If my script writes to the actGA, I see the value with a GroupValueWrite on the actGA on the KNX Bus.
actGA and stateGA objects are correctly referenced in ioBroker.

> Oh by the way, you should change the value for stateGA If your zigbee sends the value AND ACK=true.
Sure, I do that.

**Comment by chefkoch009** [comment]
Hm...courious. Did you have restartet the adapter after changing the properties of the objects?

**Comment by Garfonso** [comment]
Yes, I did that. It is not even working today after a restart of iobroker, which happens every morning. Just checked everything again. If the scripts writes on the object for the status GA with write=false I will still see a GroupValueRead on that GA and no update of the state in the KNX Bus Monitor.

**Comment by chefkoch009** [comment]
Well, i will have a Look at this Point. So maybe it is better to have Something Like this: 
Read=true write= false => performs Like Ü-Flag
Read=true write=true=> performs Like R-Flag
Read=false WRITE=true=> performs Like S-Flag
?

**Comment by chefkoch009** [comment]
Any news or updates?

**Comment by Garfonso** [comment]
To be honest I don't really know what your proposal would mean. For me the current situation works, after I understood what is happening in what state of read/write flags and adjusted my system to the current state.

**Comment by chefkoch009** [comment]
Thanks for your response. The readme is in process but takes a lot of time. But for now I close this issue.
