### ISSUE TITLE
Rückmeldeobjekte

### ISSUE THREAD

**Issue by perfSE** [ioBroker/ioBroker.knx#7]
Wie soll ich Rückmeldeobjekte ins ioBroker bringen? Wenn ich z.B. einen Slider im VIS einsetze um einen Dimmer zu räpresentieren, müsste der Slider von sowohl dem Dimmerobjekt als dem Rückmeldeobjekt beeinflusst werden. Geht das?

Hat das etwas mit "statusGARefId" zu tun?

**Comment by chefkoch009** [comment]
Nun sollte es funktionieren. Ich habe nun ein update auf dem act-object eingefügt, für den Fall das sich das state-object ändert.
