### ISSUE TITLE
Raum und Funktion aus GA ableiten

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#70]
Da ioBroker sehr stark von den enums Raum und Funktion abhängig wenn man Datenpunkte automatisiert nutzen möchten.
Deswegen wollte ich die Idee einbringen, dass man ein regex definieren kann aus dem man mit $1 und $2 Raum und Funktion definieren kann.

Ausserdem könnte Datenpunkte die eine Regex Übereinstimmung aufweisen (ein Gerät sind) zu einem Channel zusammenfassen.

Somit könnte man eine Kompatibilität zum iobroker.TypeDetector herstellen
https://github.com/ioBroker/ioBroker.type-detector

**Comment by chefkoch009** [comment]
Wenn in der ETS die Geräte sauber in die Gebäudestruktur einsortiert sind, dann wird beim Import auch die Raumzuordnung durchgeführt. Eine Raumerkennung über die GA-Namen macht keinen Sinn, weil diese beliebig komplex vergeben werden. 

> Ausserdem könnte Datenpunkte die eine Regex Übereinstimmung aufweisen (ein Gerät sind) zu einem Channel zusammenfassen.
Das wird bereits gemacht. Wenn beim Import herausgefunden wird, das eine ActGA eine StatusGA hat, dann wird dies über die properties "actGARefId" und "statusGARefId" relisiert. Dabei funktioniert die actGA als sozusagen channelmaster und wird durch die statusGA aktualisiert.

**Comment by TA2k** [comment]
Das Problem ist aber zb. ein LED Controller der dem Raum Hauptverteilung zugeordnet ist und Die Beleuchtung für 4 Räume übernimmt. Diese Information über den konkreten Raum und Funktion  ist in der GA abgebildet.

Im Objektbaum gibt es kein State vom Typ Channel somit funktioniert der TypeDetector nicht.
Damit ist keine automatische Integration in iobroker.iot und die verfügbaren Vis möglich.

**Comment by chefkoch009** [comment]
Wenn es einen Taster in dem Raum gibt, der diesen LED Controller steuert, dann ist darüber die Zuordnung getroffen. Man hat auch die Möglichkeit die Raumzuordnung selbst zu bearbeiten.

Tendenziell würde ich das mit dem linkeddevices Adapter machen. Der erstellt die Channels zu states, wie z.B. aus knx. Und darüber sollte auch der TypeDetector funktionieren.

Die Integration in Vis bereitet (bei mir) keine Probleme. An welcher Stelle entsteht bei Dir das Problem?

**Comment by TA2k** [comment]
Z.b im Material UI sind alle meine Lampen im HV wie in der ETS zugeordnet.
Ich nutze MDT Smart Taster 2 die nicht nur die Beleuchtung steueren bzw MDT PIR um die Beleuchtung zu steuern aber damit wird kein Channel oder Device erzeugt was mit typedetector funktioniert.
Man kann natürlich mit virtuellen Devices arbeiten aber per Hand jetzt nochmal 500 Datenpunkte neu anordnen damit sie der ioBroker Hierarchie entsprechen ist für mich nicht sinnvoll.

**Comment by tavoli-rgb** [comment]
hallo ta2k 
sry dass ich mich einklinke, stehe aber momentan vor dem gleichen problem
hast du für dich schon eine lösung gefunden?

**Comment by TA2k** [comment]
Nein wir können nur beten das chefkoch die Funktion integriert oder dass der Adapter irgendwann OpenSource wird.

**Comment by ZeroQool007** [comment]
> Nein wir können nur beten das chefkoch die Funktion integriert oder dass der Adapter irgendwann OpenSource wird.

Die Source liegen doch hier in Github!

**Comment by TA2k** [comment]
Die Source liegt nicht hier in Github! Der Adapter ist nicht OpenSource. Er wird obfuscated bei der Installation heruntergeladen.

**Comment by chefkoch009** [comment]
@TA2k: beten wird an dieser Stelle nichts bringen. Ich denke man sollte es ganz irdisch angehen. Schreibe mir dazu bitte mal eine PN im iobroker Forum.
