### ISSUE TITLE
problem with the conversion of the knx-project files to automatically create the objects in iobroker

### ISSUE THREAD

**Issue by STPOGY** [ioBroker/ioBroker.knx#73]
Dear all,
i have problems with the conversion function of the knx project file due to get the correct adresses in the iobroker surrounding.
That means: adresses from 1/1/1 to 15/x/x were converted correct.
KNX Adresses from 16/1/1 were converted to adresses starting again at 1/1/1 in the iobroker.
So if i have two variables with different names an for example the adress 1/1/1 and 16/1/1 then the conversion function will map them to one adress.

kind regards.

**Comment by STPOGY** [comment]
Hallo Zusammen, Hallo chefkoch009,
ich wollte nochmal zu diesem Problem nachfragen.
Habt Ihr beim Import von KNX Files ebenfalls das Problem, dass KNX Adressen grösser 16/1/1 nicht dort hin gemappt werden?
Vielen Dank !
MFG Steffen

**Comment by STPOGY** [comment]
Hallo Zusammen,
leider hab ich das Problem mit der Adresskonvertierung (wie oben beschrieben) der KNX Projectfiles nach wie vor.
Zur Konvertierung der Projektdateien hab ich im IOBroker die aktuellste KNX Adapterversion (1.0.42) im Einsatz.
Könnt Ihr mein Problem nachvollziehen?
Gibt es eine Chance auf ein Update des KNX Adapters?
Falls gewünscht/gewollt kann der Adapter auch gerne "gemeinsam" weiterentwickelt werden.
MFG Steffen

**Comment by RESDE** [comment]
Hallo, diese Probelem sind bisher nicht bekannt. Schick mir mal bitte Deine ETS Datei, dann schaue ich mir das an. Du findest mich im IOBroker Forum als User RES_DE. Werden wir schon hinbekommen...

**Comment by RESDE** [comment]
@STPOGY Ist Dein Issue noch akut bzw. hast Du das Angebot der Projektfile prüfung oben gelesen?

**Comment by STPOGY** [comment]
Hallo Lieber RES,

ja mein Problem bestaht nach wie vor.

Leider hab ich von Dir keine Mailadresse um die Datei zu übertragen.

Kannst Du mir deine Mailadresse durchgeben?

Vielen Dank !

MFG Steffen

Am So., 14. Feb. 2021 um 12:30 Uhr schrieb RES <notifications@github.com>:

**Comment by RESDE** [comment]
Hallo,

Schick mir bitte deine Etsprojektdatei an:
Reinersmail@yahoo.de
Packe bitte den GA Report aus der ETS dabei?
Welche GAs hatte Du Dir schon in IOBroker konkret angeschaut die nicht funzen?
Welche Adapter hast Du noch in Benutzung? Screenshot vom View auf Deine Instanzen...
Was für ne Hardware beflügelt den IOhost?
Grüsse
Reiner

**Comment by STPOGY** [comment]
Hallo Zusammen,

Korrektur - nach nochmaligem Test mit dem Adapter 1.0.39 besteht das Problem nun nicht mehr.

MFG Steffen
