### ISSUE TITLE
Wenn kein Netzwerk ausgewählt ist und die Optionen (Debug) gespeichert wird baut der adapter keine Verbindung auf

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#74]
Wenn kein Netzwerk ausgewählt ist und die Optionen (Debug) gespeichert wird baut der adapter keine Verbindung auf. Alte Versionen haben noch kein Adapter gewählt.

**Comment by chefkoch009** [comment]
Richtig...ein Netzwerk MUSS ausgewählt sein.
