### ISSUE TITLE
KNX connection problem with Timberwolf Server

### ISSUE THREAD

**Issue by ms20de** [ioBroker/ioBroker.knx#78]
I'm working for Elaborated Networks GmbH, we are developing and building a product called Timberwolf Server.
Timberwolf Server is hard and software to control your smart home.
The server features a KNX TP interface with KNX IP tunneling options.
The KNX stack used is validated and certified by the KNX Association.

Our users have reported problems connecting ioBroker.knx with our KNX IP interface.
**The KNX IP connection is dropped after two minutes.**
We invested some time to debug this issue.
It looks like ioBroker.knx sends a malformed KNX connection request.
In the connection request two pairs of IP address and port must be specified, one for the data and the other for the control connection.
If a KNX IP client want to use NAT mode, then all addresses and ports should be filled with zeros.
Our findings say the ioBroker.knx fills **both addresses with real data, but both ports with zeros**.
So your KNX tunnel endpoint doesn't know if ioBroker.knx wants to use NAT mode or not for the tunnel.
We checked knxd and ETS, both sending all zeros for address and port in NAT mode.

If you need additional information, please respond to this ticket.

Best Regards,
Matthias Schmidt
DevOps Engineer

**Comment by chefkoch009** [comment]
is fixed since v1.0.37
