### ISSUE TITLE
Changing objects from mqtt does not send to knx

### ISSUE THREAD

**Issue by RobertHerter** [ioBroker/ioBroker.knx#8]
Hello,

i don't know where exactly the Problem ist, but i try to explain.

I have two adapters knx an mqtt, both of them are working flawless alone, and every change of knx is send to mqtt without Problem. But if i send a knx.object via mqtt, the object in iobroker is changing, but not send to knx. 

Hope this explains the Problem clear.

**Comment by RobertHerter** [comment]
Found the Problem, message from mqtt was ack: true so it is not sent over knx.

**Comment by chefkoch009** [comment]
solved.
