### ISSUE TITLE
Import schlägt fehl

### ISSUE THREAD

**Issue by Missenberger79** [ioBroker/ioBroker.knx#80]
Moin,
wollte am Wochenende einsteigen und habe nun das Problem das der Import der KNX Datei die unter 5.7.2 nicht zum importieren geht.

Es ist kein Passwort gesetzt. Der Adapter ist auf der 1.0.36. Die Datei würde unter 1.0.20 gehen. Jedoch sind hier alle Stati nicht gesetzt.

Eine alte 5.6.6 vom Oktober geht.

Im Log finde ich folgende Warnmeldung:

knx.0 | 2019-12-16 07:23:10.634 | warn | at runCallback (timers.js:705:18)
knx.0 | 2019-12-16 07:23:10.634 | warn | at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:224:41)
knx.0 | 2019-12-16 07:23:10.634 | warn | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4708:34)
knx.0 | 2019-12-16 07:23:10.634 | warn | at Adapter.emit (events.js:198:13)
knx.0 | 2019-12-16 07:23:10.634 | warn | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:6848)
knx.0 | 2019-12-16 07:23:10.634 | warn | at _0x601f89 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8157)
knx.0 | 2019-12-16 07:23:10.634 | warn | at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13770)
knx.0 | 2019-12-16 07:23:10.634 | warn | at Object._0x228177 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40114)
knx.0 | 2019-12-16 07:23:10.634 | warn | at _0x486492 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:15343)
knx.0 | 2019-12-16 07:23:10.634 | warn | at _0x3d0a60 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:11164)
knx.0 | 2019-12-16 07:23:10.634 | warn | (5709) TypeError: Cannot read property 'range' of undefined
knx.0 | 2019-12-16 07:23:10.633 | warn | (5709) States pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":567,"ack":false,"time":1576477390

Gibt es dazu schon eine Lösung?

danke

**Comment by icxcube** [comment]
Hallo,
wollte mein KNX Datein (ETS 5.7.3) in den Adapter 1.0.36 hoch laden was nicht funktioniert bekomme die 
gleiche Fehler Meldung wie @Missenberger79. Wird das mal gefixt ?
Das problem ist das man die ETS nicht auf eine unterere Version upgraden kann.

**Comment by Missenberger79** [comment]
Habe langsam die Befürchtung Chefkoch hat die Weiterentwicklung fallen lassen

**Comment by chefkoch009** [comment]
Hallo,

keine Panik, hab ich nicht. Bin momentan nur etwas ausgelastet. Der 5.7.3 Import Patch geht bald online.

VG 
chefkoch009

**Comment by ZeroQool007** [comment]
Du bist der Beste! Danke!

**Comment by Missenberger79** [comment]
Geht dann auch meine 5.7.2. 
mein Problem bezieht sich noch auf 5.7.2

Kann dir gerne meine 5.7.2 Datei zum Testen geben

**Comment by chefkoch009** [comment]
Wäre schön, wenn ich die bekommen könnte. Anbei: ein import mit einer Passwort gesicherten Datei funktioniert auch nicht. Bitte vorher prüfen.

**Comment by Missenberger79** [comment]
Gibt es hier eine Möglichkeit eine PN zu verfassen oder soll ich einen Link als PN über das Knx User Forum senden. 

Nein es ist kein PW gesetzt.  

Wie geschrieben, habe ich noch am Laptop die 5.6.6 und da noch ein Backup liegen. Dieses ging

**Comment by chefkoch009** [comment]
über knx forum.

**Comment by icxcube** [comment]
Hi,
das hört sich doch gut an würde dir auch meine KNX 5.7.3 Datei zur Verfügung stellen

**Comment by Missenberger79** [comment]
unter latest wird mir das 1.0.37 nicht angezeigt.

Habe auf meiner Testumgebung mal so installiert und bekomme dann folgende Fehlermeldungen:

opt/iobroker/node_modules$ npm i iobroker.knx@1.0.37
[sudo] Passwort für missenberger: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: osx-temperature-sensor@1.0.4 (node_modules/osx-temperature-sensor):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for osx-temperature-sensor@1.0.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ iobroker.knx@1.0.37
added 16 packages from 23 contributors in 3.894s

**Comment by subwoofer17** [comment]
Hallo zusammen,

ich habe auch die ETS 5.7.2 und mein Import schlägt leider auch fehlt mit der 1.0.37 wie auch der 1.0.36 :(

Gibt es hier schon eine Lösung oder Workaround?

knx.0 | 2020-02-09 08:44:52.100 | warn | at runCallback (timers.js:705:18)
-- | -- | -- | --
knx.0 | 2020-02-09 08:44:52.100 | warn | at Immediate.setImmediate [as _onImmediate] (/opt/iobroker/node_modules/iobroker.js-controller/lib/states/statesInRedis.js:227:41)
knx.0 | 2020-02-09 08:44:52.100 | warn | at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:4805:34)
knx.0 | 2020-02-09 08:44:52.100 | warn | at Adapter.emit (events.js:198:13)
knx.0 | 2020-02-09 08:44:52.100 | warn | at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:6963)
knx.0 | 2020-02-09 08:44:52.100 | warn | at _0x2aafe9 (/opt/iobroker/node_modules/iobroker.knx/knx.js:80:8351)
knx.0 | 2020-02-09 08:44:52.100 | warn | at Object.getGAS (/opt/iobroker/node_modules/iobroker.knx/knx.js:72:13603)
knx.0 | 2020-02-09 08:44:52.100 | warn | at Object._0x1424f8 [as convertAll] (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:40158)
knx.0 | 2020-02-09 08:44:52.100 | warn | at _0x1d36fc (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:38652)
knx.0 | 2020-02-09 08:44:52.100 | warn | at _0x3a2c96 (/opt/iobroker/node_modules/iobroker.knx/knx.js:44:37253)
knx.0 | 2020-02-09 08:44:52.100 | warn | (1673) TypeError: Cannot read property 'Space' of undefined
knx.0 | 2020-02-09 08:44:52.095 | warn | (1673) States system pmessage io.messagebox.system.adapter.knx.0 {"command":"projectFinished","message":null,"from":"system.adapter.admin.0","callback":{"message":null,"id":165,"ack":false,"time":158
knx.0 | 2020-02-09 08:44:11.381 | info | (1673) Connecting to knx GW: 192.168.3.50:3671 with phy. Adr: 1.1.243
knx.0 | 2020-02-09 08:44:11.375 | info | (1673) knx license is OK.
knx.0 | 2020-02-09 08:44:11.100 | info | (1673) starting. Version 1.0.37 in /opt/iobroker/node_modules/iobroker.knx, node: v10.19.0

MfG

Andre

**Comment by ZeroQool007** [comment]
Ich habe die ETS 5.7.2 Build 743 und KNX Adapter 1.0.36. 0-Probleme. Läuft super!

**Comment by chefkoch009** [comment]
Hallo Missenberger79,

du installierst in das falsche Verzeichnis.

Wie es geht steht hier:
https://www.iobroker.net/docu/index-23.htm?page_id=8511&lang=de

VG
chefkoch009

**Comment by chefkoch009** [comment]
Bitte auch die ETS aktualisieren und update auf Adapterversion 1.0.38.
