### ISSUE TITLE
Falsches Datum

### ISSUE THREAD

**Issue by Fareroo7** [ioBroker/ioBroker.knx#81]
Ich kriege ein falsches Datum im ioBroker.
In der ETS ist das richtige Datum, z.B.: 18.01.2020 (DPT 11.001)
und im ioBroker Objekt steht 1990-01-31T23:00:00.000Z

Kann es sein, dass der KNX-Adapter eine Fehler bei der Datumskonvertierung hat?

Mit der Uhrzeit (DPT 10.001) gibt es keine Probleme.

**Comment by chefkoch009** [comment]
Das ist richtig und wurde in V2.0.4 gefixt.
