### ISSUE TITLE
ioBroker.knx does not automatically reconnect

### ISSUE THREAD

**Issue by ccie32305** [ioBroker/ioBroker.knx#83]
Hi,
first of all thanks for your great work on iobroker and the knx adapter.

I figured out an issue when iobroker loses connectivity to the KNX IP router/IP Interface, it does not automatically reconnect.
For example if i unplug the KNX IP router/interface, the adapter does not reconnect and objects fail to update. The instance has to be stopped and enabled again otherwise objects to no longer update.
Usually the connection between iobroker and the KNX IP router should be stable as it is patched with network cables in the basement, but you'll never know. 
Currently i'm doing a lot of KNX testing and sometimes unplug the KNX IP router cable, that's why i figured out this issue
Using knx version 1.0.33

knx.0 | 2020-01-26 18:43:45.218 | info | (66259) Connected!   with 85 datapoints of 327 Datapoints over all.
-- | -- | -- | --
knx.0 | 2020-01-26 18:43:45.214 | info | (66259) Connected  - local UDP Server listening on 192.168.3.65:46145
knx.0 | 2020-01-26 18:43:45.210 | info | (66259) Debuglevel: 0    1
knx.0 | 2020-01-26 18:43:45.207 | info | (66259) Connecting to knx GW:  192.168.3.64:3671   with phy. Adr:  1.0.253
knx.0 | 2020-01-26 18:43:45.206 | info | (66259) knx license is OK.
knx.0 | 2020-01-26 18:43:45.096 | info | (66259) starting. Version 1.0.33 in /opt/iobroker/node_modules/iobroker.knx, node: v10.17.0
knx.0 | 2020-01-26 18:43:41.554 | info | (66244)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-01-26 18:43:41.547 | info | (66244)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-01-26 18:43:41.546 | info | (66244) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
knx.0 | 2020-01-26 18:43:41.545 | info | (66244) terminating
knx.0 | 2020-01-26 18:43:41.545 | info | (66244)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-01-26 18:43:41.544 | info | (66244) Got terminate signal TERMINATE_YOURSELF
knx.0 | 2020-01-26 18:43:40.440 | info | (66244) Connected!   with 85 datapoints of 327 Datapoints over all.
knx.0 | 2020-01-26 18:43:40.435 | info | (66244) Connected  - local UDP Server listening on 192.168.3.65:56202
knx.0 | 2020-01-26 18:43:40.432 | info | (66244) Debuglevel: 0    1
knx.0 | 2020-01-26 18:43:40.429 | info | (66244) Connecting to knx GW:  192.168.3.64:3671   with phy. Adr:  1.0.253
knx.0 | 2020-01-26 18:43:40.427 | info | (66244) knx license is OK.
knx.0 | 2020-01-26 18:43:40.315 | info | (66244) starting. Version 1.0.33 in /opt/iobroker/node_modules/iobroker.knx, node: v10.17.0
knx.0 | 2020-01-26 18:43:35.794 | info | (54563)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-01-26 18:43:35.792 | info | (54563)  STATE_NOT_CONNECTED : Stop connection :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-01-26 18:43:35.791 | info | (54563) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
knx.0 | 2020-01-26 18:43:35.791 | info | (54563) terminating
knx.0 | 2020-01-26 18:43:35.790 | info | (54563)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-01-26 18:43:35.788 | info | (54563) Got terminate signal TERMINATE_YOURSELF

**Comment by chefkoch009** [comment]
Please update to 1.0.38...you are running 1.0.33.
