### ISSUE TITLE
Hex to DEC DPT 12.001

### ISSUE THREAD

**Issue by 1704eu** [ioBroker/ioBroker.knx#84]
Hi, 

ich glaube, dass die Convertierung von hex nach dec bei DPT 12.001 falsch ist. Laut Busmonitor in der ETS habe ich:
00 00 93 C5  |  37830 counter pulses im entsprechenden Objekt im ioBroker habe ich dafür aber 3314745344 stehen. Convertiere ich das zurück in hex bekomme ich C5 93 00 00. Kann es sein, dass die Konvertierung "falsch rum" liest?

Danke Benni

**Comment by chefkoch009** [comment]
auf was für einen processor läuft der IoBroker?

**Comment by 1704eu** [comment]
Läuft auf einem qnap virtualisiert. CPU 

Intel Celeron J1900 Quad-Core 2,0 GHz Prozessor
--

**Comment by spaceman667** [comment]
Ich kann diese Verhalten bestätigen.

Bei einem Datenpunkt vom Typ DPT 12.001 erhalte ich folgenden Wert in ioBroker.knx: 916545280 (entspricht hex 36 A1 5F 00)
Richtig lt. Zähler ist allerdings 6267190 (entspricht hex 00 5F A1 36) also die einzelnen Bytes in genau umgekehrter Reihenfolge.

Läuft auf einem raspi 3.
Ich kann das Verhalten in den Adapter-Versionen 1.0.20, 1.0.39 und 1.0.42 reproduzieren.

Konnte das Ganze über ein Script korrigieren, da die Zählerimpulse sowieso noch umgerechnet werden müssen. Dennoch wäre es schön, wenn auch DPT12.*-Werte richtig angezeigt würden.

**Comment by Pharaun32** [comment]
@spaceman667 

Kannst du mir sagen mit was für einem Skript du das Problem gelöst hast?
Das Problem besteht ja offensichtlich bis heute noch und macht ein Monitoren meiner Verbrauchswerte schwer.

Zumindest sind bei mir alle 4 byte unsigned Werte der DPT 12* falsch

@chefkoch009 Gibts hier noch Hoffnung auf eine Lösung?

**Comment by Videonisse** [comment]
I can confirm the above behaviour. I'm using v 1.0.45 and Debian Buster 64-bit running on ESXi 6.5.

Writing Hex c5 93 00 00 from Busmonitor in ETS5 results in 37829

![image](https://user-images.githubusercontent.com/13684218/116104872-18c64000-a6b1-11eb-9f61-755d45865c08.png)

Writing 00 00 93 c5 results in 3314745344 
![image](https://user-images.githubusercontent.com/13684218/116105344-83777b80-a6b1-11eb-807e-6073a68da841.png)

**Comment by spaceman667** [comment]
@Pharaun32
Hab mir eine Funktion convertCounter geschrieben, der ich den falschen Wert und die Soll-Länge in Byte mitgebe - also 4.
Darin wird der falsche Wert in einen Hex-String umgewandelt, evtl. führend mit Nullen auf die Soll-Länge aufgefüllt und anschließend Byteweise (je 2 Character des Strings) umgekehrt in einen neuen String geschrieben.

Sieht bei mir folgendermaßen  aus:

```javascript
on({id: 'knx.0.Informationswerte.Allgemein.ZaehlerstandHStrom', change: 'any'}, function (obj) {
    var zaehlerstandNeu = convertCounter(obj.state.val, 4)/100;
    setState('0_userdata.0.informationswerte.zaehler.haushaltsstrom_zaehlerstand', zaehlerstandNeu);
});

function convertCounter(value, bytes) {
    var convertedValue = "";
    var myHex = value.toString(16);

    while(myHex.length < (bytes*2)) {
        myHex = "0" + myHex;
    }

    for (let i = bytes-1; i >= 0; i--) {
        convertedValue += myHex[i*2] + myHex[i*2+1];
    }

    return parseInt(convertedValue, 16);
}
```
 Ich hoffe das hilft dir weiter.

**Comment by chefkoch009** [comment]
Klingt wie ein Little endian / big endian Problem.

**Comment by Pharaun32** [comment]
@chefkoch009 
Heißt das du hast bereits einen Ansatz für die Lösung und kümmerst dich darum? Das wäre nämlich wirklich super ;)

**Comment by ingel81** [comment]
Habe das ebenfalls festgestellt. Ist vermutlich eine big / little endian thematik hier. 

Quelle bei mir sind zwei KNX Wasseruhren und Zielsystem ein ioBroker auf einem Xeon.
Raw kommt auf der Gruppe laut ETS Diagnose an: 00 00 00 04
IoBroker gibt aus: 67108864

Ausgabe von 4 im IoBroker wäre korrekt ( in meinem Fall 4 m³ Wasser)

**Comment by ingel81** [comment]
> Das ist durchaus möglich. Im Adapter ist zwar eine Routine drin, die das abfangen soll, aber das konnte ich mangels Rechner mit unterschiedlichen Architekturen nicht richtig testen. Was ist das für ein Rechner, bei dem das auftritt?

Eine Intel® Xeon® E-2146G CPU. Als stinkormaler x86 PC eigentlich und damit little endian.

**Comment by chefkoch009** [comment]
Habs gefunden und behoben....ist in der nächsten Version drin.
