### ISSUE TITLE
Passwort auf Projekten ohne Passwort erkannt.

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#86]
Seit 1.0.38 bekomme ich die Meldung dass ein Passwort auf meinem 5.7.4 Projekt ist. Aber es war nie ein Passwort auf dem Projekt

**Comment by chefkoch009** [comment]
kann ich bitte das projekt einmal haben?

**Comment by TA2k** [comment]
via iobroker forum

**Comment by chefkoch009** [comment]
Bitte 1.0.39 testen.

**Comment by TA2k** [comment]
Funktioniert. Beim ersten Wahl gab es eine restart loop vom adapter aber beim zweiten mal wurde das Projekt erfolgreich importiert.
