### ISSUE TITLE
Reconnect every 5min-10min

### ISSUE THREAD

**Issue by TA2k** [ioBroker/ioBroker.knx#87]
The Adapter is reconnecting every 5-10min. If this is normal behavior please move it in debug log.

knx.0 | 2020-03-01 11:22:04.837 | info | (7255) Connected - local UDP Server listening on 192.168.178.2:42747
-- | -- | -- | --
knx.0 | 2020-03-01 11:22:04.835 | info | (7255) Using UDP with local IP: 192.168.178.2
knx.0 | 2020-03-01 11:22:02.842 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:22:02.838 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:22:02.835 | info | (7255) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:11:04.853 | info | (7255) Connected - local UDP Server listening on 192.168.178.2:43977
knx.0 | 2020-03-01 11:11:04.850 | info | (7255) Using UDP with local IP: 192.168.178.2
knx.0 | 2020-03-01 11:11:02.858 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:11:02.854 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:11:02.850 | info | (7255) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:00:04.948 | info | (7255) Connected - local UDP Server listening on 192.168.178.2:59420
knx.0 | 2020-03-01 11:00:04.946 | info | (7255) Using UDP with local IP: 192.168.178.2
knx.0 | 2020-03-01 11:00:02.955 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:00:02.950 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 11:00:02.946 | info | (7255) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:55:01.640 | info | (7255) Connected - local UDP Server listening on 192.168.178.2:57564
knx.0 | 2020-03-01 10:55:01.636 | info | (7255) Using UDP with local IP: 192.168.178.2
knx.0 | 2020-03-01 10:54:59.657 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:54:59.645 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:54:59.636 | info | (7255) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:54:54.383 | info | (7255) Connected - local UDP Server listening on 192.168.178.2:59436
knx.0 | 2020-03-01 10:54:54.378 | info | (7255) Using UDP with local IP: 192.168.178.2
knx.0 | 2020-03-01 10:54:52.402 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:54:52.386 | info | (7255) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:54:52.377 | info | (7255) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
knx.0 | 2020-03-01 10:54:42.872 | info | (7255) Connected! with 701 datapoints of 1404 Datapoints over all.
knx.0 | 2020-03-01 10:54:42.821 | info | (7255) Connected - local UDP Server listening on 192.168.178.2:45997
knx.0 | 2020-03-01 10:54:42.800 | info | (7255) Debuglevel: 0 1
knx.0 | 2020-03-01 10:54:42.787 | info | (7255) Connecting to knx GW: 192.168.178.37:3671 with phy. Adr: 1.1.0
knx.0 | 2020-03-01 10:54:42.782 | info | (7255) knx license is OK.
knx.0 | 2020-03-01 10:54:42.364 | info | (7255) starting. Version 1.0.39 in /opt/iobroker/node_modules/iobroker.knx, node: v10.18.0

**Comment by AlexSpaeth** [comment]
I have the same problem. Any comments about this issue?

**Comment by TomSC1984** [comment]
I Have same problem

**Comment by GRaptor** [comment]
Same with me, on current version 1.0.41
And it loses connection to the bus after several hours. Have to restart the adapter to get it working again.

**Comment by Anzic23** [comment]
+1
v 1.0.44

**Comment by RESDE** [comment]
Hi guys, do you have imported several times the ETS project while changing the GA in your ETS project beforehand. In many cases the reimport is not working accurately enough so please delete all the KNX objects manually before (!) reimporting. Pending on your hardware performance and the interaction with other IOBroker adapters the reimporting is struggling as the KNX objects are referenced already by other knx adapters etc

**Comment by boellner** [comment]
possibly same as #184

**Comment by chefkoch009** [comment]
is fixed from 2.0.x
