### ISSUE TITLE
VIS Verhalten von KNX Datenpunkten / keine VIS Aktualisierung

### ISSUE THREAD

**Issue by Gompman** [ioBroker/ioBroker.knx#88]
KNX Adapter Verion: 1.0.39

Beschreibung:
    Beleuchtung über BASIC-BOOL-CHECKBOX (Beispielhaft) eingeschaltet
    Schalten der Beleuchtung durch einen Hardware Wandtaster oder Browser von einem anderen Gerät oder aber direkt im Admin Bereich von iobroker den Datenpunkt wieder auf "aus" gestellt.
    Beleuchtung ist aus. Materialdesign Widget änder aber das Symbol nicht auf "aus" (Haken entfernt)

Das Verhalten ist aber nur bei KNX Datenpunkten der Fall. Bei verwendung von Materialdesign von Uhula (script in website) werden die Daten passend aktualisiert auch wenn nicht auf der VIS sondern per Hardware geändert wird.

Hier die Action
`{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1583157259960,
  "common": {
    "name": "OG-Büro-Beleuchtung Schräge-schalten",
    "type": "boolean",
    "role": "switch",
    "read": true,
    "write": true,
    "min": false,
    "max": true
  },
  "native": {
    "dpt": "DPT1.001",
    "address": "0/1/25",
    "addressRefId": "P-0545-0_GA-303",
    "statusGARefId": "P-0545-0_GA-304",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Licht.Schalten_(Ein_Aus).OG-Büro-Beleuchtung_Schräge-schalten",
  "type": "state"
}`

und der Status:
`{
  "_id": "knx.0.Licht.Rückmeldung_status_(Ein_Aus_1_Bit).OG-Büro-Beleuchtung_Schräge-schalten-status",
  "type": "state",
  "common": {
    "name": "OG-Büro-Beleuchtung Schräge-schalten-status",
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.switch",
    "min": false,
    "max": true
  },
  "native": {
    "dpt": "DPT1.011",
    "address": "0/4/26",
    "addressRefId": "P-0545-0_GA-304",
    "statusGARefId": "",
    "actGARefId": "P-0545-0_GA-303"
  },
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1583157260036,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

Falls weitere Informationen benötigt werden bitte eine Info.

Great project

**Comment by chefkoch009** [comment]
Siege dazu in der Tabelle Unter „ 3) Herausfinden der Schalt- und Statusaddressen“.
Vermutlich sind die KO‘s nicht so parameterisiert wie es sein soll.

**Comment by Gompman** [comment]
Steige da noch noch nicht folends durch.

- KNX Taster
  -Status an/aus       KLÜ
  -Schaltadresse mit KS

- KNX Aktor
  - Schaltadresse mit KS
  - Status an/aus       KLÜ

![Anmerkung 2020-03-03 140832](https://user-images.githubusercontent.com/10465613/75778807-c2819980-5d58-11ea-9810-55e012f8f606.png)

wo muss ich sonst noch schauen?

**Comment by chefkoch009** [comment]
Dein Ausschnitt sieht soweit mustergültig aus.
Aber hier: 
Licht/Schalten_(Ein_Aus)/OG-Büro-Beleuchtung_Schräge-schalten
Licht/Rückmeldung_status_(Ein_Aus_1_Bit)/OG-Büro-Beleuchtung_Schräge-schalten-status
hast du es mit der Info, das es sich um eine Rückmeldung handelt, sehr gut gemeint. Aber er scheint es zu erkennen. Welche ETS Version hast Du? Scheint schon etwas älter zu sein, oder du hast vor dem Import nicht die KNX-Objekte im ioBroker gelöscht.

**Comment by Gompman** [comment]
Die KNX Version ist die 5.5.2 Build 665
Die Datenpunkte habe ich zuvor gelöscht und dann nur neue Datenpunkte importiert.

**Comment by chefkoch009** [comment]
Nun...am Importfilter für ETS Version 5.5.2 habe ich keinerlei weitere Veränderungen vorgenommen. Ab ETS Version 5.7.2 greift der neue Importfilter. Was passiert wenn du eine aktuellere Version der ETS verwendest? Lässt es sich dann importieren?

**Comment by chefkoch009** [comment]
no response from reporter. should check new adapter version.
