### ISSUE TITLE
Somtimes no Datapoint is received.

### ISSUE THREAD

**Issue by RobertHerter** [ioBroker/ioBroker.knx#9]
Hello,

sometimes after a while there is no knx message send/received. Even after restart.
i have to change the knx-address then its working again.

Working log:
`knx.0	2017-02-22 10:50:55.890	info	knx.0 CHANGE from 1.1.5 to (2/4/80) Jalousie Kind 3 Positionstatus: �
knx.0	2017-02-22 10:50:53.915	info	knx.0 Connected! with 100 datapoints of 201 Datapoints over all.
knx.0	2017-02-22 10:50:53.915	info	knx.0 DPP erstellt für : 7/1/120 Terasse Außensteckdose schalten`

Not working log:
`knx.0	2017-02-22 10:50:53.915	info	knx.0 Connected! with 100 datapoints of 201 Datapoints over all.
knx.0	2017-02-22 10:50:53.915	info	knx.0 DPP erstellt für : 7/1/120 Terasse Außensteckdose schalten`

**Comment by chefkoch009** [comment]
* should be solved in V1.0.0 because rebuild KNX-Stack and connection handling.
