### ISSUE TITLE
import KNX Datei dauert sehr lange

### ISSUE THREAD

**Issue by RESDE** [ioBroker/ioBroker.knx#91]
Hallo,
ersteinmal Danke für diesen tollen Adapter, der aber auch wirklich die Verbindung der KNX Welt in den IOBroker schafft.
Bisher hatte ich immer einen stabilen Zustand, nur habe ich jetzt JS, Admin und andere Adapter aktualisiert. Ebenso den KNX adapter auf das aktuellste Release.
Gleichzeitig habe ich noch ein paar neue GA Adressen in KNX anleget und wollte daher die aktuelleste KNX Datei mal eben importieren (ETS Stand 5.7.3.)
Die Devices werden zwar nach ca. 3 min auch als angelegt bestätigt, aber dann läuft sich der Projektfile-Import ins Unendliche...
Ebenfalls hatte ich auch ein downgrade des Adapters auf 1.0.32 versucht, um wieder einen stabilen Stand zu erhalten. Aber auch das war nicht möglich.
Aktuell steht der KNX Adapter auf gelb, meldet aber im Log als ordentlich verbunden, KNX Lizenz geprüft etc.
Wie kann ich mich selbst noch prüfen, dass ich die aktuelle Version des KNX AAdapter auch wieder ans Laufen bekomme? Es ist schon dringend, denn via SQL Adapter zeichne ich auch die Historie der KNX GA Veränderungen auf.... der hakt natürlich auch derzeit.
Grüße
Reiner

**Comment by chefkoch009** [comment]
Hallo,

die Dauer des Importes hängt zum einen von der Leistung der Maschine ab, auf der der ioBroker läuft und zum anderen von der Projektgrösse. Deshalb ist die Aussage "dauert sehr lange" sehr relativ. 

Folgende Informationen wären toll: 
npm version, node version, version des js-controllers.

Bitte schreib mir im iobroker-Forum eine PN.

VG

**Comment by chefkoch009** [comment]
no response from reporter.
