### ISSUE TITLE
Datenpunkt 9.001/9.028 liefert 8 Nachkomma Stellen

### ISSUE THREAD

**Issue by lammy000** [ioBroker/ioBroker.knx#93]
Hi,

ich bekomme bei den Datenpunkten 9.001 und 9.028 in den Geräten Werte mit 8 Nachkommastellen. 
Ich habe mir so Beholfen, dass ich "Math.round(val*10)/10" als Read Parameter bei den jeweiligen Geräten eingefügt habe.
Damit läuft es, was denke ich aber nicht im Sinne des Erfinders ist :-)
Ich glaube das es auch erst seid dem Update auf 1.0.39 so ist.

**Comment by CarminKern** [comment]
Oh, habe das selbe Problem, jedoch noch nicht so viel Erfahrung mit ioBroker. Würdest du mir kurz erklären wie du das Problem gelöst hast Bzw. wo/wie du die round Funktion eingefügt hast?

**Comment by chefkoch009** [comment]
seems to be fixed, no response over 1 year.
