### ISSUE TITLE
Automatische Zuweisung von Status Adressen funktioniert nicht bei unterschiedlichen Mittelgruppen

### ISSUE THREAD

**Issue by chrisp0** [ioBroker/ioBroker.knx#94]
Bei mir sind Schalt- und Statusgruppenadressen getrennt in unterschiedlichen Mittelgruppen.

Die automatische Zuweisung von Status Gruppenadressen beim Import funktioniert nicht, wenn Sollwert Gruppenadresse und Status Gruppenadresse in unterschiedlichen Mittelgruppen sind.

![image](https://user-images.githubusercontent.com/47448571/78260032-c5a9aa00-74fd-11ea-93cc-b5193213e164.png)

Funktioniert 
![image](https://user-images.githubusercontent.com/47448571/78260098-dbb76a80-74fd-11ea-98dc-e8dfe1b8b320.png)

Funktioniert nicht
![image](https://user-images.githubusercontent.com/47448571/78260167-f12c9480-74fd-11ea-8891-98ffe8079037.png)

Wäre es möglich durch einen Parameter in der Adapter Konfiguration einzustellen, ob die komplette ObjektID oder nur der reine Gruppenadressename verglichen werden soll (also ohne Haupt- und Mittelgruppe)

Nur Gruppenadressename
![image](https://user-images.githubusercontent.com/47448571/78260879-c7c03880-74fe-11ea-91c3-872e22d8f9f3.png)

**Comment by tseroo** [comment]
Habe das gleiche Problem. Bei mir unterscheiden sich die Status GAs über die Hauptgruppe, z.B. 1/1/45 mit Status 5/1/45. Habe Details dazu [hier](https://github.com/ioBroker/ioBroker.knx/issues/38#issuecomment-610262096) gepostet.

**Comment by Garfonso** [comment]
Es ist nicht so, dass es grundsätzlich nicht funktioniert. Siehe meinen Kommentar in #38 .

**Comment by chrisp0** [comment]
@Garfonso Danke für den Hinweis

Es funktioniert tatsächlich, wenn sich die Mittelgruppen sehr ähnlich sind.
Im obigen Fall mit "Absolute_Position" und "Position_Status" als Mittelgruppe hat es nicht funktioniert.
Wenn ich die Mittelgruppen umbenenne nach z.B. "Schalten" und "Schalten Status" oder "Dimmen Absolut" und "Dimmen Absolut Status" funktioniert alles bestens.

Ich benenne nun die Mittelgruppen um...das ist kein großer Aufwand #

Ich denke das Issue hat sich damit erledigt
