### ISSUE TITLE
1.0.40 liefert falsche Status-Werte

### ISSUE THREAD

**Issue by tseroo** [ioBroker/ioBroker.knx#95]
Nach dem Upgrade auf 1.0.40 zeigen so ziemlich alle KNX Status GAs im ioBroker den Wert TRUE, obwohl der tatsächliche Status FALSE ist!
![image](https://user-images.githubusercontent.com/10330889/78422696-7aa8a780-7661-11ea-997a-5577b8b2c73e.png)
Nach downgrade auf 1.0.39 sind die Werte wieder korrekt:
![image](https://user-images.githubusercontent.com/10330889/78422708-872d0000-7661-11ea-998e-1d3573362941.png)

**Comment by icxcube** [comment]
Kann ich auch so bestätigen

**Comment by tseroo** [comment]
Mit 1.0.41 werden wieder die korrekten Status angezeigt.

**Comment by Erfor85** [comment]
wieso wird bei mir nur 1.0.39 angezeigt und nicht 1.0.41?
Bin zur Zeit noch auf 1.0.20, alles was höherist lässt sich nicht schreiben (1bit Werte true/false)...?

**Comment by mghomedev** [comment]
Ich musste auch wieder auf 1.0.20 downgraden von 1.0.41 damit 1bit Werte beschreibbar sind. 
Alles über 1.0.20 wird entweder gar nicht fertig importiert, oder die 1-bit Werte die eigentlich "state" "value" writable sein sollten, sind plötzlich fälschlicherweise "indicator"  und "readonly" . Ich weiß nicht was hier los ist, aber irgendwie bekommt der Entwickler  seit 1 Jahr den ETS Import nicht mehr in den Griff. Man kann ihm aber auch nicht helfen, weil dieses KNX iobroker kein Open Source mehr ist , d.h. niemand außer ihm kann Bugs fixen - was aber in der Praxis nicht geht, weil er ja nicht die vielen Gebäudekonfigurationen testen/debuggen kann.

**Comment by Garfonso** [comment]
Ja, die Prozedur musste ich heute auch wieder durchführen... :-( Es war ein anderer Fehler, aber alle neuen Objekte ließen sich nicht auf den Bus schreiben und lieferten aber auch die Werte, die vom Bus kamen nicht... :-( zurück auf  1.0.20 -> neuer import -> geht -> update 1.0.41 -> geht immer noch... what??

@chefkoch009 kannst du nicht ein paar Entwickler, die auch KNX einsetzen (und unter dem Zustand leiden) mit in die Entwicklung nehmen, damit wir dir helfen können? Ich würde dir auch einen NDA unterschreiben, wenn ich den Code gucken dürfte und PRs machen.

**Comment by mghomedev** [comment]
Ich würde übrigens auch ein NDA unterschreiben  - dann kann ich auch debuggen, damit das hier mal voran geht.

**Comment by chefkoch009** [comment]
@Garfonso und @mghomedev : bitte PN im Iobroker Forum an mich oder eine Mail.

**Comment by chefkoch009** [comment]
.

**Comment by RESDE** [comment]
Hallo @chefkoch,

konnten den beiden Usern geholfen werden? Falls ja, diesen Issue dann besser schliessen, da es ein paar andere #import issues gibt.
Grüße
Reiner

**Comment by chefkoch009** [comment]
ist behoben.
