### ISSUE TITLE
KNX Message leer

### ISSUE THREAD

**Issue by githubtzzz** [ioBroker/ioBroker.knx#97]
Hi,
ich habe ein komisches verhalten.
Wenn ich eine Temperatur senden will, kommt die Nachricht zwar auf den Bus (Sichtbar im Gruppenmonitor im ETS) aber der Inhalt ist leer.
Hat sowas noch jemand?
So sieht das Objekt aus:
`

{

  "_id": "knx.0.Fremdbusse.iobroker-zigbee.reed-temperatur-1",

  "type": "state",

  "common": {

    "name": "reed-temperatur-1",

    "type": "number",

    "read": true,

    "write": true,

    "role": "value.temperature.number",

    "min": -273,

    "max": 670670

  },

  "native": {

    "dpt": "DPT9.001",

    "address": "x/x/x",

    "addressRefId": "P-035D-0_GA-21",

    "statusGARefId": "",

    "actGARefId": ""

  },

  "from": "system.adapter.knx.0",

  "user": "system.user.admin",

  "ts": xxxxx,

  "acl": {

    "object": xxxx,

    "state": xxxx,

    "owner": "system.user.admin",

    "ownerGroup": "system.group.administrator"

  }

}
`

**Comment by ccie32305** [comment]
Hab hier ein ähnliches Thema
Auf dem Bus kommt die Temperatur von der Wetterstation 
#	Zeit	Dienst	Flags 	Prio	Quelladresse	Quellname	Zieladresse	Zielname	Rout	Typ	DPT	Info
1099	16.04.2020 22:04:39,896	vom Bus		Niedrig	1.1.254	-	7/7/5	Wetter/Zentral/Temperatur	6	GroupValueRead		
1100	16.04.2020 22:04:39,982	vom Bus		Niedrig	1.1.40	GA-AU-Wetterstation	7/7/5	Wetter/Zentral/Temperatur	5	GroupValueResponse	  9.001 Temperatur (°C)	0C 5B | 22,3 °C
1229	16.04.2020 22:09:58,522	zum Bus		Niedrig	1.0.252	Tunnelling Kanal 3	7/7/5	Wetter/Zentral/Temperatur	6	GroupValueRead		
1230	16.04.2020 22:09:58,588	vom Bus		Niedrig	1.1.40	GA-AU-Wetterstation	7/7/5	Wetter/Zentral/Temperatur	5	GroupValueResponse	  9.001 Temperatur (°C)	0C 5B | 22,3 °C

Im iobroker mit Version 1.0.39 kommt nichts im Objekt an.


Raw Objekt :
{
  "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1587063681087,
  "common": {
    "name": "Wetter/Zentral/Temperatur",
    "type": "number",
    "role": "level.temperature.number",
    "min": -273,
    "max": 670670,
    "read": true,
    "write": false,
    "custom": {
      "history.0": null,
      "iqontrol.0": null,
      "lovelace.0": null,
      "sql.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": "31536000",
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      },
      "telegram.0": null,
      "material": {
        "admin": {
          "name": "Wetter/Zentral/Temperatur",
          "colorOn": "",
          "doubleSize": "",
          "icon": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA1MTIuMDA2IDUxMi4wMDYiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDUxMi4wMDYgNTEyLjAwNjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8cGF0aCBzdHlsZT0iZmlsbDojQzUyODI4OyIgZD0iTTUwMi4zNzksMjExLjI0OWMwLDc0LjY1Ni02MC41MiwxMzUuMTc2LTEzNS4xNzYsMTM1LjE3NmMtNi40NjksMC4wMS0xMi45MTktMC40NzMtMTkuMzExLTEuNDQ4CgljLTY2LjQ4Ny05LjU5OC0xMTUuODM3LTY2LjU1NS0xMTUuODY2LTEzMy43MjhjLTAuMDE5LTY3LjIxMiw0OS4zNDktMTI0LjIyNywxMTUuODY2LTEzMy44MjUKCWM2LjQwMi0wLjg4OCwxMi44NTEtMS4zNDIsMTkuMzExLTEuMzUyQzQ0MS44NTksNzYuMDcyLDUwMi4zNzksMTM2LjU5Myw1MDIuMzc5LDIxMS4yNDl6Ii8+CjxwYXRoIHN0eWxlPSJmaWxsOiNGNDQzMzU7IiBkPSJNNDYzLjc1NywyMTEuMjQ5Yy0wLjAyOSw2Ny4xNzMtNDkuMzc4LDEyNC4xMzEtMTE1Ljg2NSwxMzMuNzI4CgljLTY2LjQ4Ny05LjU5OC0xMTUuODM3LTY2LjU1NS0xMTUuODY2LTEzMy43MjhjLTAuMDE5LTY3LjIxMiw0OS4zNDktMTI0LjIyNywxMTUuODY2LTEzMy44MjUKCUM0MTQuNDA4LDg3LjAyMiw0NjMuNzY3LDE0NC4wMzcsNDYzLjc1NywyMTEuMjQ5eiIvPgo8Zz4KCTxwYXRoIHN0eWxlPSJmaWxsOiNGREQ4MzQ7IiBkPSJNMzgwLjUyNywyMzAuNTZoLTI2LjY0OWMtNC4yNTgsMC4xMjYtNy44OTgtMy4wMTMtOC40LTcuMjQybC03LjI0Mi05MC40NzIKCQljLTAuMjEyLTQuNDcsMy4yMzUtOC4yNzUsNy43MDUtOC40OTdjMC4yMzItMC4wMSwwLjQ2My0wLjAxLDAuNjk1LDBoNDEuMDM2YzQuNDgtMC4xNjQsOC4yMzYsMy4zMzEsOC40LDcuODAyCgkJYzAuMDEsMC4yMzIsMC4wMSwwLjQ2MywwLDAuNjk1bC03LjI0Miw5MC40NzJDMzg4LjMyOSwyMjcuNDk5LDM4NC43MzcsMjMwLjYzNywzODAuNTI3LDIzMC41NnoiLz4KCTxwYXRoIHN0eWxlPSJmaWxsOiNGREQ4MzQ7IiBkPSJNMzYyLjA4NSwyNjkuMTgxaDEwLjIzNWM3Ljg0LDAsMTQuMTk0LDYuMzUzLDE0LjE5NCwxNC4xOTR2MTAuMjM1CgkJYzAsNy44NC02LjM1MywxNC4xOTQtMTQuMTk0LDE0LjE5NGgtMTAuMjM1Yy03Ljg0LDAtMTQuMTk0LTYuMzUzLTE0LjE5NC0xNC4xOTR2LTEwLjIzNQoJCUMzNDcuODkyLDI3NS41MzUsMzU0LjI0NSwyNjkuMTgxLDM2Mi4wODUsMjY5LjE4MXoiLz4KPC9nPgo8cGF0aCBzdHlsZT0iZmlsbDojRjU3QzAwOyIgZD0iTTMwOC4wMTUsMzMyLjcxNGMtOC42NDItNC4xOS0xNi44MDEtOS4yOTgtMjQuMzMyLTE1LjI1NmMtOS42NjUtNy42MzctMTguMjc4LTE2LjU0LTI1LjU4Ny0yNi40NTYKCWMtMTYuOTk0LTIzLjExNS0yNi4xMzctNTEuMDY4LTI2LjA3LTc5Ljc1NGMtMC4wMS05Ljc0MiwxLjAzMy0xOS40NDYsMy4wOS0yOC45NjZjMi4wNjYtMTAuMDAzLDUuMzExLTE5LjcyNiw5LjY1NS0yOC45NjYKCWMtMjQuNDI4LTM5LjIwMS01MC42OTEtNzguMTEzLTg1LjU0Ny0xMDguMzM0Yy0yLjYwNy0yLjIyMS01LjIxNC00LjQ0Mi03LjkxNy02LjU2NmMtNC41OTYtMy44MDQtOS4zOTUtNy4zNDgtMTQuMzg3LTEwLjYyMQoJYy00LjM2NC0yLjgxOS04Ljk4OS01LjIxNC0xMy44MDctNy4xNDVjMS42NDEsNy4zMzgsMy40NzYsMTQuNzczLDQuNzMxLDIyLjIwOGMxLjY3LDguODkzLDIuNjc1LDE3LjkwMSwyLjk5MywyNi45MzkKCWMwLDIuMzE3LDAsNC43MzEsMCw3LjE0NWMtMC4xOTMsNTIuOTAyLTIyLjE5OCwxMDMuMzgxLTYwLjgyOSwxMzkuNTIxYy0xNy40OTYsMTQuOTU2LTMyLjMyNiwzMi43OC00My44MzYsNTIuNzE5CglDNy4yMzcsMzA2LjQ5LDQuODUzLDM1MC4wNDYsMTkuNjA2LDM4OS4xOTljNS4zMywxNC40MzUsMTIuODEzLDI3Ljk4MiwyMi4yMDgsNDAuMTY3YzI2LjEwOCwzMy41NDMsNjQuMTUxLDU1LjcyMiwxMDYuMjEsNjEuODkxCgljLTE4LjA0Ni01LjU5LTMzLjc2NS0xNi45MTYtNDQuODAxLTMyLjI0OWMtMS4zNDItMS43ODYtMi41NjgtMy42NS0zLjY2OS01LjZjLTIuNTc4LTQuMjE5LTQuNzQxLTguNjktNi40NjktMTMuMzI1CgljLTcuNzA1LTIwLjgzNi02LjM0NC00My45NDIsMy43NjYtNjMuNzI2YzYuMTk5LTEwLjY4OSwxNC4xMjYtMjAuMjg2LDIzLjQ2My0yOC4zODdjMjAuNjA1LTE5LjIwNSwzMi4zNDYtNDYuMDg2LDMyLjQ0Mi03NC4yNQoJYzAtMS4zNTIsMC0yLjYwNywwLTMuODYyYy0wLjI5LTkuMjIxLTEuODgzLTE4LjM1NS00LjczMS0yNy4xMzJjMy43NTYsMS45NzksNy4zOTYsNC4xNzEsMTAuOTExLDYuNTY2CgljMTIuMDQsOC4xMywyMi4zMjMsMTguNjA2LDMwLjIyMiwzMC44MDFjOS4wMTgsMTMuOTQyLDE0LjQ1NCwyOS44OTMsMTUuODM1LDQ2LjQ0M2MwLDIuNDE0LDAsNC44MjgsMCw3LjMzOHYxLjA2MgoJYzAuMDEsMjAuNzMtNi4zNjMsNDAuOTU4LTE4LjI0OSw1Ny45MzNjMjIuOTgsMTMuMDM1LDM4LjYyMi04LjU5Myw0NC45OTQtMjguOTY2YzEuMzAzLTQuMTgxLDIuMTQ0LTguNDg3LDIuNTEtMTIuODQyCgljMTcuNDE4LDE1Ljc3NywyNy44MzcsMzcuODQsMjguOTY2LDYxLjMxMmMwLDEuNzM4LDAsMy40NzYsMCw1LjIxNGMtMi43MDQsMzMuNjc4LTI1LjM0Niw2Mi40NTEtNTcuNDUsNzIuOTk1CgljNzMuMzUzLTExLjc4OSwxMjguNzE3LTcyLjg4OSwxMzMuMjQ1LTE0Ny4wNTNDMzI4LjI2MiwzNDEuMjMsMzE3Ljg1NCwzMzcuNTksMzA4LjAxNSwzMzIuNzE0eiIvPgo8cGF0aCBzdHlsZT0iZmlsbDojRkY5ODAxOyIgZD0iTTI2My4xMTcsNDE3LjQ4OWMwLTEuNzM4LDAtMy40NzYsMC01LjIxNGMtMS4xMy0yMy40NzItMTEuNTQ4LTQ1LjUzNS0yOC45NjYtNjEuMzEyCgljLTAuMzY3LDQuMzU1LTEuMjA3LDguNjYxLTIuNTEsMTIuODQyYy01Ljk4NiwyMC40Ny0yMi4wMTQsNDIuMDk4LTQ0Ljk5NCwyOC45NjZjMTEuODg2LTE2Ljk3NCwxOC4yNTgtMzcuMjAyLDE4LjI0OS01Ny45MzN2LTAuOTY2CgljMC0yLjUxLDAtNC45MjQsMC03LjMzOGMtMS4zODEtMTYuNTQ5LTYuODE3LTMyLjUtMTUuODM1LTQ2LjQ0M2MtNy44OTgtMTIuMTk1LTE4LjE4MS0yMi42NzEtMzAuMjIyLTMwLjgwMQoJYy0xMC4xMzgtMTQuOTY2LTIzLjgzOS0yNy4xOC0zOS44NzctMzUuNTMyYzIuODQ4LDguNzc3LDQuNDQyLDE3LjkxMSw0LjczMSwyNy4xMzJjMCwxLjI1NSwwLDIuNTEsMCwzLjg2MgoJYy0wLjA5NywyOC4xNjUtMTEuODM4LDU1LjA0Ni0zMi40NDIsNzQuMjVjLTkuMjk4LDguMTExLTE3LjE5NiwxNy42OTgtMjMuMzY2LDI4LjM4N2MtMTAuMDQyLDE5LjgxMy0xMS4zMzYsNDIuOTE5LTMuNTczLDYzLjcyNgoJYzYuNzExLDE3LjY4OSwxOS4xOTUsMzIuNTg3LDM1LjQzNiw0Mi4yOTFjMS4xMDEsMS45NSwyLjMyNywzLjgxNCwzLjY2OSw1LjZjMTAuOTMsMTUuMjY1LDI2LjUxNCwyNi41ODEsNDQuNDE1LDMyLjI0OQoJYy00Mi4wNTktNi4xNy04MC4xMDItMjguMzQ4LTEwNi4yMS02MS44OTJjLTkuMzI3LTEyLjIwNC0xNi43NDMtMjUuNzQxLTIyLjAxNC00MC4xNjdDNC44NTMsMzUwLjA0Niw3LjIzOCwzMDYuNDksMjYuMTcyLDI2OS4xODEKCWMxMS41MjktMjAuMTIyLDI2LjQxNy0zOC4xMiw0NC4wMjktNTMuMjAyYzM4LjYzMS0zNi4xNCw2MC42MzYtODYuNjE5LDYwLjgyOS0xMzkuNTIxYzAtMi40MTQsMC00LjgyOCwwLTcuMTQ1CgljLTAuMzE5LTkuMDM4LTEuMzIzLTE4LjA0Ni0yLjk5My0yNi45MzljLTEuMjU1LTcuNDM1LTMuMDktMTQuODY5LTQuNzMxLTIyLjIwOGM0LjgxOCwxLjkzMSw5LjQ0Myw0LjMyNiwxMy44MDcsNy4xNDUKCWM1LjEyNywzLjI5MywxMC4wNjEsNi44NjUsMTQuNzczLDEwLjcxOGMyLjcwNCwyLjEyNCw1LjMxMSw0LjM0NSw3LjkxNyw2LjU2NmMzNC44NTYsMzAuMjIyLDYxLjExOSw2OS4xMzMsODUuNTQ3LDEwOC4zMzQKCWMtNC4zNDUsOS4yNC03LjU4OSwxOC45NjMtOS42NTUsMjguOTY2Yy0yLjI3OSw5LjYyNi0zLjUxNSwxOS40NjUtMy42NjksMjkuMzUzYy0wLjA2OCwyOC42ODYsOS4wNzYsNTYuNjM5LDI2LjA3LDc5Ljc1NAoJYzcuMzA5LDkuOTE2LDE1LjkyMiwxOC44MTgsMjUuNTg3LDI2LjQ1NmM3LjUzMSw1Ljk1NywxNS42OSwxMS4wNjUsMjQuMzMyLDE1LjI1NkMzMDIuNTc5LDM2NS4wNywyODYuODMxLDM5NC44MDksMjYzLjExNyw0MTcuNDg5egoJIi8+CjxwYXRoIGQ9Ik0xNDcuODMxLDUwMC45MTJoLTEuNDQ4Yy02MS43NTYtOC43LTExMy45NjMtNTAuMTUtMTM2LjQzMi0xMDguMzM0Yy0xNS40NjgtNDEuNjE1LTEyLjgxMy04Ny43OTcsNy4zMzgtMTI3LjM1NQoJYzEyLjAyMS0yMS4wOTcsMjcuNTY2LTM5Ljk2NCw0NS45Ni01NS44MDljMzYuNzk3LTM0LjI0OCw1Ny43NjktODIuMjA3LDU3LjkzMy0xMzIuNDczYzAtMi4zMTcsMC00LjUzOCwwLTYuNzU5CgljLTAuMjktOC41ODQtMS4yMjYtMTcuMTM4LTIuOC0yNS41ODdjLTAuOTY2LTUuNjk3LTIuMjIxLTExLjItMy40NzYtMTYuNzA0bC0xLjE1OS01LjExN2MtMS4xNzgtNS4yMDQsMi4wNzYtMTAuMzcsNy4yOC0xMS41NDgKCWMxLjk4OS0wLjQ1NCw0LjA3NS0wLjI2MSw1Ljk0OCwwLjU0MWM1LjM5NywyLjE2MywxMC41NzMsNC44NDcsMTUuNDQ5LDguMDE0YzUuMzQ5LDMuNDQ3LDEwLjUxNSw3LjE4NCwxNS40NDksMTEuMgoJYzQxLjAzNiwzMi43MzIsNzAuODcxLDc3LjI0NCw5NS41ODksMTE3LjMxNGMxLjg3MywyLjg5NywyLjA1Nyw2LjU4NSwwLjQ4Myw5LjY1NWMtNC4yNjgsOC41MzUtNy41MDIsMTcuNTQ0LTkuNjU1LDI2Ljg0MgoJYy0xLjc4Niw4LjctMi42NTUsMTcuNTczLTIuNjA3LDI2LjQ1NmMwLjAxLDU5LjE5OCw0MS4zNzQsMTEwLjMzMyw5OS4yNTgsMTIyLjcyMWM0LjUyOCwwLjk3NSw3LjczNCw1LjAyMSw3LjYyOCw5LjY1NQoJYy0zLjE4Niw3Ny4yNDQtNjEuMjE2LDE0MS43NDItMTQxLjE2MywxNTYuMTI5Yy01LjI1MywwLjkyNy0xMC4yNTQtMi41ODgtMTEuMTgxLTcuODRjLTAuODIxLTQuNjczLDEuODczLTkuMjUsNi4zNTMtMTAuNzk1CgljMjkuOTktOS44LDUwLjUxNy0zNy40OTIsNTEuMTc0LTY5LjAzN2MtMC4yMTItMTQuNzkyLTUuMjYyLTI5LjEwMi0xNC4zODctNDAuNzQ2Yy00LjA4NCwxMi45MDktMTIuNjM5LDIzLjkzNi0yNC4xMzksMzEuMDkxCgljLTEwLjU4Miw1LjU5LTIzLjM0Nyw1LjAzLTMzLjQwOC0xLjQ0OGMtNC42NDQtMi42MjYtNi4yNzYtOC41MTYtMy42NTktMTMuMTZjMC4xNDUtMC4yNjEsMC4yOTktMC41MDIsMC40NzMtMC43NDMKCWMxMC43NjYtMTUuMzYyLDE2LjUzLTMzLjY2OSwxNi41MTEtNTIuNDI5di0wLjc3MmMtMC4yMDMtMTcuMTQ4LTUuMjUzLTMzLjg4MS0xNC41OC00OC4yNzcKCWMtNS4zMzktOC4wOTEtMTEuODQ3LTE1LjM1Mi0xOS4zMTEtMjEuNTMyYzAsMS45MzEsMCwzLjg2MiwwLDUuNzkzYzAsMS4wNjIsMCwyLjUxLDAsNC4xNTIKCWMtMC4wMTksMzAuODQtMTIuODUxLDYwLjI4OS0zNS40MzYsODEuMjk5Yy04LjUzNSw3LjM2Ny0xNS44MDYsMTYuMDY3LTIxLjUzMiwyNS43OGMtOC44MDYsMTcuNDE4LTkuOTI2LDM3LjcyNC0zLjA5LDU2LjAwMgoJYzguODI1LDIxLjYzOCwyNy4wNzQsMzguMDQzLDQ5LjUzMyw0NC41MTJjNS4zMywwLjgwMSw5LjAwOSw1Ljc3NCw4LjIwNywxMS4xMDRDMTU4LjEzMyw0OTguMDM1LDE1My4xNiw1MDEuNzA0LDE0Ny44MzEsNTAwLjkxMnoKCSBNMTM3LjExMywzOS40Nzh2MS43MzhjMS43MzgsOS4zMDgsMi43NzEsMTguNzMyLDMuMDksMjguMTk0YzAsMi4zMTcsMCw0LjkyNCwwLDcuNDM1Yy0wLjExNiw1NS41NDgtMjMuMjEyLDEwOC41NjYtNjMuODIzLDE0Ni40NzMKCWMtMTYuODIsMTQuMy0zMS4wNTIsMzEuMzgtNDIuMDk4LDUwLjQ5OGMtMTcuNzE4LDM0Ljc1LTIwLjA2NCw3NS4zNDItNi40NjksMTExLjkwN2MxMi4yNzIsMzIuMzc1LDM1LjQ1NSw1OS40NTgsNjUuNTYxLDc2LjU2OAoJYy05Ljg1OC0xNC43MTUtMTUuMTQtMzIuMDE4LTE1LjE1OS00OS43MjZjMC4xMDYtMTMuOTUyLDMuNDA4LTI3LjY5Miw5LjY1NS00MC4xNjdjNi42NTMtMTEuNzIyLDE1LjIzNi0yMi4yMzcsMjUuMzk0LTMxLjA5MQoJYzE4LjgwOS0xNy40MzgsMjkuNDc4LTQxLjk0MywyOS40NDktNjcuNTg4YzAtMS4wNjIsMC0yLjEyNCwwLTMuMDljLTAuMjIyLTguNDY4LTEuNjUxLTE2Ljg0OS00LjI0OC0yNC45MTEKCWMtMS42MzItNS4wNzksMS4xNTktMTAuNTE1LDYuMjM3LTEyLjE0N2MyLjQ4MS0wLjgwMSw1LjE3NS0wLjU2LDcuNDczLDAuNjU3YzE4LjE0Myw5LjQ5MSwzMy41MzMsMjMuNDkyLDQ0LjcwNSw0MC42NDkKCWMxMS4zNjQsMTcuNTU0LDE3LjQ5NiwzNy45ODUsMTcuNjY5LDU4Ljg5OHYxLjE1OWMwLjAxOSwxOC4xOTEtNC40NjEsMzYuMTAyLTEzLjAzNSw1Mi4xMzljMS42NjEtMC4xNjQsMy4yNjQtMC42NTcsNC43MzEtMS40NDgKCWM5LjY1NS01LjMxLDE3LjI4My0yMi40OTcsMTguMzQ1LTM1LjQzNmMwLjQzNC01LjMxLDUuMDg4LTkuMjY5LDEwLjQwOS04Ljg0NGMyLjI2OSwwLjE4Myw0LjM5MywxLjE1OSw2LjAwNiwyLjc2MQoJYzE5LjYwMSwxNy4zNjEsMzEuMjI2LDQyLjAwMSwzMi4xNTMsNjguMTY4Yy0wLjAzOSwxNi43NzItNC43ODksMzMuMjA1LTEzLjcxMSw0Ny40MDhjMzguNTkzLTIzLjY2Niw2NC4xMDMtNjMuODIzLDY5LjEzMy0xMDguODE3CgljLTYyLjc3LTE3LjM3LTEwNi4yMi03NC40OTItMTA2LjIxLTEzOS42MThjLTAuMDEtMTAuNDE4LDEuMDkxLTIwLjgwOCwzLjI4My0zMC45OTRjMS45Ni05LjAxOCw0LjgwOC0xNy44MTQsOC40OTctMjYuMjYzCgljLTIzLjI3LTM3LjA3Ny01MS4yNy03OC40MDItODguNTQxLTEwOC4wNDVDMTQyLjgzOSw0My42MywxNDAuMDEsNDEuNDY3LDEzNy4xMTMsMzkuNDc4eiIvPgo8cGF0aCBkPSJNMzY3LjIwMywzNTYuMDgxYy0zMi40NjItMC4wMS02My45ODctMTAuOTItODkuNTA2LTMwLjk5NGMtMzUuMDQtMjcuMzY0LTU1LjQ2MS02OS4zODQtNTUuMzI2LTExMy44MzgKCWMtMC4wMS0xMC40MTgsMS4wOTEtMjAuODA4LDMuMjgzLTMwLjk5NGMyLjM3NS0xMC43NTYsNi4wMDYtMjEuMTg0LDEwLjgxNC0zMS4wOTFjMjMuOTY1LTUwLjQ5OCw3NC44MzktODIuNjk5LDEzMC43MzUtODIuNzQ3CgljNzkuOTg2LDAuMDE5LDE0NC44MTMsNjQuODc1LDE0NC44MDMsMTQ0Ljg2MWMtMC4wMSw0NC40MDUtMjAuMzkyLDg2LjM0OS01NS4yOTcsMTEzLjgwOQoJQzQzMS4yMzgsMzQ1LjI0NywzOTkuNjg0LDM1Ni4xNzcsMzY3LjIwMywzNTYuMDgxeiBNMzY3LjIwMyw4NS43MjhjLTQ4LjQ3LDAuMDE5LTkyLjU4NiwyNy45NDMtMTEzLjM1NSw3MS43NAoJYy00LjI2OCw4LjU2NC03LjUwMiwxNy42MTItOS42NTUsMjYuOTM5Yy0xLjc3Nyw4LjgzNS0yLjYyNiwxNy44MzQtMi41MSwyNi44NDJjMC4wMSw1OS4xOTgsNDEuMzc0LDExMC4zMzMsOTkuMjU4LDEyMi43MjEKCWM4LjYzMiwxLjg1NCwxNy40MzgsMi43OSwyNi4yNjMsMi44YzY5LjMyNiwwLDEyNS41MjEtNTYuMTk1LDEyNS41MjEtMTI1LjUyMVM0MzYuNTE5LDg1LjcyOCwzNjcuMjAzLDg1LjcyOHoiLz4KPHBhdGggZD0iTTM4MC41MjcsMjQwLjIxNWgtMjYuNjQ5Yy05LjI3OSwwLjA5Ny0xNy4xMDktNi44OTQtMTguMDU2LTE2LjEyNWwtNy4yNDItOTAuMDg1Yy0wLjM3Ny00Ljc4OSwxLjI3NS05LjUxMSw0LjUzOC0xMy4wMzUKCWMzLjQ4Ni0zLjc2Niw4LjM5MS01Ljg5OSwxMy41MTgtNS44OWg0MS4wMzZjNS4xMjctMC4wMSwxMC4wMzIsMi4xMjQsMTMuNTE4LDUuODljMy4zMDIsMy41MDUsNC45ODIsOC4yMzYsNC42MzUsMTMuMDM1CglsLTcuMjQyLDkwLjQ3MkMzOTcuNDQ0LDIzMy41NTMsMzg5LjY3MSwyNDAuMzMxLDM4MC41MjcsMjQwLjIxNXogTTM1NS4wMzcsMjIwLjkwNGgyNC41MjVsNi45NTItODYuODk5aC0zOC42MjJMMzU1LjAzNywyMjAuOTA0eiIKCS8+CjxwYXRoIGQ9Ik0zNzIuMzIsMzE3LjQ1OWgtMTAuMjM1Yy0xMy4xNTEtMC4wNDgtMjMuODAxLTEwLjY5OC0yMy44NDktMjMuODQ5di0xMC4yMzVjMC4wNDgtMTMuMTUxLDEwLjY5OC0yMy44MDEsMjMuODQ5LTIzLjg0OQoJaDEwLjEzOGMxMy4xODksMCwyMy44ODgsMTAuNjYsMjMuOTQ2LDIzLjg0OXYxMC4xMzhDMzk2LjE2OSwzMDYuNjkzLDM4NS41LDMxNy40MDEsMzcyLjMyLDMxNy40NTl6IE0zNjIuMTgyLDI3OC44MzcKCWMtMi40ODEsMC4wNDgtNC40OSwyLjA1Ny00LjUzOCw0LjUzOHYxMC4xMzhjMC4wNDgsMi40ODEsMi4wNTcsNC40OSw0LjUzOCw0LjUzOGgxMC4xMzhjMi40ODEtMC4wNDgsNC40OS0yLjA1Nyw0LjUzOC00LjUzOAoJdi0xMC4xMzhjLTAuMDQ4LTIuNDgxLTIuMDU3LTQuNDktNC41MzgtNC41MzhIMzYyLjE4MnoiLz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPGc+CjwvZz4KPC9zdmc+Cg==",
          "background": "",
          "enabled": false
        }
      }
    }
  },
  "native": {
    "dpt": "DPT9.001",
    "address": "7/7/5",
    "addressRefId": "P-046F-0_GA-96",
    "statusGARefId": "",
    "actGARefId": ""
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "knx.0.Wetter.Zentral.Wetter_Zentral_Temperatur",
  "type": "state"
}

**Comment by chefkoch009** [comment]
Bitte dringend die README lesen bezüglich der READ und WRITE Flags.

**Comment by githubtzzz** [comment]
@chefkoch009 
KAnnst du mir sagen warum die KNX Nachricht leer ist auf dem Bus?

**Comment by chefkoch009** [comment]
Bestimmt. Kannst du bitte ein JSON von dem Objekt Posten auf welches das zutrifft?

**Comment by Videonisse** [comment]
@githubtzzz Could you close this Issue or what is your status?

**Comment by chefkoch009** [comment]
No response from reporter anymore. Seems to be fixed.
