### ISSUE TITLE
Fehlerhafte Gruppenadressen

### ISSUE THREAD

**Issue by Maik-ux** [ioBroker/ioBroker.knx#98]
Hi! Habe ein update auf 1.40.0 gemacht. Kann bei diversen GA`s nichts auf den BUS senden.Hauptsächlich Rollo Befehle aber auch andere schalten-GA`s. Kann auch Schalt-Befehle von der ETS zum Iobroker senden aber vom Iobroker zur ETS geht gar nichts.

**Comment by RESDE** [comment]
Hallo, besteht das Problem noch?
Grüße
Reiner

**Comment by Maik-ux** [comment]
Hallo! Habe nach dem Fehler erstmal wieder auf die Version 1.0.20 gemacht und da ist sie bisher noch! :) Läuft alles z.Z.
Hatte auch keine Zeit auf die aktuelle upzudaten!

**Comment by Maik-ux** [comment]
Habe meine Projektdatei Testweise einmal von der ETS 5.7.3 und 5.7.4 bei Iobroker importiert. Mir ist aufgefallen das diverse Gruppenadressen, Hauptsächlich die ohne Statusadressen, Fehlerhaft importiert werden. 
Unter den Einstellungen der jeweiligen Fehlerhaften Adresse steht beim Importieren unter read und write nichts. Wenn ich da True und false eingebe, den Adapter neu starte kann ich vom Iobroker wieder auf den BUS senden.

 "from": "system.adapter.knx.0",
  "user": "system.user.admin",
  "ts": 1605900191004,
  "common": {
    "name": "Messwert-Anfordern-Eingang-A",
    "type": "boolean",
    "role": "",
    "read": false,
    "write": true,
    "update": "",
    "unit": "",
    "max": true,
    "min": false


Zumindest vorerst nur versucht bei manchen GA´s wie Rollo Position anfahren, Werte anfordern usw.

**Comment by chefkoch009** [comment]
is fixed in V2.0.5
